# =========================================================================================================================================
#   __script_name : CTPOSTCTBK.PY(AMAT)
#   __script_description : THIS SCRIPT IS USED TO UPDATE CONTACT DATA FROM STAGING TABLE TO THE MAIN TABLE
#   __primary_author__ : SURESH MUNIYANDI
#   __create_date :
#   © BOSTON HARBOR TECHNOLOGY LLC - ALL RIGHTS RESERVED
# ==========================================================================================================================================
import sys
import datetime
import clr

clr.AddReference("System.Net")
from System.Net import CookieContainer, NetworkCredential, Mail
from System.Net.Mail import SmtpClient, MailAddress, Attachment, MailMessage

try:
	sessionid = SqlHelper.GetFirst("SELECT NEWID() AS Guid")
	timestamp_sessionid = "'" + str(sessionid.Guid) + "'"

	Parameter = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'SELECT' ")
	Parameter1 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'UPD' ")
	Parameter2 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'DEL' ")

	today = datetime.datetime.now()
	Modi_date = today.strftime("%m/%d/%Y %H:%M:%S %p")
	
	
	#Pick Latest One 
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCNRT_INBOUND SET PROCESS_STATUS=''DUPLICATE'' FROM CTCNRT_INBOUND (NOLOCK)  JOIN (SELECT CONTRACT_ID,MAX(CPQTABLEENTRYID) AS CPQTABLEENTRYID FROM CTCNRT_INBOUND(NOLOCK) GROUP BY CONTRACT_ID HAVING COUNT(CPQTABLEENTRYID)>1)SUB_CTCNRT ON CTCNRT_INBOUND.CONTRACT_ID = SUB_CTCNRT.CONTRACT_ID WHERE CTCNRT_INBOUND.CPQTABLEENTRYID <> SUB_CTCNRT.CPQTABLEENTRYID  ' "
	)
	
	#Timestamp Update
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCNRT_INBOUND set CTCNRT_INBOUND.process_status=''Inprogress'',CTCNRT_INBOUND.integration_status='''',CTCNRT_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' FROM CTCNRT_INBOUND (NOLOCK) where isnull(CTCNRT_INBOUND.process_status,'''')='''' and isnull(CTCNRT_INBOUND.session_id,'''')<>'''' ' "
	)
	
	#Status Change in all child tables 
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND set CTCICO_INBOUND.process_status=''Inprogress'',CTCICO_INBOUND.integration_status='''',CTCICO_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' FROM CTCICO_INBOUND (NOLOCK) where isnull(CTCICO_INBOUND.session_id,'''') in (SELECT SESSION_ID FROM CTCNRT_INBOUND(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND ISNULL(TIMESTAMP,'''') = '"+ str(timestamp_sessionid)+ "')  ' ")
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCSCE_INBOUND set CTCSCE_INBOUND.process_status=''Inprogress'',CTCSCE_INBOUND.integration_status='''',CTCSCE_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' FROM CTCSCE_INBOUND (NOLOCK) where isnull(CTCSCE_INBOUND.session_id,'''') in (SELECT SESSION_ID FROM CTCNRT_INBOUND(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND ISNULL(TIMESTAMP,'''') = '"+ str(timestamp_sessionid)+ "') '")
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND set CTCIFP_INBOUND.process_status=''Inprogress'',CTCIFP_INBOUND.INTEGRATION_STTAUS='''',CTCIFP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' FROM CTCIFP_INBOUND (NOLOCK) where isnull(CTCIFP_INBOUND.session_id,'''') in (SELECT SESSION_ID FROM CTCNRT_INBOUND(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND ISNULL(TIMESTAMP,'''') = '"+ str(timestamp_sessionid)+ "') '")
	
		
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCTIP_INBOUND set CTCTIP_INBOUND.process_status=''Inprogress'',CTCTIP_INBOUND.integration_status='''',CTCTIP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' FROM CTCTIP_INBOUND (NOLOCK) where isnull(CTCTIP_INBOUND.session_id,'''') in (SELECT SESSION_ID FROM CTCNRT_INBOUND(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND ISNULL(TIMESTAMP,'''') = '"+ str(timestamp_sessionid)+ "')'" )
		
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND set CTCITM_INBOUND.process_status=''Inprogress'',CTCITM_INBOUND.integration_status='''',CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' FROM CTCITM_INBOUND (NOLOCK) where isnull(CTCITM_INBOUND.session_id,'''') in (SELECT SESSION_ID FROM CTCNRT_INBOUND(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND ISNULL(TIMESTAMP,'''') = '"+ str(timestamp_sessionid)+ "')'" )
	
	#Business Validation Starts 
	#CTCNRT
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCNRT_INBOUND SET CTCNRT_INBOUND.INTEGRATION_STATUS = ISNULL(CTCNRT_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCNRT_INBOUND.CONTRACT_CURRENCY),CTCNRT_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCNRT_INBOUND(NOLOCK) LEFT JOIN PRCURR (NOLOCK) ON CTCNRT_INBOUND.CONTRACT_CURRENCY = PRCURR.CURRENCY  LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200051'' WHERE CTCNRT_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCNRT'' AND CTCNRT_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND PRCURR.CURRENCY IS NULL AND CTCNRT_INBOUND.CONTRACT_CURRENCY <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  CTCNRT_INBOUND SET CTCNRT_INBOUND.INTEGRATION_STATUS = ISNULL(CTCNRT_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCNRT_INBOUND.CONTRACT_CURRENCY),CTCNRT_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCNRT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200052'' WHERE CTCNRT_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCNRT'' AND CTCNRT_INBOUND.TIMESTAMP='"
			+ str(timestamp_sessionid)
			+ "' AND  ISNULL(CONTRACT_CURRENCY,'''') = '''' '"
		)

	primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  CTCNRT_INBOUND SET CTCNRT_INBOUND.INTEGRATION_STATUS = ISNULL(CTCNRT_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCNRT_INBOUND.CONTRACT_ID),CTCNRT_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCNRT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200053'' WHERE CTCNRT_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCNRT'' AND CTCNRT_INBOUND.TIMESTAMP='"
			+ str(timestamp_sessionid)
			+ "' AND  ISNULL(CONTRACT_ID,'''') = '''' '"
		) 
		
	primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  CTCNRT_INBOUND SET CTCNRT_INBOUND.INTEGRATION_STATUS = ISNULL(CTCNRT_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCNRT_INBOUND.CONTRACT_NAME),CTCNRT_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCNRT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200054'' WHERE CTCNRT_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCNRT'' AND CTCNRT_INBOUND.TIMESTAMP='"
			+ str(timestamp_sessionid)
			+ "' AND  ISNULL(CONTRACT_NAME,'''') = '''' '"
		)
		
	primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  CTCNRT_INBOUND SET CTCNRT_INBOUND.INTEGRATION_STATUS = ISNULL(CTCNRT_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCNRT_INBOUND.CONTRACT_VALID_FROM),CTCNRT_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCNRT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200055'' WHERE CTCNRT_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCNRT'' AND CTCNRT_INBOUND.TIMESTAMP='"
			+ str(timestamp_sessionid)
			+ "' AND  ISNULL(CONTRACT_VALID_FROM,'''') = '''' '"
		)
		
	primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  CTCNRT_INBOUND SET CTCNRT_INBOUND.INTEGRATION_STATUS = ISNULL(CTCNRT_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCNRT_INBOUND.CONTRACT_VALID_TO),CTCNRT_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCNRT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200056'' WHERE CTCNRT_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCNRT'' AND CTCNRT_INBOUND.TIMESTAMP='"
			+ str(timestamp_sessionid)
			+ "' AND  ISNULL(CONTRACT_VALID_TO,'''') = '''' '"
		)

	#CTCITM 
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.CURRENCY),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK) LEFT JOIN PRCURR  (NOLOCK) ON CTCITM_INBOUND.CURRENCY = PRCURR.CURRENCY  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200059'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND PRCURR.CURRENCY IS NULL AND CTCITM_INBOUND.CURRENCY <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.DIVISION_ID),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK) LEFT JOIN SADIVN (NOLOCK) ON CTCITM_INBOUND.DIVISION_ID = SADIVN.DIVISION_ID  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200060'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND SADIVN.DIVISION_ID IS NULL AND CTCITM_INBOUND.DIVISION_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.CONTRACT_ID),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK) LEFT JOIN CTCNRT_INBOUND  (NOLOCK) ON CTCITM_INBOUND.CONTRACT_ID = CTCNRT_INBOUND.CONTRACT_ID  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200061'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND CTCNRT_INBOUND.CONTRACT_ID IS NULL AND CTCITM_INBOUND.CONTRACT_ID <> '''''"
	) 

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.SERVICE_ID),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK)  LEFT JOIN MAMTRL (NOLOCK) ON CTCITM_INBOUND.SERVICE_ID = MAMTRL.SAP_PART_NUMBER  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200062'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND MAMTRL.SAP_PART_NUMBER IS NULL AND CTCITM_INBOUND.SERVICE_ID <> '''''"
	) 

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.UOM_ID),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK) LEFT JOIN MAMUOM(NOLOCK) ON CTCITM_INBOUND.UOM_ID = MAMUOM.UOM  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200063'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND MAMUOM.UOM IS NULL AND CTCITM_INBOUND.UOM_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.CURRENCY),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200066'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(CURRENCY,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.DIVISION_ID),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200067'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(DIVISION_ID,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.LINE_ITEM_ID),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200068'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(LINE_ITEM_ID,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.CONTRACT_ID),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200069'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(CONTRACT_ID,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.SERVICE_ID),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK)  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200070'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(SERVICE_ID,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET CTCITM_INBOUND.INTEGRATION_STATUS = ISNULL(CTCITM_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCITM_INBOUND.UOM_ID),CTCITM_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND(NOLOCK)  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200071'' WHERE CTCITM_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCITM'' AND CTCITM_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(UOM_ID,'''') = '''' '"
	)
	
	#CTCICO
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  CTCICO_INBOUND SET CTCICO_INBOUND.INTEGRATION_STATUS = ISNULL(CTCICO_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCICO_INBOUND.EQUIPMENT_ID),CTCICO_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCICO_INBOUND(NOLOCK) LEFT JOIN MAEQUP  (NOLOCK) ON CTCICO_INBOUND.EQUIPMENT_ID = MAEQUP.EQUIPMENT_ID  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200072'' WHERE CTCICO_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCICO'' AND CTCICO_INBOUND.TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "'  AND MAEQUP.EQUIPMENT_ID IS NULL AND CTCICO_INBOUND.EQUIPMENT_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET CTCICO_INBOUND.INTEGRATION_STATUS = ISNULL(CTCICO_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCICO_INBOUND.LINE_ITEM_ID),CTCICO_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCICO_INBOUND(NOLOCK) LEFT JOIN  CTCITM_INBOUND (NOLOCK) ON CTCICO_INBOUND.LINE_ITEM_ID = CTCITM_INBOUND.LINE_ITEM_ID  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200073'' WHERE CTCICO_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCICO'' AND CTCICO_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND CTCITM_INBOUND.LINE_ITEM_ID IS NULL AND CTCICO_INBOUND.LINE_ITEM_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET CTCICO_INBOUND.INTEGRATION_STATUS = ISNULL(CTCICO_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCICO_INBOUND.CONTRACT_ID),CTCICO_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCICO_INBOUND(NOLOCK) LEFT JOIN CTCNRT_INBOUND (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCNRT_INBOUND.CONTRACT_ID  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200074'' WHERE CTCICO_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCICO'' AND CTCICO_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND CTCNRT_INBOUND.CONTRACT_ID IS NULL AND CTCICO_INBOUND.CONTRACT_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET CTCICO_INBOUND.INTEGRATION_STATUS = ISNULL(CTCICO_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCICO_INBOUND.SERIAL_NO),CTCICO_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCICO_INBOUND(NOLOCK) LEFT JOIN MAEQUP (NOLOCK) ON CTCICO_INBOUND.SERIAL_NO = MAEQUP.SERIAL_NO  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200075'' WHERE CTCICO_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCICO'' AND CTCICO_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND MAEQUP.SERIAL_NO IS NULL AND CTCICO_INBOUND.SERIAL_NO <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET CTCICO_INBOUND.INTEGRATION_STATUS = ISNULL(CTCICO_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCICO_INBOUND.EQUIPMENT_ID),CTCICO_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCICO_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200076'' WHERE CTCICO_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCICO'' AND CTCICO_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(EQUIPMENT_ID,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET CTCICO_INBOUND.INTEGRATION_STATUS = ISNULL(CTCICO_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCICO_INBOUND.LINE_ITEM_ID),CTCICO_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCICO_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200077'' WHERE CTCICO_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCICO'' AND CTCICO_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(LINE_ITEM_ID,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET CTCICO_INBOUND.INTEGRATION_STATUS = ISNULL(CTCICO_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCICO_INBOUND.CONTRACT_ID),CTCICO_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCICO_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200078'' WHERE CTCICO_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCICO'' AND CTCICO_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(CONTRACT_ID,'''') = '''' '"
	)

	#CTCSCE 
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET CTCICO_INBOUND.INTEGRATION_STATUS = ISNULL(CTCICO_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCICO_INBOUND.CONTRACT_ID),CTCICO_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCICO_INBOUND(NOLOCK) LEFT JOIN CTCNRT_INBOUND (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCNRT_INBOUND.CONTRACT_ID  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200080'' WHERE CTCICO_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCSCE'' AND CTCNRT_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND CTCNRT_INBOUND.CONTRACT_ID IS NULL AND CTCICO_INBOUND.CONTRACT_ID <> '''''"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCSCE_INBOUND SET CTCSCE_INBOUND.INTEGRATION_STATUS = ISNULL(CTCSCE_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCSCE_INBOUND.ENTITLEMENT_NAME),CTCSCE_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCSCE_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200081'' WHERE CTCSCE_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCSCE'' AND CTCSCE_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(ENTITLEMENT_NAME,'''') = '''' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCSCE_INBOUND SET CTCSCE_INBOUND.INTEGRATION_STATUS = ISNULL(CTCSCE_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCSCE_INBOUND.CONTRACT_ID),CTCSCE_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCSCE_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200083'' WHERE CTCSCE_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCSCE'' AND CTCSCE_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(CONTRACT_ID,'''') = '''' '"
	)
	
	#CTCIFP 
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET CTCIFP_INBOUND.INTEGRATION_STTAUS = ISNULL(CTCIFP_INBOUND.INTEGRATION_STTAUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCIFP_INBOUND.CONTRACT_ID),CTCIFP_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCIFP_INBOUND(NOLOCK) LEFT JOIN CTCNRT_INBOUND(NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID = CTCNRT_INBOUND.CONTRACT_ID  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200084'' WHERE CTCIFP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCIFP'' AND CTCIFP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND CTCNRT_INBOUND.CONTRACT_ID IS NULL AND CTCIFP_INBOUND.CONTRACT_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET CTCIFP_INBOUND.INTEGRATION_STTAUS = ISNULL(CTCIFP_INBOUND.INTEGRATION_STTAUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCIFP_INBOUND.PART_NUMBER),CTCIFP_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCIFP_INBOUND(NOLOCK) LEFT JOIN MAMTRL(NOLOCK) ON CTCIFP_INBOUND.PART_NUMBER = MAMTRL.SAP_PART_NUMBER  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200085'' WHERE CTCIFP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCIFP'' AND CTCIFP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND MAMTRL.SAP_PART_NUMBER IS NULL AND CTCIFP_INBOUND.PART_NUMBER <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET CTCIFP_INBOUND.INTEGRATION_STTAUS = ISNULL(CTCIFP_INBOUND.INTEGRATION_STTAUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCIFP_INBOUND.LINE_ITEM_ID),CTCIFP_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCIFP_INBOUND(NOLOCK) LEFT JOIN CTCITM_INBOUND(NOLOCK) ON CTCIFP_INBOUND.LINE_ITEM_ID = CTCITM_INBOUND.LINE_ITEM_ID  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200086'' WHERE CTCIFP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCIFP'' AND CTCIFP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND CTCITM_INBOUND.LINE_ITEM_ID IS NULL AND CTCIFP_INBOUND.LINE_ITEM_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET CTCIFP_INBOUND.INTEGRATION_STTAUS = ISNULL(CTCIFP_INBOUND.INTEGRATION_STTAUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCIFP_INBOUND.LINE_ITEM_ID),CTCIFP_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCIFP_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200087'' WHERE CTCIFP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCIFP'' AND CTCIFP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(LINE_ITEM_ID,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET CTCIFP_INBOUND.INTEGRATION_STTAUS = ISNULL(CTCIFP_INBOUND.INTEGRATION_STTAUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCIFP_INBOUND.PART_NUMBER),CTCIFP_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCIFP_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200088'' WHERE CTCIFP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCIFP'' AND CTCIFP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(PART_NUMBER,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET CTCIFP_INBOUND.INTEGRATION_STTAUS = ISNULL(CTCIFP_INBOUND.INTEGRATION_STTAUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCIFP_INBOUND.CONTRACT_ID),CTCIFP_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCIFP_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200089'' WHERE CTCIFP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCIFP'' AND CTCIFP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(CONTRACT_ID,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET CTCIFP_INBOUND.INTEGRATION_STTAUS = ISNULL(CTCIFP_INBOUND.INTEGRATION_STTAUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCIFP_INBOUND.VALID_FROM_DATE),CTCIFP_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCIFP_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200090'' WHERE CTCIFP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCIFP'' AND CTCIFP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(VALID_FROM_DATE,'''') = '''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET CTCIFP_INBOUND.INTEGRATION_STTAUS = ISNULL(CTCIFP_INBOUND.INTEGRATION_STTAUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCIFP_INBOUND.VALID_TO_DATE),CTCIFP_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCIFP_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200091'' WHERE CTCIFP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCIFP'' AND CTCIFP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(VALID_TO_DATE,'''') = '''' '"
	)
	
	#CTCTIP 
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCTIP_INBOUND SET CTCTIP_INBOUND.INTEGRATION_STATUS = ISNULL(CTCTIP_INBOUND.INTEGRATION_STATUS,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,CTCTIP_INBOUND.CONTRACT_ID),CTCTIP_INBOUND.PROCESS_STATUS=''ERROR'' FROM CTCTIP_INBOUND(NOLOCK) LEFT JOIN CTCNRT_INBOUND(NOLOCK) ON CTCTIP_INBOUND.CONTRACT_ID = CTCNRT_INBOUND.CONTRACT_ID  LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200092'' WHERE CTCTIP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''CTCTIP'' AND CTCTIP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND CTCNRT_INBOUND.CONTRACT_ID IS NULL AND CTCTIP_INBOUND.CONTRACT_ID <> '''''"
	)

	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter2.QUERY_CRITERIA_1)
		+ "  CTCTIP_INBOUND FROM CTCTIP_INBOUND(NOLOCK) WHERE CTCTIP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND CTCTIP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND  ISNULL(PARTY_ID,'''') = '''' '"
	)
	
	# Validation Completed and updating process status as "READY FOR UPLOAD"
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCNRT_INBOUND SET PROCESS_STATUS=''READY FOR UPLOAD'' WHERE PROCESS_STATUS=''Inprogress'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET PROCESS_STATUS=''READY FOR UPLOAD'' WHERE PROCESS_STATUS=''Inprogress'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET PROCESS_STATUS=''READY FOR UPLOAD'' WHERE PROCESS_STATUS=''Inprogress'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCSCE_INBOUND SET PROCESS_STATUS=''READY FOR UPLOAD'' WHERE PROCESS_STATUS=''Inprogress'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET PROCESS_STATUS=''READY FOR UPLOAD'' WHERE PROCESS_STATUS=''Inprogress'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STTAUS,'''')='''' '"
	)
	
		
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCTIP_INBOUND SET PROCESS_STATUS=''READY FOR UPLOAD'' WHERE PROCESS_STATUS=''Inprogress'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)
	
	# Updating Error sessions in "ERROR_SESSION" table

	# Dynamically creating ERROR_SESSION table
	Temp_Table_Name = 'ERROR_SESSION'
	
	ERRLOG_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(Temp_Table_Name)+"'' ) BEGIN DROP TABLE "+str(Temp_Table_Name)+" END  ' ")

	TempTable = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(Temp_Table_Name)+"'' ) BEGIN DROP TABLE "+str(Temp_Table_Name)+" END CREATE TABLE "+str(Temp_Table_Name)+" (SESSION_ID VARCHAR(100),INTEGRATION_TYPE VARCHAR(100) ,PROCESS_STATUS VARCHAR(100) ,ERROR_MESSAGE VARCHAR(4000),ERROR_DESCRIPTION VARCHAR(4000),TIMESTAMP VARCHAR(250),CpqTableEntryDateModified date)'")
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " ERROR_SESSION (SESSION_ID,CpqTableEntryDateModified,INTEGRATION_TYPE) SELECT SESSION_ID,getdate(),''CRM-CPQ'' FROM (	SELECT DISTINCT CTCNRT_INBOUND.SESSION_ID as SESSION_ID FROM CTCNRT_INBOUND (NOLOCK) WHERE  ISNULL(CTCNRT_INBOUND.PROCESS_STATUS,'''')=''ERROR'' AND CTCNRT_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "'  union SELECT CTCITM_INBOUND.SESSION_ID FROM CTCITM_INBOUND (NOLOCK)  WHERE  ISNULL(CTCITM_INBOUND.PROCESS_STATUS,'''')=''ERROR'' AND CTCITM_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' UNION SELECT CTCICO_INBOUND.SESSION_ID FROM CTCICO_INBOUND(NOLOCK) WHERE  ISNULL(CTCICO_INBOUND.PROCESS_STATUS,'''')=''ERROR'' AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)	+ "' UNION SELECT CTCSCE_INBOUND.SESSION_ID FROM CTCSCE_INBOUND (NOLOCK)  WHERE  ISNULL(CTCSCE_INBOUND.PROCESS_STATUS,'''')=''ERROR'' AND CTCSCE_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)	+ "'UNION SELECT CTCIFP_INBOUND.SESSION_ID FROM CTCIFP_INBOUND (NOLOCK) WHERE  ISNULL(CTCIFP_INBOUND.PROCESS_STATUS,'''')=''ERROR'' AND CTCIFP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "'UNION  SELECT CTCTIP_INBOUND.SESSION_ID FROM CTCTIP_INBOUND (NOLOCK)  WHERE  ISNULL(CTCTIP_INBOUND.PROCESS_STATUS,'''')=''ERROR'' AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')SUB_INBOUND  ' ")
	
	# Updating process status as "ERROR"
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCNRT_INBOUND SET PROCESS_STATUS=''ERROR'' FROM CTCNRT_INBOUND JOIN ERROR_SESSION ON CTCNRT_INBOUND.SESSION_ID = ERROR_SESSION.SESSION_ID WHERE TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET PROCESS_STATUS=''ERROR'' FROM CTCITM_INBOUND  JOIN ERROR_SESSION ON CTCITM_INBOUND.SESSION_ID = ERROR_SESSION.SESSION_ID WHERE TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET PROCESS_STATUS=''ERROR'' FROM CTCICO_INBOUND JOIN ERROR_SESSION ON CTCICO_INBOUND.SESSION_ID = ERROR_SESSION.SESSION_ID WHERE TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCSCE_INBOUND SET PROCESS_STATUS=''ERROR'' FROM CTCSCE_INBOUND JOIN ERROR_SESSION ON CTCSCE_INBOUND.SESSION_ID = ERROR_SESSION.SESSION_ID WHERE TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET PROCESS_STATUS=''ERROR'' FROM CTCIFP_INBOUND JOIN ERROR_SESSION ON CTCIFP_INBOUND.SESSION_ID = ERROR_SESSION.SESSION_ID WHERE TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' '"
	)
	
		
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCTIP_INBOUND SET PROCESS_STATUS=''ERROR'' FROM CTCTIP_INBOUND  JOIN ERROR_SESSION  ON CTCTIP_INBOUND.SESSION_ID = ERROR_SESSION.SESSION_ID WHERE TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' '"
	)
	
	#Upload Starts
	
	#Quote Status
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  SAQTMT SET CpqTableEntryModifiedBy = ''"
	+ str(User.Id)
	+ "'',CpqTableEntryDateModified = GetDate(),QUOTE_STATUS=''CONVERTED TO CONTRACT'',CRM_CONTRACT_ID=CONTRACT_ID FROM CTCNRT_INBOUND(NOLOCK) JOIN SAQTMT(NOLOCK) ON SAQTMT.C4C_QUOTE_ID = CTCNRT_INBOUND.QUOTE_ID WHERE CTCNRT_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''   AND CTCNRT_INBOUND.TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "' AND QUOTE_STATUS=''BOOKING SUBMITTED'' ' "
	)
	
	#CTCNRT 
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  CTCNRT SET CTCNRT.CpqTableEntryModifiedBy = ''"
	+ str(User.Id)
	+ "'',CTCNRT.CpqTableEntryDateModified = GetDate(),CTCNRT.CANCELLATION_PERIOD = CTCNRT_INBOUND.CANCELLATION_PERIOD,  CTCNRT.CONTRACT_CURRENCY = PRCURR.CURRENCY, CTCNRT.CONTRACT_CURRENCY_RECORD_ID = PRCURR.CURRENCY_RECORD_ID ,CTCNRT.CONTRACT_NAME = CTCNRT_INBOUND.CONTRACT_NAME,CTCNRT.CONTRACT_STATUS = CTCNRT_INBOUND.CONTRACT_STATUS,CTCNRT.CONTRACT_VALID_FROM = CTCNRT_INBOUND.CONTRACT_VALID_FROM,CTCNRT.CONTRACT_VALID_TO = CTCNRT_INBOUND.CONTRACT_VALID_TO,CTCNRT.CUSTOMER_NOTES = CTCNRT_INBOUND.CUSTOMER_NOTES,CTCNRT.NET_VALUE = CTCNRT_INBOUND.NET_VALUE,CTCNRT.PRICING_DATE = CTCNRT_INBOUND.PRICING_DATE,CTCNRT.PO_DATE = CTCNRT_INBOUND.PO_DATE,CTCNRT.PO_NOTES = CTCNRT_INBOUND.PO_NOTES,CTCNRT.PO_NUMBER = CTCNRT_INBOUND.PO_NUMBER FROM CTCNRT_INBOUND(NOLOCK) JOIN PRCURR(NOLOCK) on CTCNRT_INBOUND.CONTRACT_CURRENCY = PRCURR.CURRENCY LEFT  JOIN CTCNRT(NOLOCK) ON CTCNRT_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID   WHERE CTCNRT_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''   AND CTCNRT_INBOUND.TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "'  ' "
	)

	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " CTCNRT (ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_RECORD_ID,CANCELLATION_PERIOD,CONTRACT_CURRENCY,CONTRACT_CURRENCY_RECORD_ID ,CONTRACT_ID,CONTRACT_NAME,CONTRACT_STATUS,CONTRACT_TYPE,CONTRACT_VALID_FROM,CONTRACT_VALID_TO,CUSTOMER_NOTES,INCOTERMS,INCOTERMS_LOCATION,NET_VALUE,PRICING_DATE,PO_DATE,PO_NOTES,PO_NUMBER,REASONFOR_REJECTION ,CONTRACT_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_CTCNRT.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',GETDATE() FROM (SELECT DISTINCT (SELECT SAACNT.ACCOUNT_ID FROM CTCTIP_INBOUND (NOLOCK) JOIN SAACNT (NOLOCK) ON (REPLICATE(''0'',10-LEN(CTCTIP_INBOUND.PARTY_ID))+CTCTIP_INBOUND.PARTY_ID) = ACCOUNT_ID WHERE PARTY_ROLE=''SOLD_TO'' AND CTCNRT_INBOUND.CONTRACT_ID = CTCTIP_INBOUND.CONTRACT_ID  AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')AS ACCOUNT_ID, (SELECT SAACNT.ACCOUNT_NAME FROM CTCTIP_INBOUND (NOLOCK) JOIN SAACNT (NOLOCK) ON (REPLICATE(''0'',10-LEN(CTCTIP_INBOUND.PARTY_ID))+CTCTIP_INBOUND.PARTY_ID) = ACCOUNT_ID WHERE PARTY_ROLE=''SOLD_TO'' AND CTCNRT_INBOUND.CONTRACT_ID = CTCTIP_INBOUND.CONTRACT_ID AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')AS ACCOUNT_NAME,(SELECT SAACNT.ACCOUNT_RECORD_ID FROM CTCTIP_INBOUND(NOLOCK) JOIN SAACNT (NOLOCK) ON (REPLICATE(''0'',10-LEN(CTCTIP_INBOUND.PARTY_ID))+CTCTIP_INBOUND.PARTY_ID) = ACCOUNT_ID WHERE PARTY_ROLE=''SOLD_TO'' AND CTCNRT_INBOUND.CONTRACT_ID = CTCTIP_INBOUND.CONTRACT_ID AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "') AS ACCOUNT_RECORD_ID,CTCNRT_INBOUND.CANCELLATION_PERIOD,PRCURR.CURRENCY AS CONTRACT_CURRENCY,PRCURR.CURRENCY_RECORD_ID  AS CONTRACT_CURRENCY_RECORD_ID,CTCNRT_INBOUND.CONTRACT_ID,CTCNRT_INBOUND.CONTRACT_NAME,CTCNRT_INBOUND.CONTRACT_STATUS,CASE WHEN CTCNRT_INBOUND.CONTRACT_TYPE = ''ZTBC'' THEN ''ZTBC - TOOL BASED'' WHEN CTCNRT_INBOUND.CONTRACT_TYPE = ''ZNBC'' THEN ''ZNBC - NON TOOL BASED'' WHEN CTCNRT_INBOUND.CONTRACT_TYPE = ''ZWK1'' THEN ''ZWK1 - SPARES'' ELSE CTCNRT_INBOUND.CONTRACT_TYPE END AS CONTRACT_TYPE,CONVERT(DATE,CTCNRT_INBOUND.CONTRACT_VALID_FROM) AS CONTRACT_VALID_FROM,CONVERT(DATE,CTCNRT_INBOUND.CONTRACT_VALID_TO) AS CONTRACT_VALID_TO,CTCNRT_INBOUND.CUSTOMER_NOTES,CTCNRT_INBOUND.INCOTERMS,CTCNRT_INBOUND.INCOTERMS_LOCATION,CTCNRT_INBOUND.NET_VALUE,CONVERT(DATE,CTCNRT_INBOUND.PRICING_DATE) AS PRICING_DATE,CONVERT(DATE,CTCNRT_INBOUND.PO_DATE) AS PO_DATE,CTCNRT_INBOUND.PO_NOTES,CTCNRT_INBOUND.PO_NUMBER,CTCNRT_INBOUND.REASONFOR_REJECTION FROM CTCNRT_INBOUND(NOLOCK) JOIN PRCURR(NOLOCK) on CTCNRT_INBOUND.CONTRACT_CURRENCY = PRCURR.CURRENCY  WHERE CTCNRT_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCNRT_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')SUB_CTCNRT LEFT JOIN CTCNRT(NOLOCK) ON SUB_CTCNRT.CONTRACT_ID = CTCNRT.CONTRACT_ID WHERE CTCNRT.CONTRACT_ID IS NULL '")
	
	#CTCTSO
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " CTCTSO (ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_RECORD_ID,CONTRACT_CURRENCY,CONTRACT_CURRENCY_RECORD_ID,CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,DISTRIBUTIONCHANNEL_ID,DISTRIBUTIONCHANNEL_RECORD_ID,DIVISION_ID,DIVISION_RECORD_ID,SARACC_RECORD_ID,SALESOFFICE_ID,SALESOFFICE_NAME,SALESOFFICE_RECORD_ID,SORG_CURRENCY,SORGCURRENCY_RECORD_ID,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,CONTRACT_SALES_ORG_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified)SELECT DISTINCT SUB_CTCTSO.*,CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CTCNRT.ACCOUNT_ID,CTCNRT.ACCOUNT_NAME,CTCNRT.ACCOUNT_RECORD_ID,CTCNRT.CONTRACT_CURRENCY,CTCNRT.CONTRACT_CURRENCY_RECORD_ID,CTCNRT.CONTRACT_ID,CTCNRT.CONTRACT_NAME,CTCNRT.CONTRACT_RECORD_ID,(SELECT DISTINCT DISTRIBUTIONCHANNEL_ID FROM SADSCH(NOLOCK) WHERE DISTRIBUTIONCHANNEL_ID=''01'') AS DISTRIBUTIONCHANNEL_ID,(SELECT DISTINCT DISTRIBUTION_CHANNEL_RECORD_ID FROM SADSCH(NOLOCK) WHERE DISTRIBUTIONCHANNEL_ID=''01'') AS DISTRIBUTION_CHANNEL_RECORD_ID,(SELECT DISTINCT DIVISION_ID FROM SADIVN(NOLOCK) WHERE DIVISION_ID=''98'') AS DIVISION_ID,(SELECT DISTINCT DIVISION_RECORD_ID FROM SADIVN(NOLOCK) WHERE DIVISION_ID=''98'') AS DIVISION_RECORD_ID ,NULL AS SARACC_RECORD_ID,CTCNRT_INBOUND.SALESOFFICE_ID,SASLOF.SALES_OFFICE_NAME,SASLOF.SALES_OFFICE_RECORD_ID,DEF_CURRENCY AS SORG_CURRENCY,DEF_CURRENCY_RECORD_ID AS SORGCURRENCY_RECORD_ID,SASORG.SALESORG_ID,SASORG.SALESORG_NAME,SASORG.SALES_ORG_RECORD_ID FROM CTCNRT_INBOUND(NOLOCK) JOIN CTCNRT(NOLOCK) ON CTCNRT_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID LEFT JOIN SASLOF(NOLOCK) ON CTCNRT_INBOUND.SALESOFFICE_ID = SASLOF.SALES_OFFICE_ID JOIN SASORG(NOLOCK) ON CTCNRT_INBOUND.SALESORG_ID = SASORG.SALESORG_ID WHERE CTCNRT_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''   AND CTCNRT_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' )SUB_CTCTSO LEFT JOIN CTCTSO (NOLOCK) ON SUB_CTCTSO.CONTRACT_ID = CTCTSO.CONTRACT_ID AND SUB_CTCTSO.SALESORG_ID = CTCTSO.SALESORG_ID WHERE CTCTSO.CONTRACT_ID IS NULL   '")

	#CTCTIP Uploaded 
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " CTCTIP (ADDRESS,CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,EMAIL,IS_MAIN,PARTY_ID,PARTY_NAME,PARTY_RECORD_ID,PARTY_ROLE,PHONE,CONTRACT_INVOLVED_PARTIES_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified)SELECT SUB_CTCTIP.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT ISNULL(SAACNT.ADDRESS_1,'''')+'' ''+ISNULL(SAACNT.ADDRESS_2,'''')+'' ''+ISNULL(SAACNT.ADDRESS_3,'''')+'' ''+ISNULL(SAACNT.CITY,'''')+'' ''+ISNULL(SAACNT.COUNTRY,'''') AS ADDRESS,CTCNRT.CONTRACT_ID,CTCNRT.CONTRACT_NAME,CTCNRT.CONTRACT_RECORD_ID,SAACNT.EMAIL, ''TRUE'' AS IS_MAIN, SAACNT.ACCOUNT_ID AS PARTY_ID, SAACNT.ACCOUNT_NAME, SAACNT.ACCOUNT_RECORD_ID,''PAYER'' AS PARTY_ROLE, SAACNT.PHONE FROM CTCTIP_INBOUND(NOLOCK) JOIN CTCNRT(NOLOCK) on CTCTIP_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID JOIN SAACNT(NOLOCK) ON (''STP-''+REPLICATE(''0'',10-LEN(CTCTIP_INBOUND.PARTY_ID))+CTCTIP_INBOUND.PARTY_ID) = SAACNT.ACCOUNT_ID WHERE CTCTIP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND CTCTIP_INBOUND.PARTY_ROLE = ''PAYER'' UNION SELECT DISTINCT ISNULL(SAACNT.ADDRESS_1,'''')+'' ''+ISNULL(SAACNT.ADDRESS_2,'''')+'' ''+ISNULL(SAACNT.ADDRESS_3,'''')+'' ''+ISNULL(SAACNT.CITY,'''')+'' ''+ISNULL(SAACNT.COUNTRY,'''') AS ADDRESS,CTCNRT.CONTRACT_ID,CTCNRT.CONTRACT_NAME,CTCNRT.CONTRACT_RECORD_ID,SAACNT.EMAIL, ''TRUE'' AS IS_MAIN, SAACNT.ACCOUNT_ID, SAACNT.ACCOUNT_NAME, SAACNT.ACCOUNT_RECORD_ID,''SOLD TO'' AS PARTY_ROLE, SAACNT.PHONE FROM CTCTIP_INBOUND(NOLOCK) JOIN CTCNRT(NOLOCK) on CTCTIP_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID JOIN SAACNT(NOLOCK) ON (''STP-''+REPLICATE(''0'',10-LEN(CTCTIP_INBOUND.PARTY_ID))+CTCTIP_INBOUND.PARTY_ID) = SAACNT.ACCOUNT_ID WHERE CTCTIP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND CTCTIP_INBOUND.PARTY_ROLE = ''SOLD_TO'' UNION SELECT DISTINCT ISNULL(SAACNT.ADDRESS_1,'''')+'' ''+ISNULL(SAACNT.ADDRESS_2,'''')+'' ''+ISNULL(SAACNT.ADDRESS_3,'''')+'' ''+ISNULL(SAACNT.CITY,'''')+'' ''+ISNULL(SAACNT.COUNTRY,'''') AS ADDRESS,CTCNRT.CONTRACT_ID,CTCNRT.CONTRACT_NAME,CTCNRT.CONTRACT_RECORD_ID,SAACNT.EMAIL, ''TRUE'' AS IS_MAIN, SAACNT.ACCOUNT_ID, SAACNT.ACCOUNT_NAME, SAACNT.ACCOUNT_RECORD_ID,''SHIP TO'' AS PARTY_ROLE, SAACNT.PHONE FROM CTCTIP_INBOUND(NOLOCK) JOIN CTCNRT(NOLOCK)  on CTCTIP_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID JOIN SAACNT(NOLOCK) ON REPLICATE(''0'',10-LEN(CTCTIP_INBOUND.PARTY_ID))+CTCTIP_INBOUND.PARTY_ID = SUBSTRING(SAACNT.ACCOUNT_ID,5,20) WHERE CTCTIP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND CTCTIP_INBOUND.PARTY_ROLE = ''SHIP_TO'' UNION SELECT DISTINCT ISNULL(SAACNT.ADDRESS_1,'''')+'' ''+ISNULL(SAACNT.ADDRESS_2,'''')+'' ''+ISNULL(SAACNT.ADDRESS_3,'''')+'' ''+ISNULL(SAACNT.CITY,'''')+'' ''+ISNULL(SAACNT.COUNTRY,'''') AS ADDRESS,CTCNRT.CONTRACT_ID,CTCNRT.CONTRACT_NAME,CTCNRT.CONTRACT_RECORD_ID,SAACNT.EMAIL, ''TRUE'' AS IS_MAIN, SAACNT.ACCOUNT_ID, SAACNT.ACCOUNT_NAME, SAACNT.ACCOUNT_RECORD_ID,''BILL TO'' AS PARTY_ROLE, SAACNT.PHONE FROM CTCTIP_INBOUND(NOLOCK) JOIN CTCNRT(NOLOCK) on CTCTIP_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID JOIN SAACNT(NOLOCK) ON REPLICATE(''0'',10-LEN(CTCTIP_INBOUND.PARTY_ID))+CTCTIP_INBOUND.PARTY_ID = SUBSTRING(SAACNT.ACCOUNT_ID,5,20) WHERE CTCTIP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND CTCTIP_INBOUND.PARTY_ROLE = ''BILL_TO'' UNION SELECT DISTINCT ISNULL(SAEMPL.ADDRESS_1,'''')+'' ''+ISNULL(SAEMPL.ADDRESS_2,'''')+'' ''+ISNULL(SAEMPL.CITY,'''')+'' ''+ISNULL(SAEMPL.COUNTRY,'''') AS ADDRESS,CTCNRT.CONTRACT_ID,CTCNRT.CONTRACT_NAME,CTCNRT.CONTRACT_RECORD_ID,SAEMPL.EMAIL, ''TRUE'' AS IS_MAIN, SAEMPL.EMPLOYEE_ID, SAEMPL.EMPLOYEE_NAME, SAEMPL.EMPLOYEE_RECORD_ID,''EMPLOYEE RESPONSIBLE'' AS PARTY_ROLE, SAEMPL.PHONE FROM CTCTIP_INBOUND(NOLOCK) JOIN CTCNRT(NOLOCK) on CTCTIP_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID LEFT JOIN SAEMPL(NOLOCK) ON CTCTIP_INBOUND.PARTY_ID = EMPLOYEE_ID WHERE CTCTIP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND CTCTIP_INBOUND.PARTY_ROLE = ''EMPLOYEE_RESPONSIBLE'' UNION SELECT DISTINCT ISNULL(SAEMPL.ADDRESS_1,'''')+'' ''+ISNULL(SAEMPL.ADDRESS_2,'''')+'' ''+ISNULL(SAEMPL.CITY,'''')+'' ''+ISNULL(SAEMPL.COUNTRY,'''') AS ADDRESS,CTCNRT.CONTRACT_ID,CTCNRT.CONTRACT_NAME,CTCNRT.CONTRACT_RECORD_ID,SAEMPL.EMAIL, ''TRUE'' AS IS_MAIN, SAEMPL.EMPLOYEE_ID, SAEMPL.EMPLOYEE_NAME, SAEMPL.EMPLOYEE_RECORD_ID,''CONTRACT MANAGER'' AS PARTY_ROLE, SAEMPL.PHONE FROM CTCTIP_INBOUND(NOLOCK) JOIN CTCNRT(NOLOCK) on CTCTIP_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID LEFT JOIN SAEMPL(NOLOCK) ON CTCTIP_INBOUND.PARTY_ID = EMPLOYEE_ID WHERE CTCTIP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND CTCTIP_INBOUND.PARTY_ROLE = ''CUSTOMER_CONTACT'' UNION SELECT DISTINCT ISNULL(SAEMPL.ADDRESS_1,'''')+'' ''+ISNULL(SAEMPL.ADDRESS_2,'''')+'' ''+ISNULL(SAEMPL.CITY,'''')+'' ''+ISNULL(SAEMPL.COUNTRY,'''') AS ADDRESS,CTCNRT.CONTRACT_ID,CTCNRT.CONTRACT_NAME,CTCNRT.CONTRACT_RECORD_ID,SAEMPL.EMAIL, ''TRUE'' AS IS_MAIN, SAEMPL.EMPLOYEE_ID, SAEMPL.EMPLOYEE_NAME, SAEMPL.EMPLOYEE_RECORD_ID,''SALES PERSON'' AS PARTY_ROLE, SAEMPL.PHONE FROM CTCTIP_INBOUND(NOLOCK) JOIN CTCNRT(NOLOCK) on CTCTIP_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID LEFT JOIN SAEMPL(NOLOCK) ON CTCTIP_INBOUND.PARTY_ID = EMPLOYEE_ID WHERE CTCTIP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCTIP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND CTCTIP_INBOUND.PARTY_ROLE = ''SALES_PERSON'')SUB_CTCTIP LEFT JOIN CTCTIP(NOLOCK) ON SUB_CTCTIP.CONTRACT_ID = CTCTIP.CONTRACT_ID AND SUB_CTCTIP.PARTY_ROLE = CTCTIP.PARTY_ROLE  WHERE CTCTIP.CONTRACT_ID IS NULL AND ISNULL(SUB_CTCTIP.PARTY_ID,'''')<>'''' '")
	
	#CTCITM

	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  CTCITM SET CTCITM.CpqTableEntryModifiedBy = ''"
	+ str(User.Id)
	+ "'',CTCITM.CpqTableEntryDateModified = GetDate(),CTCITM.CONTRACT_VALID_FROM = CONVERT(DATE,CTCITM_INBOUND.CONTRACT_VALID_FROM), CTCITM.CONTRACT_VALID_TO = CONVERT(DATE,CTCITM_INBOUND.CONTRACT_VALID_TO),CTCITM.DISCOUNT = CTCITM_INBOUND.DISCOUNT ,CTCITM.EXTENDED_PRICE = CTCITM_INBOUND.EXTENDED_PRICE,CTCITM.INTERNAL_NOTES = CTCITM_INBOUND.INTERNAL_NOTES,CTCITM.ITEM_STATUS = CTCITM_INBOUND.ITEM_STATUS,CTCITM.TAX = CTCITM_INBOUND.TAX FROM CTCITM_INBOUND(NOLOCK) JOIN CTCITM(NOLOCK) ON CTCITM_INBOUND.CONTRACT_ID = CTCITM.CONTRACT_ID  AND CTCITM_INBOUND.LINE_ITEM_ID = CTCITM.LINE_ITEM_ID WHERE CTCITM_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''   AND CTCITM_INBOUND.TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "'  ' "
	)

	primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter.QUERY_CRITERIA_1)+ " CTCITM (CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,CONTRACT_VALID_FROM,CONTRACT_VALID_TO,CONTRACT_CURRENCY,CONTRACT_CURRENCY_RECORD_ID,DIVISION_ID,DIVISION_RECORD_ID,EXTENDED_PRICE,ITEM_NOTES,LINE_ITEM_ID,MATERIALGROUP_ID,MATERIALGROUP_NAME,MATERIALGROUP_RECORD_ID,MAX_DELIVER_QTY,OBJECT_QUANTITY,QUANTITY,REASON_FOR_REJECTION,RELEASED_QUANTITY,REMAINING_QUANTITY,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,TAX,UOM_ID,UOM_RECORD_ID ,CONTRACT_ITEM_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_CTCITM.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',GETDATE() FROM (SELECT DISTINCT CTCTSO.CONTRACT_ID,CTCTSO.CONTRACT_NAME,CTCTSO.CONTRACT_RECORD_ID,CONVERT(DATE,MIN(CTCITM_INBOUND.CONTRACT_VALID_FROM)) AS CONTRACT_VALID_FROM,CONVERT(DATE,MAX(CTCITM_INBOUND.CONTRACT_VALID_TO)) AS CONTRACT_VALID_TO,PRCURR.CURRENCY,PRCURR.CURRENCY_RECORD_ID AS CURRENCY_RECORD_ID,SADIVN.DIVISION_ID,SADIVN.DIVISION_RECORD_ID,SUM(CTCITM_INBOUND.EXTENDED_PRICE) AS EXTENDED_PRICE,CTCITM_INBOUND.ITEM_NOTES,NULL AS LINE_ITEM_ID,MAMTRL.MATERIALGROUP_ID,MAMGRP.MATERIALGROUP_NAME,MAMTRL.MATERIALGROUP_RECORD_ID,CTCITM_INBOUND.MAX_DELIVER_QTY,CTCITM_INBOUND.OBJECT_QUANTITY,CTCITM_INBOUND.QUANTITY,CTCITM_INBOUND.REASON_FOR_REJECTION,CTCITM_INBOUND.RELEASED_QUANTITY,CTCITM_INBOUND.REMAINING_QUANTITY,CTCTSO.SALESORG_ID,CTCTSO.SALESORG_NAME,CTCTSO.SALESORG_RECORD_ID,MAMTRL.SAP_DESCRIPTION AS SERVICE_DESCRIPTION,MAMTRL.SAP_PART_NUMBER AS SERVICE_ID,MAMTRL.MATERIAL_RECORD_ID AS SERVICE_RECORD_ID,SUM(CTCITM_INBOUND.TAX) AS TAX,MAMTRL.UNIT_OF_MEASURE AS UOM_ID,MAMTRL.UOM_RECORD_ID  FROM CTCITM_INBOUND(NOLOCK)  JOIN CTCTSO(NOLOCK) ON CTCITM_INBOUND.CONTRACT_ID = CTCTSO.CONTRACT_ID JOIN MAMTRL(NOLOCK) ON CTCITM_INBOUND.SERVICE_ID = MAMTRL.SAP_PART_NUMBER JOIN PRCURR(NOLOCK) ON CTCITM_INBOUND.CURRENCY = PRCURR.CURRENCY LEFT JOIN MAMGRP(NOLOCK) ON MAMTRL.MATERIALGROUP_ID = MAMGRP.MATERIALGROUP_ID LEFT JOIN SADIVN(NOLOCK) ON CTCITM_INBOUND.DIVISION_ID = SADIVN.DIVISION_ID WHERE CTCITM_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCITM_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' GROUP BY CTCTSO.CONTRACT_ID,CTCTSO.CONTRACT_NAME,CTCTSO.CONTRACT_RECORD_ID,PRCURR.CURRENCY,PRCURR.CURRENCY_RECORD_ID ,SADIVN.DIVISION_ID,SADIVN.DIVISION_RECORD_ID,CTCITM_INBOUND.ITEM_NOTES,MAMTRL.MATERIALGROUP_ID,MAMGRP.MATERIALGROUP_NAME,MAMTRL.MATERIALGROUP_RECORD_ID,CTCITM_INBOUND.MAX_DELIVER_QTY,CTCITM_INBOUND.OBJECT_QUANTITY,CTCITM_INBOUND.QUANTITY,CTCITM_INBOUND.REASON_FOR_REJECTION,CTCITM_INBOUND.RELEASED_QUANTITY,CTCITM_INBOUND.REMAINING_QUANTITY,CTCTSO.SALESORG_ID,CTCTSO.SALESORG_NAME,CTCTSO.SALESORG_RECORD_ID,MAMTRL.SAP_DESCRIPTION ,MAMTRL.SAP_PART_NUMBER ,MAMTRL.MATERIAL_RECORD_ID ,MAMTRL.UNIT_OF_MEASURE ,MAMTRL.UOM_RECORD_ID )SUB_CTCITM LEFT JOIN CTCITM(NOLOCK) ON SUB_CTCITM.CONTRACT_ID = CTCITM.CONTRACT_ID and SUB_CTCITM.LINE_ITEM_ID = CTCITM.LINE_ITEM_ID WHERE CTCITM.CONTRACT_ID IS NULL '")
	
	primaryQueryItems = SqlHelper.GetFirst(""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  CTCITM set CTCITM.line_item_id =  SUB_CTCITM.line_item_Id FROM CTCITM(NOLOCK) JOIN(SELECT DISTINCT CONTRACT_ID,SERVICE_ID,ROW_NUMBER () OVER(PARTITION BY CONTRACT_ID ORDER BY CONTRACT_ID,cpqtableentryid) * 10 AS LINE_ITEM_ID FROM CTCITM (NOLOCK) ) SUB_CTCITM  ON CTCITM.CONTRACT_ID = SUB_CTCITM.CONTRACT_ID AND CTCITM.SERVICE_ID = SUB_CTCITM.SERVICE_ID  '")
	
	
	
	#CTCICO 
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  CTCICO SET CTCICO.CpqTableEntryModifiedBy = ''"
	+ str(User.Id)
	+ "'',CTCICO.CpqTableEntryDateModified = GetDate(),CTCICO.EXTENDED_PRICE = CTCITM_INBOUND.EXTENDED_PRICE,CTCICO.TAX = CTCITM_INBOUND.TAX,CTCICO.TOTAL_COST = ISNULL(CTCITM_INBOUND.EXTENDED_PRICE,0)-ISNULL(CTCITM_INBOUND.TAX,0) FROM CTCICO_INBOUND(NOLOCK) JOIN CTCITM_INBOUND(NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCITM_INBOUND.CONTRACT_ID AND CTCICO_INBOUND.LINE_ITEM_ID = CTCITM_INBOUND.LINE_ITEM_ID JOIN CTCICO(NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID and CTCICO_INBOUND.LINE_ITEM_ID = CTCICO.LINE_ITEM_ID  AND CTCICO.EQUIPMENT_ID = CTCICO_INBOUND.EQUIPMENT_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''   AND CTCICO_INBOUND.TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "'  ' "
	)
	
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " CTCICO (CONTRACT_ID,CNTITM_RECORD_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,CONTRACT_CURRENCY,CONTRACT_CURRENCY_RECORD_ID,CUSTOMER_TOOL_ID,DISCOUNT,EQUIPMENTCATEGORY_ID,EQUIPMENTCATEGORY_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_LINE_ID,EQUIPMENT_RECORD_ID,EQUIPMENT_STATUS,EQUIPMENTTYPE_ID,EQUIPMENTTYPE_RECORD_ID,EXTENDED_PRICE,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,GREENBOOK,GREENBOOK_RECORD_ID,LINE_ITEM_ID,MNT_PLANT_ID,MNT_PLANT_NAME,MNT_PLANT_RECORD_ID,MATERIAL_RECORD_ID,PLATFORM,PBG,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SAP_PART_NUMBER,SERIAL_NO,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,SUBSTRACT_SIZE,TAX,TECHNOLOGY,TOTAL_COST,WARRANTY_END_DATE,WARRANTY_START_DATE ,CONTRACT_ITEM_COVERED_OBJECT_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_CTCICO.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',GETDATE() FROM (SELECT DISTINCT CTCNRT.CONTRACT_ID,CTCITM.CONTRACT_ITEM_RECORD_ID AS CNTITM_RECORD_ID,CTCNRT.CONTRACT_NAME,CTCNRT.CONTRACT_RECORD_ID,PRCURR.CURRENCY,PRCURR.CURRENCY_RECORD_ID,MAEQUP.CUSTOMER_TOOL_ID,CTCITM_INBOUND.DISCOUNT,MAEQUP.EQUIPMENTCATEGORY_ID,MAEQUP.EQUIPMENTCATEGORY_RECORD_ID,MAEQUP.EQUIPMENT_DESCRIPTION,MAEQUP.EQUIPMENT_ID,CTCICO_INBOUND.LINE_ITEM_ID,MAEQUP.EQUIPMENT_RECORD_ID,MAEQUP.EQUIPMENT_STATUS,MAEQUP.EQUIPMENTTYPE_ID,MAEQUP.EQUIPMENTTYPE_RECORD_ID,CTCITM_INBOUND.EXTENDED_PRICE,MAEQUP.FABLOCATION_ID,MAEQUP.FABLOCATION_NAME,MAEQUP.FABLOCATION_RECORD_ID,MAEQUP.GREENBOOK,MAEQUP.GREENBOOK_RECORD_ID,CTCITM.LINE_ITEM_ID AS LINE_ITEM,MAEQUP.MNT_PLANT_ID,MAEQUP.MNT_PLANT_NAME,MAEQUP.MNT_PLANT_RECORD_ID,MAEQUP.MATERIAL_RECORD_ID,MAEQUP.PLATFORM,MAEQUP.PBG,CTCTSO.SALESORG_ID,CTCTSO.SALESORG_NAME,CTCTSO.SALESORG_RECORD_ID,MAEQUP.SAP_PART_NUMBER,MAEQUP.SERIAL_NO,MAMTRL.SAP_DESCRIPTION ,CTCITM_INBOUND.SERVICE_ID,MAMTRL.MATERIAL_RECORD_ID AS SERVICE_RECORD_ID,MAEQUP.SUBSTRATE_SIZE AS SUBSTRACT_SIZE,CTCITM_INBOUND.TAX,MAEQUP.TECHNOLOGY,ISNULL(CTCITM_INBOUND.EXTENDED_PRICE,0)-ISNULL(CTCITM_INBOUND.TAX,0) AS TOTAL_COST,MAEQUP.WARRANTY_END_DATE,MAEQUP.WARRANTY_START_DATE FROM CTCICO_INBOUND(NOLOCK) JOIN CTCNRT(NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID JOIN CTCITM_INBOUND(NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCITM_INBOUND.CONTRACT_ID AND CTCICO_INBOUND.LINE_ITEM_ID = CTCITM_INBOUND.LINE_ITEM_ID JOIN CTCITM(NOLOCK) ON CTCITM_INBOUND.CONTRACT_ID = CTCITM.CONTRACT_ID AND CTCITM_INBOUND.SERVICE_ID = CTCITM.SERVICE_ID  JOIN PRCURR(NOLOCK) ON CTCITM_INBOUND.CURRENCY = PRCURR.CURRENCY JOIN MAMTRL(NOLOCK) ON CTCITM_INBOUND.SERVICE_ID = MAMTRL.SAP_PART_NUMBER JOIN MAEQUP(NOLOCK) ON CTCICO_INBOUND.EQUIPMENT_ID = MAEQUP.EQUIPMENT_ID JOIN CTCTSO(NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCTSO.CONTRACT_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND ISNULL(CTCICO_INBOUND.INTEGRATION_STATUS,'''')='''')SUB_CTCICO LEFT JOIN CTCICO(NOLOCK) ON SUB_CTCICO.CONTRACT_ID = CTCICO.CONTRACT_ID AND SUB_CTCICO.LINE_ITEM_ID = CTCICO.EQUIPMENT_LINE_ID AND SUB_CTCICO.LINE_ITEM = CTCICO.LINE_ITEM_ID AND CTCICO.EQUIPMENT_ID = SUB_CTCICO.EQUIPMENT_ID WHERE CTCICO.CONTRACT_ID IS NULL '")
	
	#CTCIGB 
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCIGB(CONTRACT_ID,CNTITM_RECORD_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,EQUIPMENT_QUANTITY,EXTENDED_PRICE,GREENBOOK,GREENBOOK_RECORD_ID,LINE_ITEM_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,TAX,TOTAL_COST,CONTRACT_ITEM_GREENBOOK_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified ) SELECT SUB_CTCIGB.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM(SELECT DISTINCT CTCICO.CONTRACT_ID,CTCICO.CNTITM_RECORD_ID,CTCICO.CONTRACT_NAME,CTCICO.CONTRACT_RECORD_ID,COUNT(*) AS EQUIPMENT_QUANTITY,SUM(EXTENDED_PRICE) AS EXTENDED_PRICE,CTCICO.GREENBOOK,CTCICO.GREENBOOK_RECORD_ID,CTCICO.LINE_ITEM_ID,CTCICO.SERVICE_DESCRIPTION,CTCICO.SERVICE_ID,CTCICO.SERVICE_RECORD_ID,SUM(TAX) AS TAX,SUM(TOTAL_COST) AS TOTAL_COST FROM CTCICO_INBOUND(NOLOCK) JOIN CTCICO (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID AND CTCICO_INBOUND.LINE_ITEM_ID = CTCICO.EQUIPMENT_LINE_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' GROUP BY CTCICO.CONTRACT_ID,CTCICO.CNTITM_RECORD_ID,CTCICO.CONTRACT_NAME,CTCICO.CONTRACT_RECORD_ID,CTCICO.GREENBOOK,CTCICO.GREENBOOK_RECORD_ID,CTCICO.LINE_ITEM_ID,CTCICO.SERVICE_DESCRIPTION,CTCICO.SERVICE_ID,CTCICO.SERVICE_RECORD_ID )SUB_CTCIGB  LEFT JOIN CTCIGB(NOLOCK) ON SUB_CTCIGB.CONTRACT_ID = CTCIGB.CONTRACT_ID AND SUB_CTCIGB.LINE_ITEM_ID= CTCIGB.LINE_ITEM_ID AND SUB_CTCIGB.GREENBOOK = CTCIGB.GREENBOOK WHERE CTCIGB.CONTRACT_ID IS NULL '")

	#CTCIEN
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCIEN(CONTRACT_ID,CNTITMCOB_RECORD_ID,CNTITM_RECORD_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,CTESRVCOE_RECORD_ID,ENTITLEMENT_DESCRIPTION,ENTITLEMENT_DISPLAY_VALUE,ENTITLEMENT_NAME,ENTITLEMENT_TYPE,ENTITLEMENT_VALUE_CODE,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_LINE_ID,EQUIPMENT_RECORD_ID,LINE_ITEM_ID,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SERIAL_NUMBER,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,CONTRACT_ITEM_COV_OBJ_ENTITLEMENT_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified)SELECT SUB_CTCIEN.*,CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CTCICO.CONTRACT_ID,CTCICO.CONTRACT_ITEM_COVERED_OBJECT_RECORD_ID,CTCICO.CNTITM_RECORD_ID,CTCICO.CONTRACT_NAME,CTCICO.CONTRACT_RECORD_ID,NULL AS CTESRVCOE_RECORD_ID,NULL AS ENTITLEMENT_DESCRIPTION,NULL AS ENTITLEMENT_DISPLAY_VALUE,CTCSCE_INBOUND.ENTITLEMENT_NAME,NULL AS ENTITLEMENT_TYPE,CTCSCE_INBOUND.ENTITLEMENT_VALUE_CODE,CTCICO.EQUIPMENT_DESCRIPTION,CTCICO.EQUIPMENT_ID,CTCICO.EQUIPMENT_LINE_ID,CTCICO.EQUIPMENT_RECORD_ID,CTCICO.LINE_ITEM_ID,CTCICO.SALESORG_ID,CTCICO.SALESORG_NAME,CTCICO.SALESORG_RECORD_ID,CTCICO.SERIAL_NO,CTCICO.SERVICE_DESCRIPTION,CTCICO.SERVICE_ID,CTCICO.SERVICE_RECORD_ID FROM CTCSCE_INBOUND(NOLOCK) JOIN CTCICO(NOLOCK) ON CTCSCE_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID AND CTCSCE_INBOUND.LINE_ITEM_ID = CTCICO.EQUIPMENT_LINE_ID WHERE CTCSCE_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND CTCSCE_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''') SUB_CTCIEN LEFT JOIN CTCIEN(NOLOCK) ON SUB_CTCIEN.CONTRACT_ID = CTCIEN.CONTRACT_ID AND SUB_CTCIEN.EQUIPMENT_LINE_ID = CTCIEN.EQUIPMENT_LINE_ID AND SUB_CTCIEN.LINE_ITEM_ID = CTCIEN.LINE_ITEM_ID WHERE CTCIEN.CONTRACT_ID IS NULL   '")
	
	
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ " CTCIEN set CTCIEN.ENTITLEMENT_DISPLAY_VALUE=PRENVL.ENTITLEMENT_DISPLAY_VALUE,ENTITLEMENT_DESCRIPTION = PRENVL.ENTITLEMENT_DESCRIPTION FROM CTCIEN (NOLOCK) JOIN PRENVL(NOLOCK) ON LTRIM(RTRIM(CTCIEN.ENTITLEMENT_NAME)) = PRENVL.ENTITLEMENT_NAME AND PRENVL.ENTITLEMENT_VALUE_CODE=LTRIM(RTRIM(CTCIEN.ENTITLEMENT_VALUE_CODE)) WHERE ISNULL(CTCIEN.ENTITLEMENT_DISPLAY_VALUE,'''')='''' OR ISNULL(CTCIEN.ENTITLEMENT_DESCRIPTION,'''')=''''  '")

	"""	
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ " CTCIEN set CTCIEN.ENTITLEMENT_DISPLAY_VALUE=STANDARD_ATTRIBUTE_VALUES.STANDARD_ATTRIBUTE_DISPLAY_VAL FROM CTCIEN (NOLOCK) JOIN ATTRIBUTE_DEFN (NOLOCK) ON LTRIM(RTRIM(CTCIEN.ENTITLEMENT_NAME)) = ATTRIBUTE_DEFN.SYSTEM_ID INNER JOIN STANDARD_ATTRIBUTE_VALUES (NOLOCK) ON ATTRIBUTE_DEFN.STANDARD_ATTRIBUTE_CODE=STANDARD_ATTRIBUTE_VALUES.STANDARD_ATTRIBUTE_CODE WHERE STANDARD_ATTRIBUTE_VALUES.STANDARD_ATTRIBUTE_VALUE=LTRIM(RTRIM(CTCIEN.ENTITLEMENT_VALUE_CODE))  '")

	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ " CTCIEN set CTCIEN.ENTITLEMENT_DESCRIPTION=ATTRIBUTE_DEFN.STANDARD_ATTRIBUTE_NAME FROM CTCIEN (NOLOCK) JOIN ATTRIBUTE_DEFN (NOLOCK) ON LTRIM(RTRIM(CTCIEN.ENTITLEMENT_NAME)) = ATTRIBUTE_DEFN.SYSTEM_ID  '")"""

	#CTCIFP
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  CTCIFP SET CTCIFP.CpqTableEntryModifiedBy = ''"
	+ str(User.Id)
	+ "'',CTCIFP.CpqTableEntryDateModified = GetDate(),CTCIFP.ANNUAL_QUANTITY =  CTCIFP_INBOUND.ANNUAL_QUANTITY ,CTCIFP.EXTENDED_PRICE = CTCIFP_INBOUND.EXTENDED_PRICE,CTCIFP.UNIT_PRICE = CTCIFP_INBOUND.UNIT_PRICE FROM CTCIFP_INBOUND(NOLOCK) JOIN CTCIFP(NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID = CTCIFP.CONTRACT_ID AND CTCIFP.PART_NUMBER = CTCIFP_INBOUND.PART_NUMBER AND CTCIFP_INBOUND.LINE_ITEM_ID = CTCIFP.PART_LINE_ID  WHERE CTCIFP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND ISNULL(INTEGRATION_STTAUS,'''')='''' AND CTCIFP_INBOUND.TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "'  ' "
	)
	#CTCIKP
	primaryQueryItems = SqlHelper.GetFirst( 
	"sp_executesql @t=N'insert CTCIKP(CONTRACT_ID,CNTITM_RECORD_ID,CNTITMCOB_RECORD_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_LINE_ID,EQUIPMENT_RECORD_ID,LINE_ITEM_ID,PART_DESCRIPTION,PART_NUMBER,PART_RECORD_ID,QUANTITY,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,CONTRACT_ITEM_KIT_PARTS_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_CTCIKP.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',GETDATE() FROM (SELECT DISTINCT CTCITM.CONTRACT_ID,CTCITM.CONTRACT_ITEM_RECORD_ID AS CNTITM_RECORD_ID,CONTRACT_ITEM_COVERED_OBJECT_RECORD_ID,CTCITM.CONTRACT_NAME,CTCITM.CONTRACT_RECORD_ID,CTCICO.EQUIPMENT_DESCRIPTION,CTCICO.EQUIPMENT_ID,CTCICO.EQUIPMENT_LINE_ID,CTCICO.EQUIPMENT_RECORD_ID,CTCICO.LINE_ITEM_ID, MAMTRL.SAP_DESCRIPTION AS PART_DESCRIPTION,MAMTRL.SAP_PART_NUMBER AS PART_NUMBER,MAMTRL.MATERIAL_RECORD_ID AS PART_RECORD_ID, ANNUAL_QUANTITY,CTCITM.SERVICE_DESCRIPTION,CTCITM.SERVICE_ID,CTCITM.SERVICE_RECORD_ID FROM CTCIFP_INBOUND(NOLOCK) JOIN CTCTSO(NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID = CTCTSO.CONTRACT_ID JOIN CTCICO (NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID AND CTCIFP_INBOUND.LINE_ITEM_ID = CTCICO.EQUIPMENT_LINE_ID JOIN CTCITM(NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID = CTCITM.CONTRACT_ID AND CTCICO.LINE_ITEM_ID = CTCITM.LINE_ITEM_ID  JOIN MAMTRL(NOLOCK) ON CTCIFP_INBOUND.PART_NUMBER = MAMTRL.SAP_PART_NUMBER JOIN CTCNRT(NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID  WHERE CTCIFP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STTAUS,'''')='''' AND CTCIFP_INBOUND.TIMESTAMP=''FFSFS'' AND CTCNRT.CONTRACT_TYPE <> ''ZWK1 - SPARES''  ) SUB_CTCIKP LEFT JOIN CTCIKP(NOLOCK) ON SUB_CTCIKP.CONTRACT_ID = CTCIKP.CONTRACT_ID AND SUB_CTCIKP.LINE_ITEM_ID = CTCIKP.LINE_ITEM_ID AND CTCIKP.PART_NUMBER = SUB_CTCIKP.PART_NUMBER   WHERE CTCIKP.CONTRACT_ID IS NULL '")

	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " CTCIFP (ANNUAL_QUANTITY ,BASEUOM_ID,BASEUOM_RECORD_ID,CONTRACT_ID,CNTITM_RECORD_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,DELIVERY_MODE,EXTENDED_PRICE,ITEM_LINE_ID, PART_DESCRIPTION,PART_LINE_ID,PART_NUMBER,PART_RECORD_ID, SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SCHEDULE_MODE,SERVICE_DESCRIPTION, SERVICE_ID, SERVICE_RECORD_ID,UNIT_PRICE, VALID_FROM_DATE,VALID_TO_DATE  ,CONTRACT_ITEM_FORECAST_PART_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_CTCIFP.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',GETDATE() FROM (SELECT DISTINCT convert(decimal,CTCIFP_INBOUND.ANNUAL_QUANTITY) as ANNUAL_QUANTITY ,MAMTRL.UNIT_OF_MEASURE,MAMTRL.UOM_RECORD_ID,CTCITM.CONTRACT_ID,CTCITM.CONTRACT_ITEM_RECORD_ID AS CNTITM_RECORD_ID,CTCITM.CONTRACT_NAME,CTCITM.CONTRACT_RECORD_ID,convert(varchar(100),CTCIFP_INBOUND.DELIVERY_MODE) as DELIVERY_MODE,convert(float,CTCIFP_INBOUND.EXTENDED_PRICE) as EXTENDED_PRICE, CTCITM.LINE_ITEM_ID AS ITEM_LINE_ID,MAMTRL.SAP_DESCRIPTION AS PART_DESCRIPTION,CTCIFP_INBOUND.LINE_ITEM_ID,MAMTRL.SAP_PART_NUMBER AS PART_NUMBER,MAMTRL.MATERIAL_RECORD_ID AS PART_RECORD_ID, CTCTSO.SALESORG_ID,CTCTSO.SALESORG_NAME,CTCTSO.SALESORG_RECORD_ID, convert(varchar(100),CTCIFP_INBOUND.SCHEDULE_MODE) as SCHEDULE_MODE,CTCITM.SERVICE_DESCRIPTION,CTCITM.SERVICE_ID,CTCITM.SERVICE_RECORD_ID,convert(float,CTCIFP_INBOUND.UNIT_PRICE) as UNIT_PRICE, convert(date,CTCIFP_INBOUND.VALID_FROM_DATE) as VALID_FROM_DATE,convert(date,CTCIFP_INBOUND.VALID_TO_DATE) as VALID_TO_DATE FROM CTCIFP_INBOUND(NOLOCK) JOIN CTCITM_INBOUND(NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID =CTCITM_INBOUND.CONTRACT_ID AND CTCIFP_INBOUND.LINE_ITEM_ID = CTCITM_INBOUND.LINE_ITEM_ID JOIN CTCTSO(NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID = CTCTSO.CONTRACT_ID JOIN CTCITM(NOLOCK)  ON CTCIFP_INBOUND.CONTRACT_ID = CTCITM.CONTRACT_ID AND CTCITM_INBOUND.SERVICE_ID = CTCITM.SERVICE_ID JOIN MAMTRL(NOLOCK) ON CTCIFP_INBOUND.PART_NUMBER = MAMTRL.SAP_PART_NUMBER JOIN CTCNRT (NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID = CTCNRT.CONTRACT_ID  WHERE CTCIFP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCIFP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' AND CTCNRT.CONTRACT_TYPE = ''ZWK1 - SPARES'' ) SUB_CTCIFP LEFT JOIN CTCIFP(NOLOCK) ON SUB_CTCIFP.CONTRACT_ID = CTCIFP.CONTRACT_ID AND SUB_CTCIFP.LINE_ITEM_ID = CTCIFP.PART_LINE_ID AND CTCIFP.PART_NUMBER = SUB_CTCIFP.PART_NUMBER   WHERE CTCIFP.CONTRACT_ID IS NULL '")

	#CTCFBL
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCFBL(ADDRESS_1,ADDRESS_2,CITY,CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,COUNTRY,COUNTRY_RECORD_ID,EQUIPMENT_QUANTITY,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,FABLOCATION_STATUS,MNT_PLANT_ID,MNT_PLANT_NAME,MNT_PLANT_RECORD_ID,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,STATE,STATE_RECORD_ID,CONTRACT_FAB_LOCATION_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified)SELECT SUB_CTCFBL.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT MAFBLC.ADDRESS_1,MAFBLC.ADDRESS_2,MAFBLC.CITY,CTCICO.CONTRACT_ID,CTCICO.CONTRACT_NAME,CTCICO.CONTRACT_RECORD_ID,MAFBLC.COUNTRY,MAFBLC.COUNTRY_RECORD_ID,NULL AS EQUIPMENT_QUANTITY,CTCICO.FABLOCATION_ID,CTCICO.FABLOCATION_NAME,CTCICO.FABLOCATION_RECORD_ID,MAFBLC.STATUS,MAFBLC.MNT_PLANT_ID,MAFBLC.MNT_PLANT_NAME,MAFBLC.MNT_PLANT_RECORD_ID,MAFBLC.SALESORG_ID,MAFBLC.SALESORG_NAME,MAFBLC.SALESORG_RECORD_ID,MAFBLC.STATE,MAFBLC.STATE_RECORD_ID FROM CTCICO_INBOUND (NOLOCK) JOIN CTCICO (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID JOIN MAFBLC(NOLOCK) ON CTCICO.FABLOCATION_ID = MAFBLC.FAB_LOCATION_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')SUB_CTCFBL LEFT JOIN CTCFBL(NOLOCK) ON SUB_CTCFBL.CONTRACT_ID = CTCFBL.CONTRACT_ID AND SUB_CTCFBL.FABLOCATION_ID = CTCFBL.FABLOCATION_ID WHERE CTCFBL.CONTRACT_ID IS NULL '")
	
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ " CTCFBL SET EQUIPMENT_QUANTITY = SUB_CTCFBL.EQUIPMENT_QUANTITY FROM CTCFBL (NOLOCK) JOIN (SELECT CTCICO.CONTRACT_ID,FABLOCATION_ID,COUNT(DISTINCT CTCICO.EQUIPMENT_ID) AS EQUIPMENT_QUANTITY FROM CTCICO_INBOUND (NOLOCK) JOIN CTCICO (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID AND CTCICO_INBOUND.LINE_ITEM_ID = CTCICO.EQUIPMENT_LINE_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' GROUP BY CTCICO.CONTRACT_ID,FABLOCATION_ID) SUB_CTCFBL ON CTCFBL.CONTRACT_ID = SUB_CTCFBL.CONTRACT_ID AND CTCFBL.FABLOCATION_ID = SUB_CTCFBL.FABLOCATION_ID '")

	#CTCFGB
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCFGB(CNTFBL_RECORD_ID,CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,EQUIPMENT_QUANTITY,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,GREENBOOK,GREENBOOK_RECORD_ID,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,CONTRACT_FAB_LOCATION_GREENBOOK_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified) SELECT SUB_CTCFGB.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CONTRACT_FAB_LOCATION_RECORD_ID,CTCICO.CONTRACT_ID,CTCICO.CONTRACT_NAME,CTCICO.CONTRACT_RECORD_ID,NULL AS EQUIPMENT_QUANTITY,CTCICO.FABLOCATION_ID,CTCICO.FABLOCATION_NAME,CTCICO.FABLOCATION_RECORD_ID,CTCICO.GREENBOOK,CTCICO.GREENBOOK_RECORD_ID,CTCFBL.SALESORG_ID,CTCFBL.SALESORG_NAME,CTCFBL.SALESORG_RECORD_ID FROM CTCICO_INBOUND(NOLOCK) JOIN CTCICO (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID JOIN CTCFBL (NOLOCK) ON CTCICO.CONTRACT_ID = CTCFBL.CONTRACT_ID AND CTCICO.FABLOCATION_ID = CTCFBL.FABLOCATION_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' )SUB_CTCFGB LEFT JOIN CTCFGB(NOLOCK) ON SUB_CTCFGB.CONTRACT_ID = CTCFGB.CONTRACT_ID AND SUB_CTCFGB.FABLOCATION_ID = CTCFGB.FABLOCATION_ID AND SUB_CTCFGB.GREENBOOK = CTCFGB.GREENBOOK WHERE CTCFGB.CONTRACT_ID IS NULL '")
	
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ " CTCFGB SET EQUIPMENT_QUANTITY = SUB_CTCFGB.EQUIPMENT_QUANTITY FROM CTCFGB (NOLOCK) JOIN (SELECT CTCICO.CONTRACT_ID,FABLOCATION_ID,GREENBOOK,COUNT(DISTINCT CTCICO.EQUIPMENT_ID) AS EQUIPMENT_QUANTITY FROM CTCICO_INBOUND (NOLOCK) JOIN CTCICO (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID AND CTCICO_INBOUND.LINE_ITEM_ID = CTCICO.EQUIPMENT_LINE_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' GROUP BY CTCICO.CONTRACT_ID,FABLOCATION_ID,GREENBOOK) SUB_CTCFGB ON CTCFGB.CONTRACT_ID = SUB_CTCFGB.CONTRACT_ID AND CTCFGB.FABLOCATION_ID = SUB_CTCFGB.FABLOCATION_ID AND CTCFGB.GREENBOOK = SUB_CTCFGB.GREENBOOK '")

	#CTCFEQ CTCFGB
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCFEQ(CNTFBLGBK_RECORD_ID,CNTFBL_RECORD_ID,CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,CUSTOMER_TOOL_ID,EQUIPMENTCATEGORY_ID,EQUIPMENTCATEGORY_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,EQUIPMENT_STATUS,EQUIPMENTTYPE_ID,EQUIPMENTTYPE_RECORD_ID,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,GREENBOOK,GREENBOOK_RECORD_ID,MNT_PLANT_ID,MNT_PLANT_NAME,MNT_PLANT_RECORD_ID,PLATFORM,PBG,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SERIAL_NUMBER,SUBSTRATE_SIZE,TECHNOLOGY,WARRANTY_END_DATE,WARRANTY_START_DATE,CONTRACT_FAB_LOC_GB_EQUIPMENT_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified) SELECT SUB_CTCFEQ.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CONTRACT_FAB_LOCATION_GREENBOOK_RECORD_ID,CNTFBL_RECORD_ID,CTCICO.CONTRACT_ID,CTCICO.CONTRACT_NAME,CTCICO.CONTRACT_RECORD_ID,CTCICO.CUSTOMER_TOOL_ID,CTCICO.EQUIPMENTCATEGORY_ID,CTCICO.EQUIPMENTCATEGORY_RECORD_ID,CTCICO.EQUIPMENT_DESCRIPTION,CTCICO.EQUIPMENT_ID,CTCICO.EQUIPMENT_RECORD_ID,CTCICO.EQUIPMENT_STATUS,CTCICO.EQUIPMENTTYPE_ID,CTCICO.EQUIPMENTTYPE_RECORD_ID,CTCICO.FABLOCATION_ID,CTCICO.FABLOCATION_NAME,CTCICO.FABLOCATION_RECORD_ID,CTCICO.GREENBOOK,CTCICO.GREENBOOK_RECORD_ID,CTCICO.MNT_PLANT_ID,CTCICO.MNT_PLANT_NAME,CTCICO.MNT_PLANT_RECORD_ID,CTCICO.PLATFORM,CTCICO.PBG,CTCFGB.SALESORG_ID,CTCFGB.SALESORG_NAME,CTCFGB.SALESORG_RECORD_ID,CTCICO.SERIAL_NO,CTCICO.SUBSTRACT_SIZE,CTCICO.TECHNOLOGY,CTCICO.WARRANTY_END_DATE,CTCICO.WARRANTY_START_DATE FROM CTCICO_INBOUND (NOLOCK) JOIN CTCICO (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID JOIN CTCFGB (NOLOCK) ON CTCICO.CONTRACT_ID = CTCFGB.CONTRACT_ID AND CTCICO.FABLOCATION_ID = CTCFGB.FABLOCATION_ID AND CTCICO.GREENBOOK = CTCFGB.GREENBOOK WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "') SUB_CTCFEQ LEFT JOIN CTCFEQ(NOLOCK) ON SUB_CTCFEQ.CONTRACT_ID = CTCFEQ.CONTRACT_ID AND SUB_CTCFEQ.FABLOCATION_ID = CTCFEQ.FABLOCATION_ID AND SUB_CTCFEQ.GREENBOOK = CTCFEQ.GREENBOOK AND SUB_CTCFEQ.EQUIPMENT_ID = CTCFEQ.EQUIPMENT_ID  WHERE CTCFEQ.CONTRACT_ID IS NULL  '")
	
	#CTCTSV
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCTSV(CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,PRODUCT_TYPE,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,UOM_ID,UOM_RECORD_ID,CONTRACT_SERVICES_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified) SELECT SUB_CTCTSV.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CTCITM.CONTRACT_ID,CTCITM.CONTRACT_NAME,CTCITM.CONTRACT_RECORD_ID,C.PRODUCT_TYPE,CTCTSO.SALESORG_ID,CTCTSO.SALESORG_NAME,CTCTSO.SALESORG_RECORD_ID,CTCITM.SERVICE_DESCRIPTION,CTCITM.SERVICE_ID,CTCITM.SERVICE_RECORD_ID,C.UNIT_OF_MEASURE,C.UOM_RECORD_ID FROM CTCITM_INBOUND (NOLOCK) JOIN CTCTSO (NOLOCK) ON CTCITM_INBOUND.CONTRACT_ID = CTCTSO.CONTRACT_ID JOIN CTCITM (NOLOCK) ON CTCITM_INBOUND.CONTRACT_ID = CTCITM.CONTRACT_ID AND CTCITM_INBOUND.SERVICE_ID = CTCITM.SERVICE_ID JOIN MAMTRL C(NOLOCK) ON CTCITM_INBOUND.SERVICE_ID = C.SAP_PART_NUMBER WHERE CTCITM_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCITM_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')SUB_CTCTSV LEFT JOIN CTCTSV(NOLOCK) ON SUB_CTCTSV.CONTRACT_ID = CTCTSV.CONTRACT_ID AND SUB_CTCTSV.SERVICE_ID = CTCTSV.SERVICE_ID WHERE CTCTSV.CONTRACT_ID IS NULL '")
	
	#CTCSGB
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCSGB(CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,EQUIPMENT_QUANTITY,GREENBOOK,GREENBOOK_RECORD_ID,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,UOM_ID,UOM_RECORD_ID,CNTSRVGB_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified) SELECT SUB_CTCSGB.*,CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CTCICO.CONTRACT_ID,CTCICO.CONTRACT_NAME,CTCICO.CONTRACT_RECORD_ID,NULL AS EQUIPMENT_QUANTITY,CTCICO.GREENBOOK,CTCICO.GREENBOOK_RECORD_ID,CTCTSV.SALESORG_ID,CTCTSV.SALESORG_NAME,CTCTSV.SALESORG_RECORD_ID,CTCTSV.SERVICE_DESCRIPTION,CTCTSV.SERVICE_ID,CTCTSV.SERVICE_RECORD_ID,CTCTSV.UOM_ID,CTCTSV.UOM_RECORD_ID FROM CTCICO_INBOUND (NOLOCK) JOIN CTCICO (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID AND CTCICO_INBOUND.LINE_ITEM_ID = CTCICO.EQUIPMENT_LINE_ID JOIN CTCTSV (NOLOCK) ON CTCICO.CONTRACT_ID = CTCTSV.CONTRACT_ID AND CTCICO.SERVICE_ID = CTCTSV.SERVICE_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' )SUB_CTCSGB LEFT JOIN CTCSGB (NOLOCK) ON SUB_CTCSGB.CONTRACT_ID = CTCSGB.CONTRACT_ID AND SUB_CTCSGB.SERVICE_ID = CTCSGB.SERVICE_ID AND SUB_CTCSGB.GREENBOOK = CTCSGB.GREENBOOK WHERE CTCSGB.CONTRACT_ID IS NULL '")

	primaryQueryItems = SqlHelper.GetFirst( 
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ " CTCSGB SET CTCSGB.EQUIPMENT_QUANTITY = SUB_CTCSGB.EQUIPMENT_QUANTITY FROM CTCSGB (NOLOCK) JOIN (SELECT CTCICO.CONTRACT_ID,SERVICE_ID,GREENBOOK,COUNT(DISTINCT CTCICO.EQUIPMENT_ID) AS EQUIPMENT_QUANTITY FROM CTCICO_INBOUND (NOLOCK) JOIN CTCICO (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID AND CTCICO_INBOUND.LINE_ITEM_ID = CTCICO.EQUIPMENT_LINE_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' GROUP BY CTCICO.CONTRACT_ID,SERVICE_ID,GREENBOOK) SUB_CTCSGB ON CTCSGB.CONTRACT_ID = SUB_CTCSGB.CONTRACT_ID AND CTCSGB.SERVICE_ID = SUB_CTCSGB.SERVICE_ID AND CTCSGB.GREENBOOK = SUB_CTCSGB.GREENBOOK '")
		
	#CTCSCO
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCSCO(CONTRACT_ID,CONTRACT_NAME,SERVICE_ID,SERVICE_DESCRIPTION,CUSTOMER_TOOL_ID,SUBSTRACT_SIZE,PBG,PLATFORM,MATERIAL_RECORD_ID,MNT_PLANT_RECORD_ID,MNT_PLANT_NAME,MNT_PLANT_ID,EQUIPMENTCATEGORY_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_STATUS,EQUIPMENTTYPE_ID,FABLOCATION_ID,FABLOCATION_NAME,EQUIPMENTCATEGORY_RECORD_ID,EQUIPMENT_RECORD_ID,EQUIPMENTTYPE_RECORD_ID,FABLOCATION_RECORD_ID,SERIAL_NUMBER,WARRANTY_START_DATE,SAP_PART_NUMBER,GREENBOOK,GREENBOOK_RECORD_ID,CONTRACT_RECORD_ID,CNTSRV_RECORD_ID,WARRANTY_END_DATE,TECHNOLOGY,SERVICE_RECORD_ID,CONTRACT_SERVICE_EQUIPMENT_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified) SELECT SUB_CTCSCO.*,CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CTCICO.CONTRACT_ID,CTCICO.CONTRACT_NAME,CTCICO.SERVICE_ID,CTCICO.SERVICE_DESCRIPTION,CTCICO.CUSTOMER_TOOL_ID,CTCICO.SUBSTRACT_SIZE,CTCICO.PBG,CTCICO.PLATFORM,CTCICO.MATERIAL_RECORD_ID,CTCICO.MNT_PLANT_RECORD_ID,CTCICO.MNT_PLANT_NAME,CTCICO.MNT_PLANT_ID,CTCICO.EQUIPMENTCATEGORY_ID,CTCICO.EQUIPMENT_DESCRIPTION,CTCICO.EQUIPMENT_ID,CTCICO.EQUIPMENT_STATUS,CTCICO.EQUIPMENTTYPE_ID,CTCICO.FABLOCATION_ID,CTCICO.FABLOCATION_NAME,CTCICO.EQUIPMENTCATEGORY_RECORD_ID,CTCICO.EQUIPMENT_RECORD_ID,CTCICO.EQUIPMENTTYPE_RECORD_ID,CTCICO.FABLOCATION_RECORD_ID,CTCICO.SERIAL_NO,CTCICO.WARRANTY_START_DATE,CTCICO.SAP_PART_NUMBER,CTCICO.GREENBOOK,CTCICO.GREENBOOK_RECORD_ID,CTCICO.CONTRACT_RECORD_ID,CTCTSV.CONTRACT_SERVICES_RECORD_ID,CTCICO.WARRANTY_END_DATE,CTCICO.TECHNOLOGY,CTCICO.SERVICE_RECORD_ID FROM CTCICO_INBOUND(NOLOCK) JOIN CTCICO (NOLOCK) ON CTCICO_INBOUND.CONTRACT_ID = CTCICO.CONTRACT_ID AND CTCICO_INBOUND.LINE_ITEM_ID = CTCICO.EQUIPMENT_LINE_ID JOIN CTCTSV (NOLOCK) ON CTCICO.CONTRACT_ID = CTCTSV.CONTRACT_ID AND CTCICO.SERVICE_ID = CTCTSV.SERVICE_ID WHERE CTCICO_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCICO_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' )SUB_CTCSCO LEFT JOIN CTCSCO (NOLOCK) ON SUB_CTCSCO.CONTRACT_ID = CTCSCO.CONTRACT_ID AND SUB_CTCSCO.SERVICE_ID = CTCSCO.SERVICE_ID AND SUB_CTCSCO.EQUIPMENT_ID = CTCSCO.EQUIPMENT_ID WHERE CTCSCO.CONTRACT_ID IS NULL '")

	#CTCSPT
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCSPT(BASEUOM_ID,BASEUOM_RECORD_ID,CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,CUSTOMER_ANNUAL_QUANTITY,EXTENDED_UNIT_PRICE,PART_DESCRIPTION,PART_NUMBER,PART_RECORD_ID,SALESORG_ID,SALESORG_RECORD_ID,SALESUOM_CONVERSION_FACTOR,SALESUOM_ID,SALESUOM_RECORD_ID,SCHEDULE_MODE,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,UNIT_PRICE,VALID_FROM_DATE,VALID_TO_DATE,CONTRACT_SERVICE_PARTS_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified) SELECT SUB_CTCSPT.*,CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM(SELECT DISTINCT CTCIFP.BASEUOM_ID,CTCIFP.BASEUOM_RECORD_ID,CTCIFP.CONTRACT_ID,CTCIFP.CONTRACT_NAME,CTCIFP.CONTRACT_RECORD_ID,CTCIFP.ANNUAL_QUANTITY,CTCIFP.EXTENDED_PRICE,CTCIFP.PART_DESCRIPTION,CTCIFP.PART_NUMBER,CTCIFP.PART_RECORD_ID,CTCIFP.SALESORG_ID,CTCIFP.SALESORG_RECORD_ID,CTCIFP.SALESUOM_CONVERSION_FACTOR,CTCIFP.SALESUOM_ID,CTCIFP.SALESUOM_RECORD_ID,CTCIFP.SCHEDULE_MODE,CTCIFP.SERVICE_DESCRIPTION,CTCIFP.SERVICE_ID,CTCIFP.SERVICE_RECORD_ID,CTCIFP.UNIT_PRICE,CTCIFP.VALID_FROM_DATE,CTCIFP.VALID_TO_DATE FROM CTCIFP_INBOUND (NOLOCK) JOIN CTCIFP (NOLOCK) ON CTCIFP_INBOUND.CONTRACT_ID = CTCIFP.CONTRACT_ID AND CTCIFP_INBOUND.LINE_ITEM_ID = CTCIFP.PART_LINE_ID JOIN CTCTSV (NOLOCK) ON CTCIFP.CONTRACT_ID = CTCTSV.CONTRACT_ID AND CTCIFP.SERVICE_ID = CTCTSV.SERVICE_ID WHERE CTCIFP_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STTAUS,'''')='''' AND CTCIFP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')SUB_CTCSPT LEFT JOIN CTCSPT(NOLOCK) ON SUB_CTCSPT.CONTRACT_ID = CTCSPT.CONTRACT_ID AND SUB_CTCSPT.SERVICE_ID = CTCSPT.SERVICE_ID AND SUB_CTCSPT.PART_NUMBER = CTCSPT.PART_NUMBER WHERE CTCSPT.CONTRACT_ID IS NULL  '")

	#CTCSCE
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCSCE(CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,CNTSRVCOB_RECORD_ID,ENTITLEMENT_DESCRIPTION,ENTITLEMENT_DISPLAY_VALUE,ENTITLEMENT_NAME,ENTITLEMENT_TYPE,ENTITLEMENT_VALUE_CODE,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,SERIAL_NO,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,CNTSRVCOB_ENTITLEMENT_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified) SELECT SUB_CTCSCE.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CTCIEN.CONTRACT_ID,CTCIEN.CONTRACT_NAME,CTCIEN.CONTRACT_RECORD_ID,CONTRACT_SERVICE_EQUIPMENT_RECORD_ID,CTCIEN.ENTITLEMENT_DESCRIPTION,CTCIEN.ENTITLEMENT_DISPLAY_VALUE,CTCIEN.ENTITLEMENT_NAME,CTCIEN.ENTITLEMENT_TYPE,CTCIEN.ENTITLEMENT_VALUE_CODE,CTCIEN.EQUIPMENT_DESCRIPTION,CTCIEN.EQUIPMENT_ID,CTCIEN.EQUIPMENT_RECORD_ID,CTCIEN.SERIAL_NUMBER,CTCIEN.SERVICE_DESCRIPTION,CTCIEN.SERVICE_ID,CTCIEN.SERVICE_RECORD_ID FROM CTCSCE_INBOUND (NOLOCK) JOIN CTCIEN (NOLOCK) ON CTCSCE_INBOUND.CONTRACT_ID = CTCIEN.CONTRACT_ID AND CTCSCE_INBOUND.LINE_ITEM_ID = CTCIEN.EQUIPMENT_LINE_ID JOIN CTCSCO (NOLOCK) ON CTCIEN.CONTRACT_ID = CTCSCO.CONTRACT_ID AND CTCIEN.SERVICE_ID = CTCSCO.SERVICE_ID AND CTCIEN.EQUIPMENT_ID = CTCSCO.EQUIPMENT_ID WHERE CTCSCE_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCSCE_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' )SUB_CTCSCE LEFT JOIN CTCSCE (NOLOCK) ON SUB_CTCSCE.CONTRACT_ID = CTCSCE.CONTRACT_ID AND SUB_CTCSCE.SERVICE_ID = CTCSCE.SERVICE_ID AND SUB_CTCSCE.EQUIPMENT_ID = CTCSCE.EQUIPMENT_ID AND SUB_CTCSCE.ENTITLEMENT_NAME = CTCSCE.ENTITLEMENT_NAME WHERE CTCSCE.CONTRACT_ID IS NULL '")
	
	#CTCTSE
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCTSE(CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,CNTSRV_RECORD_ID,ENTITLEMENT_DESCRIPTION,ENTITLEMENT_DISPLAY_VALUE,ENTITLEMENT_NAME,ENTITLEMENT_TYPE,ENTITLEMENT_VALUE_CODE,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SERVICE_ID,SERVICE_DESCRIPTION,SERVICE_RECORD_ID,CONTRACT_SERVICE_ENTITLEMENTS_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified) SELECT SUB_CTCTSE.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CTCSCE.CONTRACT_ID,CTCSCE.CONTRACT_NAME,CTCSCE.CONTRACT_RECORD_ID,CONTRACT_SERVICES_RECORD_ID,CTCSCE.ENTITLEMENT_DESCRIPTION,NULL AS ENTITLEMENT_DISPLAY_VALUE,CTCSCE.ENTITLEMENT_NAME,CTCSCE.ENTITLEMENT_TYPE,NULL AS ENTITLEMENT_VALUE_CODE,CTCTSV.SALESORG_ID,CTCTSV.SALESORG_NAME,CTCTSV.SALESORG_RECORD_ID,CTCSCE.SERVICE_ID,CTCSCE.SERVICE_DESCRIPTION,CTCSCE.SERVICE_RECORD_ID FROM CTCSCE_INBOUND (NOLOCK) JOIN CTCSCE (NOLOCK) ON CTCSCE_INBOUND.CONTRACT_ID = CTCSCE.CONTRACT_ID JOIN CTCTSV (NOLOCK) ON CTCSCE.CONTRACT_ID = CTCTSV.CONTRACT_ID AND CTCSCE.SERVICE_ID = CTCTSV.SERVICE_ID WHERE CTCSCE_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCSCE_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' )SUB_CTCTSE LEFT JOIN CTCTSE(NOLOCK) ON SUB_CTCTSE.CONTRACT_ID = CTCTSE.CONTRACT_ID AND SUB_CTCTSE.SERVICE_ID = CTCTSE.SERVICE_ID AND SUB_CTCTSE.ENTITLEMENT_NAME = CTCTSE.ENTITLEMENT_NAME WHERE CTCTSE.CONTRACT_ID IS NULL '")

	primaryQueryItems = SqlHelper.GetFirst( 
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCTSE SET ENTITLEMENT_DISPLAY_VALUE = CTCIEN.ENTITLEMENT_DISPLAY_VALUE,ENTITLEMENT_VALUE_CODE = CTCIEN.ENTITLEMENT_VALUE_CODE FROM CTCTSE (NOLOCK) JOIN CTCIEN (NOLOCK) ON CTCTSE.CONTRACT_ID = CTCIEN.CONTRACT_ID AND CTCTSE.SERVICE_ID = CTCIEN.SERVICE_ID AND CTCTSE.ENTITLEMENT_NAME = CTCIEN.ENTITLEMENT_NAME JOIN CTCSCE_INBOUND (NOLOCK) ON CTCTSE.CONTRACT_ID = CTCSCE_INBOUND.CONTRACT_ID WHERE CTCSCE_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(CTCSCE_INBOUND.INTEGRATION_STATUS,'''')='''' AND CTCSCE_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' '")
	
	#CTCSGE
	primaryQueryItems = SqlHelper.GetFirst( 
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  CTCSGE(CONTRACT_ID,CONTRACT_NAME,CONTRACT_RECORD_ID,CNTSRVENT_RECORD_ID,ENTITLEMENT_DESCRIPTION,ENTITLEMENT_TYPE,ENTITLEMENT_DISPLAY_VALUE,ENTITLEMENT_NAME,ENTITLEMENT_VALUE_CODE,GREENBOOK,GREENBOOK_RECORD_ID,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,CONTRACT_SERVICE_GREENBOOK_ENTITLEMENT_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,CpqTableEntryModifiedBy,CpqTableEntryDateModified) SELECT SUB_CTCSGE.*,CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',''"+ str(User.Id)+ "'',GETDATE(), ''"+ str(User.Id)+ "'',GETDATE() FROM (SELECT DISTINCT CTCSGB.CONTRACT_ID,CTCSGB.CONTRACT_NAME,CTCSGB.CONTRACT_RECORD_ID,CONTRACT_SERVICE_ENTITLEMENTS_RECORD_ID,CTCTSE.ENTITLEMENT_DESCRIPTION,CTCTSE.ENTITLEMENT_TYPE,CTCTSE.ENTITLEMENT_DISPLAY_VALUE,CTCTSE.ENTITLEMENT_NAME,CTCTSE.ENTITLEMENT_VALUE_CODE,CTCSGB.GREENBOOK,CTCSGB.GREENBOOK_RECORD_ID,CTCTSE.SALESORG_ID,CTCTSE.SALESORG_NAME,CTCTSE.SALESORG_RECORD_ID,CTCTSE.SERVICE_DESCRIPTION,CTCTSE.SERVICE_ID,CTCTSE.SERVICE_RECORD_ID FROM CTCSCE_INBOUND (NOLOCK) JOIN CTCSGB (NOLOCK) ON CTCSCE_INBOUND.CONTRACT_ID = CTCSGB.CONTRACT_ID JOIN CTCTSE (NOLOCK) ON CTCSGB.CONTRACT_ID = CTCTSE.CONTRACT_ID AND CTCSGB.SERVICE_ID = CTCTSE.SERVICE_ID  WHERE CTCSCE_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD'' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND CTCSCE_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')SUB_CTCSGE LEFT JOIN CTCSGE (NOLOCK) ON SUB_CTCSGE.CONTRACT_ID = CTCSGE.CONTRACT_ID AND SUB_CTCSGE.SERVICE_ID = CTCSGE.SERVICE_ID AND SUB_CTCSGE.GREENBOOK = CTCSGE.GREENBOOK AND SUB_CTCSGE.ENTITLEMENT_NAME = CTCSGE.ENTITLEMENT_NAME WHERE CTCSGE.CONTRACT_ID IS NULL '")
	
	#Status Change to Uploaded 
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  CTCNRT_INBOUND SET PROCESS_STATUS=''UPLOADED'' WHERE PROCESS_STATUS=''READY FOR UPLOAD'' AND TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCITM_INBOUND SET PROCESS_STATUS=''UPLOADED'' WHERE PROCESS_STATUS=''READY FOR UPLOAD'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCICO_INBOUND SET PROCESS_STATUS=''UPLOADED'' WHERE PROCESS_STATUS=''READY FOR UPLOAD'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCSCE_INBOUND SET PROCESS_STATUS=''UPLOADED'' WHERE PROCESS_STATUS=''READY FOR UPLOAD'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCIFP_INBOUND SET PROCESS_STATUS=''UPLOADED'' WHERE PROCESS_STATUS=''READY FOR UPLOAD'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STTAUS,'''')='''' '"
	)	

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  CTCTIP_INBOUND SET PROCESS_STATUS=''UPLOADED'' WHERE PROCESS_STATUS=''READY FOR UPLOAD'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(INTEGRATION_STATUS,'''')='''' '"
	)

	
	#Errors mail system 
	Error_list = []
	Resp_msg = {}
	Lst_resp = []
	Check_flag = 1
	while Check_flag == 1:
		Error_primaryQuery = SqlHelper.GetList(
			"select top 10 SESSION_ID from ERROR_SESSION(NOLOCK) where ISNULL(PROCESS_STATUS,'')= '' and isnull(SESSION_ID,'')<>''  "
		)

		Session_lst_count = []
		for data in Error_primaryQuery:
			Session_lst_count.append(data.SESSION_ID)

		Session_lst = tuple(Session_lst_count)
		if len(Session_lst_count) == 1:
			Session_lst = "('" + Session_lst_count[0] + "')"
		
		if len(Session_lst_count) > 0:
			primaryQueryItems = SqlHelper.GetList(
				"select distinct CONTRACT_ID,integration_status from CTCNRT_INBOUND (nolock) where isnull(integration_status,'')<>'' and session_id in "
				+ str(Session_lst)
				+ " union select distinct CONTRACT_ID,integration_status from CTCITM_INBOUND (nolock) where isnull(integration_status,'')<>'' and session_id in "
				+ str(Session_lst)
				+ "union select distinct CONTRACT_ID,integration_status from CTCICO_INBOUND (nolock) where isnull(integration_status,'')<>'' and session_id in "
				+ str(Session_lst)
				+ " union select distinct CONTRACT_ID,integration_status from CTCSCE_INBOUND (nolock) where isnull(integration_status,'')<>'' and session_id in "
				+ str(Session_lst)
				+ " union select distinct CONTRACT_ID,INTEGRATION_STTAUS from CTCIFP_INBOUND (nolock) where isnull(INTEGRATION_STTAUS,'')<>'' and session_id in "
				+ str(Session_lst)
				+ " union select distinct CONTRACT_ID,integration_status from CTCTIP_INBOUND (nolock) where isnull(integration_status,'')<>'' and session_id in "
				+ str(Session_lst)
				+ " "
			)
			Dt = {}
			for ins in primaryQueryItems:
				Modi_integration_status = []
				inte_status = str(ins.integration_status).split("||")
				ERROR = set(inte_status)
				ERROR = list(ERROR)
				if "" in ERROR:
					ERROR.remove("")
				
				for uu in ERROR:
					split_data = uu.split("-", 1)
					SYMSGS_MSG_TEXT = SqlHelper.GetFirst(
						"SELECT MESSAGE_TEXT,RECORD_ID AS REC_ID,OBJECT_APINAME,OBJECT_RECORD_ID,MESSAGE_TYPE FROM SYMSGS(NOLOCK) WHERE MESSAGE_CODE = '"
						+ str(split_data[0])
						+ "'"
					)

					if len(split_data) > 1:
						CONVERTED_MSG = SYMSGS_MSG_TEXT.MESSAGE_TEXT + " - " + split_data[-1]
					else:
						CONVERTED_MSG = SYMSGS_MSG_TEXT.MESSAGE_TEXT

					Modi_integration_status.append(CONVERTED_MSG)
					
					SYELOG_tableInfo = SqlHelper.GetTable("SYELOG")
					GuidQuery = SqlHelper.GetFirst("SELECT CONVERT(VARCHAR(4000),NEWID()) AS A")
					Dit = {}
					Dit["ERROR_LOGS_RECORD_ID"] = GuidQuery.A
					Dit["ERRORMESSAGE_RECORD_ID"] = SYMSGS_MSG_TEXT.REC_ID
					Dit["ERRORMESSAGE_DESCRIPTION"] = SYMSGS_MSG_TEXT.MESSAGE_TEXT
					Dit["OBJECT_RECORD_ID"] = SYMSGS_MSG_TEXT.OBJECT_RECORD_ID
					Dit["OBJECT_TYPE"] = SYMSGS_MSG_TEXT.MESSAGE_TYPE
					Dit["OBJECT_NAME"] = SYMSGS_MSG_TEXT.OBJECT_APINAME
					if len(split_data) > 1:
						Dit["OBJECT_VALUE"] = split_data[-1]
					if len(split_data) == 1:
						Dit["OBJECT_VALUE"] = ""
					Dit["CPQTABLEENTRYDATEADDED"] = Modi_date
					Dit["CPQTABLEENTRYADDEDBY"] = User.UserName
					SYELOG_tableInfo.AddRow(Dit)
				sqlInfo = SqlHelper.Upsert(SYELOG_tableInfo)
				if str(ins.CONTRACT_ID) in Dt:
					for data in Modi_integration_status:
						if data not in Dt[ins.CONTRACT_ID]:
							Dt[ins.CONTRACT_ID].append(data)
				else:
					Dt[ins.CONTRACT_ID] = Modi_integration_status
					
				for CONTRACT_ID in Dt:
					inte_status_info = ""
					for data in Dt[CONTRACT_ID]:
						inte_status_info = inte_status_info + data + "||"

					Error_list.append(CONTRACT_ID + "--" + inte_status_info[:-2])

				ErrorQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  "+str(Temp_Table_Name)+" SET PROCESS_STATUS = ''UPLOADED'' WHERE SESSION_ID  IN "+ str(Session_lst).replace("'","''")+ "  '")
		
		else:
			Check_flag = 0
	
	# Dynamically created table deletion
	TempTable = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(Temp_Table_Name)+"'' ) BEGIN DROP TABLE "+str(Temp_Table_Name)+" END'")

	if len(Error_list) > 0:
	
		Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;}</style></head><body>"

		Table_start = "<p>Hi Team,<br>Please find the below exceptions for your reference</p><table class='table table-bordered'><tr><th>SNO</th><th>CONTRACT_ID</th><th>ERROR MESSAGE</th></tr>"
		Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"
		Table_info = ""
		unique_Error_list = set(Error_list)
		for indx, data in enumerate(unique_Error_list, 1):
			data = data.split("--")
			Table_record = (
				"<tr>"
				+ "<td>"
				+ str(indx)
				+ "</td>"
				+ "<td>"
				+ str(data[0])
				+ "</td>"
				+ "<td>"
				+ str(data[-1])
				+ "</td>"
				+ "</tr>"
			)
			Table_info = Table_info + Table_record

		Error_Info = Header + Table_start + Table_info + Table_End

		LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

		# Create new SmtpClient object
		mailClient = SmtpClient()

		# Set the host and port (eg. smtp.gmail.com)
		mailClient.Host = "smtp.gmail.com"
		mailClient.Port = 587
		mailClient.EnableSsl = "true"

		# Setup NetworkCredential
		mailCred = NetworkCredential()
		mailCred.UserName = str(LOGIN_CRE.Username)
		mailCred.Password = str(LOGIN_CRE.Password)
		mailClient.Credentials = mailCred

		# Create two mail adresses, one for send from and the another for recipient
		toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
		fromEmail = MailAddress("INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM")

		# Create new MailMessage object
		msg = MailMessage(fromEmail, toEmail)

		# Set message subject and body
		msg.Subject = "AMAT INTEGRATION CRM TO CPQ EXCEPTIONS - CPQ TST"
		msg.IsBodyHtml = True
		msg.Body = Error_Info

		# CC Emails	
		copyEmail5 = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
		msg.CC.Add(copyEmail5)
		
		copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
		msg.CC.Add(copyEmail4)
		
		# Send the message
		mailClient.Send(msg)
	else:
		ApiResponse = ApiResponseFactory.JsonResponse({"Response": [{"Status": "200", "Message": "CONTRACT DATA SUCCESSFULLY UPLOADED"}]})
		
except:	
	# Dynamically created table deletion
	Temp_Table_Name = 'ERROR_SESSION'
	TempTable = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(Temp_Table_Name)+"'' ) BEGIN DROP TABLE "+str(Temp_Table_Name)+" END'")

	Log.Info("CTPOSTCTBK ERROR---->:" + str(sys.exc_info()[1]))
	Log.Info("CTPOSTCTBK ERROR LINE NO---->:" + str(sys.exc_info()[-1].tb_lineno))
	ApiResponse = ApiResponseFactory.JsonResponse({"Response": [{"Status": "400", "Message": str(sys.exc_info()[1])}]})