import sys
import datetime
import clr
import System.Net
from System.Text.Encoding import UTF8
from System import Convert
from SYDATABASE import SQL
import CQVLDRIFLW
import CQCPQC4CWB

clr.AddReference("System.Net")
from System.Net import CookieContainer, NetworkCredential, Mail
from System.Net.Mail import SmtpClient, MailAddress, Attachment, MailMessage

Parameter = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'SELECT' ")
Parameter1 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'UPD' ")
Parameter2 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'DEL' ")

SYINPL_SESSION = SqlHelper.GetFirst("SELECT NEWID() AS A")

exceptinfo = ''

try:

	Stausquery = SqlHelper.GetFirst("SELECT count(*) as cnt from SYINPL(NOLOCK) WHERE INTEGRATION_NAME = 'SSCM_TO_CPQ_PRICING_DATA' AND ISNULL(STATUS,'') = 'INPROGRESS' ")	
	
	if Stausquery.cnt == 0:

		#Status Inprogress SYINPL by CPQ Table Entry ID
		
		StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''ERROR'',SESSION_ID=''"+str(SYINPL_SESSION.A)+"'' FROM SYINPL (NOLOCK)  WHERE isnull(status,'''')='''' AND INTEGRATION_NAME = ''SSCM_TO_CPQ_PRICING_DATA'' AND INTEGRATION_PAYLOAD NOT LIKE ''%QUOTE_ID%'' ' ")

		StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''INPROGRESS'',SESSION_ID=''"+str(SYINPL_SESSION.A)+"'' FROM SYINPL (NOLOCK)  WHERE isnull(status,'''')='''' AND INTEGRATION_NAME = ''SSCM_TO_CPQ_PRICING_DATA''  ' ")

		#Status Empty
		Jsonquery = SqlHelper.GetList("SELECT replace(INTEGRATION_PAYLOAD,'null','\"\"') as INTEGRATION_PAYLOAD,CpqTableEntryId from SYINPL(NOLOCK) WHERE INTEGRATION_NAME = 'SSCM_TO_CPQ_PRICING_DATA' AND ISNULL(STATUS,'') = 'INPROGRESS' AND SESSION_ID = '"+str(SYINPL_SESSION.A)+"' ")
		
		for json_data in Jsonquery:
				
			exceptinfo = str(json_data.CpqTableEntryId)
			sessiondetail = SqlHelper.GetFirst("SELECT NEWID() AS A")
			
			if "Param" in str(json_data.INTEGRATION_PAYLOAD):
				splited_list = str(json_data.INTEGRATION_PAYLOAD).split("%%")
				rebuilt_data = eval(str(splited_list[1]))
			else:
				splited_list = str(json_data.INTEGRATION_PAYLOAD)
				rebuilt_data = eval(splited_list)		
			
			primaryQuerysession =  SqlHelper.GetFirst("SELECT NEWID() AS A")
			today = datetime.datetime.now()
			Modi_date = today.strftime("%m/%d/%Y %H:%M:%S %p")


			if len(rebuilt_data) != 0:      

				rebuilt_data = rebuilt_data["CPQ_Columns"]
				Table_Names = rebuilt_data.keys()
				Check_flag = 0
				Qt_Id = ''
				Saqico_Flag = 0
				
				for tn in Table_Names:
					if tn in rebuilt_data:	
						if 1:
							if str(type(rebuilt_data[tn])) == "<type 'dict'>":
								Tbl_data = [rebuilt_data[tn]]
							else:
								Tbl_data = rebuilt_data[tn]
								
							for record_dict in Tbl_data:

								if 'HEADBUILD_QTY' not in record_dict:
									record_dict['HEADBUILD_QTY'] = ''

								for col in ['PM_TECH_LABOR_RATE','LESS_THAN_QTLY_HRS','LABOR_RATE','GREATER_THAN_QTLY_HRS','CM_LABOR_HRS','CM_HOURS_7_24','CM_HOURS_7_12','CM_HOURS_5_8']:
									if col not in record_dict:
										record_dict[col] = ''

								primaryQueryItems = SqlHelper.GetFirst( ""+ str(Parameter.QUERY_CRITERIA_1)+ " SAQICO_INBOUND (SESSION_ID,QUOTE_ID,EQUIPMENT_ID,ASSEMBLY_ID,SERVICE_ID,COST_MODULE_AVAILABLE,ASSEMBLY_NOT_REQUIRED_FLAG,GREATER_THAN_QTLY_COST,LESS_THAN_QTLY_COST,CLEAN_COST,SEEDSTOCK_COST,METROLOGY_COST,REFURB_COST,RECOATING_COST,CM_PART_COST,PM_PART_COST,LABOUR_COST,KPI_COST,TOTAL_COST_WISEEDSTOCK,TOTAL_COST_WOSEEDSTOCK,COST_CALCULATION_STATUS,MODULE_ID,MODULE_NAME,NPI,SERVICE_COMPLEXITY,PM_TECH_LABOR_RATE,LESS_THAN_QTLY_HRS,LABOR_RATE,GREATER_THAN_QTLY_HRS,CM_LABOR_HRS,CM_HOURS_7_24,CM_HOURS_7_12,CM_HOURS_5_8,HEADREBUILD_QTY)  select ''"+str(sessiondetail.A)+ "'',''"+str(record_dict['QUOTE_ID'])+ "'',''"+str(record_dict['EQUIPMENT_ID'])+ "'',''"+str(record_dict['ASSEMBLY_ID'])+ "'',''"+ str(record_dict['SERVICE_ID'])+ "'',''"+ str(record_dict['COST_MODULE_AVAILABLE'])+ "'',''"+ str(record_dict['ASSEMBLY_NOT_REQUIRED_FLAG'])+ "'',''"+ str(record_dict['GREATER_THAN_QTLY_COST'])+ "'',''"+ str(record_dict['LESS_THAN_QTLY_COST'])+ "'',''"+str(record_dict['CLEAN_COST'])+ "'',''"+str(record_dict['SEEDSTOCK_COST'])+ "'',''"+str(record_dict['METROLOGY_COST'])+ "'',''"+str(record_dict['REFURB_COST'])+ "'',''"+str(record_dict['RECOATING_COST'])+ "'',''"+str(record_dict['CM_PART_COST'])+ "'',''"+str(record_dict['PM_PART_COST'])+ "'',''"+str(record_dict['LABOR_COST'])+ "'',''"+str(record_dict['KPI_COST'])+ "'',''"+str(record_dict['TOTAL_COST_WISEEDSTOCK'])+ "'',''"+str(record_dict['TOTAL_COST_WOSEEDSTOCK'])+ "'',''"+str(record_dict['COST_CALCULATION_STATUS'])+ "'',''"+str(record_dict['MODULE_ID'])+ "'',''"+str(record_dict['MODULE_NAME'])+ "'',''"+str(record_dict['NPI'])+ "'',''"+str(record_dict['SERVICE_COMPLEXITY'])+ "'',''"+str(record_dict['PM_TECH_LABOR_RATE'])+ "'',''"+str(record_dict['LESS_THAN_QTLY_HRS'])+ "'',''"+str(record_dict['LABOR_RATE'])+ "'',''"+str(record_dict['GREATER_THAN_QTLY_HRS'])+ "'',''"+str(record_dict['CM_LABOR_HRS'])+ "'',''"+str(record_dict['CM_HOURS_7_24'])+ "'',''"+str(record_dict['CM_HOURS_7_12'])+ "'',''"+str(record_dict['CM_HOURS_5_8'])+ "'',CASE WHEN ISNULL(''"+str(record_dict['HEADBUILD_QTY'])+ "'','''')='''' THEN NULL ELSE ''"+str(record_dict['HEADBUILD_QTY'])+ "'' END ' ")
								
								
								Check_flag = 1
				
				primaryQueryItems = SqlHelper.GetFirst(
									""
									+ str(Parameter1.QUERY_CRITERIA_1)
									+ "  SAQICO_INBOUND SET QUOTE_ID = B.QUOTE_ID,REVISION_ID = B.QTEREV_ID FROM SAQICO_INBOUND (NOLOCK) A JOIN SAQTRV B(NOLOCK) ON A.QUOTE_ID = B.QUOTE_ID+''-''+CONVERT(VARCHAR,QTEREV_ID)  WHERE ISNULL(PROCESS_STATUS,'''')='''' AND ISNULL(SESSION_ID,'''')=''"+str(sessiondetail.A)+ "'' '")
				
				primaryQueryItems = SqlHelper.GetFirst(
									""
									+ str(Parameter1.QUERY_CRITERIA_1)
									+ "  SAQICO_INBOUND SET LINE = B.LINE FROM SAQICO_INBOUND (NOLOCK) A JOIN SAQRIT B(NOLOCK) ON A.QUOTE_ID = B.QUOTE_ID AND A.REVISION_ID = B.QTEREV_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.OBJECT_ID WHERE ISNULL(PROCESS_STATUS,'''')='''' AND ISNULL(SESSION_ID,'''')=''"+str(sessiondetail.A)+ "'' AND B.OBJECT_TYPE=''EQUIPMENT'' '")
				
				primaryQueryItems = SqlHelper.GetFirst(
									""
									+ str(Parameter1.QUERY_CRITERIA_1)
									+ "  SAQICO_INBOUND SET TOTAL_COST_WISEEDSTOCK = TOTAL_COST_WOSEEDSTOCK FROM SAQICO_INBOUND (NOLOCK) A WHERE ISNULL(PROCESS_STATUS,'''')='''' AND ISNULL(SESSION_ID,'''')=''"+str(sessiondetail.A)+ "'' AND ISNULL(CONVERT(FLOAT,TOTAL_COST_WISEEDSTOCK),0)<=0 '")
								
				Qt_Id = SqlHelper.GetFirst("select QUOTE_ID,REVISION_ID from SAQICO_INBOUND(Nolock) where ISNULL(SESSION_ID,'')='"+str(sessiondetail.A)+ "' ")
				
				Saqicoquery = SqlHelper.GetFirst("select count(*) as cnt from SAQICO(Nolock) where QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"' AND SAQICO.QTEREV_ID = '"+str(Qt_Id.REVISION_ID)+"' ")
				
				if Saqicoquery.cnt >0:
					Saqico_Flag = 1
				
				if Check_flag == 1 and Saqico_Flag == 1:
					
					Emailinfo = SqlHelper.GetFirst("SELECT QUOTE_ID,SSCM,0 as REMANING,QUOTE_RECORD_ID FROM (SELECT SAQICO.QUOTE_ID,COUNT(DISTINCT SAQICO.EQUIPMENT_ID) AS SSCM,SAQICO.QUOTE_RECORD_ID  FROM SAQICO (NOLOCK) WHERE SAQICO.QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"' AND SAQICO.QTEREV_ID = '"+str(Qt_Id.REVISION_ID)+"' AND ISNULL(STATUS,'') not in ('','Assembly is missing') group by SAQICO.Quote_ID,SAQICO.QUOTE_RECORD_ID )SUB_SAQICO ")  
					
					ToEml = SqlHelper.GetFirst("SELECT ISNULL(OWNER_ID,'X0116954') as OWNER_ID FROM SAQTMT (NOLOCK) WHERE SAQTMT.QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"'  ")  
					
					Emailinfo1 = SqlHelper.GetFirst("SELECT QUOTE_ID,CPQ FROM (SELECT SAQICO_INBOUND.QUOTE_ID,COUNT(DISTINCT SAQICO_INBOUND.EQUIPMENT_ID) AS CPQ FROM SAQICO_INBOUND (NOLOCK) WHERE SAQICO_INBOUND.QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"' AND SAQICO_INBOUND.REVISION_ID = '"+str(Qt_Id.REVISION_ID)+"' AND ISNULL(SESSION_ID,'')='"+str(sessiondetail.A)+ "' group by SAQICO_INBOUND.Quote_ID )SUB_SAQICO ")  
				
					# Mail system				
					Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #grey{background: rgb(245,245,245);} #bd{color : 'black';} </style></head><body id = 'bd'>"

					Table_start = "<p>Hi Team,<br><br>Cost data has been received from SSCM for the below Quote ID and the CPQ price calculation has been initiated. Will let you know shortly about the pricing status.</p><table class='table table-bordered'><tr><th id = 'grey'>Quote ID</th><th id = 'grey'>Tools sent (CPQ-SSCM)</th><th id = 'grey'>Tools received (SSCM-CPQ)</th><th id = 'grey'>Price Calculation Status</th></tr><tr><td >"+str(Qt_Id.QUOTE_ID)+"</td><td>"+str(Emailinfo.SSCM)+"</td ><td>"+str(Emailinfo1.CPQ)+"</td><td>Initiated</td></tr>"

					Table_info = ""
					Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"

					Error_Info = Header + Table_start + Table_info + Table_End

					LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

					# Create new SmtpClient object
					mailClient = SmtpClient()

					# Set the host and port (eg. smtp.gmail.com)
					mailClient.Host = "smtp.gmail.com"
					mailClient.Port = 587
					mailClient.EnableSsl = "true"

					# Setup NetworkCredential
					mailCred = NetworkCredential()
					mailCred.UserName = str(LOGIN_CRE.Username)
					mailCred.Password = str(LOGIN_CRE.Password)
					mailClient.Credentials = mailCred

					UserEmail = SqlHelper.GetFirst("SELECT isnull(email,'"+str(LOGIN_CRE.Username)+"') as email FROM saempl (nolock) where employee_id  = '"+str(ToEml.OWNER_ID)+"'")

					# Create two mail adresses, one for send from and the another for recipient
					if UserEmail is None:
						toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
					else:
						toEmail = MailAddress(UserEmail.email)
					fromEmail = MailAddress(str(LOGIN_CRE.Username))

					# Create new MailMessage object
					msg = MailMessage(fromEmail, toEmail)

					# Set message subject and body
					msg.Subject = "Pricing Initiated - AMAT CPQ(X-Tenant)"
					msg.IsBodyHtml = True
					msg.Body = Error_Info

					# Bcc Emails	
					copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail4)

					copyEmail6 = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail6) 

					# Send the message
					mailClient.Send(msg)

					#Calculation code started	
					sessionid = SqlHelper.GetFirst("SELECT NEWID() AS A")
					timestamp_sessionid = "'" + str(sessionid.A) + "'"	
					
					CRMQT = SqlHelper.GetFirst("select convert(varchar(100),c4c_quote_id) as c4c_quote_id from SAQTMT(nolock) WHERE QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"' ") 
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET TIMESTAMP = '"+str(timestamp_sessionid)+"',PROCESS_STATUS = ''INPROGRESS'' FROM SAQICO_INBOUND (NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')='''' AND ISNULL(SESSION_ID,'''')=''"+str(sessiondetail.A)+ "'' '")
					
					#Entitlement Temp		
					sess = SqlHelper.GetFirst("select left(convert(varchar(100),newid()),5) as sess  ")

					SAQIEN = "SAQIEN_BKP_"+str(CRMQT.c4c_quote_id)+str(sess.sess)
					CRMTMP = "CRMTMP_BKP_"+str(CRMQT.c4c_quote_id)+str(sess.sess)
					SAQSCE = "SAQSCE_BKP_"+str(CRMQT.c4c_quote_id)+str(sess.sess)
					
					SAQIEN_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(SAQIEN)+"'' ) BEGIN DROP TABLE "+str(SAQIEN)+" END  ' ")
					
					CRMTMP_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(CRMTMP)+"'' ) BEGIN DROP TABLE "+str(CRMTMP)+" END  ' ")
					
					SAQSCE_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(SAQSCE)+"'' ) BEGIN DROP TABLE "+str(SAQSCE)+" END  ' ")
					
					#Exchange Rate
					roundcurr1 = SqlHelper.GetFirst("select distinct CASE WHEN ROUNDING_DECIMAL_PLACES = '' THEN 0  ELSE ROUNDING_DECIMAL_PLACES END  AS DECIMAL_PLACES,CASE WHEN ROUNDING_METHOD='ROUND DOWN' THEN 1 ELSE 0 END AS ROUNDING_METHOD from prcurr (nolock) where currency= 'USD' ")
					
					roundcurr = SqlHelper.GetFirst("select distinct CASE WHEN ROUNDING_DECIMAL_PLACES = '' THEN 0  ELSE ROUNDING_DECIMAL_PLACES END  AS DECIMAL_PLACES,CASE WHEN ROUNDING_METHOD='ROUND DOWN' THEN 1 ELSE 0 END AS ROUNDING_METHOD from SAQRIT(nolock) a join prcurr (nolock) on a.DOC_CURRENCY = prcurr.currency where QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"' AND QTEREV_ID = '"+str(Qt_Id.REVISION_ID)+"' ")
					
					#Quote Item Covered Object Assembly Update 
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET CM_PART_COST=CONVERT(FLOAT,B.CM_PART_COST),PM_PART_COST = CONVERT(FLOAT,B.PM_PART_COST),ASSEMBLY_NOT_MAPPED = B.ASSEMBLY_NOT_REQUIRED_FLAG,CLEANING_COST = CONVERT(FLOAT,B.CLEAN_COST),COST_MODULE_AVAILABLE = B.COST_MODULE_AVAILABLE,COST_MODULE_STATUS = B.COST_CALCULATION_STATUS,GREATER_THAN_QTLY_PM_COST = CONVERT(FLOAT,B.GREATER_THAN_QTLY_COST),KPI_COST = CONVERT(FLOAT,B.KPI_COST),LABOR_COST = CONVERT(FLOAT,B.LABOUR_COST),LESS_THAN_QTLY_PM_COST= CONVERT(FLOAT,B.LESS_THAN_QTLY_COST),METROLOGY_COST=CONVERT(FLOAT, B.METROLOGY_COST),RECOATING_COST = CONVERT(FLOAT,B.RECOATING_COST),REFURB_COST = CONVERT(FLOAT,B.REFURB_COST),SEEDSTOCK_COST = CONVERT(FLOAT,B.SEEDSTOCK_COST),TOTAL_COST_WOSEEDSTOCK = CONVERT(FLOAT,B.TOTAL_COST_WOSEEDSTOCK),TOTAL_COST_WSEEDSTOCK = CONVERT(FLOAT,TOTAL_COST_WISEEDSTOCK),NPI = B.NPI,SERVICE_COMPLEXITY = B.SERVICE_COMPLEXITY FROM SAQICA A(NOLOCK) JOIN SAQICO_INBOUND B(NOLOCK) ON A.QUOTE_ID = B.QUOTE_ID AND A.QTEREV_ID = B.REVISION_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.ASSEMBLY_ID = B.ASSEMBLY_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND A.QUOTE_ID =''"+str(Qt_Id.QUOTE_ID)+"'' ' ")
					
					#Quote Item Covered Object Roll Up Cost
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET CMLBRC = B.LABOUR_COST, CMPREC = REPLACE_COST, CMPRFC =  REFURB_COST, GQPLBC = GREATER_THAN_QTLY_COST, LQPLBC = LESS_THAN_QTLY_COST, PMPCLC = CLEAN_COST, PMPMEC	= METROLOGY_COST, PMPRCC = RECOATING_COST, SDSTKC =  SEEDSTOCK_COST, KPINDC = KPI_COST, FAILRC = FAILURE_COST, OUTSRC = OUTSOURCE_COST, LGSTCC = LOGISTICS_COST , TNHRPT = HEADREBUILD_QTY, TCWOSS = B.TOTAL_COST_WOSEEDSTOCK,TCWISS = TOTAL_COST_WISEEDSTOCK FROM SAQICO A(NOLOCK) JOIN (SELECT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,SUM(CONVERT(FLOAT,CM_PART_COST)) AS CM_PART_COST,SUM(CONVERT(FLOAT,PM_PART_COST)) AS PM_PART_COST,SUM(CONVERT(FLOAT,CLEAN_COST)) AS CLEAN_COST, SUM(CONVERT(FLOAT,GREATER_THAN_QTLY_COST)) AS GREATER_THAN_QTLY_COST,SUM(CONVERT(FLOAT,KPI_COST)) AS KPI_COST,SUM(CONVERT(FLOAT,LABOUR_COST)) AS LABOUR_COST,SUM(CONVERT(FLOAT,LESS_THAN_QTLY_COST)) AS LESS_THAN_QTLY_COST,SUM(CONVERT(FLOAT,METROLOGY_COST)) AS METROLOGY_COST,SUM(CONVERT(FLOAT,RECOATING_COST)) AS RECOATING_COST,SUM(CONVERT(FLOAT,REFURB_COST)) AS REFURB_COST, SUM(CONVERT(FLOAT,SEEDSTOCK_COST)) AS SEEDSTOCK_COST,SUM(CONVERT(FLOAT,TOTAL_COST_WOSEEDSTOCK)) AS TOTAL_COST_WOSEEDSTOCK,SUM(CONVERT(FLOAT,TOTAL_COST_WISEEDSTOCK)) AS TOTAL_COST_WISEEDSTOCK,REVISION_ID,MIN(HEADREBUILD_QTY) AS HEADREBUILD_QTY,SUM(REPLACE_COST) AS REPLACE_COST,SUM(FAILURE_COST) AS FAILURE_COST, SUM(OUTSOURCE_COST) AS OUTSOURCE_COST, SUM(LOGISTICS_COST) AS LOGISTICS_COST FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' GROUP BY QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID ' ")
						
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET MODULE_ID=B.MODULE_ID,MODULE_NAME = B.MODULE_NAME,MODULE_RECORD_ID=COST_MODULE_RECORD_ID FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,MODULE_ID,MODULE_NAME  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID LEFT JOIN MACMDL (NOLOCK) ON B.MODULE_ID = MACMDL.MODULE_ID  ' ")
					
					#NPI Starts
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TOOL_NPI = ''Yes'' FROM SAQICO_INBOUND A(NOLOCK) JOIN (SELECT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,TIMESTAMP,SESSION_ID FROM SAQICO_INBOUND (NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND NPI = ''TRUE'' )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.TIMESTAMP = B.TIMESTAMP AND A.SESSION_ID = B.SESSION_ID  ' ")

					primaryQueryItems = SqlHelper.GetFirst(
											""
											+ str(Parameter1.QUERY_CRITERIA_1)
											+ "  SAQICO_INBOUND SET TOOL_NPI = ''No'' FROM SAQICO_INBOUND (NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_NPI,'''') = ''''  ' ")
					
					#Z0091 NPI
					primaryQueryItems = SqlHelper.GetFirst(
												""
												+ str(Parameter1.QUERY_CRITERIA_1)
												+ "  A SET NPI_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),NPI_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_NPI = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_NPI,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0091_VAL_NPIREC'' AND A.SERVICE_ID = ''Z0091'' ' ")
					
					#Z0092 NPI
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  A SET NPI_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),NPI_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_NPI = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_NPI,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0092_VAL_NPIREC'' AND A.SERVICE_ID = ''Z0092'' ' ")
					
					#Z0004 NPI
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  A SET NPI_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),NPI_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_NPI = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_NPI,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0004_VAL_NPIREC'' AND A.SERVICE_ID = ''Z0004'' ' ")
					
					#Z0099 NPI
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  A SET NPI_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),NPI_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_NPI = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_NPI,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0099_VAL_NPIREC'' AND A.SERVICE_ID = ''Z0099'' ' ")
					
					#Z0035 NPI
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  A SET NPI_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),NPI_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_NPI = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_NPI,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0035_VAL_NPIREC'' AND A.SERVICE_ID = ''Z0035'' ' ")
					
					#Z0009 NPI
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  A SET NPI_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),NPI_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_NPI = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_NPI,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0009_VAL_NPIREC'' AND A.SERVICE_ID = ''Z0009'' ' ")

					#Service Complexity	Starts								
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ " A SET GREENBOOK = B.GRNBOK, BLUEBOOK = B.BLUBOK, REGION = B.REGION FROM SAQICO_INBOUND (NOLOCK) A JOIN SAQICO (NOLOCK) B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.REVISION_ID = B.QTEREV_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' '")
						
					primaryQueryItems = SqlHelper.GetFirst(
											""
											+ str(Parameter1.QUERY_CRITERIA_1)
											+ " A SET TOOL_SERVICE_COMPLEXITY = B.SERVICE_COMPLEXITY FROM SAQICO_INBOUND A(NOLOCK) JOIN (SELECT A.QUOTE_ID,A.SERVICE_ID,A.EQUIPMENT_ID,A.REVISION_ID AS QTEREV_ID,CASE WHEN A.SERVICE_COMPLEXITY = ''DIFFICULT'' THEN ''Difficult'' ELSE A.SERVICE_COMPLEXITY END AS SERVICE_COMPLEXITY FROM SAQICO_INBOUND (NOLOCK) A JOIN SAQICA (NOLOCK) B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.REVISION_ID = B.QTEREV_ID AND A.ASSEMBLY_ID = B.ASSEMBLY_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND B.EQUIPMENTTYPE_ID=''MAINFRAME'' AND A.GREENBOOK IN (''CMP'',''PDC'',''MPS'',''IMPLANT'') )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.REVISION_ID = B.QTEREV_ID   '")

					primaryQueryItems = SqlHelper.GetFirst(
																""
																+ str(Parameter1.QUERY_CRITERIA_1)
																+ " A SET TOOL_SERVICE_COMPLEXITY = ''Difficult'' FROM SAQICO_INBOUND A(NOLOCK) JOIN (SELECT A.QUOTE_ID,A.SERVICE_ID,A.EQUIPMENT_ID,A.REVISION_ID AS QTEREV_ID,COUNT(*) AS SERVICE_COMPLEXITY FROM SAQICO_INBOUND (NOLOCK) A WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND A.SERVICE_COMPLEXITY = ''Difficult'' AND A.GREENBOOK NOT IN (''CMP'',''PDC'',''MPS'',''IMPLANT'') GROUP BY A.QUOTE_ID,A.SERVICE_ID,A.EQUIPMENT_ID,A.REVISION_ID )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.REVISION_ID = B.QTEREV_ID WHERE B.SERVICE_COMPLEXITY >= 2  '")

					primaryQueryItems = SqlHelper.GetFirst( ""+ str(Parameter1.QUERY_CRITERIA_1)+ " A SET TOOL_SERVICE_COMPLEXITY = CASE WHEN WA>=75 THEN ''Difficult'' WHEN WA>=25 AND WA<75 THEN ''MEDIUM'' WHEN WA<25 THEN ''EASY'' ELSE NULL END  FROM SAQICO_INBOUND A(NOLOCK) JOIN (SELECT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,QTEREV_ID,SCORE/SERVICE_COMPLEXITY AS WA FROM (SELECT A.QUOTE_ID,A.SERVICE_ID,A.EQUIPMENT_ID,A.REVISION_ID AS QTEREV_ID,COUNT(CASE WHEN ISNULL(SERVICE_COMPLEXITY,'''')='''' THEN NULL ELSE 1 END) AS SERVICE_COMPLEXITY,SUM(CASE WHEN ISNULL(SERVICE_COMPLEXITY,'''')=''DIFFICULT'' THEN 100 WHEN ISNULL(SERVICE_COMPLEXITY,'''')=''MEDIUM'' THEN 50 ELSE 0 END) AS SCORE FROM SAQICO_INBOUND (NOLOCK) A WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND A.GREENBOOK NOT IN (''CMP'',''PDC'',''MPS'',''IMPLANT'') GROUP BY A.QUOTE_ID,A.SERVICE_ID,A.EQUIPMENT_ID,A.REVISION_ID)B WHERE EQUIPMENT_ID IN (SELECT DISTINCT EQUIPMENT_ID FROM (SELECT A.QUOTE_ID,A.SERVICE_ID,A.EQUIPMENT_ID,A.REVISION_ID AS QTEREV_ID,COUNT(CASE WHEN ISNULL(SERVICE_COMPLEXITY,'''')=''DIFFICULT'' THEN 1 ELSE NULL END) AS SERV_COMP  FROM SAQICO_INBOUND (NOLOCK) A  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_SERVICE_COMPLEXITY,'''')='''' AND A.GREENBOOK NOT IN (''CMP'',''PDC'',''MPS'',''IMPLANT'') GROUP BY A.QUOTE_ID,A.SERVICE_ID,A.EQUIPMENT_ID,A.REVISION_ID ) A WHERE SERV_COMP<2) AND ISNULL(SERVICE_COMPLEXITY,0)>0 )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.REVISION_ID = B.QTEREV_ID    '")
					
					#Z0091 Service Complexity
					primaryQueryItems = SqlHelper.GetFirst(
																	""
																	+ str(Parameter1.QUERY_CRITERIA_1)
																	+ "  A SET SERVICECOMPLEXITY_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),SERVICE_COMPLEXITY_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_SERVICE_COMPLEXITY = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_SERVICE_COMPLEXITY,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0091_VAL_SCCCDF'' AND A.SERVICE_ID = ''Z0091'' ' ")
					
					#Z0092	Service Complexity 				
					primaryQueryItems = SqlHelper.GetFirst(
										""
										+ str(Parameter1.QUERY_CRITERIA_1)
										+ "  A SET SERVICECOMPLEXITY_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),SERVICE_COMPLEXITY_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_SERVICE_COMPLEXITY = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_SERVICE_COMPLEXITY,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0092_VAL_SCCCDF'' AND A.SERVICE_ID = ''Z0092'' ' ")
					
					#Z0004	Service Complexity				
					primaryQueryItems = SqlHelper.GetFirst(
										""
										+ str(Parameter1.QUERY_CRITERIA_1)
										+ "  A SET SERVICECOMPLEXITY_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),SERVICE_COMPLEXITY_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_SERVICE_COMPLEXITY = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_SERVICE_COMPLEXITY,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0004_VAL_SCCCDF'' AND A.SERVICE_ID = ''Z0004'' ' ")
					
					#Z0099 Service Complexity					
					primaryQueryItems = SqlHelper.GetFirst(
										""
										+ str(Parameter1.QUERY_CRITERIA_1)
										+ "  A SET SERVICECOMPLEXITY_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),SERVICE_COMPLEXITY_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_SERVICE_COMPLEXITY = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_SERVICE_COMPLEXITY,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0099_VAL_SCCCDF'' AND A.SERVICE_ID = ''Z0099'' ' ")
					
					#Z0035 Service Complexity					
					primaryQueryItems = SqlHelper.GetFirst(
										""
										+ str(Parameter1.QUERY_CRITERIA_1)
										+ "  A SET SERVICECOMPLEXITY_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),SERVICE_COMPLEXITY_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_SERVICE_COMPLEXITY = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_SERVICE_COMPLEXITY,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0035_VAL_SCCCDF'' AND A.SERVICE_ID = ''Z0035'' ' ")
					
					#Z0009	Service Complexity				
					primaryQueryItems = SqlHelper.GetFirst(
										""
										+ str(Parameter1.QUERY_CRITERIA_1)
										+ "  A SET SERVICECOMPLEXITY_COEFFICIENT = CONVERT(VARCHAR,ENTITLEMENT_COEFFICIENT),SERVICE_COMPLEXITY_CODE = ENTITLEMENT_VALUE_CODE FROM SAQICO_INBOUND (NOLOCK) A JOIN PRENVL B(NOLOCK) ON A.TOOL_SERVICE_COMPLEXITY = B.ENTITLEMENT_DISPLAY_VALUE WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(TOOL_SERVICE_COMPLEXITY,'''') <> '''' AND ENTITLEMENT_ID = ''AGS_Z0009_VAL_SCCCDF'' AND A.SERVICE_ID = ''Z0009'' ' ")
					
					#LTCOSS - Total Cost without Seedstock Coefficient
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET LTCOSS = LOG(TCWOSS) * OSSVDV FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE AND ISNULL(TCWOSS,0)>0 ' ")
					
					#CAVVDV - Capital Avoidance Coefficient
					primaryQueryItems = SqlHelper.GetFirst(
												""
												+ str(Parameter1.QUERY_CRITERIA_1)
												+ "  A SET CAVVDV = B.SEEDSTOCK_COST / B.TOTAL_COST_WISEEDSTOCK FROM SAQICO (NOLOCK) A JOIN (SELECT DISTINCT QUOTE_ID,REVISION_ID,EQUIPMENT_ID,SERVICE_ID,SUM(CONVERT(FLOAT,SEEDSTOCK_COST)) AS SEEDSTOCK_COST,SUM(CONVERT(FLOAT,TOTAL_COST_WISEEDSTOCK)) AS TOTAL_COST_WISEEDSTOCK,LINE FROM SAQICO_INBOUND(NOLOCK)B  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' GROUP BY QUOTE_ID,REVISION_ID,SERVICE_ID,EQUIPMENT_ID,LINE)B ON A.QUOTE_ID = B.QUOTE_ID AND A.QTEREV_ID = B.REVISION_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.LINE = B.LINE WHERE ISNULL(B.TOTAL_COST_WISEEDSTOCK,0)>0 ' ")
					
					#SCMVDV - Service Complexity Value Driver
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET SCMVDV = TOOL_SERVICE_COMPLEXITY FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE,TOOL_SERVICE_COMPLEXITY  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
						
					#SCMVDC - Service Complexity Coefficient
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET SCMVDC = SERVICECOMPLEXITY_COEFFICIENT FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE,SERVICECOMPLEXITY_COEFFICIENT  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#NPIVDV - NPI Tool Value Driver
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET NPIVDV = TOOL_NPI FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE,TOOL_NPI  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
						
					#NPIVDC - NPI Tool Coefficient
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET NPIVDC = NPI_COEFFICIENT FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE,NPI_COEFFICIENT  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#PBPVDC - PDC Coefficent
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET PBPVDC = LOG(PDCBPR) * PBPVDV FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE,NPI_COEFFICIENT  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
						
					#SUMCOF - Sum of All Coefficient
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET SUMCOF = ISNULL(INTCPC,0) + ISNULL(LTCOSS,0) + ISNULL(POFVDC,0) + ISNULL(GBKVDC,0) + ISNULL(UIMVDC,0) + ISNULL(CAVVDC,0) + ISNULL(WNDVDC,0) + ISNULL(SCMVDC,0) + ISNULL(CCDFFC,0) + ISNULL(NPIVDC,0) + ISNULL(DTPVDC,0) + ISNULL(CSTVDC,0) + ISNULL(CSGVDC,0) + ISNULL(QRQVDC,0) + ISNULL(SVCVDC,0) + ISNULL(RKFVDC,0) + ISNULL(PBPVDC,0) + ISNULL(ADDCOF,0) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#INMP01 - Intermediate Model Price 1
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET INMP01 = EXP(SUMCOF) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
						
					#INMP02 / FNMDPR - Intermediate Model Price 2 /  Final Model Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET INMP02 = INMP01 * (1 + ISNULL(CCRTMC,0)), FNMDPR = INMP01 * (1 + ISNULL(CCRTMC,0)) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#FNMDPR - Final Model Price (Z0100 / Z0101)
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A CNSM_MARGIN_PERCENT = D.CNSM_MARGIN_PERCENT FROM SAQICO_INBOUND(NOLOCK)A JOIN SABGMR D(NOLOCK) ON A.GREENBOOK = D.GREENBOOK AND A.BLUEBOOK = D.BLUEBOOK WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A CNSM_MARGIN_PERCENT = D.CNSM_MARGIN_PERCENT FROM SAQICO_INBOUND(NOLOCK)A JOIN SABGMR D(NOLOCK) ON A.GREENBOOK = D.GREENBOOK AND A.REGION = D.REGION WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND CNSM_MARGIN_PERCENT IS NULL ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET FNMDPR =  TCWISS / (1 - (CNSM_MARGIN_PERCENT/100)), MTGPRC =  TCWISS / (1 - (CNSM_MARGIN_PERCENT/100)), MSLPRC =  TCWISS / (1 - (CNSM_MARGIN_PERCENT/100)), MBDPRC =  TCWISS / (1 - (CNSM_MARGIN_PERCENT/100)), MCLPRC =  TCWISS / (1 - (CNSM_MARGIN_PERCENT/100)) ,CNTCST = TCWISS, CNTPRC = TCWISS / (1 - (CNSM_MARGIN_PERCENT/100))  FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE,CNSM_MARGIN_PERCENT FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' )B ON A.QUOTE_ID = B.QUOTE_ID AND A.LINE = B.LINE AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND QTEREV_ID = REVISION_ID  WHERE ISNULL(TCWISS,0)>0 AND A.SERVICE_ID IN (''Z0100'',''Z0101'')  ' ")
					
					#MTGPRC - Target Model Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET MTGPRC = CASE WHEN ISNULL(FNMDPR/(1-(CONVERT(FLOAT,SADSPC)/100)),0) > ISNULL(TCWISS / (1-(TAPMMP/100)),0) THEN ISNULL(FNMDPR/(1-(CONVERT(FLOAT,SADSPC)/100)),0) ELSE ISNULL(TCWISS / (1-(TAPMMP/100)),0) END FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#MSLPRC - Sales Model Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET MSLPRC = CASE WHEN ISNULL(FNMDPR,0) > ISNULL(TCWISS / (1-(CONVERT(FLOAT,SAPMMP)/100)),0) THEN ISNULL(FNMDPR,0) ELSE ISNULL(TCWISS / (1-(CONVERT(FLOAT,SAPMMP)/100)),0) END  FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#MBDPRC - BD Model Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET MBDPRC = CASE WHEN ISNULL(FNMDPR * (1-(CONVERT(FLOAT,BDDSPC)/100)) ,0) > ISNULL(TCWISS / (1-(CONVERT(FLOAT,BDPMMP)/100)),0) THEN ISNULL(FNMDPR * (1-(CONVERT(FLOAT,BDDSPC)/100)) ,0) ELSE ISNULL(TCWISS / (1-(CONVERT(FLOAT,BDPMMP)/100)),0) END FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#MCLPRC - Ceiling Model Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET MCLPRC = MTGPRC * (1 + ISNULL(CEPRUP,0)) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#TOTLCI - Total Cost Impact
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TOTLCI = ISNULL(CAVVCI,0) + ISNULL(UIMVCI,0) + ISNULL(ATGKEC,0) + ISNULL(AMNCCI,0) + ISNULL(HEDBIC,0) + ISNULL(NWPTOC,0) + ISNULL(NUMLCI,0) + ISNULL(SPCCLC,0) + ISNULL(SPCCCI,0) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#TOTLPI - Total Price Impact
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TOTLPI = ISNULL(ATGKEP,0) + ISNULL(AMNPPI,0) + ISNULL(CAVVPI,0) + ISNULL(HEDBIP,0) + ISNULL(NWPTOP,0) + ISNULL(NUMLPI,0) + ISNULL(SPCCLP,0) + ISNULL(SPCCPI,0) + ISNULL(UIMVPI,0) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#FCWOSS - Final Total Cost without Seedstock
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET FCWOSS = ISNULL(TCWOSS,0) + ISNULL(TOTLCI,0) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#FCWISS - Final Total Cost with Seedstock
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET FCWISS = ISNULL(TCWISS,0) + ISNULL(TOTLCI,0) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#TRGPRC /SLSPRC / BDVPRC /CELPRC - Target / Sales / BD / Ceiling Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TRGPRC = ISNULL(MTGPRC,0) + ISNULL(TOTLPI,0), SLSPRC = ISNULL(MSLPRC,0) + ISNULL(TOTLPI,0), BDVPRC = ISNULL(MBDPRC,0) + ISNULL(TOTLPI,0), CELPRC = ISNULL(MCLPRC,0) + ISNULL(TOTLPI,0)  FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#USRPRC / TGADJP - User Price / Target User Price Adjustment
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET USRPRC = TRGPRC,TGADJP = ''0.00'' FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#CNTPRC - Contractual Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET CNTPRC = ((USRPRC / 365) * CNTDAY * ISNULL(CTPDFP ,1) ) * (1 - (ISNULL(YOYPCT,0)/100))  FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE WHERE A.SERVICE_ID NOT IN (''Z0100'',''Z0101'')  ' ")
					
					#CNTCST - Contractual Cost
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET CNTCST = ((FCWISS / 365) * CNTDAY )  FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE WHERE A.SERVICE_ID NOT IN (''Z0100'',''Z0101'') ' ")
					
					#CNTMGN - Contractual Margin
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET CNTMGN = CNTPRC - CNTCST FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE WHERE A.SERVICE_ID NOT IN (''Z0100'',''Z0101'') ' ")
					
					#SPCTPR /SPCTCS - Spares Contractual Price / Cost
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET SPCTPR = CNTPRC * SPSPCT, SPCTCS = CNTCST * SPSPCT FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
						
					#SPCTMG - Spares Contractual Margin
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET SPCTMG = (SPCTPR - SPCTCS) / SPCTPR FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#SVCTPR /SVCTCS - Service Contractual Price / Cost
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET SVCTPR = CNTPRC * SVSPCT, SVCTCS = CNTCST * SVSPCT FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#SVCTMG - Service Contractual Margin
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET SVCTMG = (SVCTPR - SVCTCS) / SVCTPR FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE  ' ")
					
					#TNTVGC / TNTMGC / TNTMPC - Total Net Value / Total Net Value in Margin / Margin % (Global Currency) 
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TNTVGC = CASE WHEN ISNULL(SPQTEV,''NO'')=''NO'' THEN CNTPRC ELSE SPCTPR END, TNTMGC = CASE WHEN ISNULL(SPQTEV,''NO'')=''NO'' THEN CNTPRC - CNTCST ELSE SPCTPR - SPCTCS END, TNTMPC = CASE WHEN ISNULL(SPQTEV,''NO'')=''NO'' THEN (CNTPRC - CNTCST) / CNTPRC ELSE (SPCTPR - SPCTCS) / SPCTPR END FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE WHERE A.BILTYP <> ''VARIABLE'' ' ")
					
					#TENVGC - Estimated Value (Global Currency)
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TENVGC = CASE WHEN ISNULL(SPQTEV,''NO'')=''NO'' THEN CNTPRC ELSE SPCTPR END, TNTMGC = CASE WHEN ISNULL(SPQTEV,''NO'')=''NO'' THEN CNTPRC - CNTCST ELSE SPCTPR - SPCTCS END FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE WHERE A.BILTYP = ''VARIABLE'' ' ")
						
					#TAXVGC - Tax Amount (Global Currency) 
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TAXVGC = TNTVGC * (ISNULL(TAXVTP,0)/100) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE ' ")
					
					#TAMTGC - Total Amount (Global Currency) 
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TAMTGC = TNTVGC + ISNULL(TAXVGC,0) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE ' ")
					
					#Round Off
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TAMTGC = ROUND(TAMTGC ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")), TAXVGC = ROUND(TAXVGC ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")), TNTVGC = ROUND(TNTVGC ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")) FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE ' ")
					
					#TNTVDC / TAXVDC / TAMTDC /TENVDC - Total Net Value / Tax / Total Amount/ Estimated (Document Currency) 
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET TNTVDC = ROUND( (TNTVGC * ISNULL(DCCRFX,1)) ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")), TAXVDC = ROUND( (TAXVGC * ISNULL(DCCRFX,1)) ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")), TAMTDC = ROUND( (TAMTGC * ISNULL(DCCRFX,1)) ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")), TENVDC = ROUND( (TENVGC * ISNULL(DCCRFX,1)) ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+"))  FROM SAQICO A(NOLOCK) JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID,LINE  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.QTEREV_ID = B.REVISION_ID AND A.LINE = B.LINE ' ")

					#Item Roll Up
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET TAX_AMOUNT_INGL_CURR = ROUND(ISNULL(TAXVGC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")) ,NET_VALUE_INGL_CURR =  ROUND(ISNULL(TNTVGC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")),UNIT_PRICE_INGL_CURR = ROUND(ISNULL(USRPRC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")),TAX_AMOUNT = ROUND(ISNULL(TAXVDC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")) ,NET_VALUE =  ROUND(ISNULL(TNTVDC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")),UNIT_PRICE = ROUND(ISNULL(USRPRC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")),TOTAL_AMOUNT = ROUND(ISNULL(TAMTDC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")),TOTAL_AMOUNT_INGL_CURR = ROUND(ISNULL(TAMTGC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")),ESTIMATED_VALUE = ROUND(ISNULL(TENVDC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")),ESTVAL_INGL_CURR = ROUND(ISNULL(TENVGC,0),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")) FROM SAQRIT SAQITM(NOLOCK) JOIN(SELECT SAQICO.QTEREV_ID,LINE,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SUM(TAXVGC) AS TAXVGC, SUM(TNTVGC) AS TNTVGC,SUM(USRPRC) AS USRPRC,SUM(TAXVDC) AS TAXVDC, SUM(TAMTDC) AS TAMTDC,SUM(TAMTGC) AS TAMTGC, SUM(TNTVDC) AS TNTVDC,SUM(TENVDC) AS TENVDC, SUM(TENVGC) AS TENVGC FROM SAQICO (NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'' GROUP BY SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.QTEREV_ID,SAQICO.LINE) SUB_SAQITM  ON SAQITM.QUOTE_ID = SUB_SAQITM.QUOTE_ID AND SAQITM.SERVICE_ID = SUB_SAQITM.SERVICE_ID  AND SAQITM.SERVICE_ID <> ''Z0116'' AND SUB_SAQITM.QTEREV_ID = SAQITM.QTEREV_ID  AND SAQITM.LINE = SUB_SAQITM.LINE ' ")

					#Item Roll Up Year 1
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET YEAR_1_INGL_CURR = TNTVGC, YEAR_1 = TNTVDC FROM SAQRIT SAQITM(NOLOCK) JOIN(SELECT SUM(SAQICO.TNTVGC) AS TNTVGC,SAQICO.QTEREV_ID,LINE,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SUM(TNTVDC) AS TNTVDC FROM SAQICO (NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'' AND CNTYER=''YEAR 1'' GROUP BY SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.QTEREV_ID,SAQICO.LINE) SUB_SAQITM  ON SAQITM.QUOTE_ID = SUB_SAQITM.QUOTE_ID AND SAQITM.SERVICE_ID = SUB_SAQITM.SERVICE_ID AND SUB_SAQITM.QTEREV_ID = SAQITM.QTEREV_ID  AND SAQITM.LINE = SUB_SAQITM.LINE ' ")

					#Item Roll Up Year 2
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET YEAR_2_INGL_CURR = TNTVGC, YEAR_2 = TNTVDC FROM SAQRIT SAQITM(NOLOCK) JOIN(SELECT SUM(SAQICO.TNTVGC) AS TNTVGC,SAQICO.QTEREV_ID,LINE,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SUM(TNTVDC) AS TNTVDC FROM SAQICO (NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'' AND CNTYER=''YEAR 2'' GROUP BY SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.QTEREV_ID,SAQICO.LINE) SUB_SAQITM  ON SAQITM.QUOTE_ID = SUB_SAQITM.QUOTE_ID AND SAQITM.SERVICE_ID = SUB_SAQITM.SERVICE_ID AND SUB_SAQITM.QTEREV_ID = SAQITM.QTEREV_ID  AND SAQITM.LINE = SUB_SAQITM.LINE ' ")

					#Item Roll Up Year 3
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET YEAR_3_INGL_CURR = TNTVGC, YEAR_3 = TNTVDC FROM SAQRIT SAQITM(NOLOCK) JOIN(SELECT SUM(SAQICO.TNTVGC) AS TNTVGC,SAQICO.QTEREV_ID,LINE,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SUM(TNTVDC) AS TNTVDC FROM SAQICO (NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'' AND CNTYER=''YEAR 3'' GROUP BY SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.QTEREV_ID,SAQICO.LINE) SUB_SAQITM  ON SAQITM.QUOTE_ID = SUB_SAQITM.QUOTE_ID AND SAQITM.SERVICE_ID = SUB_SAQITM.SERVICE_ID AND SUB_SAQITM.QTEREV_ID = SAQITM.QTEREV_ID  AND SAQITM.LINE = SUB_SAQITM.LINE ' ")

					#Item Roll Up Year 4
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET YEAR_4_INGL_CURR = TNTVGC, YEAR_4 = TNTVDC FROM SAQRIT SAQITM(NOLOCK) JOIN(SELECT SUM(SAQICO.TNTVGC) AS TNTVGC,SAQICO.QTEREV_ID,LINE,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SUM(TNTVDC) AS TNTVDC FROM SAQICO (NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'' AND CNTYER=''YEAR 4'' GROUP BY SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.QTEREV_ID,SAQICO.LINE) SUB_SAQITM  ON SAQITM.QUOTE_ID = SUB_SAQITM.QUOTE_ID AND SAQITM.SERVICE_ID = SUB_SAQITM.SERVICE_ID AND SUB_SAQITM.QTEREV_ID = SAQITM.QTEREV_ID  AND SAQITM.LINE = SUB_SAQITM.LINE ' ")

					#Item Roll Up Year 5
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET YEAR_5_INGL_CURR =TNTVGC, YEAR_5 = TNTVDC FROM SAQRIT SAQITM(NOLOCK) JOIN(SELECT SUM(SAQICO.TNTVGC) AS TNTVGC,SAQICO.QTEREV_ID,LINE,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SUM(TNTVDC) AS TNTVDC FROM SAQICO (NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'' AND CNTYER=''YEAR 5'' GROUP BY SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.QTEREV_ID,SAQICO.LINE) SUB_SAQITM  ON SAQITM.QUOTE_ID = SUB_SAQITM.QUOTE_ID AND SAQITM.SERVICE_ID = SUB_SAQITM.SERVICE_ID AND SUB_SAQITM.QTEREV_ID = SAQITM.QTEREV_ID  AND SAQITM.LINE = SUB_SAQITM.LINE ' ")
					
					#Status - Partially Priced
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQICO SET STATUS=''PARTIALLY PRICED'' FROM SAQICO (NOLOCK) JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(COST_MODULE_AVAILABLE,'''')=''UNAVAILABLE'' AND ISNULL(COST_CALCULATION_STATUS,'''') <> ''Chamber map not required'' )SAQICO_INBOUND ON SAQICO.QUOTE_ID = SAQICO_INBOUND.QUOTE_ID AND SAQICO.SERVICE_ID = SAQICO_INBOUND.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQICO_INBOUND.EQUIPMENT_ID AND SAQICO.QTEREV_ID = SAQICO_INBOUND.REVISION_ID  '")
					
					#Status - Error
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQICO SET STATUS=''ERROR'' FROM SAQICO (NOLOCK) JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,REVISION_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(COST_MODULE_AVAILABLE,'''')=''UNAVAILABLE'' AND ISNULL(COST_CALCULATION_STATUS,'''') = ''Tool Not Available'' )SAQICO_INBOUND ON SAQICO.QUOTE_ID = SAQICO_INBOUND.QUOTE_ID AND SAQICO.SERVICE_ID = SAQICO_INBOUND.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQICO_INBOUND.EQUIPMENT_ID AND SAQICO.QTEREV_ID = SAQICO_INBOUND.REVISION_ID  '")
					
					#Status - Acquired
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQICO SET STATUS=''ACQUIRED'' FROM SAQICO (NOLOCK) JOIN SAQICA(NOLOCK) ON SAQICO.QUOTE_ID = SAQICA.QUOTE_ID AND SAQICO.SERVICE_ID = SAQICA.SERVICE_ID AND SAQICO.QTEREV_ID = SAQICA.QTEREV_ID AND SAQICO.EQUIPMENT_ID = SAQICA.EQUIPMENT_ID JOIN SAQICO_INBOUND C(NOLOCK)ON SAQICO.QUOTE_ID = C.QUOTE_ID AND SAQICO.QTEREV_ID = C.REVISION_ID  AND SAQICO.SERVICE_ID = C.SERVICE_ID AND SAQICO.EQUIPMENT_ID = C.EQUIPMENT_ID WHERE TIMESTAMP = '"+str(timestamp_sessionid)+"' AND STATUS NOT IN (''PARTIALLY PRICED'',''ERROR'',''ASSEMBLY IS MISSING'') '")
					
					#Status - Partially Priced
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET STATUS=''PARTIALLY PRICED'' FROM SAQRIT SAQITM (NOLOCK) WHERE QUOTE_REVISION_CONTRACT_ITEM_ID IN (SELECT DISTINCT QTEITM_RECORD_ID FROM SAQICO_INBOUND(NOLOCK)A JOIN SAQICO B(NOLOCK) ON A.QUOTE_ID= B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(COST_MODULE_AVAILABLE,'''')=''UNAVAILABLE'' AND B.STATUS=''PARTIALLY PRICED'') AND SERVICE_ID IN (SELECT DISTINCT SERVICE_ID FROM PRSPRV(NOLOCK) WHERE ISNULL(SSCM_COST,''FALSE'')=''TRUE'' )  '")
					
					#Status - Acquired
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET STATUS=''ACQUIRED'' FROM SAQRIT SAQITM (NOLOCK) WHERE QUOTE_REVISION_CONTRACT_ITEM_ID IN (SELECT DISTINCT QTEITM_RECORD_ID FROM SAQICO_INBOUND(NOLOCK)A JOIN SAQICO B(NOLOCK) ON A.QUOTE_ID= B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND B.STATUS=''ACQUIRED'') AND SERVICE_ID IN (SELECT DISTINCT SERVICE_ID FROM PRSPRV(NOLOCK) WHERE ISNULL(SSCM_COST,''FALSE'')=''TRUE'' )  '")
					
					#Status - Error
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET STATUS=''ERROR'' FROM SAQRIT SAQITM (NOLOCK) WHERE QUOTE_REVISION_CONTRACT_ITEM_ID IN (SELECT DISTINCT QTEITM_RECORD_ID FROM SAQICO(NOLOCK)  WHERE QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'' AND STATUS IN (''ERROR'',''ASSEMBLY IS MISSING'')) AND SERVICE_ID IN (SELECT DISTINCT SERVICE_ID FROM PRSPRV(NOLOCK) WHERE ISNULL(SSCM_COST,''FALSE'')=''TRUE'' )  '")
					
					#Status - On Hold Costing
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQTRV SET REVISION_STATUS=''ON HOLD - COSTING'' FROM SAQTRV A(NOLOCK) JOIN (SELECT DISTINCT QUOTE_ID,QTEREV_ID FROM SAQICO B(NOLOCK)  WHERE  STATUS  IN (''PARTIALLY PRICED'',''ERROR'',''ASSEMBLY IS MISSING'') AND QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'')B ON A.QUOTE_ID = B.QUOTE_ID AND A.QTEREV_ID = B.QTEREV_ID '")
					
					#Status - Approval Pending
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQTRV SET REVISION_STATUS=''APPROVAL PENDING'' FROM SAQTRV A(NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'' AND NOT EXISTS (SELECT ''X'' FROM SAQICO B(NOLOCK)  WHERE  STATUS IN(''PARTIALLY PRICED'',''ERROR'',''ASSEMBLY IS MISSING'') AND QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'') '")
					
					#Status - Priced
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET STATUS=''PRICED'' FROM SAQRIT SAQITM (NOLOCK) WHERE QUOTE_REVISION_CONTRACT_ITEM_ID NOT IN (SELECT QTEITM_RECORD_ID FROM SAQICO B(NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id.QUOTE_ID)+"'' AND QTEREV_ID = ''"+str(Qt_Id.REVISION_ID)+"'' AND STATUS IN (''PARTIALLY PRICED'',''ERROR'',''ASSEMBLY IS MISSING'')) AND STATUS NOT IN (''ON HOLD - COSTING'',''ON HOLD - PRICING'',''ACQUIRING'',''PARTIALLY PRICED'',''ERROR'',''ASSEMBLY IS MISSING'') '")

					quote_revision_object = SqlHelper.GetFirst("SELECT QUOTE_RECORD_ID, QTEREV_RECORD_ID FROM SAQTRV WHERE QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"' AND QTEREV_ID = '"+str(Qt_Id.REVISION_ID)+"' ")

					##Calling the iflow script to update the details in c4c..(cpq to c4c write back...)
					CQCPQC4CWB.writeback_to_c4c("quote_header",quote_revision_object.QUOTE_RECORD_ID,quote_revision_object.QTEREV_RECORD_ID)
					CQCPQC4CWB.writeback_to_c4c("opportunity_header",quote_revision_object.QUOTE_RECORD_ID,quote_revision_object.QTEREV_RECORD_ID)
					
					#Status Completed in SYINPL by CPQ Table Entry ID
					StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''COMPLETED'' FROM SYINPL (NOLOCK) A WHERE CpqTableEntryId = ''"+str(json_data.CpqTableEntryId)+"'' AND SESSION_ID =''"+str(SYINPL_SESSION.A)+"'' ' ")

					StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter2.QUERY_CRITERIA_1)+ " FROM SAQICO_INBOUND  WHERE ISNULL(SESSION_ID,'''')=''"+str(sessiondetail.A)+ "'' ' ")

					SAQIEN_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(SAQIEN)+"'' ) BEGIN DROP TABLE "+str(SAQIEN)+" END  ' ")
					
					CRMTMP_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(CRMTMP)+"'' ) BEGIN DROP TABLE "+str(CRMTMP)+" END  ' ")
					
					Log.Info("QTPOSTQTPR pricing async call End --->"+str(Qt_Id.QUOTE_ID))
					# Mail system				
					Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #grey{background: rgb(245,245,245);} #bd{color : 'black';} </style></head><body id = 'bd'>"

					Table_start = "<p>Hi Team,<br><br>Pricing has been completed in CPQ, for the equipment's in below Quote ID.</p><table class='table table-bordered'><tr><th id = 'grey'>Quote ID</th><th id = 'grey'>Tools sent (CPQ-SSCM)</th><th id = 'grey'>Tools received (SSCM-CPQ)</th><th id = 'grey'>Price Calculation Status</th></tr><tr><td >"+str(Emailinfo.QUOTE_ID)+"</td><td>"+str(Emailinfo.SSCM)+"</td ><td>"+str(Emailinfo1.CPQ)+"</td><td>Completed</td></tr>"

					Table_info = ""
					Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"

					Error_Info = Header + Table_start + Table_info + Table_End

					LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

					# Create new SmtpClient object
					mailClient = SmtpClient()

					# Set the host and port (eg. smtp.gmail.com)
					mailClient.Host = "smtp.gmail.com"
					mailClient.Port = 587
					mailClient.EnableSsl = "true"

					# Setup NetworkCredential
					mailCred = NetworkCredential()
					mailCred.UserName = str(LOGIN_CRE.Username)
					mailCred.Password = str(LOGIN_CRE.Password)
					mailClient.Credentials = mailCred

					#Current user email(Toemail)
					#UserId = User.Id
					#Log.Info("123 UserId.UserId --->"+str(UserId))
					UserEmail = SqlHelper.GetFirst("SELECT isnull(email,'"+str(LOGIN_CRE.Username)+"') as email FROM saempl (nolock) where employee_id  = '"+str(ToEml.OWNER_ID)+"'")
					#Log.Info("123 UserEmail.email --->"+str(UserEmail.email))

					# Create two mail adresses, one for send from and the another for recipient
					if UserEmail is None:
						toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
					else:
						toEmail = MailAddress(UserEmail.email)
					fromEmail = MailAddress(str(LOGIN_CRE.Username))

					# Create new MailMessage object
					msg = MailMessage(fromEmail, toEmail)

					# Set message subject and body
					msg.Subject = "Pricing Completed - AMAT CPQ(X-Tenant)"
					msg.IsBodyHtml = True
					msg.Body = Error_Info

					# Bcc Emails	
					copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail4)

					copyEmail6 = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail6)

					# Send the message
					mailClient.Send(msg)


					Greenbkquery=SqlHelper.GetList("SELECT DISTINCT SAQICO.GRNBOK as GREENBOOK,ISNULL(SABUUN.DISTRIBUTION_EMAIL,'') AS DISTRIBUTION_EMAIL  FROM SAQICO(NOLOCK) JOIN SABUUN (NOLOCK) ON SAQICO.GRNBOK = SABUUN.BUSINESSUNIT_ID WHERE SAQICO.STATUS IN ('ERROR','PARTIALLY PRICED','ASSEMBLY IS MISSING') AND SAQICO.QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"' AND SAQICO.QTEREV_ID = '"+str(Qt_Id.REVISION_ID)+"' ")

					for Gbk in Greenbkquery:


						Grnbkdataquery=SqlHelper.GetList("SELECT SAQICO.GRNBOK as GREENBOOK,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.EQUIPMENT_ID,SAQICA.ASSEMBLY_ID,SAQICA.COST_MODULE_AVAILABLE,ISNULL(SAQICA.COST_MODULE_STATUS,'ASSEMBLY IS MISSING') AS COST_MODULE_STATUS FROM SAQICO (NOLOCK) JOIN SAQICA (NOLOCK) ON SAQICO.QUOTE_ID = SAQICA.QUOTE_ID AND SAQICO.QTEREV_ID = SAQICA.QTEREV_ID AND SAQICO.SERVICE_ID = SAQICA.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQICA.EQUIPMENT_ID WHERE SAQICO.STATUS IN ('ERROR','PARTIALLY PRICED' ) AND SAQICO.GRNBOK= '"+str(Gbk.GREENBOOK)+"' AND SAQICO.QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"' AND SAQICO.QTEREV_ID = '"+str(Qt_Id.REVISION_ID)+"' AND  SAQICA.COST_MODULE_AVAILABLE= 'UNAVAILABLE' AND SAQICA.COST_MODULE_STATUS <>'Chamber map not required' UNION ALL SELECT SAQICO.GRNBOK,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.EQUIPMENT_ID,'' AS ASSEMBLY_ID,'' AS COST_MODULE_AVAILABLE,'ASSEMBLY IS MISSING' AS COST_MODULE_STATUS FROM SAQICO (NOLOCK)  WHERE SAQICO.STATUS IN ('ASSEMBLY IS MISSING' ) AND SAQICO.GRNBOK= '"+str(Gbk.GREENBOOK)+"' AND SAQICO.QUOTE_ID = '"+str(Qt_Id.QUOTE_ID)+"' AND SAQICO.QTEREV_ID = '"+str(Qt_Id.REVISION_ID)+"' ")

						tbl_info = ''
						for gbkinfo in Grnbkdataquery:
							tbl_info = tbl_info+"<tr><td>"+str(gbkinfo.SERVICE_ID)+"</td><td>"+str(gbkinfo.GREENBOOK)+"</td ><td>"+str(gbkinfo.EQUIPMENT_ID)+"</td><td>"+str(gbkinfo.ASSEMBLY_ID)+"</td><td>"+str(gbkinfo.COST_MODULE_AVAILABLE)+"</td><td>"+str(gbkinfo.COST_MODULE_STATUS)+"</td></tr>"
						if len(tbl_info) > 0:
							Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #grey{background: rgb(245,245,245);} #bd{color : 'black';} </style></head><body id = 'bd'>"

							Table_start = "<p>Hi Team,<br><br>This Quote "+str(Qt_Id.QUOTE_ID)+"  is placed on ON HOLD COSTING status for the below cost information pending from SSCM system or Assembly missing in CPQ from IBASE.</p><table class='table table-bordered'><tr><th id = 'grey'>Service ID</th><th id = 'grey'>Green Book</th><th id = 'grey'>Equipment ID</th><th id = 'grey'>Assembly ID</th><th id = 'grey'>Cost Module Available</th><th id = 'grey'>Cost Module Status</th></tr>"+str(tbl_info)

							Table_info = ""
							Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"

							Error_Info = Header + Table_start + Table_info + Table_End

							LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

							# Create new SmtpClient object
							mailClient = SmtpClient()

							# Set the host and port (eg. smtp.gmail.com)
							mailClient.Host = "smtp.gmail.com"
							mailClient.Port = 587
							mailClient.EnableSsl = "true"

							# Setup NetworkCredential
							mailCred = NetworkCredential()
							mailCred.UserName = str(LOGIN_CRE.Username)
							mailCred.Password = str(LOGIN_CRE.Password)
							mailClient.Credentials = mailCred

							UserEmail = []
							if len(Gbk.DISTRIBUTION_EMAIL) > 0:
								UserEmail = str(Gbk.DISTRIBUTION_EMAIL).split(';')

							if len(UserEmail) == 0:
									toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
							else:								
								toEmail = MailAddress(UserEmail[0])
							
							fromEmail = MailAddress(str(LOGIN_CRE.Username))	

							# Create new MailMessage object
							msg = MailMessage(fromEmail, toEmail)							

							# Set message subject and body
							sub = "On Hold - Costing Quote("+str(Gbk.GREENBOOK)+")- AMAT CPQ (X-Tenant)"
							msg.Subject = sub
							msg.IsBodyHtml = True
							msg.Body = Error_Info

							#Comon CC mails
							copyEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
							msg.CC.Add(copyEmail)					

							copyEmail5 = MailAddress("baji.baba@bostonharborconsulting.com")
							msg.CC.Add(copyEmail5) 

							# Bcc Emails	
							if len(UserEmail) > 0:
								for emalinfo in  UserEmail:
									copyEmail = MailAddress(emalinfo)
									msg.Bcc.Add(copyEmail)

							# Send the message QT_REC_ID
							mailClient.Send(msg)
					#opening quote for update quote items
					try:
						quote_Edit = QuoteHelper.Edit(Qt_Id.QUOTE_ID)
					except:
						Log.Info("quote error")
					CallingCQIFWUDQTM = ScriptExecutor.ExecuteGlobal("CQIFWUDQTM",{"QT_REC_ID":Qt_Id.QUOTE_ID})	
					# Billing matrix async call
					LOGIN_CREDENTIALS = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password,Domain FROM SYCONF where Domain='AMAT_TST'")

					if LOGIN_CREDENTIALS is not None:
						Login_Username = str(LOGIN_CREDENTIALS.Username)
						Login_Password = str(LOGIN_CREDENTIALS.Password)
						authorization = Login_Username+":"+Login_Password
						binaryAuthorization = UTF8.GetBytes(authorization)
						authorization = Convert.ToBase64String(binaryAuthorization)
						authorization = "Basic " + authorization


						webclient = System.Net.WebClient()
						webclient.Headers[System.Net.HttpRequestHeader.ContentType] = "application/json"
						webclient.Headers[System.Net.HttpRequestHeader.Authorization] = authorization;
						
						result = '''<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">	<soapenv:Body><CPQ_Columns>	<QUOTE_ID>{Qt_Id}</QUOTE_ID><REVISION_ID>{Rev_Id}</REVISION_ID></CPQ_Columns></soapenv:Body></soapenv:Envelope>'''.format( Qt_Id= quote_revision_object.QUOTE_RECORD_ID,Rev_Id = quote_revision_object.QTEREV_RECORD_ID)
						
						#LOGIN_CRE = SqlHelper.GetFirst("SELECT URL FROM SYCONF where EXTERNAL_TABLE_NAME ='BILLING_MATRIX_ASYNC'")
						#Async = webclient.UploadString(str(LOGIN_CRE.URL), str(result))

						level = "QT_QTQICO LEVEL"
						try:
							CQVLDRIFLW.iflow_valuedriver_rolldown(str(Emailinfo.QUOTE_RECORD_ID),level)
						except:
							Log.Info('Quote error')
					
					
					Unprocsseddataquery = SqlHelper.GetFirst("SELECT count(*) as cnt from SYINPL(NOLOCK) WHERE INTEGRATION_NAME = 'SSCM_TO_CPQ_PRICING_DATA' AND ISNULL(STATUS,'') = '' ")	

					if Unprocsseddataquery.cnt > 0 :
						#Async call for SSCM TO CPQ Unprocessed data 
						LOGIN_CREDENTIALS = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password,Domain FROM SYCONF where Domain='AMAT_TST'")
						if LOGIN_CREDENTIALS is not None:
							Login_Username = str(LOGIN_CREDENTIALS.Username)
							Login_Password = str(LOGIN_CREDENTIALS.Password)
							authorization = Login_Username+":"+Login_Password
							binaryAuthorization = UTF8.GetBytes(authorization)
							authorization = Convert.ToBase64String(binaryAuthorization)
							authorization = "Basic " + authorization


							webclient = System.Net.WebClient()
							webclient.Headers[System.Net.HttpRequestHeader.ContentType] = "application/json"
							webclient.Headers[System.Net.HttpRequestHeader.Authorization] = authorization;
							
							result = '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body ></soapenv:Body></soapenv:Envelope>'
							
							LOGIN_CRE = SqlHelper.GetFirst("SELECT URL FROM SYCONF where EXTERNAL_TABLE_NAME ='CPQ_TO_SSCM_PRICING_ASYNC'")
							Async = webclient.UploadString(str(LOGIN_CRE.URL), str(result))
					else: 
						ApiResponse = ApiResponseFactory.JsonResponse({"Response": [{"Status": "200", "Message": "Data Successfully Uploaded"}]})
				else:
					if Saqico_Flag == 0:
						Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #bd{color : 'black';} </style></head><body id = 'bd'>"

						Table_start = "<p>Hi Team,<br><br>SSCM Pricing script having follwing SAQICO data error for following Quote Id ---  "+str(Qt_Id.QUOTE_ID)+".<br><br></p><br>"
						
						Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"
						Table_info = ""     

						Error_Info = Header + Table_start + Table_info + Table_End

						LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

						# Create new SmtpClient object
						mailClient = SmtpClient()

						# Set the host and port (eg. smtp.gmail.com)
						mailClient.Host = "smtp.gmail.com"
						mailClient.Port = 587
						mailClient.EnableSsl = "true"

						# Setup NetworkCredential
						mailCred = NetworkCredential()
						mailCred.UserName = str(LOGIN_CRE.Username)
						mailCred.Password = str(LOGIN_CRE.Password)
						mailClient.Credentials = mailCred

						# Create two mail adresses, one for send from and the another for recipient
						toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
						fromEmail = MailAddress(str(LOGIN_CRE.Username))

						# Create new MailMessage object
						msg = MailMessage(fromEmail, toEmail)

						# Set message subject and body
						msg.Subject = "SSCM to CPQ - SAQICO Error Notification(X-Tenant)"
						msg.IsBodyHtml = True
						msg.Body = Error_Info

						# CC Emails 	
						copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
						msg.CC.Add(copyEmail4)
						
						copyEmail5 = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
						msg.CC.Add(copyEmail5) 					

						# Send the message
						mailClient.Send(msg)
					if Check_flag == 1:
						#Status Empty in SYINPL
						StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  A SET STATUS = ''Hold'' FROM SYINPL (NOLOCK) A WHERE SESSION_ID=''"+str(SYINPL_SESSION.A)+"''   AND  STATUS = ''INPROGRESS'' '")
	else:
		ApiResponse = ApiResponseFactory.JsonResponse({"Response": [{"Status": "200", "Message": "Session is running.Status is Inprogress"}]})
		

except:
	#Status Empty in SYINPL
	StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  A SET STATUS = '''' FROM SYINPL (NOLOCK) A WHERE SESSION_ID=''"+str(SYINPL_SESSION.A)+"''  ' ")
				
	Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #bd{color : 'black';} </style></head><body id = 'bd'>"

	Table_start = "<p>Hi Team,<br><br>SSCM Pricing script having follwing Error in Line number "+str(sys.exc_info()[-1].tb_lineno)+".<br><br>"+str(sys.exc_info()[1])+"</p><br>"
	
	Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"
	Table_info = ""     

	Error_Info = Header + Table_start + Table_info + Table_End

	LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

	# Create new SmtpClient object
	mailClient = SmtpClient()

	# Set the host and port (eg. smtp.gmail.com)
	mailClient.Host = "smtp.gmail.com"
	mailClient.Port = 587
	mailClient.EnableSsl = "true"

	# Setup NetworkCredential
	mailCred = NetworkCredential()
	mailCred.UserName = str(LOGIN_CRE.Username)
	mailCred.Password = str(LOGIN_CRE.Password)
	mailClient.Credentials = mailCred

	# Create two mail adresses, one for send from and the another for recipient
	toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
	fromEmail = MailAddress(str(LOGIN_CRE.Username))

	# Create new MailMessage object
	msg = MailMessage(fromEmail, toEmail)

	# Set message subject and body
	msg.Subject = "SSCM to CPQ - Pricing Error Notification(X-Tenant)"
	msg.IsBodyHtml = True
	msg.Body = Error_Info

	# CC Emails 	
	copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
	msg.CC.Add(copyEmail4)

	copyEmail5 = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
	msg.CC.Add(copyEmail5)
	
	# Send the message
	mailClient.Send(msg) 
	
	Log.Info("QTPOSTQTPR ERROR---->:" + str(sys.exc_info()[1]))
	Log.Info("QTPOSTQTPR ERROR LINE NO---->:" + str(sys.exc_info()[-1].tb_lineno))
	ApiResponse = ApiResponseFactory.JsonResponse({"Response": [{"Status": "400", "Message": str(sys.exc_info()[1])}]})