# =========================================================================================================================================
#   __script_name : QTPOSTQTPR.PY
#   __script_description : THIS SCRIPT IS USED TO INSERT PRICING DATA IN SAQICO_INBOUND FROM SYINPL
#   __primary_author__ : SURESH MUNIYANDI, BAJI
#   __create_date : 2020-11-16
#   © BOSTON HARBOR TECHNOLOGY LLC - ALL RIGHTS RESERVED
# ==========================================================================================================================================
import sys
import datetime
import clr
import System.Net
from System.Text.Encoding import UTF8
from System import Convert
from SYDATABASE import SQL
import CQVLDRIFLW

clr.AddReference("System.Net")
from System.Net import CookieContainer, NetworkCredential, Mail
from System.Net.Mail import SmtpClient, MailAddress, Attachment, MailMessage

Parameter = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'SELECT' ")
Parameter1 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'UPD' ")
Parameter2 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'DEL' ")

SYINPL_SESSION = SqlHelper.GetFirst("SELECT NEWID() AS A")

exceptinfo = ''

try:

	Stausquery = SqlHelper.GetFirst("SELECT count(*) as cnt from SYINPL(NOLOCK) WHERE INTEGRATION_NAME = 'SSCM_TO_CPQ_PRICING_DATA' AND ISNULL(STATUS,'') = 'INPROGRESS' ")	
	
	if Stausquery.cnt == 0:

		#Status Inprogress SYINPL by CPQ Table Entry ID

		StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''DUPLICATE'' FROM SYINPL (NOLOCK)  WHERE isnull(status,'''')='''' AND INTEGRATION_NAME = ''SSCM_TO_CPQ_PRICING_DATA'' AND integration_key IN (SELECT integration_key FROM SYINPL(NOLOCK) WHERE isnull(status,'''')=''INPROGRESS'' AND INTEGRATION_NAME = ''SSCM_TO_CPQ_PRICING_DATA'') ' ")

		StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''INPROGRESS'',SESSION_ID=''"+str(SYINPL_SESSION.A)+"'' FROM SYINPL (NOLOCK)  WHERE isnull(status,'''')='''' AND INTEGRATION_NAME = ''SSCM_TO_CPQ_PRICING_DATA''  ' ")

		#Status Empty
		Jsonquery = SqlHelper.GetList("SELECT INTEGRATION_PAYLOAD,CpqTableEntryId from SYINPL(NOLOCK) WHERE INTEGRATION_NAME = 'SSCM_TO_CPQ_PRICING_DATA' AND ISNULL(STATUS,'') = 'INPROGRESS' AND SESSION_ID = '"+str(SYINPL_SESSION.A)+"' ")
		
		for json_data in Jsonquery:			
			
			exceptinfo = str(json_data.CpqTableEntryId)
			sessiondetail = SqlHelper.GetFirst("SELECT NEWID() AS A")
			
			if "Param" in str(json_data.INTEGRATION_PAYLOAD):
				splited_list = str(json_data.INTEGRATION_PAYLOAD).split("'")
				rebuilt_data = eval(str(splited_list[1]))
			else:
				splited_list = str(json_data.INTEGRATION_PAYLOAD)
				rebuilt_data = eval(splited_list)		
			
			primaryQuerysession =  SqlHelper.GetFirst("SELECT NEWID() AS A")
			today = datetime.datetime.now()
			Modi_date = today.strftime("%m/%d/%Y %H:%M:%S %p")


			if len(rebuilt_data) != 0:      

				rebuilt_data = rebuilt_data["CPQ_Columns"]
				Table_Names = rebuilt_data.keys()
				Check_flag = 0
				Qt_Id = ''

				
				for tn in Table_Names:
					if tn in rebuilt_data:	
						if 1:
							if str(type(rebuilt_data[tn])) == "<type 'dict'>":
								Tbl_data = [rebuilt_data[tn]]
							else:
								Tbl_data = rebuilt_data[tn]
								
							for record_dict in Tbl_data:

								primaryQueryItems = SqlHelper.GetFirst( ""+ str(Parameter.QUERY_CRITERIA_1)+ " SAQICO_INBOUND (SESSION_ID,QUOTE_ID,EQUIPMENT_ID,ASSEMBLY_ID,SERVICE_ID,COST_MODULE_AVAILABLE,ASSEMBLY_NOT_REQUIRED_FLAG,GREATER_THAN_QTLY_COST,LESS_THAN_QTLY_COST,CLEAN_COST,SEEDSTOCK_COST,METROLOGY_COST,REFURB_COST,RECOATING_COST,CM_PART_COST,PM_PART_COST,LABOUR_COST,KPI_COST,TOTAL_COST_WISEEDSTOCK,TOTAL_COST_WOSEEDSTOCK,COST_CALCULATION_STATUS)  select ''"+str(sessiondetail.A)+ "'',''"+str(record_dict['QUOTE_ID'])+ "'',''"+str(record_dict['EQUIPMENT_ID'])+ "'',''"+str(record_dict['ASSEMBLY_ID'])+ "'',''"+ str(record_dict['SERVICE_ID'])+ "'',''"+ str(record_dict['COST_MODULE_AVAILABLE'])+ "'',''"+ str(record_dict['ASSEMBLY_NOT_REQUIRED_FLAG'])+ "'',''"+ str(record_dict['GREATER_THAN_QTLY_COST'])+ "'',''"+ str(record_dict['LESS_THAN_QTLY_COST'])+ "'',''"+str(record_dict['CLEAN_COST'])+ "'',''"+str(record_dict['SEEDSTOCK_COST'])+ "'',''"+str(record_dict['METROLOGY_COST'])+ "'',''"+str(record_dict['REFURB_COST'])+ "'',''"+str(record_dict['RECOATING_COST'])+ "'',''"+str(record_dict['CM_PART_COST'])+ "'',''"+str(record_dict['PM_PART_COST'])+ "'',''"+str(record_dict['LABOR_COST'])+ "'',''"+str(record_dict['KPI_COST'])+ "'',''"+str(record_dict['TOTAL_COST_WISEEDSTOCK'])+ "'',''"+str(record_dict['TOTAL_COST_WOSEEDSTOCK'])+ "'',''"+str(record_dict['COST_CALCULATION_STATUS'])+ "'' ' ")
								
								Qt_Id = str(record_dict['QUOTE_ID'])
								Check_flag = 1
								
				if Check_flag == 1:  

					Emailinfo = SqlHelper.GetFirst("SELECT QUOTE_ID,SSCM,0 as REMANING,QUOTE_RECORD_ID FROM (SELECT SAQICO.QUOTE_ID,COUNT(DISTINCT SAQICO.EQUIPMENT_ID) AS SSCM,SAQICO.QUOTE_RECORD_ID  FROM SAQICO (NOLOCK) WHERE SAQICO.QUOTE_ID = '"+str(Qt_Id)+"' AND ISNULL(PRICING_STATUS,'')<> '' group by SAQICO.Quote_ID,SAQICO.QUOTE_RECORD_ID )SUB_SAQICO ")  
					
					ToEml = SqlHelper.GetFirst("SELECT ISNULL(OWNER_ID,'X0116959') as OWNER_ID FROM SAQTMT (NOLOCK) WHERE SAQTMT.QUOTE_ID = '"+str(Qt_Id)+"'  ")  
					
					Emailinfo1 = SqlHelper.GetFirst("SELECT QUOTE_ID,CPQ FROM (SELECT SAQICO_INBOUND.QUOTE_ID,COUNT(DISTINCT SAQICO_INBOUND.EQUIPMENT_ID) AS CPQ FROM SAQICO_INBOUND (NOLOCK) WHERE SAQICO_INBOUND.QUOTE_ID = '"+str(Qt_Id)+"' AND ISNULL(SESSION_ID,'')='"+str(sessiondetail.A)+ "' group by SAQICO_INBOUND.Quote_ID )SUB_SAQICO ")  
				
					# Mail system				
					Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #grey{background: rgb(245,245,245);} #bd{color : 'black';} </style></head><body id = 'bd'>"

					Table_start = "<p>Hi Team,<br><br>Cost data has been received from SSCM for the below Quote ID and the CPQ price calculation has been initiated. Will let you know shortly about the pricing status.</p><table class='table table-bordered'><tr><th id = 'grey'>Quote ID</th><th id = 'grey'>Tools sent (CPQ-SSCM)</th><th id = 'grey'>Tools received (SSCM-CPQ)</th><th id = 'grey'>Price Calculation Status</th></tr><tr><td >"+str(Qt_Id)+"</td><td>"+str(Emailinfo.SSCM)+"</td ><td>"+str(Emailinfo1.CPQ)+"</td><td>Initiated</td></tr>"

					Table_info = ""
					Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"

					Error_Info = Header + Table_start + Table_info + Table_End

					LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

					# Create new SmtpClient object
					mailClient = SmtpClient()

					# Set the host and port (eg. smtp.gmail.com)
					mailClient.Host = "smtp.gmail.com"
					mailClient.Port = 587
					mailClient.EnableSsl = "true"

					# Setup NetworkCredential
					mailCred = NetworkCredential()
					mailCred.UserName = str(LOGIN_CRE.Username)
					mailCred.Password = str(LOGIN_CRE.Password)
					mailClient.Credentials = mailCred

					UserEmail = SqlHelper.GetFirst("SELECT isnull(email,'INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM') as email FROM saempl (nolock) where employee_id  = '"+str(ToEml.OWNER_ID)+"'")

					# Create two mail adresses, one for send from and the another for recipient
					if UserEmail is None:
						toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
					else:
						toEmail = MailAddress(UserEmail.email)
					fromEmail = MailAddress("INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM")

					# Create new MailMessage object
					msg = MailMessage(fromEmail, toEmail)

					# Set message subject and body
					msg.Subject = "Pricing Initiated - AMAT CPQ QA"
					msg.IsBodyHtml = True
					msg.Body = Error_Info

					# Bcc Emails	
					copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail4)

					copyEmail1 = MailAddress("ranjani.parkavi@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail1) 

					copyEmail3 = MailAddress("sathyabama.akhala@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail3)

					copyEmail5 = MailAddress("ashish.gandotra@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail5)
					
					copyEmail6 = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail6)

					# Send the message
					mailClient.Send(msg)

					#Calculation code started	
					sessionid = SqlHelper.GetFirst("SELECT NEWID() AS A")
					timestamp_sessionid = "'" + str(sessionid.A) + "'"	
					
					CRMQT = SqlHelper.GetFirst("select convert(varchar(100),c4c_quote_id) as c4c_quote_id from SAQTMT(nolock) WHERE QUOTE_ID = '"+str(Qt_Id)+"' ") 
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET TIMESTAMP = '"+str(timestamp_sessionid)+"',PROCESS_STATUS = ''INPROGRESS'' FROM SAQICO_INBOUND (NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')='''' AND ISNULL(SESSION_ID,'''')=''"+str(sessiondetail.A)+ "'' '")
					
					#Managed Service					
					SAQIEN = "SAQIEN_BKP_"+str(CRMQT.c4c_quote_id)
					
					#Exchange Rate
					roundcurr1 = SqlHelper.GetFirst("select distinct CASE WHEN ROUNDING_DECIMAL_PLACES = '' THEN 0  ELSE ROUNDING_DECIMAL_PLACES END  AS DECIMAL_PLACES,CASE WHEN ROUNDING_METHOD='ROUND DOWN' THEN 1 ELSE 0 END AS ROUNDING_METHOD from prcurr (nolock) where currency= 'USD' ")
					
					roundcurr = SqlHelper.GetFirst("select distinct CASE WHEN ROUNDING_DECIMAL_PLACES = '' THEN 0  ELSE ROUNDING_DECIMAL_PLACES END  AS DECIMAL_PLACES,CASE WHEN ROUNDING_METHOD='ROUND DOWN' THEN 1 ELSE 0 END AS ROUNDING_METHOD from SAQICO(nolock) a join prcurr (nolock) on a.DOC_CURRENCY = prcurr.currency where quote_Id= '"+str(Qt_Id)+"' ")
						
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET EXCHANGE_RATE = SAQICO.EXCHANGE_RATE FROM SAQICO_INBOUND (NOLOCK) JOIN SAQICO (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQICO.QUOTE_ID AND SAQICO_INBOUND.EQUIPMENT_ID = SAQICO.EQUIPMENT_ID AND SAQICO_INBOUND.SERVICE_ID = SAQICO.SERVICE_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'   ' ")
					
					#Quote Item Covered Object Assembly Update 
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET CM_PART_COST=B.CM_PART_COST,PM_PART_COST = B.PM_PART_COST,ASSEMBLY_NOT_MAPPED = B.ASSEMBLY_NOT_REQUIRED_FLAG,CLEANING_COST = B.CLEAN_COST,COST_MODULE_AVAILABLE = B.COST_MODULE_AVAILABLE,COST_MODULE_STATUS = B.COST_CALCULATION_STATUS,GREATER_THAN_QTLY_PM_COST = B.GREATER_THAN_QTLY_COST,KPI_COST = B.KPI_COST,LABOR_COST = B.LABOUR_COST,LESS_THAN_QTLY_PM_COST= B.LESS_THAN_QTLY_COST,METROLOGY_COST= B.METROLOGY_COST,RECOATING_COST = B.RECOATING_COST,REFURB_COST = B.REFURB_COST,SEEDSTOCK_COST = B.SEEDSTOCK_COST,TOTAL_COST_WOSEEDSTOCK = B.TOTAL_COST_WOSEEDSTOCK,TOTAL_COST_WSEEDSTOCK = TOTAL_COST_WISEEDSTOCK FROM SAQICA A(NOLOCK) JOIN SAQICO_INBOUND B(NOLOCK) ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.ASSEMBLY_ID = B.ASSEMBLY_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  ' ")
					
					#Quote Item Covered Object Roll Up Cost
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  A SET CM_PART_COST=B.CM_PART_COST,PM_PART_COST = B.PM_PART_COST,CLEANING_COST = B.CLEAN_COST,GREATER_THAN_QTLY_PM_COST = B.GREATER_THAN_QTLY_COST,KPI_COST = B.KPI_COST,LABOR_COST = B.LABOUR_COST,LESS_THAN_QTLY_PM_COST= B.LESS_THAN_QTLY_COST,METROLOGY_COST= B.METROLOGY_COST,RECOATING_COST = B.RECOATING_COST,REFURB_COST = B.REFURB_COST,SEEDSTOCK_COST = B.SEEDSTOCK_COST,TOTAL_COST_WOSEEDSTOCK = B.TOTAL_COST_WOSEEDSTOCK,TOTAL_COST_WSEEDSTOCK = TOTAL_COST_WISEEDSTOCK FROM SAQICO A(NOLOCK) JOIN (SELECT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,SUM(CONVERT(FLOAT,CM_PART_COST)) AS CM_PART_COST,SUM(CONVERT(FLOAT,PM_PART_COST)) AS PM_PART_COST,SUM(CONVERT(FLOAT,CLEAN_COST)) AS CLEAN_COST, SUM(CONVERT(FLOAT,GREATER_THAN_QTLY_COST)) AS GREATER_THAN_QTLY_COST,SUM(CONVERT(FLOAT,KPI_COST)) AS KPI_COST,SUM(CONVERT(FLOAT,LABOUR_COST)) AS LABOUR_COST,SUM(CONVERT(FLOAT,LESS_THAN_QTLY_COST)) AS LESS_THAN_QTLY_COST,SUM(CONVERT(FLOAT,METROLOGY_COST)) AS METROLOGY_COST,SUM(CONVERT(FLOAT,RECOATING_COST)) AS RECOATING_COST,SUM(CONVERT(FLOAT,REFURB_COST)) AS REFURB_COST, SUM(CONVERT(FLOAT,SEEDSTOCK_COST)) AS SEEDSTOCK_COST,SUM(CONVERT(FLOAT,TOTAL_COST_WOSEEDSTOCK)) AS TOTAL_COST_WOSEEDSTOCK,SUM(CONVERT(FLOAT,TOTAL_COST_WISEEDSTOCK)) AS TOTAL_COST_WISEEDSTOCK  FROM SAQICO_INBOUND B(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' GROUP BY QUOTE_ID,SERVICE_ID,EQUIPMENT_ID  )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID ' ")
					
					#Coefficient
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET INTERCEPT = VALUEDRIVER_COEFFICIENT FROM SAQICO_INBOUND (NOLOCK) JOIN SAQICO (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQICO.QUOTE_ID AND SAQICO_INBOUND.EQUIPMENT_ID = SAQICO.EQUIPMENT_ID AND SAQICO_INBOUND.SERVICE_ID = SAQICO.SERVICE_ID JOIN PRGBVL C(NOLOCK) ON SAQICO.GREENBOOK = C.GREENBOOK  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND C.VALUEDRIVER_ID = ''Intercept''  ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET LOG_FACTOR = VALUEDRIVER_COEFFICIENT FROM SAQICO_INBOUND (NOLOCK) JOIN SAQICO (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQICO.QUOTE_ID AND SAQICO_INBOUND.EQUIPMENT_ID = SAQICO.EQUIPMENT_ID AND SAQICO_INBOUND.SERVICE_ID = SAQICO.SERVICE_ID JOIN PRGBVL C(NOLOCK) ON SAQICO.GREENBOOK = C.GREENBOOK  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND C.VALUEDRIVER_ID = ''Total Cost w/o seedstock''  ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET LOG_FACTOR = ''0.94'' FROM SAQICO_INBOUND (NOLOCK) JOIN SAQICO (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQICO.QUOTE_ID AND SAQICO_INBOUND.EQUIPMENT_ID = SAQICO.EQUIPMENT_ID AND SAQICO_INBOUND.SERVICE_ID = SAQICO.SERVICE_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(LOG_FACTOR,0)=0 AND SAQICO.GREENBOOK <>''PDC'' ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET LOG_FACTOR = ''0.92'' FROM SAQICO_INBOUND (NOLOCK) JOIN SAQICO (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQICO.QUOTE_ID AND SAQICO_INBOUND.EQUIPMENT_ID = SAQICO.EQUIPMENT_ID AND SAQICO_INBOUND.SERVICE_ID = SAQICO.SERVICE_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(LOG_FACTOR,0)=0 AND SAQICO.GREENBOOK=''PDC'' ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET TOTAL_COEFFICIENT = VALUEDRIVER_COEFFICIENT FROM SAQICO_INBOUND A(NOLOCK) JOIN (SELECT QUOTE_ID,EQUIPMENT_ID,SERVICE_ID,SUM(VALUEDRIVER_COEFFICIENT) AS VALUEDRIVER_COEFFICIENT FROM SAQSCV(NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id)+"'' GROUP BY QUOTE_ID,EQUIPMENT_ID,SERVICE_ID)B ON A.QUOTE_ID = B.QUOTE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID AND A.SERVICE_ID = B.SERVICE_ID  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET TOTAL_COEFFICIENT = ISNULL(TOTAL_COEFFICIENT,0) + VALUEDRIVER_COEFFICIENT FROM SAQICO_INBOUND A (NOLOCK) JOIN (SELECT QUOTE_ID,EQUIPMENT_ID,SUM(VALUEDRIVER_COEFFICIENT) AS VALUEDRIVER_COEFFICIENT FROM SAQEDV(NOLOCK) WHERE QUOTE_ID = ''"+str(Qt_Id)+"'' GROUP BY QUOTE_ID,EQUIPMENT_ID)B ON A.QUOTE_ID = B.QUOTE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  ' ")
						
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET TOTAL_COST_WSEEDSTOCK = TOTAL_COST_WSEEDSTOCK + ISNULL(ENTITLEMENT_COST_IMPACT,0) FROM SAQICO A(NOLOCK) JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID  ' ")
						
					#Model Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET MODEL_PRICE = EXP(ISNULL(INTERCEPT,0) + (LOG(TOTAL_COST_WOSEEDSTOCK)) * ISNULL(LOG_FACTOR,1) + ISNULL(TOTAL_COEFFICIENT,0) )  FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,TOTAL_COEFFICIENT,INTERCEPT,LOG_FACTOR FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID WHERE A.GREENBOOK<>''PDC'' AND ISNULL(TOTAL_COST_WOSEEDSTOCK,0)>0  ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET MODEL_PRICE = MODEL_PRICE + ISNULL(ENTITLEMENT_PRICE_IMPACT,0) FROM SAQICO A(NOLOCK) JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' )B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID  ' ")
					
					#Price Margin 
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET TARGET_PRICE_MARGIN= FACTOR_TXTVAR,TARGET_PRICE_MARGIN_RECORD_ID = CALCULATION_VARIABLE_RECORD_ID FROM SAQICO (NOLOCK)A JOIN PRCFVA B(NOLOCK) ON A.SERVICE_ID = B.FACTOR_VARIABLE_ID WHERE QUOTE_ID = ''"+str(Qt_Id)+"'' AND FACTOR_ID=''TGMRGN'' AND TARGET_PRICE_MARGIN IS NULL ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET SLSDIS_PRICE_MARGIN= FACTOR_TXTVAR,SLSDIS_PRICE_MARGIN_RECORD_ID=CALCULATION_VARIABLE_RECORD_ID FROM SAQICO (NOLOCK)A JOIN PRCFVA B(NOLOCK) ON A.SERVICE_ID = B.FACTOR_VARIABLE_ID WHERE QUOTE_ID = ''"+str(Qt_Id)+"'' AND FACTOR_ID=''SLMRGN'' AND SLSDIS_PRICE_MARGIN IS NULL ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET BD_PRICE_MARGIN= FACTOR_TXTVAR,BD_PRICE_MARGIN_RECORD_ID=CALCULATION_VARIABLE_RECORD_ID FROM SAQICO (NOLOCK)A JOIN PRCFVA B(NOLOCK) ON A.SERVICE_ID = B.FACTOR_VARIABLE_ID WHERE QUOTE_ID = ''"+str(Qt_Id)+"'' AND FACTOR_ID=''BDMRGN'' AND BD_PRICE_MARGIN IS NULL ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET CEILING_PRICE_MARGIN= FACTOR_TXTVAR,CEILING_PRICE_MARGIN_RECORD_ID=CALCULATION_VARIABLE_RECORD_ID FROM SAQICO (NOLOCK)A JOIN PRCFVA B(NOLOCK) ON A.SERVICE_ID = B.FACTOR_VARIABLE_ID WHERE QUOTE_ID = ''"+str(Qt_Id)+"'' AND FACTOR_ID=''CEMRGN'' AND CEILING_PRICE_MARGIN IS NULL ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET SALDIS_PERCENT= FACTOR_TXTVAR FROM SAQICO (NOLOCK)A JOIN PRCFVA B(NOLOCK) ON A.SERVICE_ID = B.FACTOR_VARIABLE_ID WHERE QUOTE_ID = ''"+str(Qt_Id)+"'' AND FACTOR_ID=''SLDISC'' AND SALDIS_PERCENT IS NULL ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET BD_DISCOUNT= FACTOR_TXTVAR,BD_DISCOUNT_RECORD_ID=CALCULATION_VARIABLE_RECORD_ID FROM SAQICO (NOLOCK)A JOIN PRCFVA B(NOLOCK) ON A.SERVICE_ID = B.FACTOR_VARIABLE_ID WHERE QUOTE_ID = ''"+str(Qt_Id)+"'' AND FACTOR_ID=''BDDISC'' AND BD_DISCOUNT IS NULL ' ")

					#Target Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET TARGET_PRICE = CASE WHEN ISNULL(MODEL_PRICE/(1-(SALDIS_PERCENT/100)),0) > ISNULL(TOTAL_COST_WSEEDSTOCK / (1-(TARGET_PRICE_MARGIN/100)),0) THEN ISNULL(MODEL_PRICE/(1-(SALDIS_PERCENT/100)),0) ELSE ISNULL(TOTAL_COST_WSEEDSTOCK / (1-(TARGET_PRICE_MARGIN/100)),0) END FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID ' ")
					
					#Sale Discounted Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET SALES_DISCOUNT_PRICE = CASE WHEN ISNULL(MODEL_PRICE,0) > ISNULL(TOTAL_COST_WSEEDSTOCK / (1-(CONVERT(FLOAT,SLSDIS_PRICE_MARGIN)/100)),0) THEN ISNULL(MODEL_PRICE,0) ELSE ISNULL(TOTAL_COST_WSEEDSTOCK / (1-(CONVERT(FLOAT,SLSDIS_PRICE_MARGIN)/100)/100),0) END FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID ' ")
					
					#BD Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET BD_PRICE = CASE WHEN ISNULL(MODEL_PRICE * (1-(BD_DISCOUNT/100)) ,0) > ISNULL(TOTAL_COST_WSEEDSTOCK / (1-(BD_PRICE_MARGIN/100)),0) THEN ISNULL(MODEL_PRICE,0) ELSE ISNULL(TOTAL_COST_WSEEDSTOCK / (1-(BD_PRICE_MARGIN/100)),0) END FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID ' ")
					
					#Ceiling Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET CEILING_PRICE = TARGET_PRICE * (1 + (CEILING_PRICE_MARGIN/100)) FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT  QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID ' ")
						
					#Exchange Rate
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET TARGET_PRICE = ROUND( (TARGET_PRICE * ISNULL(EXCHANGE_RATE,1)) ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")), SALES_DISCOUNT_PRICE = ROUND( (SALES_DISCOUNT_PRICE * ISNULL(EXCHANGE_RATE,1)) ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")), BD_PRICE = ROUND( (BD_PRICE * ISNULL(EXCHANGE_RATE,1)) ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")), CEILING_PRICE = ROUND( (CEILING_PRICE * ISNULL(EXCHANGE_RATE,1)) ,CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+"))  FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID ' ")
					
					
					#Sales Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET NET_PRICE = TARGET_PRICE  FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID   ' ")
					
					#Contract Year
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO_INBOUND SET YEAR_PERIOD = datediff(yy,contract_valid_from,contract_valid_to)  FROM SAQICO_INBOUND (NOLOCK)  JOIN SAQTMT (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQTMT.QUOTE_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  ' ")
						
					#Year 1
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET YEAR_1 = NET_PRICE   FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID   ' ")
					
					#Year 2
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET YEAR_2 = YEAR_1 * (YEAR_OVER_YEAR/100)   FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,YEAR_PERIOD FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID WHERE YEAR_PERIOD>=2  ' ")
					
					#Year 3
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET YEAR_3 = YEAR_2 * (YEAR_OVER_YEAR/100)   FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,YEAR_PERIOD FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID WHERE YEAR_PERIOD>=3  ' ")
					
					#Year 4
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET YEAR_4 = YEAR_3 * (YEAR_OVER_YEAR/100)   FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,YEAR_PERIOD FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID WHERE YEAR_PERIOD>=4  ' ")
					
					#Year 5
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET YEAR_5 = YEAR_4 * (YEAR_OVER_YEAR/100)   FROM SAQICO (NOLOCK)A JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID,YEAR_PERIOD FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID WHERE YEAR_PERIOD>=5  ' ")
					
					#Tax
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET TAX = ( (ISNULL(YEAR_1,0) + ISNULL(YEAR_2,0) + ISNULL(YEAR_3,0) + ISNULL(YEAR_5,0) + ISNULL(YEAR_4,0) ) * (TAX_PERCENTAGE/100))  FROM SAQICO (NOLOCK)A JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID WHERE TAX IS NULL  ' ")
					
					#Extended Price
					primaryQueryItems = SqlHelper.GetFirst(
						""
						+ str(Parameter1.QUERY_CRITERIA_1)
						+ "  SAQICO SET NET_VALUE = ISNULL(YEAR_1,0) + ISNULL(YEAR_2,0) + ISNULL(YEAR_3,0) + ISNULL(YEAR_5,0) + ISNULL(YEAR_4,0) + ISNULL(TAX,0)  FROM SAQICO (NOLOCK)A JOIN (SELECT  DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')B ON A.QUOTE_ID = B.QUOTE_ID AND A.SERVICE_ID = B.SERVICE_ID AND A.EQUIPMENT_ID = B.EQUIPMENT_ID WHERE TAX IS NULL  ' ")

					#Greenbook Roll Up
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQIGB SET BD_PRICE = SUB_GRNBOK.BD_PRICE,CEILING_PRICE = SUB_GRNBOK.CEILING_PRICE,NET_VALUE = SUB_GRNBOK.NET_VALUE,SALES_DISCOUNT_PRICE = SUB_GRNBOK.SALES_DISCOUNT_PRICE,NET_PRICE = SUB_GRNBOK.NET_PRICE,TARGET_PRICE = SUB_GRNBOK.TARGET_PRICE,TAX = SUB_GRNBOK.TAX,TOTAL_COST_WOSEEDSTOCK = SUB_GRNBOK.TOTAL_COST_WOSEEDSTOCK,TOTAL_COST_WSEEDSTOCK = SUB_GRNBOK.TOTAL_COST_WSEEDSTOCK,MODEL_PRICE = SUB_GRNBOK.MODEL_PRICE,YEAR_1 = SUB_GRNBOK.YEAR_1,YEAR_2 = SUB_GRNBOK.YEAR_2,YEAR_3 = SUB_GRNBOK.YEAR_3,YEAR_4 = SUB_GRNBOK.YEAR_4,YEAR_5 = SUB_GRNBOK.YEAR_5 FROM SAQIGB (NOLOCK) JOIN(SELECT SUM(SAQICO.BD_PRICE) AS BD_PRICE,SUM(SAQICO.CEILING_PRICE) AS CEILING_PRICE,SUM(SAQICO.NET_VALUE) AS NET_VALUE,SUM(SAQICO.SALES_DISCOUNT_PRICE) AS SALES_DISCOUNT_PRICE,SUM(SAQICO.NET_PRICE) AS NET_PRICE,SUM(SAQICO.TARGET_PRICE) AS TARGET_PRICE,SUM(SAQICO.TAX) AS TAX,SUM(SAQICO.TOTAL_COST_WOSEEDSTOCK) AS TOTAL_COST_WOSEEDSTOCK,SUM(SAQICO.TOTAL_COST_WSEEDSTOCK) AS TOTAL_COST_WSEEDSTOCK,SUM(SAQICO.YEAR_1) AS YEAR_1,SUM(SAQICO.YEAR_2) AS YEAR_2,SUM(SAQICO.YEAR_3) AS YEAR_3,SUM(SAQICO.YEAR_4) AS YEAR_4,SUM(SAQICO.YEAR_5) AS YEAR_5,SUM(SAQICO.MODEL_PRICE) AS MODEL_PRICE,SAQICO.QUOTE_ID,SAQICO.GREENBOOK,SAQICO.SERVICE_ID,SAQICO.FABLOCATION_ID FROM SAQICO_INBOUND (NOLOCK)  JOIN SAQICO (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQICO.QUOTE_ID AND SAQICO_INBOUND.EQUIPMENT_ID = SAQICO.EQUIPMENT_ID AND SAQICO_INBOUND.SERVICE_ID = SAQICO.SERVICE_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' GROUP BY SAQICO.QUOTE_ID,SAQICO.GREENBOOK,SAQICO.SERVICE_ID, SAQICO.FABLOCATION_ID ) SUB_GRNBOK ON SAQIGB.QUOTE_ID = SUB_GRNBOK.QUOTE_ID AND SAQIGB.GREENBOOK = SUB_GRNBOK.GREENBOOK AND SAQIGB.SERVICE_ID = SUB_GRNBOK.SERVICE_ID AND SAQIGB.FABLOCATION_ID = SUB_GRNBOK.FABLOCATION_ID ' ")
					
					#Fab Location Roll Up
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQIFL SET BD_PRICE = SUB_FBL.BD_PRICE,NET_VALUE = SUB_FBL.NET_VALUE,SALES_DISCOUNT_PRICE = SUB_FBL.SALES_DISCOUNT_PRICE,NET_PRICE = SUB_FBL.NET_PRICE,TARGET_PRICE = SUB_FBL.TARGET_PRICE,TAX_AMOUNT = SUB_FBL.TAX,TOTAL_COST_WOSEEDSTOCK = SUB_FBL.TOTAL_COST_WOSEEDSTOCK,TOTAL_COST_WSEEDSTOCK = SUB_FBL.TOTAL_COST_WSEEDSTOCK,MODEL_PRICE = SUB_FBL.MODEL_PRICE,YEAR_1 = SUB_FBL.YEAR_1,YEAR_2 = SUB_FBL.YEAR_2,YEAR_3 = SUB_FBL.YEAR_3,YEAR_4 = SUB_FBL.YEAR_4,YEAR_5 = SUB_FBL.YEAR_5 FROM SAQIFL (NOLOCK) JOIN(SELECT SUM(SAQICO.BD_PRICE) AS BD_PRICE,SUM(SAQICO.CEILING_PRICE) AS CEILING_PRICE,SUM(SAQICO.NET_VALUE) AS NET_VALUE,SUM(SAQICO.SALES_DISCOUNT_PRICE) AS SALES_DISCOUNT_PRICE,SUM(SAQICO.NET_PRICE) AS NET_PRICE,SUM(SAQICO.TARGET_PRICE) AS TARGET_PRICE,SUM(SAQICO.TAX) AS TAX,SUM(SAQICO.TOTAL_COST_WOSEEDSTOCK) AS TOTAL_COST_WOSEEDSTOCK,SUM(SAQICO.TOTAL_COST_WSEEDSTOCK) AS TOTAL_COST_WSEEDSTOCK,SUM(SAQICO.YEAR_1) AS YEAR_1,SUM(SAQICO.YEAR_2) AS YEAR_2,SUM(SAQICO.YEAR_3) AS YEAR_3,SUM(SAQICO.YEAR_4) AS YEAR_4,SUM(SAQICO.YEAR_5) AS YEAR_5,SUM(SAQICO.MODEL_PRICE) AS MODEL_PRICE,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.FABLOCATION_ID FROM SAQICO_INBOUND (NOLOCK)  JOIN SAQICO (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQICO.QUOTE_ID AND SAQICO_INBOUND.EQUIPMENT_ID = SAQICO.EQUIPMENT_ID AND SAQICO_INBOUND.SERVICE_ID = SAQICO.SERVICE_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' GROUP BY SAQICO.QUOTE_ID,SAQICO.SERVICE_ID, SAQICO.FABLOCATION_ID ) SUB_FBL ON SAQIFL.QUOTE_ID = SUB_FBL.QUOTE_ID AND SAQIFL.SERVICE_ID = SUB_FBL.SERVICE_ID AND SAQIFL.FABLOCATION_ID = SUB_FBL.FABLOCATION_ID ' ")

					#Item Roll Up
					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET BD_PRICE = SUB_SAQITM.BD_PRICE,CEILING_PRICE = SUB_SAQITM.CEILING_PRICE,NET_VALUE = SUB_SAQITM.NET_VALUE,SALES_DISCOUNT_PRICE = SUB_SAQITM.SALES_DISCOUNT_PRICE,NET_PRICE = SUB_SAQITM.NET_PRICE,TARGET_PRICE = SUB_SAQITM.TARGET_PRICE,TOTAL_COST_WOSEEDSTOCK = SUB_SAQITM.TOTAL_COST_WOSEEDSTOCK,TOTAL_COST_WSEEDSTOCK = SUB_SAQITM.TOTAL_COST_WSEEDSTOCK,MODEL_PRICE = SUB_SAQITM.MODEL_PRICE,YEAR_1 = SUB_SAQITM.YEAR_1,YEAR_2 = SUB_SAQITM.YEAR_2,YEAR_3 = SUB_SAQITM.YEAR_3,YEAR_4 = SUB_SAQITM.YEAR_4,YEAR_5 = SUB_SAQITM.YEAR_5,TAX = ROUND((SUB_SAQITM.NET_VALUE * (ISNULL(SAQITM.TAX_PERCENTAGE,0)/100)),CONVERT(INT,"+str(roundcurr.DECIMAL_PLACES)+"),CONVERT(INT,"+str(roundcurr.ROUNDING_METHOD)+")) FROM SAQITM (NOLOCK) JOIN(SELECT SUM(SAQICO.BD_PRICE) AS BD_PRICE,SUM(SAQICO.CEILING_PRICE) AS CEILING_PRICE,SUM(SAQICO.NET_VALUE) AS NET_VALUE,SUM(SAQICO.SALES_DISCOUNT_PRICE) AS SALES_DISCOUNT_PRICE,SUM(SAQICO.NET_PRICE) AS NET_PRICE,SUM(SAQICO.TARGET_PRICE) AS TARGET_PRICE,SUM(SAQICO.TAX) AS TAX,SUM(SAQICO.TOTAL_COST_WOSEEDSTOCK) AS TOTAL_COST_WOSEEDSTOCK,SUM(SAQICO.TOTAL_COST_WSEEDSTOCK) AS TOTAL_COST_WSEEDSTOCK,SUM(SAQICO.YEAR_1) AS YEAR_1,SUM(SAQICO.YEAR_2) AS YEAR_2,SUM(SAQICO.YEAR_3) AS YEAR_3,SUM(SAQICO.YEAR_4) AS YEAR_4,SUM(SAQICO.YEAR_5) AS YEAR_5,SUM(SAQICO.MODEL_PRICE) AS MODEL_PRICE,SAQICO.QUOTE_ID,SAQICO.SERVICE_RECORD_ID FROM SAQICO_INBOUND (NOLOCK) JOIN SAQICO (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQICO.QUOTE_ID AND SAQICO_INBOUND.EQUIPMENT_ID = SAQICO.EQUIPMENT_ID AND SAQICO_INBOUND.SERVICE_ID = SAQICO.SERVICE_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' GROUP BY SAQICO.QUOTE_ID,SAQICO.SERVICE_RECORD_ID) SUB_SAQITM  ON SAQITM.QUOTE_ID = SUB_SAQITM.QUOTE_ID AND SAQITM.SERVICE_RECORD_ID = SUB_SAQITM.SERVICE_RECORD_ID  ' ")

					primaryQueryItems = SqlHelper.GetFirst(
					""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQITM SET BD_PRICE_MARGIN = SUB_SAQITM.BD_PRICE_MARGIN,BD_PRICE_MARGIN_RECORD_ID = SUB_SAQITM.BD_PRICE_MARGIN_RECORD_ID,DISCOUNT = SUB_SAQITM.DISCOUNT,SALES_DISCOUNT_PRICE_MARGIN_RECORD_ID = SUB_SAQITM.SALES_DISCOUNT_PRICE_MARGIN_RECORD_ID,TARGET_PRICE_MARGIN_RECORD_ID = SUB_SAQITM.TARGET_PRICE_MARGIN_RECORD_ID,TARGET_PRICE_MARGIN = SUB_SAQITM.TARGET_PRICE_MARGIN FROM SAQITM (NOLOCK) JOIN(SELECT DISTINCT SAQICO.QUOTE_ID,SAQICO.SERVICE_RECORD_ID,BD_PRICE_MARGIN,BD_PRICE_MARGIN_RECORD_ID,CEILING_PRICE_MARGIN,DISCOUNT,SALES_PRICE_MARGIN,SALES_DISCOUNT_PRICE_MARGIN_RECORD_ID,TARGET_PRICE_MARGIN_RECORD_ID,TARGET_PRICE_MARGIN FROM SAQICO_INBOUND (NOLOCK) JOIN SAQICO (NOLOCK) ON SAQICO_INBOUND.QUOTE_ID = SAQICO.QUOTE_ID AND SAQICO_INBOUND.EQUIPMENT_ID = SAQICO.EQUIPMENT_ID AND SAQICO_INBOUND.SERVICE_ID = SAQICO.SERVICE_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' ) SUB_SAQITM ON SAQITM.QUOTE_ID = SUB_SAQITM.QUOTE_ID AND SAQITM.SERVICE_RECORD_ID = SUB_SAQITM.SERVICE_RECORD_ID  ' ")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQICO SET PRICING_STATUS=''ON HOLD - COSTING'' FROM SAQICO (NOLOCK) JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(COST_MODULE_AVAILABLE,'''')=''UNAVAILABLE'')SAQICO_INBOUND ON SAQICO.QUOTE_ID = SAQICO_INBOUND.QUOTE_ID AND SAQICO.SERVICE_ID = SAQICO_INBOUND.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQICO_INBOUND.EQUIPMENT_ID '")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQICO SET PRICING_STATUS=''ON HOLD - PRICING'' FROM SAQICO (NOLOCK) JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(COST_MODULE_AVAILABLE,'''')=''AVAILABLE'' AND EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(COST_MODULE_AVAILABLE,'''')=''UNAVAILABLE'' ) )SAQICO_INBOUND ON SAQICO.QUOTE_ID = SAQICO_INBOUND.QUOTE_ID AND SAQICO.SERVICE_ID = SAQICO_INBOUND.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQICO_INBOUND.EQUIPMENT_ID '")
					
					primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQICO SET PRICING_STATUS=''APPROVAL PENDING'' FROM SAQICO (NOLOCK) JOIN SAQICA(NOLOCK) ON SAQICO.QUOTE_ID = SAQICA.QUOTE_ID AND SAQICO.SERVICE_ID = SAQICA.SERVICE_ID AND SAQICO.EQUIPMENT_LINE_ID = SAQICA.EQUIPMENT_LINE_ID AND SAQICO.EQUIPMENT_ID = SAQICA.EQUIPMENT_ID JOIN SAQICO_INBOUND C(NOLOCK)ON SAQICO.QUOTE_ID = C.QUOTE_ID AND SAQICO.SERVICE_ID = C.SERVICE_ID AND SAQICO.EQUIPMENT_ID = C.EQUIPMENT_ID  LEFT JOIN (SELECT DISTINCT QUOTE_ID,SERVICE_ID,EQUIPMENT_ID FROM SAQICO_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(COST_MODULE_AVAILABLE,'''')=''UNAVAILABLE'')SAQICO_INBOUND ON SAQICO.QUOTE_ID = SAQICO_INBOUND.QUOTE_ID AND SAQICO.SERVICE_ID = SAQICO_INBOUND.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQICO_INBOUND.EQUIPMENT_ID WHERE SAQICO_INBOUND.EQUIPMENT_ID IS NULL AND ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' '")

					"""primaryQueryItems = SqlHelper.GetFirst(
						""
					+ str(Parameter1.QUERY_CRITERIA_1)
					+ "  SAQICO SET PRICING_STATUS=''APPROVAL REQUIRED'',BENCHMARKING_THRESHOLD  = (((ANNUAL_BENCHMARK_BOOKING_PRICE-TARGET_PRICE)/ANNUAL_BENCHMARK_BOOKING_PRICE) * 100) * -1 FROM SAQICO  (NOLOCK) JOIN (SELECT QUOTE_ID,EQUIPMENT_LINE_ID,SERVICE_ID FROM (SELECT QUOTE_ID,EQUIPMENT_LINE_ID,SERVICE_ID,ANNUAL_BENCHMARK_BOOKING_PRICE + (ANNUAL_BENCHMARK_BOOKING_PRICE * 0.25) AS HIGHTARGET,ANNUAL_BENCHMARK_BOOKING_PRICE - (ANNUAL_BENCHMARK_BOOKING_PRICE * 0.25) AS LOWTARGET,TARGET_PRICE FROM SAQICO (NOLOCK) WHERE QUOTE_ID=''"+str(Qt_Id)+"'' AND ISNULL(ANNUAL_BENCHMARK_BOOKING_PRICE,0)>0 AND ISNULL(TARGET_PRICE,0) >0)B WHERE (B.TARGET_PRICE < B.LOWTARGET OR B.TARGET_PRICE > B.HIGHTARGET ) )SUB_SAQICO ON SAQICO.QUOTE_ID = SUB_SAQICO.QUOTE_ID AND SAQICO.SERVICE_ID = SUB_SAQICO.SERVICE_ID AND SAQICO.EQUIPMENT_LINE_ID = SUB_SAQICO.EQUIPMENT_LINE_ID  '")"""

					#Status Completed in SYINPL by CPQ Table Entry ID
					StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''COMPLETED'' FROM SYINPL (NOLOCK) A WHERE CpqTableEntryId = ''"+str(json_data.CpqTableEntryId)+"'' AND SESSION_ID =''"+str(SYINPL_SESSION.A)+"'' ' ")

					StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter2.QUERY_CRITERIA_1)+ " FROM SAQICO_INBOUND  WHERE ISNULL(SESSION_ID,'''')=''"+str(sessiondetail.A)+ "'' ' ")

					SAQIEN_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(SAQIEN)+"'' ) BEGIN DROP TABLE "+str(SAQIEN)+" END  ' ")
			
					Log.Info("QTPOSTQTPR pricing async call End --->"+str(Qt_Id))
					# Mail system				
					Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #grey{background: rgb(245,245,245);} #bd{color : 'black';} </style></head><body id = 'bd'>"

					Table_start = "<p>Hi Team,<br><br>Pricing has been completed in CPQ, for the equipment's in below Quote ID.</p><table class='table table-bordered'><tr><th id = 'grey'>Quote ID</th><th id = 'grey'>Tools sent (CPQ-SSCM)</th><th id = 'grey'>Tools received (SSCM-CPQ)</th><th id = 'grey'>Price Calculation Status</th></tr><tr><td >"+str(Emailinfo.QUOTE_ID)+"</td><td>"+str(Emailinfo.SSCM)+"</td ><td>"+str(Emailinfo1.CPQ)+"</td><td>Completed</td></tr>"

					Table_info = ""
					Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"

					Error_Info = Header + Table_start + Table_info + Table_End

					LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

					# Create new SmtpClient object
					mailClient = SmtpClient()

					# Set the host and port (eg. smtp.gmail.com)
					mailClient.Host = "smtp.gmail.com"
					mailClient.Port = 587
					mailClient.EnableSsl = "true"

					# Setup NetworkCredential
					mailCred = NetworkCredential()
					mailCred.UserName = str(LOGIN_CRE.Username)
					mailCred.Password = str(LOGIN_CRE.Password)
					mailClient.Credentials = mailCred

					#Current user email(Toemail)
					#UserId = User.Id
					#Log.Info("123 UserId.UserId --->"+str(UserId))
					UserEmail = SqlHelper.GetFirst("SELECT isnull(email,'INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM') as email FROM saempl (nolock) where employee_id  = '"+str(ToEml.OWNER_ID)+"'")
					#Log.Info("123 UserEmail.email --->"+str(UserEmail.email))

					# Create two mail adresses, one for send from and the another for recipient
					if UserEmail is None:
						toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
					else:
						toEmail = MailAddress(UserEmail.email)
					fromEmail = MailAddress("INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM")

					# Create new MailMessage object
					msg = MailMessage(fromEmail, toEmail)

					# Set message subject and body
					msg.Subject = "Pricing Completed - AMAT CPQ QA"
					msg.IsBodyHtml = True
					msg.Body = Error_Info

					# Bcc Emails	
					copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail4)

					copyEmail1 = MailAddress("ranjani.parkavi@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail1) 

					#copyEmail2 = MailAddress("aditya.shivkumar@bostonharborconsulting.com")
					#msg.Bcc.Add(copyEmail2)

					copyEmail3 = MailAddress("sathyabama.akhala@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail3)

					copyEmail5 = MailAddress("ashish.gandotra@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail5)
					
					copyEmail6 = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
					msg.Bcc.Add(copyEmail6)

					# Send the message
					mailClient.Send(msg)


					Greenbkquery=SqlHelper.GetList("SELECT DISTINCT SAQICO.GREENBOOK,ISNULL(SABUUN.DISTRIBUTION_EMAIL,'') AS DISTRIBUTION_EMAIL  FROM SAQICO(NOLOCK) JOIN SAQICA (NOLOCK) ON SAQICO.QUOTE_ID = SAQICA.QUOTE_ID AND SAQICO.SERVICE_ID = SAQICA.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQICA.EQUIPMENT_ID JOIN SABUUN (NOLOCK) ON SAQICO.GREENBOOK = SABUUN.BUSINESSUNIT_ID WHERE SAQICO.PRICING_STATUS='ON HOLD - COSTING' AND SAQICO.QUOTE_ID = '"+str(Qt_Id)+"'")

					for Gbk in Greenbkquery:


						Grnbkdataquery=SqlHelper.GetList("SELECT SAQICO.GREENBOOK,SAQICO.QUOTE_ID,SAQICO.SERVICE_ID,SAQICO.EQUIPMENT_ID,SAQICO.ASSEMBLY_ID,SAQICA.COST_MODULE_AVAILABLE,SAQICO.COST_MODULE_STATUS FROM SAQICO (NOLOCK) JOIN SAQICA (NOLOCK) ON SAQICO.QUOTE_ID = SAQICA.QUOTE_ID AND SAQICO.SERVICE_ID = SAQICA.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQICA.EQUIPMENT_ID WHERE SAQICO.PRICING_STATUS='ON HOLD - COSTING' AND SAQICO.GREENBOOK= '"+str(Gbk.GREENBOOK)+"' AND SAQICO.QUOTE_ID = '"+str(Qt_Id)+"' ")

						tbl_info = ''
						for gbkinfo in Grnbkdataquery:
							tbl_info = tbl_info+"<tr><td >"+str(gbkinfo.QUOTE_ID)+"</td><td>"+str(gbkinfo.GREENBOOK)+"</td ><td>"+str(gbkinfo.SERVICE_ID)+"</td><td>"+str(gbkinfo.EQUIPMENT_ID)+"</td><td>"+str(gbkinfo.ASSEMBLY_ID)+"</td><td>"+str(gbkinfo.COST_MODULE_AVAILABLE)+"</td><td>"+str(gbkinfo.COST_MODULE_STATUS)+"</td></tr>"
						if len(tbl_info) > 0:
							Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #grey{background: rgb(245,245,245);} #bd{color : 'black';} </style></head><body id = 'bd'>"

							Table_start = "<p>Hi Team,<br><br>ON HOLD - COSTING error mail has been completed in CPQ, for the below Quote ID.</p><table class='table table-bordered'><tr><th id = 'grey'>Quote ID</th><th id = 'grey'>Green Book</th><th id = 'grey'>Service ID</th><th id = 'grey'>Equipment ID</th><th id = 'grey'>Assembly ID</th><th id = 'grey'>Cost Module Available</th><th id = 'grey'>Cost Module Status</th></tr>"+str(tbl_info)

							Table_info = ""
							Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"

							Error_Info = Header + Table_start + Table_info + Table_End

							LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

							# Create new SmtpClient object
							mailClient = SmtpClient()

							# Set the host and port (eg. smtp.gmail.com)
							mailClient.Host = "smtp.gmail.com"
							mailClient.Port = 587
							mailClient.EnableSsl = "true"

							# Setup NetworkCredential
							mailCred = NetworkCredential()
							mailCred.UserName = str(LOGIN_CRE.Username)
							mailCred.Password = str(LOGIN_CRE.Password)
							mailClient.Credentials = mailCred

							UserEmail = []
							if str(Gbk.DISTRIBUTION_EMAIL) > 0:
								UserEmail = str(Gbk.DISTRIBUTION_EMAIL).split(';')
							

							# Create two mail adresses, one for send from and the another for recipient
							toEmail = MailAddress("baji.baba@bostonharborconsulting.com")
							
							fromEmail = MailAddress("INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM")

							# Create new MailMessage object
							msg = MailMessage(fromEmail, toEmail)

							# Set message subject and body
							msg.Subject = "ON HOLD - COSTING- AMAT CPQ QA"
							msg.IsBodyHtml = True
							msg.Body = Error_Info
							Log.Info("156156 UserEmail --->"+str(UserEmail))
							# CC Emails	
							if len(UserEmail) > 0:
								for emalinfo in  UserEmail:
								    copyEmail = MailAddress(emalinfo)
								    msg.CC.Add(copyEmail)

							# Send the message
							mailClient.Send(msg)

					CallingCQIFWUDQTM = ScriptExecutor.ExecuteGlobal("CQIFWUDQTM",{"QT_REC_ID":"Qt_Id"})	
					# Billing matrix async call
					LOGIN_CREDENTIALS = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password,Domain FROM SYCONF where Domain='AMAT_TST'")

					if LOGIN_CREDENTIALS is not None:
						Login_Username = str(LOGIN_CREDENTIALS.Username)
						Login_Password = str(LOGIN_CREDENTIALS.Password)
						authorization = Login_Username+":"+Login_Password
						binaryAuthorization = UTF8.GetBytes(authorization)
						authorization = Convert.ToBase64String(binaryAuthorization)
						authorization = "Basic " + authorization


						webclient = System.Net.WebClient()
						webclient.Headers[System.Net.HttpRequestHeader.ContentType] = "application/json"
						webclient.Headers[System.Net.HttpRequestHeader.Authorization] = authorization;
						
						result = '{\r\n\"ContractQuoteRecordId\" : \"'+str(Emailinfo.QUOTE_RECORD_ID)+'\"\r\n}'
						
						LOGIN_CRE = SqlHelper.GetFirst("SELECT URL FROM SYCONF where EXTERNAL_TABLE_NAME ='BILLING_MATRIX_ASYNC'")
						Async = webclient.UploadString(str(LOGIN_CRE.URL), str(result))

						level = "QT_QTQICO LEVEL"
						CQVLDRIFLW.iflow_valuedriver_rolldown(str(Emailinfo.QUOTE_RECORD_ID),level)
					
					
					Unprocsseddataquery = SqlHelper.GetFirst("SELECT count(*) as cnt from SYINPL(NOLOCK) WHERE INTEGRATION_NAME = 'SSCM_TO_CPQ_PRICING_DATA' AND ISNULL(STATUS,'') = '' ")	

					if Unprocsseddataquery.cnt > 0 :
						#Async call for SSCM TO CPQ Unprocessed data 
						LOGIN_CREDENTIALS = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password,Domain FROM SYCONF where Domain='AMAT_TST'")
						if LOGIN_CREDENTIALS is not None:
							Login_Username = str(LOGIN_CREDENTIALS.Username)
							Login_Password = str(LOGIN_CREDENTIALS.Password)
							authorization = Login_Username+":"+Login_Password
							binaryAuthorization = UTF8.GetBytes(authorization)
							authorization = Convert.ToBase64String(binaryAuthorization)
							authorization = "Basic " + authorization


							webclient = System.Net.WebClient()
							webclient.Headers[System.Net.HttpRequestHeader.ContentType] = "application/json"
							webclient.Headers[System.Net.HttpRequestHeader.Authorization] = authorization;
							
							result = '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body ></soapenv:Body></soapenv:Envelope>'
							
							LOGIN_CRE = SqlHelper.GetFirst("SELECT URL FROM SYCONF where EXTERNAL_TABLE_NAME ='CPQ_TO_SSCM_PRICING_ASYNC'")
							Async = webclient.UploadString(str(LOGIN_CRE.URL), str(result))
					else: 
						ApiResponse = ApiResponseFactory.JsonResponse({"Response": [{"Status": "200", "Message": "Data Successfully Uploaded"}]})
				
	else:
		ApiResponse = ApiResponseFactory.JsonResponse({"Response": [{"Status": "200", "Message": "Session is running.Status is Inprogress"}]})
		

except:
	#Status Empty in SYINPL
	StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  A SET STATUS = '''' FROM SYINPL (NOLOCK) A WHERE SESSION_ID=''"+str(SYINPL_SESSION.A)+"''  ' ")
				
	Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #bd{color : 'black';} </style></head><body id = 'bd'>"

	Table_start = "<p>Hi Team,<br><br>SSCM Pricing script having follwing Error in Line number "+str(sys.exc_info()[-1].tb_lineno)+".<br><br>"+str(sys.exc_info()[1])+"</p><br>"
	
	Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"
	Table_info = ""     

	Error_Info = Header + Table_start + Table_info + Table_End

	LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

	# Create new SmtpClient object
	mailClient = SmtpClient()

	# Set the host and port (eg. smtp.gmail.com)
	mailClient.Host = "smtp.gmail.com"
	mailClient.Port = 587
	mailClient.EnableSsl = "true"

	# Setup NetworkCredential
	mailCred = NetworkCredential()
	mailCred.UserName = str(LOGIN_CRE.Username)
	mailCred.Password = str(LOGIN_CRE.Password)
	mailClient.Credentials = mailCred

	# Create two mail adresses, one for send from and the another for recipient
	toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
	fromEmail = MailAddress("INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM")

	# Create new MailMessage object
	msg = MailMessage(fromEmail, toEmail)

	# Set message subject and body
	msg.Subject = "SSCM to CPQ - Pricing Error Notification"
	msg.IsBodyHtml = True
	msg.Body = Error_Info

	# CC Emails 	
	copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
	msg.CC.Add(copyEmail4)
	
	# Send the message
	mailClient.Send(msg) 
	
	Log.Info("QTPOSTQTPR ERROR---->:" + str(sys.exc_info()[1]))
	Log.Info("QTPOSTQTPR ERROR LINE NO---->:" + str(sys.exc_info()[-1].tb_lineno))
	ApiResponse = ApiResponseFactory.JsonResponse({"Response": [{"Status": "400", "Message": str(sys.exc_info()[1])}]})