# =========================================================================================================================================
#   __script_name : SGPOSTCACT.PY
#   __script_description : THIS SCRIPT IS USED TO INSERT/UPDATE CUSTOMER FROM ECC TO CPQ
#   __primary_author__ : SURESH MUNIYANDI
#   __create_date :
#   Â© BOSTON HARBOR TECHNOLOGY LLC - ALL RIGHTS RESERVED
# ==========================================================================================================================================
# Log.Info("cpq customer inbound scripts running----->")
import sys
import datetime
Trace.Write("SAACNT--->")
try:
    
    Parameter = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'SELECT' ")
    Parameter1 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'UPD' ")
    Parameter2 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'DEL' ")
    
    S = SqlHelper.GetFirst("sp_executesql @T=N'update saacnt_inbound set account_id = convert(bigint,account_id)  where isnumeric(account_id)=1  ' ")
    S = SqlHelper.GetFirst("sp_executesql @T=N'update saacnt_inbound set PAR_ACCOUNT_ID = convert(bigint,PAR_ACCOUNT_ID)  where isnumeric(PAR_ACCOUNT_ID)=1  ' ")
    
    
    #MARKING DUPLICATES       
    #SAACNT
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAACNT_INBOUND SET INTEGRATION_STATUS = ''DUPLICATE'' FROM SAACNT_INBOUND A(NOLOCK) JOIN  (SELECT MAX(CpqTableEntryId) AS CpqTableEntryId,Account_id FROM SAACNT_INBOUND WHERE ISNULL(INTEGRATION_STATUS,'''')='''' AND ISNULL(INTEGRATION_OBJECT,'''')='''' GROUP BY Account_id HAVING COUNT(ACCOUNT_ID)>1) B ON A.ACCOUNT_ID = B.ACCOUNT_ID AND A.CpqTableEntryId <> B.CpqTableEntryId WHERE ISNULL(INTEGRATION_STATUS,'''')='''' AND ISNULL(INTEGRATION_OBJECT,'''')=''''  ' ")
    
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAACNT_INBOUND SET INTEGRATION_STATUS=''Inprogress'' WHERE ISNULL(INTEGRATION_OBJECT,'''')='''' AND ISNULL(INTEGRATION_STATUS,'''')=''''  ' ")
        
    #SASAAC
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAACNT_INBOUND SET INTEGRATION_STATUS=''Inprogress'' WHERE SESSION_ID IN  (SELECT SESSION_ID FROM SAACNT_INBOUND(NOLOCK) WHERE ISNULL(INTEGRATION_STATUS,'''')=''INPROGRESS''  ) AND ISNULL(INTEGRATION_STATUS,'''')='''' AND ISNULL(INTEGRATION_OBJECT,'''')=''SASAAC''' ")
    
    
    #SAACPF
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAACNT_INBOUND SET INTEGRATION_STATUS=''Inprogress'' WHERE SESSION_ID IN  (SELECT SESSION_ID FROM SAACNT_INBOUND(NOLOCK) WHERE ISNULL(INTEGRATION_STATUS,'''')=''INPROGRESS''  ) AND ISNULL(INTEGRATION_STATUS,'''')='''' AND ISNULL(INTEGRATION_OBJECT,'''')=''SAACPF''' ")
    
    #SAASCT
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAACNT_INBOUND SET INTEGRATION_STATUS=''Inprogress'' WHERE SESSION_ID IN  (SELECT SESSION_ID FROM SAACNT_INBOUND(NOLOCK) WHERE ISNULL(INTEGRATION_STATUS,'''')=''INPROGRESS''  ) AND ISNULL(INTEGRATION_STATUS,'''')='''' AND ISNULL(INTEGRATION_OBJECT,'''')=''SAASCT''' ")
    
    #VALIDATION STARTS
    #SAACNT 
    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.STATE),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SACYST (NOLOCK) ON SAACNT_INBOUND.STATE = SACYST.STATE LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200118'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAACNT'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''''  AND SACYST.STATE IS NULL AND SAACNT_INBOUND.STATE <> '''' '"
            )
            
    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.COUNTRY),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SACTRY (NOLOCK) ON SAACNT_INBOUND.COUNTRY = SACTRY.COUNTRY LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200119'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAACNT'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''''  AND SACTRY.COUNTRY IS NULL AND SAACNT_INBOUND.COUNTRY <> '''' '"
            )

    primaryQueryItems = SqlHelper.GetFirst(
                ""
                + str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200120'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')= '''' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAACNT''  AND ACCOUNT_ID = '''''"
            )
            
    #SAACCT

    primaryQueryItems = SqlHelper.GetFirst(
                ""
                + str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200121'' AND SAACNT_INBOUND.INTEGRATION_OBJECT= ''SAACCT'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAACCT''  AND ACCOUNT_ID = '''''"
            )

    #SASAAC 

    primaryQueryItems = SqlHelper.GetFirst(
                ""
                + str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200122'' AND SAACNT_INBOUND.INTEGRATION_OBJECT= ''SASAAC'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SASAAC''  AND ACCOUNT_ID = '''''"
            )
            
    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SADSCH (NOLOCK) ON SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID = SADSCH.DISTRIBUTIONCHANNEL_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200123'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SASAAC'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SASAAC''  AND SADSCH.DISTRIBUTIONCHANNEL_ID IS NULL AND SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID <> '''' '"
            )

    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.DIVISION_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SADIVN (NOLOCK) ON SAACNT_INBOUND.DIVISION_ID = SADIVN.DIVISION_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200124'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SASAAC'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SASAAC''  AND SADIVN.DIVISION_ID IS NULL AND SAACNT_INBOUND.DIVISION_ID <> '''' '"
            ) 


    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.SALESORG_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SASORG(NOLOCK) ON SAACNT_INBOUND.SALESORG_ID = SASORG.SALESORG_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200125'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SASAAC'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SASAAC''  AND SASORG.SALESORG_ID IS NULL AND SAACNT_INBOUND.SALESORG_ID <> '''' '"
            )
    #SAACPF

    primaryQueryItems = SqlHelper.GetFirst(
                ""
                + str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200126'' AND SAACNT_INBOUND.INTEGRATION_OBJECT= ''SAACPF'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAACPF''  AND ACCOUNT_ID = '''''"
            )
            
    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SADSCH (NOLOCK) ON SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID = SADSCH.DISTRIBUTIONCHANNEL_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200127'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAACPF'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SAACPF''  AND SADSCH.DISTRIBUTIONCHANNEL_ID IS NULL AND SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID <> '''' '"
            )

    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.DIVISION_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SADIVN (NOLOCK) ON SAACNT_INBOUND.DIVISION_ID = SADIVN.DIVISION_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200128'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAACPF'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SAACPF''  AND SADIVN.DIVISION_ID IS NULL AND SAACNT_INBOUND.DIVISION_ID <> '''' '"
            ) 


    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.SALESORG_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SASORG(NOLOCK) ON SAACNT_INBOUND.SALESORG_ID = SASORG.SALESORG_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200129'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAACPF'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SAACPF''  AND SASORG.SALESORG_ID IS NULL AND SAACNT_INBOUND.SALESORG_ID <> '''' '"
            )
    #SAASCT
    primaryQueryItems = SqlHelper.GetFirst(
                ""
                + str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200130'' AND SAACNT_INBOUND.INTEGRATION_OBJECT= ''SAASCT'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAASCT''  AND ACCOUNT_ID = '''''"
            )
            
    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SADSCH (NOLOCK) ON SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID = SADSCH.DISTRIBUTIONCHANNEL_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200131'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAASCT'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SAASCT''  AND SADSCH.DISTRIBUTIONCHANNEL_ID IS NULL AND SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID <> '''' '"
            )

    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.DIVISION_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SADIVN (NOLOCK) ON SAACNT_INBOUND.DIVISION_ID = SADIVN.DIVISION_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200132'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAASCT'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SAASCT''  AND SADIVN.DIVISION_ID IS NULL AND SAACNT_INBOUND.DIVISION_ID <> '''' '"
            ) 


    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.SALESORG_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SASORG(NOLOCK) ON SAACNT_INBOUND.SALESORG_ID = SASORG.SALESORG_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200133'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAASCT'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SAASCT''  AND SASORG.SALESORG_ID IS NULL AND SAACNT_INBOUND.SALESORG_ID <> '''' '"
            )

    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.TAXCATEGORY_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN PRTXCT(NOLOCK) ON SAACNT_INBOUND.TAXCATEGORY_ID = PRTXCT.TAX_CATEGORY_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200134'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAASCT'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SAASCT''  AND PRTXCT.TAX_CATEGORY_ID IS NULL AND SAACNT_INBOUND.TAXCATEGORY_ID <> '''' '"
            )
            
    primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)
                + "  SAACNT_INBOUND SET SAACNT_INBOUND.ERROR = SAACNT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,SAACNT_INBOUND.TAXCLASSIFICATION_ID),SAACNT_INBOUND.INTEGRATION_STATUS=''ERROR'' FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN PRTXCL(NOLOCK) ON SAACNT_INBOUND.TAXCLASSIFICATION_ID = PRTXCL.TAX_CLASSIFICATION_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200135'' WHERE SAACNT_INBOUND.INTEGRATION_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''SAASCT'' AND SAACNT_INBOUND.INTEGRATION_OBJECT=''SAASCT''  AND PRTXCL.TAX_CLASSIFICATION_ID IS NULL AND SAACNT_INBOUND.TAXCLASSIFICATION_ID <> '''' '"
            )


    #PREPARING RECORDS TO BE LOADED
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAACNT_INBOUND SET INTEGRATION_STATUS = ''READY FOR UPLOAD'' WHERE ISNULL(ERROR,'''')='''' AND INTEGRATION_STATUS = ''Inprogress'' ' ")

    
    #SAACNT
    #Update  
    UpdateQueryItems = SqlHelper.GetFirst(
        ""
        + str(Parameter1.QUERY_CRITERIA_1)
        + "  SAACNT SET SAACNT.CpqTableEntryModifiedBy = ''"
        + str(User.Id)
        + "'',SAACNT.CpqTableEntryDateModified = GetDate(),SAACNT.ACCOUNT_ID = SAACNT_INBOUND.ACCOUNT_ID,SAACNT.ACCOUNT_NAME = SAACNT_INBOUND.ACCOUNT_NAME, SAACNT.ACTIVE = ''True'',SAACNT.ADDRESS_1 = SAACNT_INBOUND.ADDRESS_1,SAACNT.CITY = SAACNT_INBOUND.CITY,SAACNT.COUNTRY = SAACNT_INBOUND.COUNTRY,SAACNT.COUNTRY_RECORD_ID = SACTRY.COUNTRY_RECORD_ID,SAACNT.STATE = SAACNT_INBOUND.STATE,SAACNT.STATE_RECORD_ID = SACYST.STATE_RECORD_ID,SAACNT.POSTAL_CODE = SAACNT_INBOUND.POSTAL_CODE,SAACNT.ACCOUNTGROUP_ID=SAACNT_INBOUND.ACCOUNTGROUP_ID,SAACNT.ACCOUNTGROUP_NAME=SAAGRP.ACCOUNT_GROUP_NAME,SAACNT.ACCOUNTGROUP_RECORD_ID=SAAGRP.ACCOUNT_GROUP_RECORD_ID,SAACNT.TAXJUR_CODE = SAACNT_INBOUND.TAX_CODE,PAR_ACCOUNT_ID = M.ACCOUNT_ID,PAR_ACCOUNT_NAME = M.ACCOUNT_NAME,PAR_ACCOUNT_RECORD_ID = M.ACCOUNT_RECORD_ID,SAACNT.LEGACY_FBL_ID = SAACNT_INBOUND.LEGACY_FBL_ID FROM SAACNT_INBOUND(NOLOCK) JOIN SACTRY(NOLOCK) on SAACNT_INBOUND.COUNTRY=SACTRY.COUNTRY LEFT JOIN  SAAGRP  on SAACNT_INBOUND.ACCOUNTGROUP_ID = SAAGRP.ACCOUNT_GROUP_ID LEFT JOIN SACYST(NOLOCK) on SAACNT_INBOUND.STATE=SACYST.STATE AND SAACNT_INBOUND.COUNTRY=SACYST.COUNTRY JOIN SAACNT(NOLOCK) SAACNT ON SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID LEFT JOIN SAACNT M(NOLOCK) ON SAACNT_INBOUND.PAR_ACCOUNT_iD = M.ACCOUNT_iD WHERE  SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''''  ' ") 
    
    #Insert   
    InsertQueryItems = SqlHelper.GetFirst(
        ""
        + str(Parameter.QUERY_CRITERIA_1)
        + " SAACNT (ACCOUNT_ID,ACCOUNT_NAME,ACTIVE,ADDRESS_1,CITY,COUNTRY,COUNTRY_RECORD_ID,STATE,STATE_RECORD_ID,POSTAL_CODE,ACCOUNTGROUP_ID,ACCOUNTGROUP_NAME,ACCOUNTGROUP_RECORD_ID,TAXJUR_CODE,LEGACY_FBL_ID,ACCOUNT_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_SAACNT.*,CONVERT(VARCHAR(4000),NEWID()),''"
        + str(User.UserName)
        + "'',GETDATE() FROM (SELECT DISTINCT SAACNT_INBOUND.ACCOUNT_ID,SAACNT_INBOUND.ACCOUNT_NAME,''True'' AS ACTIVE,SAACNT_INBOUND.ADDRESS_1,SAACNT_INBOUND.CITY,SAACNT_INBOUND.COUNTRY,SACTRY.COUNTRY_RECORD_ID,SAACNT_INBOUND.STATE,SACYST.STATE_RECORD_ID,SAACNT_INBOUND.POSTAL_CODE,SAACNT_INBOUND.ACCOUNTGROUP_ID,SAAGRP.ACCOUNT_GROUP_NAME,SAAGRP.ACCOUNT_GROUP_RECORD_ID,SAACNT_INBOUND.TAX_CODE,SAACNT_INBOUND.LEGACY_FBL_ID FROM SAACNT_INBOUND(NOLOCK)  JOIN SACTRY(NOLOCK) on SAACNT_INBOUND.COUNTRY=SACTRY.COUNTRY LEFT JOIN SACYST(NOLOCK) on SAACNT_INBOUND.STATE=SACYST.STATE AND SAACNT_INBOUND.COUNTRY=SACYST.COUNTRY LEFT JOIN  SAAGRP on SAACNT_INBOUND.ACCOUNTGROUP_ID = SAAGRP.ACCOUNT_GROUP_ID WHERE SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''''  )SUB_SAACNT LEFT JOIN SAACNT(NOLOCK) ON SUB_SAACNT.ACCOUNT_ID = SAACNT.ACCOUNT_ID WHERE SAACNT.ACCOUNT_ID IS NULL '")
    
    #Update
    UpdateQueryItems = SqlHelper.GetFirst(
        ""
        + str(Parameter1.QUERY_CRITERIA_1)
        + "  SAACNT SET SAACNT.CpqTableEntryModifiedBy = ''"
        + str(User.Id)
        + "'',SAACNT.CpqTableEntryDateModified = GetDate(),PAR_ACCOUNT_ID = M.ACCOUNT_ID,PAR_ACCOUNT_NAME = M.ACCOUNT_NAME,PAR_ACCOUNT_RECORD_ID = M.ACCOUNT_RECORD_ID FROM SAACNT_INBOUND(NOLOCK)JOIN SAACNT(NOLOCK) SAACNT ON SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID LEFT JOIN SAACNT M(NOLOCK) ON SAACNT_INBOUND.PAR_ACCOUNT_iD = M.ACCOUNT_iD WHERE  SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''''  ' ") 
    
    #SASAAC 
    #Update Query 
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SASAAC SET SASAAC.CpqTableEntryModifiedBy = ''"  
    + str(User.Id)
    + "'',SASAAC.CpqTableEntryDateModified = GetDate(),SASAAC.ACCOUNT_ID = SAACNT_INBOUND.ACCOUNT_ID,SASAAC.ACCOUNT_NAME = SAACNT.ACCOUNT_NAME,SASAAC.ACCOUNT_RECORD_ID = SAACNT.ACCOUNT_RECORD_ID,SASAAC.DISTRIBUTIONCHANNEL_ID = SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID,SASAAC.DISTRIBUTIONCHANNEL_RECORD_ID = SADSCH.DISTRIBUTION_CHANNEL_RECORD_ID,SASAAC.DIVISION_ID = SAACNT_INBOUND.DIVISION_ID,SASAAC.DIVISION_RECORD_ID = SADIVN.DIVISION_RECORD_ID,SASAAC.EXCRATTYP_ID =SAACNT_INBOUND.EXCHANGE_RATE_TYPE, SASAAC.SALESORG_ID = SAACNT_INBOUND.SALESORG_ID,SASAAC.SALESORG_RECORD_ID = SASORG.SALES_ORG_RECORD_ID,SASAAC.SALESORG_NAME = SASORG.SALESORG_NAME,SASAAC.CUSTOMER_PRICING_PROCEDURE = SAACNT_INBOUND.CUSTOMER_PRICING_PROCEDURE,SASAAC.INCOTERM_ID = SAACNT_INBOUND.INCOTERM_ID,SASAAC.INCOTERM_RECORD_ID = SAICTM.INCOTERM_RECORD_ID,SASAAC.PAYMENTTERM_ID = SAACNT_INBOUND.PAYMENTTERM_ID,SASAAC.PAYMENTTERM_DESCRIPTION = PRPTRM.PAYMENT_TERM_NAME,SASAAC.PAYMENTTERM_RECORD_ID = PRPTRM.PAYMENT_TERM_RECORD_ID,SASAAC.CURRENCY = SAACNT_INBOUND.CURRENCY,SASAAC.CURRENCY_RECORD_ID = PRCURR.CURRENCY_RECORD_ID,SASAAC.REGION = SAREGN.REGION,SASAAC.REGION_RECORD_ID = SAREGN.REGION_RECORD_ID,SASAAC.BLUEBOOK = SABLBK.BLUEBOOK,SASAAC.BLUEBOOK_RECORD_ID = SABLBK.BLUEBOOK_RECORD_ID,SASAAC.PRICELIST_ID = SAACNT_INBOUND.PRICELIST_ID,SASAAC.PRICELIST_DESCRIPTION = SAPLST.PRICELIST_NAME,SASAAC.PRICELIST_RECORD_ID = SAPLST.PRICE_LIST_RECORD_ID,SASAAC.PRICEGROUP_ID = SAACNT_INBOUND.PRICEGROUP_ID,SASAAC.PRICEGROUP_DESCRIPTION = SAPGRP.PRICEGROUP_NAME,SASAAC.PRICEGROUP_RECORD_ID = SAPGRP.PRICE_GROUP_RECORD_ID FROM SAACNT_INBOUND(NOLOCK) JOIN SAACNT(NOLOCK)  ON SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID JOIN SASORG(NOLOCK)  ON SAACNT_INBOUND.SALESORG_ID=SASORG.SALESORG_ID JOIN SADSCH(NOLOCK)  ON SADSCH.DISTRIBUTIONCHANNEL_ID=SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID LEFT JOIN SADIVN(NOLOCK)  ON SADIVN.DIVISION_ID=SAACNT_INBOUND.DIVISION_ID LEFT JOIN SAPGRP(NOLOCK)  ON SAPGRP.PRICEGROUP_ID=SAACNT_INBOUND.PRICEGROUP_ID LEFT JOIN PRPTRM(NOLOCK)  ON PRPTRM.PAYMENT_TERM_ID=SAACNT_INBOUND.PAYMENTTERM_ID LEFT JOIN SAICTM(NOLOCK) ON SAICTM.INCOTERM_ID=SAACNT_INBOUND.INCOTERM_ID LEFT JOIN SAPLST(NOLOCK) ON SAPLST.PRICELIST_ID=SAACNT_INBOUND.PRICELIST_ID LEFT JOIN PRCURR(NOLOCK)  ON PRCURR.CURRENCY=SAACNT_INBOUND.CURRENCY LEFT JOIN SAREGN(NOLOCK) ON SAACNT_INBOUND.REGION = SAREGN.EXTERNAL_ID  LEFT JOIN SABLBK(NOLOCK) ON SAACNT_INBOUND.BLUEBOOK = SABLBK.EXTERNAL_ID JOIN SASAAC(NOLOCK)  ON SAACNT_INBOUND.ACCOUNT_ID=SASAAC.ACCOUNT_ID AND SAACNT_INBOUND.SALESORG_ID=SASAAC.SALESORG_ID AND SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID = SASAAC.DISTRIBUTIONCHANNEL_ID AND SAACNT_INBOUND.DIVISION_ID = SASAAC.DIVISION_ID  WHERE  SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''SASAAC''  ' ")   

    #Insert Query
    InsertQueryItems = SqlHelper.GetFirst(""
            + str(Parameter.QUERY_CRITERIA_1)
            + " SASAAC (ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_RECORD_ID,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,DISTRIBUTIONCHANNEL_ID,DISTRIBUTIONCHANNEL_RECORD_ID,DIVISION_ID,DIVISION_RECORD_ID,PAYMENTTERM_ID,PAYMENTTERM_DESCRIPTION,PAYMENTTERM_RECORD_ID,INCOTERM_ID,INCOTERM_RECORD_ID,CURRENCY,PRICELIST_ID,PRICELIST_DESCRIPTION,PRICELIST_RECORD_ID,PRICEGROUP_ID,PRICEGROUP_DESCRIPTION,PRICEGROUP_RECORD_ID,CUSTOMER_PRICING_PROCEDURE,CURRENCY_RECORD_ID, REGION,REGION_RECORD_ID,BLUEBOOK,BLUEBOOK_RECORD_ID,EXCRATTYP_ID,SALES_AREA_ACCOUNT_RECORD_ID,CPQTABLEENTRYDATEADDED)SELECT SUB_SASAAC.*, CONVERT(VARCHAR(4000),NEWID()),GETDATE() FROM (SELECT DISTINCT SAACNT_INBOUND.ACCOUNT_ID,SAACNT.ACCOUNT_NAME,SAACNT.ACCOUNT_RECORD_ID,SASORG.SALESORG_ID,SASORG.SALESORG_NAME,SASORG.SALES_ORG_RECORD_ID,SADSCH.DISTRIBUTIONCHANNEL_ID,SADSCH.DISTRIBUTION_CHANNEL_RECORD_ID,SAACNT_INBOUND.DIVISION_ID,SADIVN.DIVISION_RECORD_ID,SAACNT_INBOUND.PAYMENTTERM_ID,PRPTRM.PAYMENT_TERM_NAME,PRPTRM.PAYMENT_TERM_RECORD_ID,SAICTM.INCOTERM_ID,SAICTM.INCOTERM_RECORD_ID,SAACNT_INBOUND.CURRENCY,SAACNT_INBOUND.PRICELIST_ID,SAPLST.PRICELIST_NAME AS PRICELIST_DESCRIPTION,SAPLST.PRICE_LIST_RECORD_ID AS PRICELIST_RECORD_ID,SAACNT_INBOUND.PRICEGROUP_ID,SAPGRP.PRICEGROUP_NAME AS PRICEGROUP_DESCRIPTION,SAPGRP.PRICE_GROUP_RECORD_ID AS PRICEGROUP_RECORD_ID,SAACNT_INBOUND.CUSTOMER_PRICING_PROCEDURE,PRCURR.CURRENCY_RECORD_ID, SAREGN.REGION,SAREGN.REGION_RECORD_ID,SABLBK.BLUEBOOK,SABLBK.BLUEBOOK_RECORD_ID,SAACNT_INBOUND.EXCHANGE_RATE_TYPE FROM SAACNT_INBOUND(NOLOCK) JOIN SAACNT(NOLOCK) on SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID JOIN SASORG(NOLOCK) ON SAACNT_INBOUND.SALESORG_ID=SASORG.SALESORG_ID JOIN SADSCH ON SADSCH.DISTRIBUTIONCHANNEL_ID=SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID LEFT JOIN SADIVN ON SADIVN.DIVISION_ID=SAACNT_INBOUND.DIVISION_ID LEFT JOIN PRPTRM ON PRPTRM.PAYMENT_TERM_ID=SAACNT_INBOUND.PAYMENTTERM_ID LEFT JOIN SAPGRP(NOLOCK)  ON SAPGRP.PRICEGROUP_ID=SAACNT_INBOUND.PRICEGROUP_ID LEFT JOIN SAPLST(NOLOCK) ON SAPLST.PRICELIST_ID=SAACNT_INBOUND.PRICELIST_ID LEFT JOIN SAICTM ON SAICTM.INCOTERM_ID=SAACNT_INBOUND.INCOTERM_ID LEFT JOIN PRCURR ON PRCURR.CURRENCY=SAACNT_INBOUND.CURRENCY LEFT JOIN SABLBK ON SABLBK.EXTERNAL_ID=SAACNT_INBOUND.BLUEBOOK LEFT JOIN SAREGN(NOLOCK) ON SAACNT_INBOUND.REGION = SAREGN.EXTERNAL_ID  WHERE SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''SASAAC'' )SUB_SASAAC LEFT JOIN SASAAC(NOLOCK) ON SUB_SASAAC.ACCOUNT_ID = SASAAC.ACCOUNT_ID AND SUB_SASAAC.SALESORG_ID = SASAAC.SALESORG_ID AND SUB_SASAAC.DISTRIBUTIONCHANNEL_ID = SASAAC.DISTRIBUTIONCHANNEL_ID AND SUB_SASAAC.DIVISION_ID = SASAAC.DIVISION_ID  WHERE SASAAC.ACCOUNT_ID IS NULL  '" )
    
    InsertQueryItems = SqlHelper.GetFirst(
            ""
            + str(Parameter.QUERY_CRITERIA_1)
            + " SASOAC(ACCOUNT_RECORD_ID,ACCOUNT_ID,ACCOUNT_NAME,DISTRIBUTIONCHANNEL_RECORD_ID,DISTRIBUTIONCHANNEL_ID,SALESORG_RECORD_ID,SALESORG_ID,SALESORG_NAME,SALESORG_ACCOUNTS_RECORD_ID)SELECT DISTINCT A.*,CONVERT(VARCHAR(100),NEWID()) FROM (SELECT DISTINCT ACCOUNT_RECORD_ID,ACCOUNT_ID,ACCOUNT_NAME,DISTRIBUTIONCHANNEL_RECORD_ID,DISTRIBUTIONCHANNEL_ID,SALESORG_RECORD_ID,SALESORG_ID,SALESORG_NAME FROM SASAAC (NOLOCK) )A LEFT JOIN SASOAC (NOLOCK) M ON A.ACCOUNT_ID = M.ACCOUNT_ID AND A.SALESORG_ID = M.SALESORG_ID WHERE M.ACCOUNT_ID IS NULL '" )
    
    #SAACPF
    #Update Query  
    S = SqlHelper.GetFirst("sp_executesql @T=N'update saacnt_inbound set PARTNER_ID = convert(bigint,PARTNER_ID)  where isnumeric(PARTNER_ID)=1  ' ")
    
    S = SqlHelper.GetFirst("sp_executesql @T=N'update saacnt_inbound set PARTNERFUNCTION_ID = CASE WHEN PARTNERFUNCTION_ID =''AD'' THEN ''AD''  WHEN PARTNERFUNCTION_ID =''AF'' THEN ''AE''  WHEN PARTNERFUNCTION_ID =''AG'' THEN ''SP''  WHEN PARTNERFUNCTION_ID =''AP'' THEN ''CP''  WHEN PARTNERFUNCTION_ID =''AU'' THEN ''AU''  WHEN PARTNERFUNCTION_ID =''BA'' THEN ''OA''  WHEN PARTNERFUNCTION_ID =''DP'' THEN ''DC''  WHEN PARTNERFUNCTION_ID =''EK'' THEN ''BU''  WHEN PARTNERFUNCTION_ID =''EN'' THEN ''EU''  WHEN PARTNERFUNCTION_ID =''HS'' THEN ''MN''  WHEN PARTNERFUNCTION_ID =''LF'' THEN ''VN''  WHEN PARTNERFUNCTION_ID =''LW'' THEN ''DP''  WHEN PARTNERFUNCTION_ID =''Q1'' THEN ''Q1''  WHEN PARTNERFUNCTION_ID =''Q2'' THEN ''Q2''  WHEN PARTNERFUNCTION_ID =''RE'' THEN ''BP''  WHEN PARTNERFUNCTION_ID =''RG'' THEN ''PY''  WHEN PARTNERFUNCTION_ID =''RS'' THEN ''PI''  WHEN PARTNERFUNCTION_ID =''SP'' THEN ''CR''  WHEN PARTNERFUNCTION_ID =''TF'' THEN ''TF''  WHEN PARTNERFUNCTION_ID =''TL'' THEN ''TL''  WHEN PARTNERFUNCTION_ID =''TR'' THEN ''TR''  WHEN PARTNERFUNCTION_ID =''TU'' THEN ''TU''  WHEN PARTNERFUNCTION_ID =''TV'' THEN ''TC''  WHEN PARTNERFUNCTION_ID =''TZ'' THEN ''TZ''  WHEN PARTNERFUNCTION_ID =''VA'' THEN ''CA''  WHEN PARTNERFUNCTION_ID =''VE'' THEN ''PE''  WHEN PARTNERFUNCTION_ID =''VP'' THEN ''PA''  WHEN PARTNERFUNCTION_ID =''WE'' THEN ''SH''  WHEN PARTNERFUNCTION_ID =''WL'' THEN ''GS''  WHEN PARTNERFUNCTION_ID =''Z9'' THEN ''Z9''  WHEN PARTNERFUNCTION_ID =''ZC'' THEN ''ZC''  WHEN PARTNERFUNCTION_ID =''ZM'' THEN ''ER''  WHEN PARTNERFUNCTION_ID =''ZP'' THEN ''ZP'' ELSE PARTNERFUNCTION_ID END  ' ")
    
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAACPF SET SAACPF.CpqTableEntryModifiedBy = ''"
    + str(User.Id)
    + "'',SAACPF.CpqTableEntryDateModified = GetDate(),SAACPF.ACCOUNT_ID = SAACNT_INBOUND.ACCOUNT_ID,SAACPF.ACCOUNT_NAME = SAACNT.ACCOUNT_NAME,SAACPF.ACCOUNT_RECORD_ID = SAACNT.ACCOUNT_RECORD_ID,SAACPF.SALESORG_ID = SAACNT_INBOUND.SALESORG_ID,SAACPF.SALESORG_RECORD_ID = SASORG.SALES_ORG_RECORD_ID,SAACPF.SALESORG_NAME = SASORG.SALESORG_NAME,SAACPF.PARTNERFUNCTION_ID = SYPFTY.PARTNERFUNCTION_ID,SAACPF.PARTNERFUNCTION_DESCRIPTION = SYPFTY.PARTNERFUNCTION_DESCRIPTION,SAACPF.PTRFUNTYP_RECORD_ID = SYPFTY.PARTNERFUNCTION_RECORD_ID,SAACPF.PARTNER_ID = SAACNT_INBOUND.PARTNER_ID,SAACPF.PARTNERTYPE_DESCRIPTION = SYPFTY.PARTNERTYPE_DESCRIPTION,SAACPF.PARTNERTYPE_ID = SYPFTY.PARTNERTYPE_ID,SAACPF.RANK = SAACNT_INBOUND.RANK,SAACPF.DISTRIBUTIONCHANNEL_ID = SADSCH.DISTRIBUTIONCHANNEL_ID,SAACPF.DISTRIBUTIONCHANNEL_RECORD_ID = SADSCH.DISTRIBUTION_CHANNEL_RECORD_ID,SAACPF.DIVISION_ID = SADIVN.DIVISION_ID,SAACPF.DIVISION_RECORD_ID = SADIVN.DIVISION_RECORD_ID FROM SAACNT_INBOUND(NOLOCK) JOIN SAACNT(NOLOCK)  ON SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID JOIN SASORG(NOLOCK) ON SAACNT_INBOUND.SALESORG_ID=SASORG.SALESORG_ID JOIN SADSCH ON SADSCH.DISTRIBUTIONCHANNEL_ID=SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID LEFT JOIN SADIVN ON SADIVN.DIVISION_ID=SAACNT_INBOUND.DIVISION_ID LEFT JOIN SYPFTY(NOLOCK) ON SAACNT_INBOUND.PARTNERFUNCTION_ID = SYPFTY.PARTNERFUNCTION_ID JOIN SAACPF(NOLOCK) ON SAACNT_INBOUND.ACCOUNT_ID=SAACPF.ACCOUNT_ID AND SAACNT_INBOUND.SALESORG_ID=SAACPF.SALESORG_ID AND  SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID=SAACPF.DISTRIBUTIONCHANNEL_ID and SAACNT_INBOUND.DIVISION_ID=SAACPF.DIVISION_ID AND SAACNT_INBOUND.PARTNER_ID = SAACPF.PARTNER_ID  WHERE  SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''SAACPF''  ' ")
    
    #Insert
    InsertQueryItems = SqlHelper.GetFirst(
        ""
        + "sp_executesql @statement = N'INSERT"
        + " SAACPF (ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_RECORD_ID,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,PARTNER_ID,PARTNERFUNCTION_ID,RANK,PARTNERFUNCTION_DESCRIPTION,DISTRIBUTIONCHANNEL_ID,DISTRIBUTIONCHANNEL_RECORD_ID,DIVISION_ID,DIVISION_RECORD_ID,PTRFUNTYP_RECORD_ID,PARTNERTYPE_DESCRIPTION,PARTNERTYPE_ID,ACCOUNT_PARTNER_FUNCTION_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_SAACPF.*, CONVERT(VARCHAR(4000),NEWID()),''"   + str(User.UserName)+ "'',GETDATE() FROM (SELECT DISTINCT SAACNT_INBOUND.ACCOUNT_ID,SAACNT.ACCOUNT_NAME,SAACNT.ACCOUNT_RECORD_ID,SAACNT_INBOUND.SALESORG_ID,SASORG.SALESORG_NAME,SASORG.SALES_ORG_RECORD_ID,SAACNT_INBOUND.PARTNER_ID,SAACNT_INBOUND.PARTNERFUNCTION_ID,SAACNT_INBOUND.RANK,SYPFTY.PARTNERFUNCTION_DESCRIPTION,SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID,SADSCH.DISTRIBUTION_CHANNEL_RECORD_ID,SAACNT_INBOUND.DIVISION_ID,SADIVN.DIVISION_RECORD_ID,SYPFTY.PARTNERFUNCTION_RECORD_ID,SYPFTY.PARTNERTYPE_DESCRIPTION,SYPFTY.PARTNERTYPE_ID FROM SAACNT_INBOUND(NOLOCK) JOIN SAACNT(NOLOCK) ON SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID  LEFT JOIN SASORG(NOLOCK) ON SAACNT_INBOUND.SALESORG_ID=SASORG.SALESORG_ID LEFT JOIN SADSCH ON SADSCH.DISTRIBUTIONCHANNEL_ID=SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID LEFT JOIN SADIVN ON SADIVN.DIVISION_ID=SAACNT_INBOUND.DIVISION_ID  LEFT JOIN SYPFTY(NOLOCK) ON  SAACNT_INBOUND.PARTNERFUNCTION_ID=SYPFTY.PARTNERFUNCTION_ID AND SAACNT_INBOUND.PARTNERFUNCTION_ID = SYPFTY.PARTNERFUNCTION_ID WHERE SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''SAACPF'' )SUB_SAACPF LEFT JOIN SAACPF(NOLOCK) ON SUB_SAACPF.ACCOUNT_ID = SAACPF.ACCOUNT_ID AND SUB_SAACPF.SALESORG_ID = SAACPF.SALESORG_ID AND SUB_SAACPF.PARTNERFUNCTION_ID=SAACPF.PARTNERFUNCTION_ID and SAACPF.DISTRIBUTIONCHANNEL_ID=SUB_SAACPF.DISTRIBUTIONCHANNEL_ID and SAACPF.DIVISION_ID=SUB_SAACPF.DIVISION_ID and SAACPF.PARTNER_ID=SUB_SAACPF.PARTNER_ID  WHERE SAACPF.ACCOUNT_ID IS NULL  '")
    
    UpdateQueryItems = SqlHelper.GetFirst(
        ""
        + str(Parameter1.QUERY_CRITERIA_1)
        + "  SAACPF SET SAACPF.CpqTableEntryModifiedBy = ''"
        + str(User.Id)
        + "'',SAACPF.CpqTableEntryDateModified = GetDate(),SAACPF.PARTNER_NAME = SAACNT.ACCOUNT_NAME FROM SAACPF(NOLOCK) JOIN SAACNT(NOLOCK)  ON SAACPF.PARTNER_ID=SAACNT.ACCOUNT_ID   ' ")

    
    #SAASCT
    #Update Query
    
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAASCT SET SAASCT.CpqTableEntryModifiedBy = ''"
    + str(User.Id)
    + "'',SAASCT.CpqTableEntryDateModified = GetDate(),SAASCT.ACCOUNT_ID = SAACNT_INBOUND.ACCOUNT_ID,SAASCT.ACCOUNT_NAME = SAACNT.ACCOUNT_NAME,SAASCT.ACCOUNT_RECORD_ID = SAACNT.ACCOUNT_RECORD_ID,SAASCT.SALESORG_ID = SAACNT_INBOUND.SALESORG_ID,SAASCT.SALESORG_RECORD_ID = SASORG.SALES_ORG_RECORD_ID,SAASCT.SALESORG_NAME = SASORG.SALESORG_NAME,SAASCT.DISTRIBUTIONCHANNEL_ID = SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID,SAASCT.DISTRIBUTIONCHANNEL_RECORD_ID = SADSCH.DISTRIBUTION_CHANNEL_RECORD_ID,SAASCT.DIVISION_ID = SADIVN.DIVISION_ID,SAASCT.DIVISION_RECORD_ID = SADIVN.DIVISION_RECORD_ID,SAASCT.COUNTRY = SAACNT_INBOUND.COUNTRY,SAASCT.COUNTRY_NAME= SACTRY.COUNTRY_NAME,SAASCT.COUNTRY_RECORD_ID = SACTRY.COUNTRY_RECORD_ID,SAASCT.TAXCATEGORY_ID = SAACNT_INBOUND.TAXCATEGORY_ID,SAASCT.TAXCLASSIFICATION_ID = SAACNT_INBOUND.TAXCLASSIFICATION_ID,SAASCT.TAXCATEGORY_DESCRIPTION = PRTXCT.TAX_CATEGORY_DESCRIPTION,SAASCT.TAXCATEGORY_RECORD_ID = PRTXCT.TAX_CATEGORY_RECORD_ID,SAASCT.TAXCLASSIFICATION_DESCRIPTION = PRTXCL.TAX_CLASSIFICATION_DESCRIPTION,SAASCT.TAXCLASSIFICATION_RECORD_ID = PRTXCL.TAX_CLASSIFICATION_RECORD_ID FROM SAACNT_INBOUND(NOLOCK) JOIN SAACNT(NOLOCK) ON SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID LEFT JOIN SASORG(NOLOCK) ON SAACNT_INBOUND.SALESORG_ID=SASORG.SALESORG_ID LEFT JOIN SADSCH ON SADSCH.DISTRIBUTIONCHANNEL_ID=SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID LEFT JOIN SADIVN ON SADIVN.DIVISION_ID=SAACNT_INBOUND.DIVISION_ID LEFT JOIN PRTXCL ON SAACNT_INBOUND.TAXCLASSIFICATION_ID=PRTXCL.TAX_CLASSIFICATION_ID AND PRTXCL.TAXCATEGORY_ID=SAACNT_INBOUND.TAXCATEGORY_ID AND PRTXCL.TAX_CLASSIFICATION_TYPE=''CUSTOMER''  LEFT JOIN PRTXCT ON PRTXCT.TAX_CATEGORY_ID=SAACNT_INBOUND.TAXCATEGORY_ID LEFT JOIN SACTRY(NOLOCK) ON SAACNT_INBOUND.COUNTRY=SACTRY.COUNTRY JOIN SAASCT(NOLOCK) ON SAACNT_INBOUND.ACCOUNT_ID=SAASCT.ACCOUNT_ID AND SAACNT_INBOUND.SALESORG_ID=SAASCT.SALESORG_ID AND SAASCT.TAXCATEGORY_ID=SAACNT_INBOUND.TAXCATEGORY_ID AND SAASCT.DISTRIBUTIONCHANNEL_ID=SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID AND SAASCT.DIVISION_ID=SAACNT_INBOUND.DIVISION_ID AND SAASCT.COUNTRY=SAACNT_INBOUND.COUNTRY AND SAASCT.TAXCLASSIFICATION_ID=SAACNT_INBOUND.TAXCLASSIFICATION_ID WHERE  SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''SAASCT''  ' ")


    #Inset Queary 
    InsertQueryItems = SqlHelper.GetFirst(
        ""
        + str(Parameter.QUERY_CRITERIA_1)
        + " SAASCT (ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_RECORD_ID,SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,DISTRIBUTIONCHANNEL_ID,DISTRIBUTIONCHANNEL_RECORD_ID,DIVISION_ID,DIVISION_RECORD_ID,COUNTRY,COUNTRY_NAME,COUNTRY_RECORD_ID,TAXCATEGORY_ID,TAXCLASSIFICATION_ID,TAXCATEGORY_DESCRIPTION,TAXCATEGORY_RECORD_ID,TAXCLASSIFICATION_DESCRIPTION,TAXCLASSIFICATION_RECORD_ID,ACCOUNT_SALES_AREA_COUNTRY_TAX_RECORD_ID,CPQTABLEENTRYDATEADDED)SELECT SUB_SAASCT.*, CONVERT(VARCHAR(4000),NEWID()),GETDATE() FROM (SELECT DISTINCT SAACNT_INBOUND.ACCOUNT_ID,SAACNT.ACCOUNT_NAME,SAACNT.ACCOUNT_RECORD_ID,SAACNT_INBOUND.SALESORG_ID,SASORG.SALESORG_NAME,SASORG.SALES_ORG_RECORD_ID,SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID,SADSCH.DISTRIBUTION_CHANNEL_RECORD_ID,SAACNT_INBOUND.DIVISION_ID,SADIVN.DIVISION_RECORD_ID,SAACNT_INBOUND.COUNTRY,SACTRY.COUNTRY_NAME,SACTRY.COUNTRY_RECORD_ID,SAACNT_INBOUND.TAXCATEGORY_ID,SAACNT_INBOUND.TAXCLASSIFICATION_ID,PRTXCT.TAX_CATEGORY_DESCRIPTION,PRTXCT.TAX_CATEGORY_RECORD_ID,PRTXCL.TAX_CLASSIFICATION_DESCRIPTION,PRTXCL.TAX_CLASSIFICATION_RECORD_ID FROM SAACNT_INBOUND(NOLOCK) JOIN SAACNT(NOLOCK) ON SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID JOIN SASORG(NOLOCK) ON SAACNT_INBOUND.SALESORG_ID=SASORG.SALESORG_ID JOIN SADSCH  ON SADSCH.DISTRIBUTIONCHANNEL_ID=SAACNT_INBOUND.DISTRIBUTIONCHANNEL_ID JOIN SADIVN ON SADIVN.DIVISION_ID=SAACNT_INBOUND.DIVISION_ID JOIN PRTXCL ON SAACNT_INBOUND.TAXCLASSIFICATION_ID=PRTXCL.TAX_CLASSIFICATION_ID AND PRTXCL.TAXCATEGORY_ID=SAACNT_INBOUND.TAXCATEGORY_ID AND PRTXCL.TAX_CLASSIFICATION_TYPE=''CUSTOMER'' LEFT JOIN PRTXCT ON PRTXCT.TAX_CATEGORY_ID=SAACNT_INBOUND.TAXCATEGORY_ID LEFT JOIN SACTRY(NOLOCK) ON SAACNT_INBOUND.COUNTRY=SACTRY.COUNTRY WHERE SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''SAASCT'' )SUB_SAASCT LEFT JOIN SAASCT(NOLOCK) ON SUB_SAASCT.ACCOUNT_ID = SAASCT.ACCOUNT_ID AND SAASCT.SALESORG_ID = SUB_SAASCT.SALESORG_ID AND SAASCT.TAXCATEGORY_ID=SUB_SAASCT.TAXCATEGORY_ID AND SAASCT.DISTRIBUTIONCHANNEL_ID=SUB_SAASCT.DISTRIBUTIONCHANNEL_ID AND SAASCT.DIVISION_ID=SUB_SAASCT.DIVISION_ID AND SUB_SAASCT.COUNTRY=SAASCT.COUNTRY AND SUB_SAASCT.TAXCLASSIFICATION_ID = SAASCT.TAXCLASSIFICATION_ID WHERE SAASCT.ACCOUNT_ID IS NULL '"
        )
    
    """InsertQueryItems = SqlHelper.GetFirst(
        ""
        + str(Parameter.QUERY_CRITERIA_1)
        + " SACONT (CITY,CONTACT_ID,CONTACT_NAME,COUNTRY,COUNTRY_RECORD_ID,PHONE,POSTAL_CODE,STATE,STATE_RECORD_ID,CPQTABLEENTRYDATEADDED,CONTACT_RECORD_ID)SELECT SUB_SACONT.*,GetDate() ,CONVERT(VARCHAR(4000),NEWID()) FROM (SELECT DISTINCT SAACNT_INBOUND.CITY,SAACNT_INBOUND.CONTACT_ID,(FIRSTNAME+'' ''+LASTNAME) AS CONTACT_NAME,SACTRY.COUNTRY,SACTRY.COUNTRY_RECORD_ID,SAACNT_INBOUND.PHONE,SAACNT_INBOUND.POSTAL_CODE,SAACNT_INBOUND.STATE,SACYST.STATE_RECORD_ID FROM SAACNT_INBOUND(NOLOCK) LEFT JOIN SACTRY(NOLOCK) ON SAACNT_INBOUND.COUNTRY=SACTRY.COUNTRY LEFT JOIN SACYST(NOLOCK)  ON SAACNT_INBOUND.STATE=SACYST.STATE AND SAACNT_INBOUND.COUNTRY=SACYST.COUNTRY WHERE  SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''SAACCT''  )SUB_SACONT LEFT JOIN SACONT(NOLOCK)  ON SUB_SACONT.CONTACT_ID=SACONT.CONTACT_ID WHERE  SACONT.CONTACT_ID IS NULL'"
        )"""
    
    #Update Query
    
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAACCT SET SAACCT.CpqTableEntryModifiedBy = ''"
    + str(User.Id)
    + "'',SAACCT.CpqTableEntryDateModified = GetDate(),SAACCT.ACCOUNT_ID = SAACNT_INBOUND.ACCOUNT_ID,SAACCT.ACCOUNT_NAME = SAACNT.ACCOUNT_NAME,SAACCT.ACCOUNT_RECORD_ID = SAACNT.ACCOUNT_RECORD_ID,SAACCT.CONTACT_ID = SAACNT_INBOUND.CONTACT_ID,SAACCT.CONTACT_NAME = SACONT.CONTACT_NAME,SAACCT.CONTACT_RECORD_ID = SACONT.CONTACT_RECORD_ID,SAACCT.EMAIL = SACONT.EMAIL,SAACCT.PHONE = SAACNT_INBOUND.PHONE FROM SAACNT_INBOUND(NOLOCK) JOIN SAACNT(NOLOCK) ON SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID LEFT JOIN SACONT(NOLOCK) ON SAACNT_INBOUND.CONTACT_ID=SACONT.CONTACT_ID   JOIN SAACCT(NOLOCK)  ON SAACNT_INBOUND.ACCOUNT_ID=SAACCT.ACCOUNT_ID AND SAACNT_INBOUND.CONTACT_ID=SAACCT.CONTACT_ID WHERE  SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''SAACCT''  ' ")
    
    InsertQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter.QUERY_CRITERIA_1)
    + " SAACCT (ACCOUNT_ID,ACCOUNT_NAME,ACCOUNT_RECORD_ID,CONTACT_ID,CONTACT_NAME,CONTACT_RECORD_ID,EMAIL,PHONE,ACCOUNT_CONTACTS_RECORD_ID,CPQTABLEENTRYDATEADDED)SELECT SUB_SAACCT.*, CONVERT(VARCHAR(4000),NEWID()),GetDate() FROM (SELECT DISTINCT SAACNT_INBOUND.ACCOUNT_ID,SAACNT.ACCOUNT_NAME,SAACNT.ACCOUNT_RECORD_ID,SAACNT_INBOUND.CONTACT_ID,SACONT.CONTACT_NAME,SACONT.CONTACT_RECORD_ID,SACONT.EMAIL,SACONT.PHONE FROM SAACNT_INBOUND(NOLOCK) JOIN SAACNT(NOLOCK)  ON SAACNT_INBOUND.ACCOUNT_ID=SAACNT.ACCOUNT_ID JOIN SACONT(NOLOCK) ON  SAACNT_INBOUND.CONTACT_ID=SACONT.CONTACT_ID  WHERE  SAACNT_INBOUND.INTEGRATION_STATUS = ''READY FOR UPLOAD'' AND ISNULL(SAACNT_INBOUND.INTEGRATION_OBJECT,'''')=''SAACCT''  )SUB_SAACCT LEFT JOIN SAACCT(NOLOCK) ON SUB_SAACCT.ACCOUNT_ID=SAACCT.ACCOUNT_ID AND SUB_SAACCT.CONTACT_ID=SAACCT.CONTACT_ID WHERE SAACCT.ACCOUNT_ID IS NULL AND SAACCT.CONTACT_ID IS NULL'"
    )
    
    
    #Status Update
    UpdateQueryItems = SqlHelper.GetFirst(
    ""
    + str(Parameter1.QUERY_CRITERIA_1)
    + "  SAACNT_INBOUND SET INTEGRATION_STATUS = ''UPLOADED'' WHERE INTEGRATION_STATUS=''READY FOR UPLOAD''' ")

    primaryQueryItems = SqlHelper.GetFirst(
                        ""
                        + str(Parameter1.QUERY_CRITERIA_1)
                        + "  A SET CRM_FABLOCATION_ID = B.ACCOUNT_ID FROM MAFBLC A(NOLOCK) JOIN SAACNT B (NOLOCK) ON A.FAB_LOCATION_ID = B.LEGACY_FBL_ID WHERE ACCOUNTGROUP_ID = ''ZFAB'' ' ")

    Result = '{"Response": [{"Status": "200", "Message": "Data successfully uploaded"}]}'

except:
    Log.Info("SGPOSTCACT ERROR---->:" + str(sys.exc_info()[1]))
    Log.Info("SGPOSTCACT ERROR LINE NO---->:" + str(sys.exc_info()[-1].tb_lineno))
    error_info = {"Response": [{"Status": "400", "Message": str(sys.exc_info()[1])}]}
    Result  = str(error_info)