# =========================================================================================================================================
#   __script_name : MAPOSTTKMU.PY
#   __script_description : THIS SCRIPT IS USED TO EXTRACT KIT BOM  AND PM BOM DATA FROM SYINPL TABLE TO STAGING TABLES
#   __primary_author__ : BAJI
#   __create_date : 2020-12-28
#   Â© BOSTON HARBOR TECHNOLOGY LLC - ALL RIGHTS RESERVED
# ==========================================================================================================================================
import sys
import datetime
import clr
import System.Net
from System.Text.Encoding import UTF8
from System import Convert
from SYDATABASE import SQL
clr.AddReference("System.Net")
from System.Net import CookieContainer, NetworkCredential, Mail
from System.Net.Mail import SmtpClient, MailAddress, Attachment, MailMessage

sscm_kitbom = ScriptExecutor.ExecuteGlobal("MAPOSTSCKT")
sscm_pmkit = ScriptExecutor.ExecuteGlobal("MAPOSTSCPM")


Parameter=SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME='SELECT' ")
Parameter1 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'UPD' ")

cpqtbleentid = ''

try :
	Status_flag = 0
	
	#Status Inprogress SYINPL by CPQ Table Entry ID
	StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''INPROGRESS'' FROM SYINPL (NOLOCK) WHERE isnull(status,'''')='''' AND (INTEGRATION_NAME = ''SSCM_TO_CPQ_TOOL_PMKIT_DATA'' or INTEGRATION_NAME = ''SSCM_TO_CPQ_KITBOM_DATA'') ' ")	
	
	while Status_flag == 0:
		#Status Empty
		Jsonquery = SqlHelper.GetList("SELECT INTEGRATION_PAYLOAD,CpqTableEntryId from SYINPL(NOLOCK) WHERE ISNULL(STATUS,'') = 'INPROGRESS' AND (INTEGRATION_NAME = 'SSCM_TO_CPQ_KITBOM_DATA' or INTEGRATION_NAME = 'SSCM_TO_CPQ_TOOL_PMKIT_DATA') ")
		
		if len(Jsonquery) > 0:
		
			primaryQuerysession =  SqlHelper.GetFirst("SELECT NEWID() AS A")
			today = datetime.datetime.now()
			Modi_date = today.strftime("%m/%d/%Y %H:%M:%S %p")
			
			for json_data in Jsonquery:

				cpqtbleentid = str(json_data.CpqTableEntryId)

				if "Param" in json_data.INTEGRATION_PAYLOAD:
					splited_list = (json_data.INTEGRATION_PAYLOAD)
					l =  splited_list.rindex("%%")
					f = splited_list.index("%%")+2						
					rebuilt_data = splited_list[f:l].replace('false','"false"')
					rebuilt_data = rebuilt_data.replace('true','"true"')
					rebuilt_data = rebuilt_data.replace('null','"NALL"')
					rebuilt_data = eval(rebuilt_data)
				else:
					splited_list = json_data.INTEGRATION_PAYLOAD
					rebuilt_data = eval(splited_list.replace('false','"false"').replace('true','"true"').replace('null','"NALL"'))       

				if len(rebuilt_data) != 0:      

					rebuilt_data = rebuilt_data["CPQ_Columns"]
					Table_Names = rebuilt_data.keys()
					Check_flag = 0
					
					for tn in Table_Names:
						if tn in rebuilt_data:
							Check_flag = 1
							if str(tn).upper() == "QTQICO":
								if str(type(rebuilt_data[tn])) == "<type 'dict'>":
									Tbl_data = [rebuilt_data[tn]]
								else:
									Tbl_data = rebuilt_data[tn]
									
								for record_dict in Tbl_data:
								
									splt_info = """ ''{TOOL_ID}'',''{Assembly_ID}'',''{PM_Event}'',''{PM_Freq}'',''{KIT_ID}'',''{KIT_Number}'',''{Seedstock_Cost}'',''{Logistics_Cost}'',''{TKM_Cost_Per_Event}'',''{Modi_date}'',''{KIT_MASTER_ID}'',''{APPLICATION}'',''{CLEANING_REGION}'',''{CUSTOMER_MARKETING_NAME}'',''{DEVICE}'',''{PROCESS_TYPE}'',''{SERVICE_COMPLEXITY}'',''{TECH_NODE}'',''{HW_TYPE}'',''{ARCM_Module_ID}'',''{RFP_Edit}'',''{Updated_Date}'',''{CPQ_Processed}'',''{Maintenance_Event_Level}'',''{KIT_CleaningCoating_Differentiation}'' """.format(TOOL_ID = record_dict['TOOL_ID'],Assembly_ID = str(record_dict['Assembly_ID']),PM_Event = record_dict['PM_Event'],PM_Freq = record_dict['PM_Freq'],KIT_ID= record_dict['KIT_ID'],KIT_Number = str(record_dict['KIT_Number']),Seedstock_Cost = record_dict['Seedstock_Cost'],Logistics_Cost = record_dict['Logistics_Cost'],TKM_Cost_Per_Event = record_dict['TKM_Cost_Per_Event'],Modi_date = Modi_date,KIT_MASTER_ID= record_dict['KIT_MASTER_ID'],APPLICATION = record_dict['APPLICATION'],CLEANING_REGION = record_dict['CLEANING_REGION'],CUSTOMER_MARKETING_NAME = record_dict['CUSTOMER_MARKETING_NAME'],DEVICE = record_dict['DEVICE'],PROCESS_TYPE= record_dict['PROCESS_TYPE'],SERVICE_COMPLEXITY = record_dict['SERVICE_COMPLEXITY'],TECH_NODE = record_dict['TECH_NODE'],HW_TYPE = record_dict['HW_TYPE'],ARCM_Module_ID = record_dict['ARCM_Module_ID'],RFP_Edit = record_dict['RFP_Edit'], Updated_Date= str(record_dict['Updated_Date']),CPQ_Processed = record_dict['CPQ_Processed'],Maintenance_Event_Level = record_dict['Maintenance_Event_Level'],KIT_CleaningCoating_Differentiation = record_dict['KIT_CleaningCoating_Differentiation'] )
									
									primaryQueryItems = SqlHelper.GetFirst( ""+ str(Parameter.QUERY_CRITERIA_1)+ " MAEAPM_INBOUND (SESSION_ID,EQUIPMENT_ID,ASSEMBLY_ID,PM_NAME,PM_FREQUENCY,KIT_ID,KIT_NUMBER,SEEDSTOCK_COST,LOGISTICS_COST,TKM_COST_PER_EVENT,cpqtableentrydatemodified,KIT_MASTER_ID,APPLICATION,REGION,CUSTOMER_MARKETING_NAME,DEVICE,PROCESS_TYPE,SERVICE_COMPLEXITY,TECHNOLOGY_NODE,HW_TYPE,ARCM_MODULE_ID,RFP_EDIT,UPDATED_DATE,CPQ_PROCESSED,PM_LEVEL,CLEAN_COATING)  select  ''"+ str(primaryQuerysession.A)+ "'',"+splt_info+ " ' ")
									
							elif str(tn).upper() == "MAKTPT":
								if str(type(rebuilt_data[tn])) == "<type 'dict'>":
									Tbl_data = [rebuilt_data[tn]]
								else:
									Tbl_data = rebuilt_data[tn]
									
								for record_dict in Tbl_data:
									primaryQueryItems = SqlHelper.GetFirst( ""+ str(Parameter.QUERY_CRITERIA_1)+ " MAKTPT_INBOUND (SESSION_ID,KIT_ID,PART_NUMBER,QUANTITY,cpqtableentrydatemodified,KIT_MASTER_ID,UPDATED_DATE,CPQ_PROCESSED,KIT_DELETED)  select  ''"+ str(primaryQuerysession.A)+ "'',''"+record_dict['KIT_ID']+ "'',''"+record_dict['PartNumber']+ "'',''"+str(record_dict['Qty'])+ "'',''"+ str(Modi_date)+ "'',''"+str(record_dict['KIT_MASTER_ID'])+ "'',''"+record_dict['Updated_Date']+ "'',''"+record_dict['CPQ_Processed']+ "'',''"+record_dict['KIT_DELETED']+ "'' ' ")                    
							
										
					StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''COMPLETED''FROM SYINPL (NOLOCK)  WHERE CpqTableEntryId = ''"+str(json_data.CpqTableEntryId)+"'' ' ")
					
				else:
					StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''COMPLETED''FROM SYINPL (NOLOCK)  WHERE CpqTableEntryId = ''"+str(json_data.CpqTableEntryId)+"'' ' ")
		else:
			Status_flag = 1	
			
	#We need to write the code for staging tables to main tables code here
	sessionid = SqlHelper.GetFirst("SELECT NEWID() AS A")
	timestamp_sessionid = "'" + str(sessionid.A) + "'"	
				
	Parameter = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'SELECT' ")
	Parameter1 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'UPD' ")
	Parameter2 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'DEL' ")

	#Staging Status Change
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAKTPT_INBOUND SET TIMESTAMP = '"+str(timestamp_sessionid)+"',PROCESS_STATUS = ''INPROGRESS'' FROM MAKTPT_INBOUND (NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''''  '")
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAEAPM_INBOUND SET TIMESTAMP = '"+str(timestamp_sessionid)+"',PROCESS_STATUS = ''INPROGRESS'' FROM MAEAPM_INBOUND (NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')='''' AND ISNULL(QUOTE_ID,'''')='''' '")
	
	#Part Validation
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAKTPT_INBOUND SET PROCESS_STATUS = ''ERROR'',INTEGRATION_STATUS=''SAP PART NUMBER not exists in Material Master table (MAMTRL). Please trigger the SAP PART NUMBER from ECC to CPQ to resolve this error.'' FROM MAKTPT_INBOUND (NOLOCK)  LEFT JOIN MAMTRL (NOLOCK) ON MAKTPT_INBOUND.PART_NUMBER = MAMTRL.SAP_PART_NUMBER WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND MAMTRL.SAP_PART_NUMBER IS NULL '")
	
	#Status Change
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAKTPT_INBOUND SET PROCESS_STATUS = ''READY FOR UPLOAD'' FROM MAKTPT_INBOUND(NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')IN (''INPROGRESS'',''ERROR'') AND TIMESTAMP = '"+str(timestamp_sessionid)+"' '")
	
	#Kit Upload
	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter.QUERY_CRITERIA_1)
				+ " MAMKIT(KIT_NAME,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,KIT_RECORD_ID,KIT_ID)SELECT DISTINCT KIT_NAME,''"+ str(User.UserName)
				+ "'',''"+ str(User.Id)
				+ "'',GETDATE(),CONVERT(VARCHAR(1000),NEWID()),KIT_ID FROM (SELECT DISTINCT MAKTPT_INBOUND.KIT_ID AS KIT_NAME,MAKTPT_INBOUND.KIT_ID FROM MAKTPT_INBOUND (NOLOCK)  LEFT JOIN MAMKIT (NOLOCK) ON MAKTPT_INBOUND.KIT_ID = MAMKIT.KIT_ID WHERE MAMKIT.KIT_ID IS NULL)SUB_MAMKIT '")
	
	#Kit BOM Upload
	
	"""
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAKTPT SET QUANTITY = SUB_MAKTPT.QUANTITY FROM (SELECT DISTINCT MAMKIT.KIT_ID,MAMKIT.KIT_NAME,MAMKIT.KIT_RECORD_ID,SAP_DESCRIPTION,MAKTPT_INBOUND.PART_NUMBER,MATERIAL_RECORD_ID,MAKTPT_INBOUND.QUANTITY,''ACTIVE'' FROM MAKTPT_INBOUND(NOLOCK) JOIN MAMKIT (NOLOCK) ON MAKTPT_INBOUND.KIT_ID = MAMKIT.KIT_NAME LEFT JOIN MAMTRL (NOLOCK) ON MAKTPT_INBOUND.PART_NUMBER = MAMTRL.SAP_PART_NUMBER WHERE ISNULL(PROCESS_STATUS,'''')= ''READY FOR UPLOAD'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')SUB_MAKTPT JOIN MAKTPT M(NOLOCK) ON SUB_MAKTPT.KIT_ID = MAKTPT.KIT_ID AND SUB_MAKTPT.PART_NUMBER = MAKTPT.PART_NUMBER '")
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ " MAKTPT_INBOUND BOM_STATUS = ''ACTIVE'' FROM MAKTPT_INBOUND (NOLOCK) JOIN MAKTPT (NOLOCK) ON MAKTPT_INBOUND.KIT_ID = MAKTPT.KIT_ID AND MAKTPT_INBOUND.PART_NUMBER = MAKTPT.PART_NUMBER WHERE ISNULL(INTEGRATION_STATUS,'''')= '''' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  '")
"""
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter2.QUERY_CRITERIA_1)
	+ " MAKTPT FROM MAKTPT JOIN MAKTPT_INBOUND  ON MAKTPT.KIT_ID = MAKTPT_INBOUND.KIT_ID WHERE ISNULL(PROCESS_STATUS,'''')= ''READY FOR UPLOAD'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  '")
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ "  MAKTPT(KIT_ID,KIT_NAME,KIT_RECORD_ID,PART_DESCRIPTION,PART_NUMBER,PART_RECORD_ID,QUANTITY,BOM_STATUS,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,KIT_PART_RECORD_ID) SELECT DISTINCT SUB_MAKTPT.KIT_ID,SUB_MAKTPT.KIT_NAME,SUB_MAKTPT.KIT_RECORD_ID,SUB_MAKTPT.SAP_DESCRIPTION,SUB_MAKTPT.PART_NUMBER,SUB_MAKTPT.MATERIAL_RECORD_ID,SUB_MAKTPT.QUANTITY,SUB_MAKTPT.BOM_STATUS,''"+ str(User.UserName)
	+ "'',''"+ str(User.Id)
	+ "'',GETDATE(),CONVERT(VARCHAR(1000),NEWID()) FROM (SELECT DISTINCT MAMKIT.KIT_ID,MAMKIT.KIT_NAME,MAMKIT.KIT_RECORD_ID,SAP_DESCRIPTION,MAKTPT_INBOUND.PART_NUMBER,MATERIAL_RECORD_ID,MAKTPT_INBOUND.QUANTITY,''ACTIVE'' AS BOM_STATUS FROM MAKTPT_INBOUND (NOLOCK) JOIN MAMKIT (NOLOCK) ON MAKTPT_INBOUND.KIT_ID = MAMKIT.KIT_ID LEFT JOIN MAMTRL (NOLOCK) ON MAKTPT_INBOUND.PART_NUMBER = MAMTRL.SAP_PART_NUMBER WHERE ISNULL(PROCESS_STATUS,'''')= ''READY FOR UPLOAD'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')SUB_MAKTPT LEFT JOIN MAKTPT (NOLOCK) ON SUB_MAKTPT.KIT_ID = MAKTPT.KIT_ID AND SUB_MAKTPT.PART_NUMBER = MAKTPT.PART_NUMBER WHERE MAKTPT.PART_NUMBER IS NULL  '")
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ " MAKTPT set BOM_STATUS = ''ERROR - PART NOT AVAILABLE'' FROM MAKTPT_INBOUND (NOLOCK) JOIN MAKTPT (NOLOCK) ON MAKTPT_INBOUND.KIT_ID = MAKTPT.KIT_ID AND MAKTPT_INBOUND.PART_NUMBER = MAKTPT.PART_NUMBER WHERE ISNULL(INTEGRATION_STATUS,'''')= ''ERROR'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"'  '")
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAKTPT_INBOUND SET PROCESS_STATUS = ''UPLOADED'' FROM MAKTPT_INBOUND (NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')= ''READY FOR UPLOAD'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' '")
	
	#Preventive Maintenance Starts
	
	#Equipment Validation
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAEAPM_INBOUND SET PROCESS_STATUS = ''ERROR'',INTEGRATION_STATUS=''Equipment ID not exists in Equipment Master table (MAEQUP). Please trigger the Ibase data from ECC to CPQ to resolve this error.'' FROM MAEAPM_INBOUND (NOLOCK) LEFT JOIN MAEQUP (NOLOCK) ON MAEAPM_INBOUND.EQUIPMENT_ID = MAEQUP.EQUIPMENT_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND MAEQUP.EQUIPMENT_ID IS NULL '")
	
	#Assembly Validation
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAEAPM_INBOUND SET PROCESS_STATUS = ''ERROR'',INTEGRATION_STATUS=''Assembly ID not exists in Equipment Master table (MAEQUP). Please trigger the Ibase data from ECC to CPQ to resolve this error.'' FROM MAEAPM_INBOUND (NOLOCK) LEFT JOIN MAEQUP (NOLOCK) ON MAEAPM_INBOUND.ASSEMBLY_ID = MAEQUP.EQUIPMENT_ID WHERE ISNULL(PROCESS_STATUS,'''')=''INPROGRESS'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND MAEQUP.EQUIPMENT_ID IS NULL '")
	
	#Status Change
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAEAPM_INBOUND SET PROCESS_STATUS = ''READY FOR UPLOAD'' FROM MAEAPM_INBOUND (NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')IN (''INPROGRESS'') AND TIMESTAMP = '"+str(timestamp_sessionid)+"' '")
	
	#PM Upload 
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " MAPMEV(ACTIVE,PM_NAME,PM_ID,MNTEVT_LEVEL,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,PM_RECORD_ID) SELECT  SUB_SGPMNT.* ,''"+ str(User.UserName)
	+ "'',''"+ str(User.Id)
	+ "'',GETDATE(),CONVERT(VARCHAR(1000),NEWID()) FROM (SELECT DISTINCT ''TRUE'' AS ACTIVE,PM_NAME,PM_NAME AS PM_ID,CASE WHEN PM_LEVEL =''Sched Maint'' THEN ''Scheduled Maintenance'' ELSE PM_LEVEL END AS MNTEVT_LEVEL FROM MAEAPM_INBOUND(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(PM_NAME,'''')<>'''' )SUB_SGPMNT LEFT JOIN MAPMEV (NOLOCK) ON SUB_SGPMNT.PM_NAME = MAPMEV.PM_NAME WHERE MAPMEV.PM_NAME IS NULL  '")
	
	#Kit Number Upload
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " MATKTN(KIT_ID,KIT_NAME,KIT_NUMBER,KIT_RECORD_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,TOOL_KIT_NUMBER_RECORD_ID) SELECT MAMKIT.KIT_ID,MAMKIT.KIT_NAME,SUB_MAMKIT.KIT_NUMBER,MAMKIT.KIT_RECORD_ID,''"+ str(User.UserName)
	+ "'',''"+ str(User.Id)
	+ "'',GETDATE(),CONVERT(VARCHAR(1000),NEWID()) FROM (SELECT DISTINCT KIT_ID as KIT_ID,KIT_NUMBER  FROM MAEAPM_INBOUND(NOLOCK) WHERE ISNULL(PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"')SUB_MAMKIT  JOIN MAMKIT (NOLOCK) ON SUB_MAMKIT.KIT_ID = MAMKIT.KIT_ID LEFT JOIN MATKTN (NOLOCK)M ON SUB_MAMKIT.KIT_ID = M.KIT_ID AND SUB_MAMKIT.KIT_NUMBER = M.KIT_NUMBER WHERE M.KIT_NUMBER IS NULL AND ISNULL(SUB_MAMKIT.KIT_NUMBER,'''')<>'''' '")

	#Equipment PM Upload
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter2.QUERY_CRITERIA_1)
	+ " MAEAPK FROM MAEAPK  JOIN MAEAPM_INBOUND ON MAEAPM_INBOUND.EQUIPMENT_ID = MAEAPK.EQUIPMENT_ID WHERE ISNULL(PROCESS_STATUS,'''')= ''READY FOR UPLOAD'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(INTEGRATION_STATUS,'''')='''' '")

	ERRLOG_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''TEMP_PROCESS_TKM'' ) BEGIN DROP TABLE TEMP_PROCESS_TKM END CREATE TABLE TEMP_PROCESS_TKM (SESSION_ID VARCHAR(100),PROCESS_STATUS VARCHAR(100),REV_ID INT) ' ")

	Check_flag1 = 1
	while Check_flag1 == 1:
		primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter.QUERY_CRITERIA_1)
			+ " TEMP_PROCESS_TKM (SESSION_ID)SELECT DISTINCT TOP 5000 MAEAPM_INBOUND.EQUIPMENT_ID FROM MAEAPM_INBOUND(NOLOCK) LEFT JOIN TEMP_PROCESS_TKM(NOLOCK) ON MAEAPM_INBOUND.EQUIPMENT_ID = TEMP_PROCESS_TKM.SESSION_ID WHERE ISNULL(MAEAPM_INBOUND.PROCESS_STATUS,'''')= ''READY FOR UPLOAD'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' AND ISNULL(INTEGRATION_STATUS,'''')='''' AND TEMP_PROCESS_TKM.SESSION_ID IS NULL  ' "
		)
		
		primaryQueryItems = SqlHelper.GetFirst(
				"select 'x' as a from TEMP_PROCESS_TKM(nolock)  where isnull(PROCESS_STATUS,'')='' "
			)

		if str(primaryQueryItems) != "None":
		
			primaryQueryItems = SqlHelper.GetFirst( 
			""
			+ str(Parameter.QUERY_CRITERIA_1)
			+ " MAEAPK (APPLICATION,ASSEMBLY_DESCRIPTION,ASSEMBLY_ID,ASSEMBLY_RECORD_ID,REGION,REGION_RECORD_ID,CUSTOMER_MARKETING_NAME,DEVICE_TYPE,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,KIT_ID,KIT_NAME,KIT_NUMBER,KIT_NUMBER_RECORD_ID,KIT_RECORD_ID,LOGISTICS_COST,PM_FREQUENCY,PM_ID,PM_NAME,PM_RECORD_ID,PROCESS_TYPE,SEEDSTOCK_COST,SERVICE_COMPLEXITY,TECHNOLOGY_NODE,HARDWARE_TYPE,TKM_COST_PER_EVENT,MODULE_ID,MODULE_NAME,MODULE_RECORD_ID,MNTEVT_LEVEL,PM_FREQUENCY_EDITABLE,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,EQUIPMENT_ASSEMBLY_PM_KIT_RECORD_ID) SELECT SUB_MAEAPK.*,''"+ str(User.UserName)
			+ "'',''"+ str(User.Id)
			+ "'',GETDATE(),CONVERT(VARCHAR(1000),NEWID())  FROM (SELECT DISTINCT MAEAPM_INBOUND.APPLICATION,MAEQUP.EQUIPMENT_DESCRIPTION AS ASSEMBLY_DESCRIPTION,MAEQUP.EQUIPMENT_ID AS ASSEMBLY_ID,MAEQUP.EQUIPMENT_RECORD_ID AS ASSEMBLY_RECORD_ID,SAREGN.REGION,SAREGN.REGION_RECORD_ID,MAEAPM_INBOUND.CUSTOMER_MARKETING_NAME,MAEAPM_INBOUND.DEVICE,MAEQUP.PAR_EQUIPMENT_DESCRIPTION AS EQUIPMENT_DESCRIPTION,MAEQUP.PAR_EQUIPMENT_ID AS EQUIPMENT_ID,MAEQUP.PAR_EQUIPMENT_RECORD_ID AS EQUIPMENT_RECORD_ID,MAMKIT.KIT_ID,MAMKIT.KIT_NAME,MATKTN.KIT_NUMBER,MATKTN.TOOL_KIT_NUMBER_RECORD_ID AS KIT_NUMBER_RECORD_ID,MAMKIT.KIT_RECORD_ID,CONVERT(FLOAT,MAEAPM_INBOUND.LOGISTICS_COST) AS LOGISTICS_COST,CONVERT(FLOAT,MAEAPM_INBOUND.PM_FREQUENCY) AS PM_FREQUENCY,MAPMEV.PM_ID,MAPMEV.PM_NAME,MAPMEV.PM_RECORD_ID,MAEAPM_INBOUND.PROCESS_TYPE,CONVERT(FLOAT,MAEAPM_INBOUND.SEEDSTOCK_COST) AS SEEDSTOCK_COST,MAEAPM_INBOUND.SERVICE_COMPLEXITY,MAEAPM_INBOUND.TECHNOLOGY_NODE,HW_TYPE,CONVERT(FLOAT,MAEAPM_INBOUND.TKM_COST_PER_EVENT) AS TKM_COST_PER_EVENT,ARCM_MODULE_ID,MACMDL.MODULE_NAME,MACMDL.COST_MODULE_RECORD_ID,MAPMEV.MNTEVT_LEVEL,RFP_EDIT FROM MAEAPM_INBOUND (NOLOCK) JOIN TEMP_PROCESS_TKM(NOLOCK) ON MAEAPM_INBOUND.EQUIPMENT_ID = TEMP_PROCESS_TKM.SESSION_ID JOIN MAEQUP (NOLOCK) ON MAEAPM_INBOUND.ASSEMBLY_ID = MAEQUP.EQUIPMENT_ID AND MAEAPM_INBOUND.EQUIPMENT_ID = MAEQUP.PAR_EQUIPMENT_ID LEFT JOIN MAMKIT (NOLOCK) ON MAEAPM_INBOUND.KIT_ID = MAMKIT.KIT_ID LEFT  JOIN MATKTN (NOLOCK) ON MAEAPM_INBOUND.KIT_ID = MATKTN.KIT_ID AND MAEAPM_INBOUND.KIT_NUMBER = MATKTN.KIT_NUMBER JOIN MAPMEV (NOLOCK) ON MAEAPM_INBOUND.PM_NAME = MAPMEV.PM_NAME AND CASE WHEN MAEAPM_INBOUND.PM_LEVEL=''Sched Maint'' THEN ''Scheduled Maintenance'' ELSE MAEAPM_INBOUND.PM_LEVEL END  = MAPMEV.MNTEVT_LEVEL LEFT JOIN MACMDL (NOLOCK)on  MAEAPM_INBOUND.ARCM_MODULE_ID = MACMDL.MODULE_ID LEFT JOIN SAREGN (NOLOCK) ON MAEAPM_INBOUND.REGION = SAREGN.REGION WHERE ISNULL(TEMP_PROCESS_TKM.PROCESS_STATUS,'''')='''' )SUB_MAEAPK   '")
		
			UpdateQuery = SqlHelper.GetFirst(
					"sp_executesql @T=N'update TEMP_PROCESS_TKM set process_status=''completed'' where isnulL(process_status,'''')='''' ' "
					)
		else:
			Check_flag1 = 0
	
	# Looping   
	ERRLOG_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''TEMP_PROCESS_TKM'' ) BEGIN DROP TABLE TEMP_PROCESS_TKM END CREATE TABLE TEMP_PROCESS_TKM (SESSION_ID VARCHAR(100),PROCESS_STATUS VARCHAR(100),REV_ID INT) ' ")
	
	TMP_TABLE = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''TEMP_TKM'' ) BEGIN DROP TABLE TEMP_TKM END CREATE TABLE TEMP_TKM (SESSION_ID VARCHAR(100),PROCESS_STATUS VARCHAR(100),REV_ID INT) ' ")
		
	primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter.QUERY_CRITERIA_1)
			+ " TEMP_TKM (SESSION_ID,REV_ID)SELECT DISTINCT SAQICA.qUOTE_ID,SAQICA.QTEREV_ID FROM SAQICA(NOLOCK) JOIN MAEAPM_INBOUND(NOLOCK) ON SAQICA.ASSEMBLY_ID = MAEAPM_INBOUND.ASSEMBLY_ID JOIN SAQRIT(NOLOCK) ON SAQICA.QUOTE_ID = SAQRIT.QUOTE_ID AND SAQICA.QTEREV_ID = SAQRIT.QTEREV_ID  WHERE TIMESTAMP = '"+str(timestamp_sessionid)+"' AND SAQRIT.STATUS=''CFG-ON HOLD TKM'' ' "
		)
	
	Check_flag1 = 1
	while Check_flag1 == 1:

		primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter.QUERY_CRITERIA_1)
			+ " TEMP_PROCESS_TKM (SESSION_ID,REV_ID)SELECT DISTINCT top 1 SAQTMT.QUOTE_ID,SAQTMT.QTEREV_ID FROM SAQTMT(NOLOCK) JOIN TEMP_TKM A ON A.SESSION_ID = SAQTMT.QUOTE_ID JOIN SAQRIT(NOLOCK) ON SAQTMT.QUOTE_ID = SAQRIT.QUOTE_ID AND SAQTMT.QTEREV_ID = SAQRIT.QTEREV_ID LEFT JOIN TEMP_PROCESS_TKM (NOLOCK) ON SAQTMT.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID WHERE SAQRIT.STATUS=''CFG-ON HOLD TKM'' AND TEMP_PROCESS_TKM.SESSION_ID IS NULL ' "
		)
		
		QUOTE_IDD = SqlHelper.GetFirst(
				"select session_id as QUOTE_ID from TEMP_PROCESS_TKM(nolock)  where isnull(PROCESS_STATUS,'')='' "
			)
			
		primaryQueryItems = SqlHelper.GetFirst(
				"select 'x' as a from TEMP_PROCESS_TKM(nolock)  where isnull(PROCESS_STATUS,'')='' "
			)

		if str(primaryQueryItems) != "None":
		
			#Kit Number Update in Quote Annualized
			primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ " A SET KIT_NUMBER = MAEAPM_INBOUND.KIT_NUMBER, STATUS = CASE WHEN ISNULL(A.STATUS,'''')=''CFG-ON HOLD TKM'' THEN ''ACQUIRED'' ELSE A.STATUS END FROM SAQICO(NOLOCK) A JOIN TEMP_PROCESS_TKM (NOLOCK) ON A.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND A.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQICA (NOLOCK) B ON A.QUOTE_ID = B.QUOTE_ID AND A.QTEREV_ID = B.QTEREV_ID AND A.LINE = B.LINE AND A.EQUIPMENT_ID = B.EQUIPMENT_ID JOIN SAQTRV(NOLOCK) C ON A.QUOTE_ID = C.QUOTE_ID AND A.QTEREV_ID = C.QTEREV_ID JOIN MAEAPM_INBOUND(NOLOCK) ON B.ASSEMBLY_ID = MAEAPM_INBOUND.ASSEMBLY_ID AND A.KIT_ID = MAEAPM_INBOUND.KIT_ID JOIN MATKTN(nOLOCK) ON MAEAPM_INBOUND.KIT_ID = MATKTN.KIT_ID AND MAEAPM_INBOUND.KIT_NUMBER = MATKTN.KIT_NUMBER  WHERE A.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND A.STATUS=''CFG-ON HOLD TKM'' AND ISNULL(MAEAPM_INBOUND.PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND ISNULL(MAEAPM_INBOUND.KIT_NUMBER,'''')<>''''  AND C.REVISION_STATUS IN (''CFG-ON HOLD COSTING'',''PRR-ON HOLD PRICING'',''PRI-PRICING'',''APR-APPROVAL PENDING'',''APR-RECALLED'',''APR-REJECTED'',''APR-APPROVED'',''APR-SUBMITTED TO CUSTOMER'',''OPD-PREPARING QUOTE DOCUMENTS'',''OPD-CUSTOMER REJECTED'',''OPD-CUSTOMER ACCEPTED'',''LGL-PREPARING LEGAL SOW'',''LGL-LEGAL SOW REJECTED'',''LGL-LEGAL SOW ACCEPTED'' )  '")
			
			#Kit Number Update in Quote Event
			primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ " A SET KIT_NUMBER = MAEAPM_INBOUND.KIT_NUMBER,KITNUMBER_RECORD_ID = TOOL_KIT_NUMBER_RECORD_ID FROM SAQGPA(NOLOCK) A JOIN TEMP_PROCESS_TKM (NOLOCK) ON A.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND A.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID  JOIN SAQTRV(NOLOCK) C ON A.QUOTE_ID = C.QUOTE_ID AND A.QTEREV_ID = C.QTEREV_ID JOIN MAEAPM_INBOUND(NOLOCK) ON A.ASSEMBLY_ID = MAEAPM_INBOUND.ASSEMBLY_ID AND A.KIT_ID = MAEAPM_INBOUND.KIT_ID AND A.PM_ID = MAEAPM_INBOUND.PM_NAME JOIN MATKTN(nOLOCK) ON MAEAPM_INBOUND.KIT_ID = MATKTN.KIT_ID AND MAEAPM_INBOUND.KIT_NUMBER = MATKTN.KIT_NUMBER WHERE A.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND ISNULL(MAEAPM_INBOUND.PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND ISNULL(MAEAPM_INBOUND.KIT_NUMBER,'''')<>'''' AND C.REVISION_STATUS IN (''CFG-ON HOLD COSTING'',''PRR-ON HOLD PRICING'',''PRI-PRICING'',''APR-APPROVAL PENDING'',''APR-RECALLED'',''APR-REJECTED'',''APR-APPROVED'',''APR-SUBMITTED TO CUSTOMER'',''OPD-PREPARING QUOTE DOCUMENTS'',''OPD-CUSTOMER REJECTED'',''OPD-CUSTOMER ACCEPTED'',''LGL-PREPARING LEGAL SOW'',''LGL-LEGAL SOW REJECTED'',''LGL-LEGAL SOW ACCEPTED'' ) '")

			primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ " A SET KIT_NUMBER = MAEAPM_INBOUND.KIT_NUMBER,KIT_NUMBER_RECORD_ID = TOOL_KIT_NUMBER_RECORD_ID FROM SAQSAP(NOLOCK) A JOIN TEMP_PROCESS_TKM (NOLOCK) ON A.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND A.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQTRV(NOLOCK) C ON A.QUOTE_ID = C.QUOTE_ID AND A.QTEREV_ID = C.QTEREV_ID JOIN MAEAPM_INBOUND(NOLOCK) ON A.ASSEMBLY_ID = MAEAPM_INBOUND.ASSEMBLY_ID AND A.KIT_ID = MAEAPM_INBOUND.KIT_ID AND A.PM_ID = MAEAPM_INBOUND.PM_NAME JOIN MATKTN(nOLOCK) ON MAEAPM_INBOUND.KIT_ID = MATKTN.KIT_ID AND MAEAPM_INBOUND.KIT_NUMBER = MATKTN.KIT_NUMBER WHERE A.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND ISNULL(MAEAPM_INBOUND.PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND ISNULL(MAEAPM_INBOUND.KIT_NUMBER,'''')<>'''' AND C.REVISION_STATUS IN (''CFG-ON HOLD COSTING'',''PRR-ON HOLD PRICING'',''PRI-PRICING'',''APR-APPROVAL PENDING'',''APR-RECALLED'',''APR-REJECTED'',''APR-APPROVED'',''APR-SUBMITTED TO CUSTOMER'',''OPD-PREPARING QUOTE DOCUMENTS'',''OPD-CUSTOMER REJECTED'',''OPD-CUSTOMER ACCEPTED'',''LGL-PREPARING LEGAL SOW'',''LGL-LEGAL SOW REJECTED'',''LGL-LEGAL SOW ACCEPTED'' ) '")

			#Kit Number Insert in Quote TKM
			primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter.QUERY_CRITERIA_1)
			+ " SAQRIP(PART_DESCRIPTION,PART_NUMBER,PART_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,QUANTITY,QUOTE_ID,QTEITM_RECORD_ID,QUOTE_RECORD_ID,QTEREV_ID,QTEREV_RECORD_ID,LINE,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,GREENBOOK_RECORD_ID,GREENBOOK,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,QUOTE_REVISION_ITEM_PRODUCT_LIST_RECORD_ID ) SELECT A.*,''"+ str(User.UserName)
				+ "'',''"+ str(User.Id)
				+ "'',GETDATE(),CONVERT(VARCHAR(100),NEWID()) FROM (SELECT DISTINCT SAP_DESCRIPTION,D.SAP_PART_NUMBER,MATERIAL_RECORD_ID,A.SERVICE_DESCRIPTION,A.SERVICE_ID,A.SERVICE_RECORD_ID,1 AS QUANTITY,A.QUOTE_ID,QTEITM_RECORD_ID,A.QUOTE_RECORD_ID,A.QTEREV_ID,A.QTEREV_RECORD_ID,A.LINE,A.FABLOCATION_ID,A.FABLOCATION_NAME,A.FABLOCATION_RECORD_ID,A.GREENBOOK_RECORD_ID,A.GREENBOOK FROM SAQRIT(NOLOCK) A JOIN TEMP_PROCESS_TKM (NOLOCK) ON A.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND A.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQRIO (NOLOCK) B ON A.QUOTE_ID = B.QUOTE_ID AND A.QTEREV_ID = B.QTEREV_ID AND A.LINE = B.LINE JOIN SAQTRV(NOLOCK) C ON A.QUOTE_ID = C.QUOTE_ID AND A.QTEREV_ID = C.QTEREV_ID JOIN MAEAPM_INBOUND(NOLOCK) ON B.ASSEMBLY_ID = MAEAPM_INBOUND.ASSEMBLY_ID AND A.KIT_ID = MAEAPM_INBOUND.KIT_ID JOIN MAMTRL(NOLOCK) D ON MAEAPM_INBOUND.KIT_NUMBER = D.SAP_PART_NUMBER WHERE A.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND A.STATUS=''CFG-ON HOLD TKM'' AND ISNULL(MAEAPM_INBOUND.PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND ISNULL(MAEAPM_INBOUND.KIT_NUMBER,'''')<>'''' AND A.SERVICE_ID IN (''Z0010'',''Z0128'') AND C.REVISION_STATUS IN (''CFG-ON HOLD COSTING'',''PRR-ON HOLD PRICING'',''PRI-PRICING'',''APR-APPROVAL PENDING'',''APR-RECALLED'',''APR-REJECTED'',''APR-APPROVED'',''APR-SUBMITTED TO CUSTOMER'',''OPD-PREPARING QUOTE DOCUMENTS'',''OPD-CUSTOMER REJECTED'',''OPD-CUSTOMER ACCEPTED'',''LGL-PREPARING LEGAL SOW'',''LGL-LEGAL SOW REJECTED'',''LGL-LEGAL SOW ACCEPTED'' ))A LEFT JOIN SAQRIP (NOLOCK) M ON A.QUOTE_ID = M.QUOTE_ID AND A.QTEREV_ID = M.QTEREV_ID AND A.LINE = M.LINE AND A.SAP_PART_NUMBER = M.PART_NUMBER WHERE M.QUOTE_ID IS NULL '")
			
			#Kit Number Insert in Quote PMSA
			primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter.QUERY_CRITERIA_1)
			+ " SAQRIP(PART_DESCRIPTION,PART_NUMBER,PART_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,QUANTITY,QUOTE_ID,QTEITM_RECORD_ID,QUOTE_RECORD_ID,QTEREV_ID,QTEREV_RECORD_ID,LINE,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,GREENBOOK_RECORD_ID,GREENBOOK,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,QUOTE_REVISION_ITEM_PRODUCT_LIST_RECORD_ID ) SELECT A.*,''"+ str(User.UserName)
				+ "'',''"+ str(User.Id)
				+ "'',GETDATE(),CONVERT(VARCHAR(100),NEWID()) FROM (SELECT DISTINCT SAP_DESCRIPTION,D.SAP_PART_NUMBER,MATERIAL_RECORD_ID,A.SERVICE_DESCRIPTION,A.SERVICE_ID,A.SERVICE_RECORD_ID,1 AS QUANTITY,A.QUOTE_ID,QTEITM_RECORD_ID,A.QUOTE_RECORD_ID,A.QTEREV_ID,A.QTEREV_RECORD_ID,A.LINE,A.FABLOCATION_ID,A.FABLOCATION_NAME,A.FABLOCATION_RECORD_ID,A.GREENBOOK_RECORD_ID,A.GREENBOOK FROM SAQRIT(NOLOCK) A JOIN TEMP_PROCESS_TKM (NOLOCK) ON A.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND A.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQRIO (NOLOCK) B ON A.QUOTE_ID = B.QUOTE_ID AND A.QTEREV_ID = B.QTEREV_ID AND A.LINE = B.LINE JOIN SAQTRV(NOLOCK) C ON A.QUOTE_ID = C.QUOTE_ID AND A.QTEREV_ID = C.QTEREV_ID JOIN MAEAPM_INBOUND(NOLOCK) ON B.ASSEMBLY_ID = MAEAPM_INBOUND.ASSEMBLY_ID AND A.PM_ID = MAEAPM_INBOUND.PM_NAME AND A.KIT_ID = MAEAPM_INBOUND.KIT_ID JOIN MAMTRL(NOLOCK) D ON MAEAPM_INBOUND.KIT_NUMBER = D.SAP_PART_NUMBER WHERE A.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND A.STATUS=''CFG-ON HOLD TKM'' AND ISNULL(MAEAPM_INBOUND.PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND ISNULL(MAEAPM_INBOUND.KIT_NUMBER,'''')<>'''' AND A.SERVICE_ID IN (''Z0009'') AND C.REVISION_STATUS IN (''CFG-ON HOLD COSTING'',''PRR-ON HOLD PRICING'',''PRI-PRICING'',''APR-APPROVAL PENDING'',''APR-RECALLED'',''APR-REJECTED'',''APR-APPROVED'',''APR-SUBMITTED TO CUSTOMER'',''OPD-PREPARING QUOTE DOCUMENTS'',''OPD-CUSTOMER REJECTED'',''OPD-CUSTOMER ACCEPTED'',''LGL-PREPARING LEGAL SOW'',''LGL-LEGAL SOW REJECTED'',''LGL-LEGAL SOW ACCEPTED'' ))A LEFT JOIN SAQRIP (NOLOCK) M ON A.QUOTE_ID = M.QUOTE_ID AND A.QTEREV_ID = M.QTEREV_ID AND A.LINE = M.LINE AND A.SAP_PART_NUMBER = M.PART_NUMBER WHERE M.QUOTE_ID IS NULL '")
				
			#Kit Number Insert for Tool Based
			primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter.QUERY_CRITERIA_1)
			+ " SAQRIP(PART_DESCRIPTION,PART_NUMBER,PART_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,QUANTITY,QUOTE_ID,QTEITM_RECORD_ID,QUOTE_RECORD_ID,QTEREV_ID,QTEREV_RECORD_ID,LINE,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,GREENBOOK_RECORD_ID,GREENBOOK,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,CPQTABLEENTRYDATEADDED,QUOTE_REVISION_ITEM_PRODUCT_LIST_RECORD_ID ) SELECT A.*,''"+ str(User.UserName)
				+ "'',''"+ str(User.Id)
				+ "'',GETDATE(),CONVERT(VARCHAR(100),NEWID()) FROM (SELECT DISTINCT SAP_DESCRIPTION,D.SAP_PART_NUMBER,MATERIAL_RECORD_ID,A.SERVICE_DESCRIPTION,A.SERVICE_ID,A.SERVICE_RECORD_ID,1 AS QUANTITY,A.QUOTE_ID,QTEITM_RECORD_ID,A.QUOTE_RECORD_ID,A.QTEREV_ID,A.QTEREV_RECORD_ID,A.LINE,A.FABLOCATION_ID,A.FABLOCATION_NAME,A.FABLOCATION_RECORD_ID,A.GREENBOOK_RECORD_ID,A.GREENBOOK FROM SAQRIT(NOLOCK) A JOIN TEMP_PROCESS_TKM (NOLOCK) ON A.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND A.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQRIO (NOLOCK) B ON A.QUOTE_ID = B.QUOTE_ID AND A.QTEREV_ID = B.QTEREV_ID AND A.LINE = B.LINE JOIN SAQTRV(NOLOCK) C ON A.QUOTE_ID = C.QUOTE_ID AND A.QTEREV_ID = C.QTEREV_ID JOIN SAQSAP (NOLOCK)E ON B.QUOTE_ID = E.QUOTE_ID AND B.QTEREV_ID = E.QTEREV_ID AND B.EQUIPMENT_ID = E.EQUIPMENT_ID JOIN MAEAPM_INBOUND(NOLOCK) ON E.ASSEMBLY_ID = MAEAPM_INBOUND.ASSEMBLY_ID AND E.KIT_ID = MAEAPM_INBOUND.KIT_ID AND E.PM_ID = MAEAPM_INBOUND.PM_NAME AND E.KIT_NUMBER = MAEAPM_INBOUND.KIT_NUMBER JOIN MAMTRL(NOLOCK) D ON MAEAPM_INBOUND.KIT_NUMBER = D.SAP_PART_NUMBER WHERE A.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND A.STATUS=''CFG-ON HOLD TKM'' AND ISNULL(MAEAPM_INBOUND.PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND ISNULL(MAEAPM_INBOUND.KIT_NUMBER,'''')<>'''' AND C.REVISION_STATUS IN (''CFG-ON HOLD COSTING'',''PRR-ON HOLD PRICING'',''PRI-PRICING'',''APR-APPROVAL PENDING'',''APR-RECALLED'',''APR-REJECTED'',''APR-APPROVED'',''APR-SUBMITTED TO CUSTOMER'',''OPD-PREPARING QUOTE DOCUMENTS'',''OPD-CUSTOMER REJECTED'',''OPD-CUSTOMER ACCEPTED'',''LGL-PREPARING LEGAL SOW'',''LGL-LEGAL SOW REJECTED'',''LGL-LEGAL SOW ACCEPTED'' ))A LEFT JOIN SAQRIP (NOLOCK) M ON A.QUOTE_ID = M.QUOTE_ID AND A.QTEREV_ID = M.QTEREV_ID AND A.LINE = M.LINE AND A.SAP_PART_NUMBER = M.PART_NUMBER WHERE M.QUOTE_ID IS NULL '")
	
			#Status - On Hold TKM
			primaryQueryItems = SqlHelper.GetFirst(
				""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  SAQICO SET STATUS=''CFG-ON HOLD TKM'' FROM SAQICO (NOLOCK) JOIN TEMP_PROCESS_TKM (NOLOCK) ON SAQICO.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND SAQICO.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQICA(NOLOCK) ON SAQICO.QUOTE_ID = SAQICA.QUOTE_ID AND SAQICO.QTEREV_ID = SAQICA.QTEREV_ID AND SAQICO.LINE = SAQICA.LINE AND SAQICO.EQUIPMENT_ID = SAQICA.EQUIPMENT_ID JOIN SAQRIT(NOLOCK) ON SAQICO.QUOTE_ID = SAQRIT.QUOTE_ID AND SAQICO.QTEREV_ID = SAQRIT.QTEREV_ID AND SAQICO.LINE = SAQRIT.LINE JOIN SAQGPA (NOLOCK) ON SAQICO.QUOTE_ID = SAQGPA.QUOTE_ID AND SAQICO.QTEREV_ID = SAQGPA.QTEREV_ID AND SAQICO.SERVICE_ID = SAQGPA.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQGPA.EQUIPMENT_ID AND SAQICA.ASSEMBLY_ID = SAQGPA.ASSEMBLY_ID AND SAQRIT.KIT_ID = SAQGPA.KIT_ID JOIN MAEAPM_INBOUND(NOLOCK) ON SAQGPA.EQUIPMENT_ID = MAEAPM_INBOUND.EQUIPMENT_ID AND SAQGPA.ASSEMBLY_ID = MAEAPM_INBOUND.ASSEMBLY_ID WHERE SAQICO.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND  ISNULL(SAQICO.STATUS,'''') NOT IN (''PRR-ON HOLD PRICING'',''CFG-ON HOLD - COSTING'',''ASSEMBLY IS MISSING'',''OFFLINE PRICING'') AND ISNULL(SAQGPA.KIT_ID,'''')<>'''' AND ISNULL(SAQGPA.KIT_NUMBER,'''')='''' AND ISNULL(TEMP_PROCESS_TKM.PROCESS_STATUS,'''')=''''  '")

			primaryQueryItems = SqlHelper.GetFirst(
				""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  SAQICO SET STATUS=''ACQUIRED'' FROM SAQICO (NOLOCK) JOIN TEMP_PROCESS_TKM (NOLOCK) ON SAQICO.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND SAQICO.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQICA(NOLOCK) ON SAQICO.QUOTE_ID = SAQICA.QUOTE_ID AND SAQICO.QTEREV_ID = SAQICA.QTEREV_ID AND SAQICO.LINE = SAQICA.LINE AND SAQICO.EQUIPMENT_ID = SAQICA.EQUIPMENT_ID JOIN SAQRIT(NOLOCK) ON SAQICO.QUOTE_ID = SAQRIT.QUOTE_ID AND SAQICO.QTEREV_ID = SAQRIT.QTEREV_ID AND SAQICO.LINE = SAQRIT.LINE JOIN SAQGPA (NOLOCK) ON SAQICO.QUOTE_ID = SAQGPA.QUOTE_ID AND SAQICO.QTEREV_ID = SAQGPA.QTEREV_ID AND SAQICO.SERVICE_ID = SAQGPA.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQGPA.EQUIPMENT_ID AND SAQICA.ASSEMBLY_ID = SAQGPA.ASSEMBLY_ID AND SAQRIT.KIT_ID = SAQGPA.KIT_ID JOIN MAEAPM_INBOUND(NOLOCK) ON SAQGPA.EQUIPMENT_ID = MAEAPM_INBOUND.EQUIPMENT_ID AND SAQGPA.ASSEMBLY_ID = MAEAPM_INBOUND.ASSEMBLY_ID WHERE SAQICO.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND  ISNULL(SAQICO.STATUS,'''') NOT IN (''PRR-ON HOLD PRICING'',''CFG-ON HOLD - COSTING'',''ASSEMBLY IS MISSING'',''OFFLINE PRICING'') AND ISNULL(SAQGPA.KIT_ID,'''')<>'''' AND ISNULL(SAQGPA.KIT_NUMBER,'''')<>'''' AND ISNULL(TEMP_PROCESS_TKM.PROCESS_STATUS,'''')='''' '")

			#Status - On Hold TKM
			primaryQueryItems = SqlHelper.GetFirst(
				""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  SAQICO SET STATUS=''CFG-ON HOLD TKM'' FROM SAQICO (NOLOCK) JOIN TEMP_PROCESS_TKM (NOLOCK) ON SAQICO.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND SAQICO.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQSAP (NOLOCK) ON SAQICO.QUOTE_ID = SAQSAP.QUOTE_ID AND SAQICO.QTEREV_ID = SAQSAP.QTEREV_ID AND SAQICO.SERVICE_ID = SAQSAP.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQSAP.EQUIPMENT_ID WHERE SAQICO.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND  ISNULL(SAQICO.STATUS,'''') NOT IN (''PRR-ON HOLD PRICING'',''CFG-ON HOLD - COSTING'',''ASSEMBLY IS MISSING'',''OFFLINE PRICING'') AND ISNULL(SAQSAP.KIT_ID,'''')<>'''' AND ISNULL(SAQSAP.KIT_NUMBER,'''')='''' AND ISNULL(TEMP_PROCESS_TKM.PROCESS_STATUS,'''')='''' '")

			primaryQueryItems = SqlHelper.GetFirst(
				""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  SAQICO SET STATUS=''ACQUIRED'' FROM SAQICO (NOLOCK) JOIN TEMP_PROCESS_TKM (NOLOCK) ON SAQICO.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND SAQICO.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQSAP (NOLOCK) ON SAQICO.QUOTE_ID = SAQSAP.QUOTE_ID AND SAQICO.QTEREV_ID = SAQSAP.QTEREV_ID AND SAQICO.SERVICE_ID = SAQSAP.SERVICE_ID AND SAQICO.EQUIPMENT_ID = SAQSAP.EQUIPMENT_ID  WHERE SAQICO.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND  ISNULL(SAQICO.STATUS,'''') NOT IN (''PRR-ON HOLD PRICING'',''CFG-ON HOLD - COSTING'',''ASSEMBLY IS MISSING'',''OFFLINE PRICING'') AND ISNULL(SAQSAP.KIT_ID,'''')<>'''' AND ISNULL(SAQSAP.KIT_NUMBER,'''')<>'''' AND ISNULL(TEMP_PROCESS_TKM.PROCESS_STATUS,'''')='''' '")
			
			primaryQueryItems = SqlHelper.GetFirst(
				""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  SAQRIT SET STATUS=''ACQUIRED'' FROM SAQICO (NOLOCK) JOIN TEMP_PROCESS_TKM (NOLOCK) ON SAQICO.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND SAQICO.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQRIT (NOLOCK) ON SAQRIT.QUOTE_ID = SAQICO.QUOTE_ID AND SAQRIT.QTEREV_ID = SAQICO.QTEREV_ID AND SAQICO.LINE = SAQRIT.LINE WHERE SAQRIT.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND ISNULL(SAQICO.KIT_NUMBER,'''')<>''''  AND SAQRIT.STATUS=''CFG-ON HOLD TKM'' AND ISNULL(TEMP_PROCESS_TKM.PROCESS_STATUS,'''')=''''  '")

			primaryQueryItems = SqlHelper.GetFirst(
				""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  SAQRIT SET STATUS=''ACQUIRED'' FROM SAQICO (NOLOCK) JOIN TEMP_PROCESS_TKM (NOLOCK) ON SAQICO.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND SAQICO.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID JOIN SAQRIT (NOLOCK) ON SAQRIT.QUOTE_ID = SAQICO.QUOTE_ID AND SAQRIT.QTEREV_ID = SAQICO.QTEREV_ID AND SAQICO.LINE = SAQRIT.LINE WHERE SAQRIT.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND  ISNULL(SAQICO.STATUS,'''') NOT IN (''PRR-ON HOLD PRICING'',''CFG-ON HOLD - COSTING'',''ASSEMBLY IS MISSING'',''OFFLINE PRICING'') AND ISNULL(SAQICO.KIT_NUMBER,'''')<>'''' AND ISNULL(TEMP_PROCESS_TKM.PROCESS_STATUS,'''')='''' '")

			#Status Item - On Hold TKM
			primaryQueryItems = SqlHelper.GetFirst(
				""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  SAQITM SET STATUS=''CFG-ON HOLD TKM'' FROM SAQRIT SAQITM (NOLOCK) WHERE QUOTE_REVISION_CONTRACT_ITEM_ID IN (SELECT SAQICO.QTEITM_RECORD_ID FROM SAQICO (NOLOCK) JOIN TEMP_PROCESS_TKM (NOLOCK) ON SAQICO.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND SAQICO.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID WHERE SAQICO.STATUS=''CFG-ON HOLD TKM'' AND ISNULL(TEMP_PROCESS_TKM.PROCESS_STATUS,'''')='''' AND SAQICO.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' ) AND ISNULL(STATUS,'''') NOT IN (''CFG-ON HOLD - COSTING'',''PRR-ON HOLD PRICING'',''OFFLINE PRICING'')  '")
			
			primaryQueryItems = SqlHelper.GetFirst(
								""
							+ str(Parameter1.QUERY_CRITERIA_1)
							+ "  SAQIBP SET STATUS=SAQRIT.STATUS FROM SAQIBP (NOLOCK) JOIN SAQRIT (NOLOCK) ON SAQIBP.QUOTE_ID = SAQRIT.QUOTE_ID AND SAQIBP.QTEREV_ID = SAQRIT.QTEREV_ID AND SAQIBP.LINE = SAQRIT.LINE JOIN TEMP_PROCESS_TKM (NOLOCK) ON SAQRIT.QUOTE_ID = TEMP_PROCESS_TKM.SESSION_ID AND SAQRIT.QTEREV_ID = TEMP_PROCESS_TKM.REV_ID WHERE SAQRIT.QUOTE_ID = ''"+str(QUOTE_IDD.QUOTE_ID)+"'' AND ISNULL(SAQRIT.STATUS,'''')<>ISNULL(SAQIBP.STATUS,'''') AND ISNULL(TEMP_PROCESS_TKM.PROCESS_STATUS,'''')='''' '")
			
			UpdateQuery = SqlHelper.GetFirst(
						"sp_executesql @T=N'update TEMP_PROCESS_TKM set process_status=''completed'' where isnulL(process_status,'''')='''' ' "
						)
		else:
			Check_flag1 = 0

	DeleteQuery = SqlHelper.GetFirst(
					"sp_executesql @T=N'Delete from TEMP_PROCESS_TKM Where process_status=''completed'' ' "
					)

	ERRLOG_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''TEMP_PROCESS_TKM'' ) BEGIN DROP TABLE TEMP_PROCESS_TKM END ' ")
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAEAPM_INBOUND SET PROCESS_STATUS = ''UPLOADED'' FROM MAEAPM_INBOUND (NOLOCK)  WHERE ISNULL(PROCESS_STATUS,'''')= ''READY FOR UPLOAD'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' '")
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter2.QUERY_CRITERIA_1)
	+ "   FROM MAEAPM_INBOUND  WHERE ISNULL(PROCESS_STATUS,'''')= ''UPLOADED'' AND TIMESTAMP = '"+str(timestamp_sessionid)+"' '")

	#Mail system
	Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #bd{color : 'black';} </style></head><body id = 'bd'>"

	Table_start = "<p>Hi Team,<br><br>KIT BOM DATA AND PM BOM DATA SUCCESSFULLY UPLOADED</p><br>"

	Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"
	Table_info = ""     

	Error_Info = Header + Table_start + Table_info + Table_End

	LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

	# Create new SmtpClient object
	mailClient = SmtpClient()

	# Set the host and port (eg. smtp.gmail.com)
	mailClient.Host = "smtp.gmail.com"
	mailClient.Port = 587
	mailClient.EnableSsl = "true"

	# Setup NetworkCredential
	mailCred = NetworkCredential()
	mailCred.UserName = str(LOGIN_CRE.Username)
	mailCred.Password = str(LOGIN_CRE.Password)
	mailClient.Credentials = mailCred

	# Create two mail adresses, one for send from and the another for recipient
	toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
	fromEmail = MailAddress("INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM")

	# Create new MailMessage object
	msg = MailMessage(fromEmail, toEmail)

	# Set message subject and body
	msg.Subject = "SC KIT DATA - Notification(P-Tenant)"
	msg.IsBodyHtml = True
	msg.Body = Error_Info

	# CC Emails 	
	copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
	msg.CC.Add(copyEmail4)

	# Send the message
	mailClient.Send(msg) 
	
except:
	#Status Empty in SYINPL
	StatusUpdateQuery = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  SYINPL SET STATUS = ''''FROM SYINPL (NOLOCK) WHERE STATUS = ''INPROGRESS'' ' ")


	Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;} #bd{color : 'black';} </style></head><body id = 'bd'>"

	Table_start = "<p>Hi Team,<br><br>KIT BOM script having follwing Error in Line number "+str(sys.exc_info()[-1].tb_lineno)+".<br><br>"+str(sys.exc_info()[1])+"</p><br>"
	
	Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"
	Table_info = ""     

	Error_Info = Header + Table_start + Table_info + Table_End

	LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

	# Create new SmtpClient object
	mailClient = SmtpClient()

	# Set the host and port (eg. smtp.gmail.com)
	mailClient.Host = "smtp.gmail.com"
	mailClient.Port = 587
	mailClient.EnableSsl = "true"

	# Setup NetworkCredential
	mailCred = NetworkCredential()
	mailCred.UserName = str(LOGIN_CRE.Username)
	mailCred.Password = str(LOGIN_CRE.Password)
	mailClient.Credentials = mailCred

	# Create two mail adresses, one for send from and the another for recipient
	toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
	fromEmail = MailAddress("INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM")

	# Create new MailMessage object
	msg = MailMessage(fromEmail, toEmail)

	# Set message subject and body
	msg.Subject = "KIT BOM - Error Notification(P-Tenant)"
	msg.IsBodyHtml = True
	msg.Body = Error_Info

	# CC Emails 	
	copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
	msg.CC.Add(copyEmail4)
	
	# Send the message
	mailClient.Send(msg) 
	
	
	Log.Info("MAPOSTTKMU cpqtbleentid---->:" + str(cpqtbleentid))	
	Log.Info("MAPOSTTKMU ERROR---->:" + str(sys.exc_info()[1]))
	Log.Info("MAPOSTTKMU ERROR LINE NO---->:" + str(sys.exc_info()[-1].tb_lineno))
	ApiResponse = ApiResponseFactory.JsonResponse({"Response": [{"Status": "400", "Message": str(sys.exc_info()[1])}]})