# =========================================================================================================================================
#   __script_name : MAPOSTBULK.PY(AMAT)
#   __script_description : THIS SCRIPT IS USED TO UPDATE MATERIALS FROM STAGING TABLE TO THE MAIN TABLE
#   __primary_author__ : SURESH MUNIYANDI
#   __create_date :
#   © BOSTON HARBOR TECHNOLOGY LLC - ALL RIGHTS RESERVED
# ==========================================================================================================================================
import sys
import datetime
import clr

clr.AddReference("System.Net")
from System.Net import CookieContainer, NetworkCredential, Mail
from System.Net.Mail import SmtpClient, MailAddress, Attachment, MailMessage

try:	

	sessionid = SqlHelper.GetFirst("SELECT NEWID() AS A")
	timestamp_sessionid = "'" + str(sessionid.A) + "'"

	Parameter = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'SELECT' ")
	Parameter1 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'UPD' ")
	Parameter2 = SqlHelper.GetFirst("SELECT QUERY_CRITERIA_1 FROM SYDBQS (NOLOCK) WHERE QUERY_NAME = 'DEL' ")

	today = datetime.datetime.now()
	Modi_date = today.strftime("%m/%d/%Y %H:%M:%S %p")
	
	UpdateTable1=SqlHelper.GetFirst("sp_executesql @T=N'update mamtrl_inbound set sap_part_number =  convert(varchar(100),convert(bigint,sap_part_number)) where isnumeric(sap_part_number)=1 and sap_part_number not like ''%.%'' '")

	UpdateTable1=SqlHelper.GetFirst("sp_executesql @T=N'update mamsop_inbound set sap_part_number =  convert(varchar(100),convert(bigint,sap_part_number)) where isnumeric(sap_part_number)=1 and sap_part_number not like ''%.%'' '")

	UpdateTable1=SqlHelper.GetFirst("sp_executesql @T=N'update mamact_inbound set sap_part_number =  convert(varchar(100),convert(bigint,sap_part_number)) where isnumeric(sap_part_number)=1 and sap_part_number not like ''%.%'' '")

	UpdateTable1=SqlHelper.GetFirst("sp_executesql @T=N'update a set sap_part_number = b.sap_part_number,division_id = b.division_id from mamsop_inbound a join mamtrl_inbound b on a.session_id = b.session_id  '")
	
	UpdateTable1=SqlHelper.GetFirst("sp_executesql @T=N'update mamsop_inbound set valid_from=null where valid_from=''00000000'' '")

	S=SqlHelper.GetFirst("sp_executesql @T=N'update mamtrl_inbound set SAP_DESCRIPTION= replace(SAP_DESCRIPTION,''&#39;'',''''''''  )  ' ")
	S=SqlHelper.GetFirst("sp_executesql @T=N'update mamtrl_inbound set SAP_DESCRIPTION= replace(SAP_DESCRIPTION,''&#92;'',''\\''  )  ' ")
	S=SqlHelper.GetFirst("sp_executesql @T=N'update mamtrl_inbound set SAP_DESCRIPTION= replace(SAP_DESCRIPTION,''&#34;'',''\"''  )  ' ")

	
	S = SqlHelper.GetFirst("sp_executesql @T=N'update mamtrl_inbound set unit_of_measure = CASE WHEN UNIT_OF_MEASURE = ''P1'' THEN ''%'' WHEN UNIT_OF_MEASURE = ''DAY'' THEN ''10'' WHEN UNIT_OF_MEASURE = ''2M'' THEN ''2M'' WHEN UNIT_OF_MEASURE = ''2X'' THEN ''2X'' WHEN UNIT_OF_MEASURE = ''4G'' THEN ''4G'' WHEN  UNIT_OF_MEASURE = ''4O'' THEN ''4O'' WHEN UNIT_OF_MEASURE = ''4T'' THEN ''4T'' WHEN UNIT_OF_MEASURE = ''AMP'' THEN ''A'' WHEN UNIT_OF_MEASURE = ''A87'' THEN ''A87'' WHEN UNIT_OF_MEASURE = ''A93'' THEN ''A93'' WHEN UNIT_OF_MEASURE = ''AGG'' THEN ''AGG'' WHEN UNIT_OF_MEASURE = ''B34'' THEN ''B34'' WHEN UNIT_OF_MEASURE = ''B45'' THEN ''B45'' WHEN UNIT_OF_MEASURE = ''B47'' THEN ''B47'' WHEN UNIT_OF_MEASURE = ''B73'' THEN ''B73'' WHEN UNIT_OF_MEASURE = ''B75'' THEN ''B75'' WHEN UNIT_OF_MEASURE = ''B78'' THEN ''B78'' WHEN UNIT_OF_MEASURE = ''B84'' THEN ''B84'' WHEN UNIT_OF_MEASURE = ''BG'' THEN ''BAG'' WHEN UNIT_OF_MEASURE = ''BAR'' THEN ''BAR'' WHEN UNIT_OF_MEASURE = ''BBL'' THEN ''BBL'' WHEN UNIT_OF_MEASURE = ''BD'' THEN ''BD'' WHEN UNIT_OF_MEASURE = ''BAG'' THEN ''BG'' WHEN UNIT_OF_MEASURE = ''BK'' THEN ''BK'' WHEN UNIT_OF_MEASURE = ''BO'' THEN ''BOT'' WHEN UNIT_OF_MEASURE = ''C10'' THEN ''C10'' WHEN UNIT_OF_MEASURE = ''C36'' THEN ''C36'' WHEN UNIT_OF_MEASURE = ''C38'' THEN ''C38'' WHEN UNIT_OF_MEASURE = ''C39'' THEN ''C39'' WHEN UNIT_OF_MEASURE = ''2J'' THEN ''C3S'' WHEN UNIT_OF_MEASURE = ''C41'' THEN ''C41'' WHEN UNIT_OF_MEASURE = ''C56'' THEN ''C56'' WHEN UNIT_OF_MEASURE = ''CAR'' THEN ''CAR'' WHEN UNIT_OF_MEASURE = ''CMQ'' THEN ''CCM'' WHEN UNIT_OF_MEASURE = ''CDL'' THEN ''CD'' WHEN UNIT_OF_MEASURE = ''DMQ'' THEN ''CDM'' WHEN UNIT_OF_MEASURE = ''CF'' THEN ''CF'' WHEN UNIT_OF_MEASURE = ''CKG'' THEN ''CKG'' WHEN UNIT_OF_MEASURE = ''CMT'' THEN ''CM'' WHEN UNIT_OF_MEASURE = ''CMK'' THEN ''CM2'' WHEN UNIT_OF_MEASURE = ''CN'' THEN ''CN'' WHEN UNIT_OF_MEASURE = ''CS'' THEN ''CS'' WHEN UNIT_OF_MEASURE = ''CT'' THEN ''CT'' WHEN UNIT_OF_MEASURE = ''CYL'' THEN ''CYL'' WHEN UNIT_OF_MEASURE = ''D10'' THEN ''D10'' WHEN UNIT_OF_MEASURE = ''D41'' THEN ''D41'' WHEN UNIT_OF_MEASURE = ''D46'' THEN ''D46'' WHEN UNIT_OF_MEASURE = ''DD'' THEN ''DEG'' WHEN UNIT_OF_MEASURE = ''DMT'' THEN ''DM'' WHEN UNIT_OF_MEASURE = ''DOZ'' THEN ''DOZ'' WHEN UNIT_OF_MEASURE = ''DPC'' THEN ''DPC'' WHEN UNIT_OF_MEASURE = ''DPR'' THEN ''DPR'' WHEN UNIT_OF_MEASURE = ''DR'' THEN ''DR'' WHEN UNIT_OF_MEASURE = ''DZ'' THEN ''DZ'' WHEN UNIT_OF_MEASURE = ''EA'' THEN ''EA'' WHEN UNIT_OF_MEASURE = ''FAR'' THEN ''F'' WHEN UNIT_OF_MEASURE = ''FAH'' THEN ''FA'' WHEN UNIT_OF_MEASURE = ''FBM'' THEN ''FBM'' WHEN UNIT_OF_MEASURE = ''FOT'' THEN ''FT'' WHEN UNIT_OF_MEASURE = ''FTK'' THEN ''FT2'' WHEN UNIT_OF_MEASURE = ''FTQ'' THEN ''FT3'' WHEN UNIT_OF_MEASURE = ''FTC'' THEN ''FTC'' WHEN UNIT_OF_MEASURE = ''GRM'' THEN ''G'' WHEN UNIT_OF_MEASURE = ''GAL'' THEN ''GA'' WHEN UNIT_OF_MEASURE = ''GBQ'' THEN ''GBQ'' WHEN UNIT_OF_MEASURE = ''CEL'' THEN ''GC'' WHEN UNIT_OF_MEASURE = ''GL'' THEN ''GL'' WHEN UNIT_OF_MEASURE = ''GLI'' THEN ''GLI'' WHEN UNIT_OF_MEASURE = ''GLL'' THEN ''GLL'' WHEN UNIT_OF_MEASURE = ''GQ'' THEN ''GQ'' WHEN UNIT_OF_MEASURE = ''GR'' THEN ''GR'' WHEN UNIT_OF_MEASURE = ''GRO'' THEN ''GRO'' WHEN UNIT_OF_MEASURE = ''GS'' THEN ''GS''  WHEN UNIT_OF_MEASURE = ''HR'' THEN ''H'' WHEN UNIT_OF_MEASURE = ''HLT'' THEN ''HL'' WHEN UNIT_OF_MEASURE = ''A97'' THEN ''HPA'' WHEN UNIT_OF_MEASURE = ''HUN'' THEN ''HUN'' WHEN UNIT_OF_MEASURE = ''HTZ'' THEN ''HZ'' WHEN UNIT_OF_MEASURE = ''INH'' THEN ''IN'' WHEN UNIT_OF_MEASURE = ''2'' THEN ''IN2'' WHEN UNIT_OF_MEASURE = ''INQ'' THEN ''IN3'' WHEN UNIT_OF_MEASURE = ''IRG'' THEN ''IRG'' WHEN UNIT_OF_MEASURE = ''JOU'' THEN ''J'' WHEN UNIT_OF_MEASURE = ''ANN'' THEN ''JHR'' WHEN UNIT_OF_MEASURE = ''B11'' THEN ''JKK'' WHEN UNIT_OF_MEASURE = ''JWL'' THEN ''JWL'' WHEN UNIT_OF_MEASURE = ''KEL'' THEN ''K'' WHEN UNIT_OF_MEASURE = ''B22'' THEN ''KA'' WHEN UNIT_OF_MEASURE = ''CA'' THEN ''KAN'' WHEN UNIT_OF_MEASURE = ''BX'' THEN ''KAR'' WHEN UNIT_OF_MEASURE = ''KGM'' THEN ''KG''  WHEN UNIT_OF_MEASURE = ''28'' THEN ''KGF'' WHEN UNIT_OF_MEASURE = ''KGS'' THEN ''KGS'' WHEN UNIT_OF_MEASURE = ''KMQ'' THEN ''KGV''  WHEN UNIT_OF_MEASURE = ''KHZ'' THEN ''KHZ''  WHEN UNIT_OF_MEASURE = ''CRT'' THEN ''KI'' WHEN UNIT_OF_MEASURE = ''KIT'' THEN ''KIT'' WHEN UNIT_OF_MEASURE = ''KJO'' THEN ''KJ'' WHEN UNIT_OF_MEASURE = ''KMT'' THEN ''KM'' WHEN UNIT_OF_MEASURE = ''KM3'' THEN ''KM3'' WHEN UNIT_OF_MEASURE = ''KMH'' THEN ''KMH'' WHEN UNIT_OF_MEASURE = ''B49'' THEN ''KOH'' WHEN UNIT_OF_MEASURE = ''KPA'' THEN ''KPA'' WHEN UNIT_OF_MEASURE = ''PA'' THEN ''KT'' WHEN UNIT_OF_MEASURE = ''KVT'' THEN ''KV'' WHEN UNIT_OF_MEASURE = ''KVA'' THEN ''KVA'' WHEN UNIT_OF_MEASURE = ''KWT'' THEN ''KW'' WHEN UNIT_OF_MEASURE = ''KWH'' THEN ''KWH'' WHEN UNIT_OF_MEASURE = ''LTR'' THEN ''L'' WHEN UNIT_OF_MEASURE = ''L2'' THEN ''L2'' WHEN UNIT_OF_MEASURE = ''LBR'' THEN ''LB'' WHEN UNIT_OF_MEASURE = ''C62'' THEN ''LE'' WHEN UNIT_OF_MEASURE = ''LNM'' THEN ''LNM'' WHEN UNIT_OF_MEASURE = ''LOT'' THEN ''LOT''  WHEN UNIT_OF_MEASURE = ''MTR'' THEN ''M'' WHEN UNIT_OF_MEASURE = ''MTS'' THEN ''M/S'' WHEN UNIT_OF_MEASURE = ''MTK'' THEN ''M2'' WHEN UNIT_OF_MEASURE = ''S4'' THEN ''M2S'' WHEN UNIT_OF_MEASURE = ''MTQ'' THEN ''M3'' WHEN UNIT_OF_MEASURE = ''MQS'' THEN ''M3S'' WHEN UNIT_OF_MEASURE = ''4K'' THEN ''MA'' WHEN UNIT_OF_MEASURE = ''MBR'' THEN ''MBA'' WHEN UNIT_OF_MEASURE = ''MBQ'' THEN ''MBQ'' WHEN UNIT_OF_MEASURE = ''MC'' THEN ''MC'' WHEN UNIT_OF_MEASURE = ''MGM'' THEN ''MG'' WHEN UNIT_OF_MEASURE = ''M1'' THEN ''MGL'' WHEN UNIT_OF_MEASURE = ''GP'' THEN ''MGQ'' WHEN UNIT_OF_MEASURE = ''MAW'' THEN ''MGW'' WHEN UNIT_OF_MEASURE = ''MHZ'' THEN ''MHZ'' WHEN UNIT_OF_MEASURE = ''SMI'' THEN ''MI'' WHEN UNIT_OF_MEASURE = ''4H'' THEN ''MIM'' WHEN UNIT_OF_MEASURE = ''MIN'' THEN ''MIN'' WHEN UNIT_OF_MEASURE = ''B98'' THEN ''MIS'' WHEN UNIT_OF_MEASURE = ''C15'' THEN ''MJ'' WHEN UNIT_OF_MEASURE = ''MLT'' THEN ''ML'' WHEN UNIT_OF_MEASURE = ''MMT'' THEN ''MM'' WHEN UNIT_OF_MEASURE = ''MMK'' THEN ''MM2'' WHEN UNIT_OF_MEASURE = ''D87'' THEN ''MMK'' WHEN UNIT_OF_MEASURE = ''C18'' THEN ''MMO'' WHEN UNIT_OF_MEASURE = ''MMQ'' THEN ''MMQ'' WHEN UNIT_OF_MEASURE = ''C16'' THEN ''MMS'' WHEN UNIT_OF_MEASURE = ''C19'' THEN ''MOK'' WHEN UNIT_OF_MEASURE = ''C34'' THEN ''MOL'' WHEN UNIT_OF_MEASURE = ''MON'' THEN ''MON'' WHEN UNIT_OF_MEASURE = ''MPA'' THEN ''MPA'' WHEN UNIT_OF_MEASURE = ''C24'' THEN ''MPS'' WHEN UNIT_OF_MEASURE = ''MQH'' THEN ''MQH'' WHEN UNIT_OF_MEASURE = ''C26'' THEN ''MS'' WHEN UNIT_OF_MEASURE = ''MSK'' THEN ''MS2'' WHEN UNIT_OF_MEASURE = ''MT'' THEN ''MT'' WHEN UNIT_OF_MEASURE = ''C29'' THEN ''MTE'' WHEN UNIT_OF_MEASURE = ''MTS'' THEN ''MTS'' WHEN UNIT_OF_MEASURE = ''2Z'' THEN ''MV'' WHEN UNIT_OF_MEASURE = ''MVA'' THEN ''MVA'' WHEN UNIT_OF_MEASURE = ''C31'' THEN ''MW'' WHEN UNIT_OF_MEASURE = ''NEW'' THEN ''N'' WHEN UNIT_OF_MEASURE = ''C45'' THEN ''NAM'' WHEN UNIT_OF_MEASURE = ''NO'' THEN ''NO'' WHEN UNIT_OF_MEASURE = ''C47'' THEN ''NS'' WHEN UNIT_OF_MEASURE = ''C60'' THEN ''OCM'' WHEN UNIT_OF_MEASURE = ''OHM'' THEN ''OHM'' WHEN UNIT_OF_MEASURE = ''C61'' THEN ''OM'' WHEN UNIT_OF_MEASURE = ''OSG'' THEN ''OSG'' WHEN UNIT_OF_MEASURE = ''ONZ'' THEN ''OZ'' WHEN UNIT_OF_MEASURE = ''OZA'' THEN ''OZA'' WHEN UNIT_OF_MEASURE = ''P'' THEN ''P'' WHEN UNIT_OF_MEASURE = ''PAL'' THEN ''PA'' WHEN UNIT_OF_MEASURE = ''PAA'' THEN ''PAA'' WHEN UNIT_OF_MEASURE = ''PK'' THEN ''PAK''  WHEN UNIT_OF_MEASURE = ''PF'' THEN ''PAL'' WHEN UNIT_OF_MEASURE = ''C65'' THEN ''PAS'' WHEN UNIT_OF_MEASURE = ''PCS'' THEN ''PCS'' WHEN UNIT_OF_MEASURE = ''PD'' THEN ''PD'' WHEN UNIT_OF_MEASURE = ''PDG'' THEN ''PDG'' WHEN UNIT_OF_MEASURE = ''59'' THEN ''PPM'' WHEN UNIT_OF_MEASURE = ''PR'' THEN ''PR'' WHEN UNIT_OF_MEASURE = ''IE'' THEN ''PRS'' WHEN UNIT_OF_MEASURE = ''PT'' THEN ''PT'' WHEN UNIT_OF_MEASURE = ''PTG'' THEN ''PTG'' WHEN UNIT_OF_MEASURE = ''QT'' THEN ''QT'' WHEN UNIT_OF_MEASURE = ''RHG'' THEN ''RHG'' WHEN UNIT_OF_MEASURE = ''23'' THEN ''RHO'' WHEN UNIT_OF_MEASURE = ''RL'' THEN ''RL'' WHEN UNIT_OF_MEASURE = ''RM'' THEN ''RM'' WHEN UNIT_OF_MEASURE = ''RO'' THEN ''ROL''  WHEN UNIT_OF_MEASURE = ''RUG'' THEN ''RUG'' WHEN UNIT_OF_MEASURE = ''SEC'' THEN ''S'' WHEN UNIT_OF_MEASURE = ''SET'' THEN ''SET'' WHEN UNIT_OF_MEASURE = ''SF'' THEN ''SF'' WHEN UNIT_OF_MEASURE = ''SHT'' THEN ''SHT'' WHEN UNIT_OF_MEASURE = ''SP'' THEN ''SP'' WHEN UNIT_OF_MEASURE = ''SQ'' THEN ''SQ'' WHEN UNIT_OF_MEASURE = ''PCE'' THEN ''ST'' WHEN UNIT_OF_MEASURE = ''HUR'' THEN ''STD'' WHEN UNIT_OF_MEASURE = ''T'' THEN ''T'' WHEN UNIT_OF_MEASURE = ''DAY'' THEN ''TAG'' WHEN UNIT_OF_MEASURE = ''TB'' THEN ''TB'' WHEN UNIT_OF_MEASURE = ''D33'' THEN ''TES'' WHEN UNIT_OF_MEASURE = ''MIL'' THEN ''TH'' WHEN UNIT_OF_MEASURE = ''TNE'' THEN ''TO'' WHEN UNIT_OF_MEASURE = ''VLT'' THEN ''V'' WHEN UNIT_OF_MEASURE = ''C36'' THEN ''V02'' WHEN UNIT_OF_MEASURE = ''WTT'' THEN ''W'' WHEN UNIT_OF_MEASURE = ''WEE'' THEN ''WCH'' WHEN UNIT_OF_MEASURE = ''D53'' THEN ''WMK'' WHEN UNIT_OF_MEASURE = ''YRD'' THEN ''YD'' WHEN UNIT_OF_MEASURE = ''YDQ'' THEN ''YD3'' WHEN UNIT_OF_MEASURE = ''EA'' THEN ''Z1'' ELSE UNIT_OF_MEASURE END '")

	S = SqlHelper.GetFirst("sp_executesql @T=N'update mamsop_inbound set SALESUOM_ID = CASE WHEN SALESUOM_ID = ''P1'' THEN ''%'' WHEN SALESUOM_ID = ''DAY'' THEN ''10'' WHEN SALESUOM_ID = ''2M'' THEN ''2M'' WHEN SALESUOM_ID = ''2X'' THEN ''2X'' WHEN SALESUOM_ID = ''4G'' THEN ''4G'' WHEN  SALESUOM_ID = ''4O'' THEN ''4O'' WHEN SALESUOM_ID = ''4T'' THEN ''4T'' WHEN SALESUOM_ID = ''AMP'' THEN ''A'' WHEN SALESUOM_ID = ''A87'' THEN ''A87'' WHEN SALESUOM_ID = ''A93'' THEN ''A93'' WHEN SALESUOM_ID = ''AGG'' THEN ''AGG'' WHEN SALESUOM_ID = ''B34'' THEN ''B34'' WHEN SALESUOM_ID = ''B45'' THEN ''B45'' WHEN SALESUOM_ID = ''B47'' THEN ''B47'' WHEN SALESUOM_ID = ''B73'' THEN ''B73'' WHEN SALESUOM_ID = ''B75'' THEN ''B75'' WHEN SALESUOM_ID = ''B78'' THEN ''B78'' WHEN SALESUOM_ID = ''B84'' THEN ''B84'' WHEN SALESUOM_ID = ''BG'' THEN ''BAG'' WHEN SALESUOM_ID = ''BAR'' THEN ''BAR'' WHEN SALESUOM_ID = ''BBL'' THEN ''BBL'' WHEN SALESUOM_ID = ''BD'' THEN ''BD'' WHEN SALESUOM_ID = ''BAG'' THEN ''BG'' WHEN SALESUOM_ID = ''BK'' THEN ''BK'' WHEN SALESUOM_ID = ''BO'' THEN ''BOT'' WHEN SALESUOM_ID = ''C10'' THEN ''C10'' WHEN SALESUOM_ID = ''C36'' THEN ''C36'' WHEN SALESUOM_ID = ''C38'' THEN ''C38'' WHEN SALESUOM_ID = ''C39'' THEN ''C39'' WHEN SALESUOM_ID = ''2J'' THEN ''C3S'' WHEN SALESUOM_ID = ''C41'' THEN ''C41'' WHEN SALESUOM_ID = ''C56'' THEN ''C56'' WHEN SALESUOM_ID = ''CAR'' THEN ''CAR'' WHEN SALESUOM_ID = ''CMQ'' THEN ''CCM'' WHEN SALESUOM_ID = ''CDL'' THEN ''CD'' WHEN SALESUOM_ID = ''DMQ'' THEN ''CDM'' WHEN SALESUOM_ID = ''CF'' THEN ''CF'' WHEN SALESUOM_ID = ''CKG'' THEN ''CKG'' WHEN SALESUOM_ID = ''CMT'' THEN ''CM'' WHEN SALESUOM_ID = ''CMK'' THEN ''CM2'' WHEN SALESUOM_ID = ''CN'' THEN ''CN'' WHEN SALESUOM_ID = ''CS'' THEN ''CS'' WHEN SALESUOM_ID = ''CT'' THEN ''CT'' WHEN SALESUOM_ID = ''CYL'' THEN ''CYL'' WHEN SALESUOM_ID = ''D10'' THEN ''D10'' WHEN SALESUOM_ID = ''D41'' THEN ''D41'' WHEN SALESUOM_ID = ''D46'' THEN ''D46'' WHEN SALESUOM_ID = ''DD'' THEN ''DEG'' WHEN SALESUOM_ID = ''DMT'' THEN ''DM'' WHEN SALESUOM_ID = ''DOZ'' THEN ''DOZ'' WHEN SALESUOM_ID = ''DPC'' THEN ''DPC'' WHEN SALESUOM_ID = ''DPR'' THEN ''DPR'' WHEN SALESUOM_ID = ''DR'' THEN ''DR'' WHEN SALESUOM_ID = ''DZ'' THEN ''DZ'' WHEN SALESUOM_ID = ''EA'' THEN ''EA'' WHEN SALESUOM_ID = ''FAR'' THEN ''F'' WHEN SALESUOM_ID = ''FAH'' THEN ''FA'' WHEN SALESUOM_ID = ''FBM'' THEN ''FBM'' WHEN SALESUOM_ID = ''FOT'' THEN ''FT'' WHEN SALESUOM_ID = ''FTK'' THEN ''FT2'' WHEN SALESUOM_ID = ''FTQ'' THEN ''FT3'' WHEN SALESUOM_ID = ''FTC'' THEN ''FTC'' WHEN SALESUOM_ID = ''GRM'' THEN ''G'' WHEN SALESUOM_ID = ''GAL'' THEN ''GA'' WHEN SALESUOM_ID = ''GBQ'' THEN ''GBQ'' WHEN SALESUOM_ID = ''CEL'' THEN ''GC'' WHEN SALESUOM_ID = ''GL'' THEN ''GL'' WHEN SALESUOM_ID = ''GLI'' THEN ''GLI'' WHEN SALESUOM_ID = ''GLL'' THEN ''GLL'' WHEN SALESUOM_ID = ''GQ'' THEN ''GQ'' WHEN SALESUOM_ID = ''GR'' THEN ''GR'' WHEN SALESUOM_ID = ''GRO'' THEN ''GRO'' WHEN SALESUOM_ID = ''GS'' THEN ''GS''  WHEN SALESUOM_ID = ''HR'' THEN ''H'' WHEN SALESUOM_ID = ''HLT'' THEN ''HL'' WHEN SALESUOM_ID = ''A97'' THEN ''HPA'' WHEN SALESUOM_ID = ''HUN'' THEN ''HUN'' WHEN SALESUOM_ID = ''HTZ'' THEN ''HZ'' WHEN SALESUOM_ID = ''INH'' THEN ''IN'' WHEN SALESUOM_ID = ''2'' THEN ''IN2'' WHEN SALESUOM_ID = ''INQ'' THEN ''IN3'' WHEN SALESUOM_ID = ''IRG'' THEN ''IRG'' WHEN SALESUOM_ID = ''JOU'' THEN ''J'' WHEN SALESUOM_ID = ''ANN'' THEN ''JHR'' WHEN SALESUOM_ID = ''B11'' THEN ''JKK'' WHEN SALESUOM_ID = ''JWL'' THEN ''JWL'' WHEN SALESUOM_ID = ''KEL'' THEN ''K'' WHEN SALESUOM_ID = ''B22'' THEN ''KA'' WHEN SALESUOM_ID = ''CA'' THEN ''KAN'' WHEN SALESUOM_ID = ''BX'' THEN ''KAR'' WHEN SALESUOM_ID = ''KGM'' THEN ''KG''  WHEN SALESUOM_ID = ''28'' THEN ''KGF'' WHEN SALESUOM_ID = ''KGS'' THEN ''KGS'' WHEN SALESUOM_ID = ''KMQ'' THEN ''KGV''  WHEN SALESUOM_ID = ''KHZ'' THEN ''KHZ''  WHEN SALESUOM_ID = ''CRT'' THEN ''KI'' WHEN SALESUOM_ID = ''KIT'' THEN ''KIT'' WHEN SALESUOM_ID = ''KJO'' THEN ''KJ'' WHEN SALESUOM_ID = ''KMT'' THEN ''KM'' WHEN SALESUOM_ID = ''KM3'' THEN ''KM3'' WHEN SALESUOM_ID = ''KMH'' THEN ''KMH'' WHEN SALESUOM_ID = ''B49'' THEN ''KOH'' WHEN SALESUOM_ID = ''KPA'' THEN ''KPA'' WHEN SALESUOM_ID = ''PA'' THEN ''KT'' WHEN SALESUOM_ID = ''KVT'' THEN ''KV'' WHEN SALESUOM_ID = ''KVA'' THEN ''KVA'' WHEN SALESUOM_ID = ''KWT'' THEN ''KW'' WHEN SALESUOM_ID = ''KWH'' THEN ''KWH'' WHEN SALESUOM_ID = ''LTR'' THEN ''L'' WHEN SALESUOM_ID = ''L2'' THEN ''L2'' WHEN SALESUOM_ID = ''LBR'' THEN ''LB'' WHEN SALESUOM_ID = ''C62'' THEN ''LE'' WHEN SALESUOM_ID = ''LNM'' THEN ''LNM'' WHEN SALESUOM_ID = ''LOT'' THEN ''LOT''  WHEN SALESUOM_ID = ''MTR'' THEN ''M'' WHEN SALESUOM_ID = ''MTS'' THEN ''M/S'' WHEN SALESUOM_ID = ''MTK'' THEN ''M2'' WHEN SALESUOM_ID = ''S4'' THEN ''M2S'' WHEN SALESUOM_ID = ''MTQ'' THEN ''M3'' WHEN SALESUOM_ID = ''MQS'' THEN ''M3S'' WHEN SALESUOM_ID = ''4K'' THEN ''MA'' WHEN SALESUOM_ID = ''MBR'' THEN ''MBA'' WHEN SALESUOM_ID = ''MBQ'' THEN ''MBQ'' WHEN SALESUOM_ID = ''MC'' THEN ''MC'' WHEN SALESUOM_ID = ''MGM'' THEN ''MG'' WHEN SALESUOM_ID = ''M1'' THEN ''MGL'' WHEN SALESUOM_ID = ''GP'' THEN ''MGQ'' WHEN SALESUOM_ID = ''MAW'' THEN ''MGW'' WHEN SALESUOM_ID = ''MHZ'' THEN ''MHZ'' WHEN SALESUOM_ID = ''SMI'' THEN ''MI'' WHEN SALESUOM_ID = ''4H'' THEN ''MIM'' WHEN SALESUOM_ID = ''MIN'' THEN ''MIN'' WHEN SALESUOM_ID = ''B98'' THEN ''MIS'' WHEN SALESUOM_ID = ''C15'' THEN ''MJ'' WHEN SALESUOM_ID = ''MLT'' THEN ''ML'' WHEN SALESUOM_ID = ''MMT'' THEN ''MM'' WHEN SALESUOM_ID = ''MMK'' THEN ''MM2'' WHEN SALESUOM_ID = ''D87'' THEN ''MMK'' WHEN SALESUOM_ID = ''C18'' THEN ''MMO'' WHEN SALESUOM_ID = ''MMQ'' THEN ''MMQ'' WHEN SALESUOM_ID = ''C16'' THEN ''MMS'' WHEN SALESUOM_ID = ''C19'' THEN ''MOK'' WHEN SALESUOM_ID = ''C34'' THEN ''MOL'' WHEN SALESUOM_ID = ''MON'' THEN ''MON'' WHEN SALESUOM_ID = ''MPA'' THEN ''MPA'' WHEN SALESUOM_ID = ''C24'' THEN ''MPS'' WHEN SALESUOM_ID = ''MQH'' THEN ''MQH'' WHEN SALESUOM_ID = ''C26'' THEN ''MS'' WHEN SALESUOM_ID = ''MSK'' THEN ''MS2'' WHEN SALESUOM_ID = ''MT'' THEN ''MT'' WHEN SALESUOM_ID = ''C29'' THEN ''MTE'' WHEN SALESUOM_ID = ''MTS'' THEN ''MTS'' WHEN SALESUOM_ID = ''2Z'' THEN ''MV'' WHEN SALESUOM_ID = ''MVA'' THEN ''MVA'' WHEN SALESUOM_ID = ''C31'' THEN ''MW'' WHEN SALESUOM_ID = ''NEW'' THEN ''N'' WHEN SALESUOM_ID = ''C45'' THEN ''NAM'' WHEN SALESUOM_ID = ''NO'' THEN ''NO'' WHEN SALESUOM_ID = ''C47'' THEN ''NS'' WHEN SALESUOM_ID = ''C60'' THEN ''OCM'' WHEN SALESUOM_ID = ''OHM'' THEN ''OHM'' WHEN SALESUOM_ID = ''C61'' THEN ''OM'' WHEN SALESUOM_ID = ''OSG'' THEN ''OSG'' WHEN SALESUOM_ID = ''ONZ'' THEN ''OZ'' WHEN SALESUOM_ID = ''OZA'' THEN ''OZA'' WHEN SALESUOM_ID = ''P'' THEN ''P'' WHEN SALESUOM_ID = ''PAL'' THEN ''PA'' WHEN SALESUOM_ID = ''PAA'' THEN ''PAA'' WHEN SALESUOM_ID = ''PK'' THEN ''PAK''  WHEN SALESUOM_ID = ''PF'' THEN ''PAL'' WHEN SALESUOM_ID = ''C65'' THEN ''PAS'' WHEN SALESUOM_ID = ''PCS'' THEN ''PCS'' WHEN SALESUOM_ID = ''PD'' THEN ''PD'' WHEN SALESUOM_ID = ''PDG'' THEN ''PDG'' WHEN SALESUOM_ID = ''59'' THEN ''PPM'' WHEN SALESUOM_ID = ''PR'' THEN ''PR'' WHEN SALESUOM_ID = ''IE'' THEN ''PRS'' WHEN SALESUOM_ID = ''PT'' THEN ''PT'' WHEN SALESUOM_ID = ''PTG'' THEN ''PTG'' WHEN SALESUOM_ID = ''QT'' THEN ''QT'' WHEN SALESUOM_ID = ''RHG'' THEN ''RHG'' WHEN SALESUOM_ID = ''23'' THEN ''RHO'' WHEN SALESUOM_ID = ''RL'' THEN ''RL'' WHEN SALESUOM_ID = ''RM'' THEN ''RM'' WHEN SALESUOM_ID = ''RO'' THEN ''ROL''  WHEN SALESUOM_ID = ''RUG'' THEN ''RUG'' WHEN SALESUOM_ID = ''SEC'' THEN ''S'' WHEN SALESUOM_ID = ''SET'' THEN ''SET'' WHEN SALESUOM_ID = ''SF'' THEN ''SF'' WHEN SALESUOM_ID = ''SHT'' THEN ''SHT'' WHEN SALESUOM_ID = ''SP'' THEN ''SP'' WHEN SALESUOM_ID = ''SQ'' THEN ''SQ'' WHEN SALESUOM_ID = ''PCE'' THEN ''ST'' WHEN SALESUOM_ID = ''HUR'' THEN ''STD'' WHEN SALESUOM_ID = ''T'' THEN ''T'' WHEN SALESUOM_ID = ''DAY'' THEN ''TAG'' WHEN SALESUOM_ID = ''TB'' THEN ''TB'' WHEN SALESUOM_ID = ''D33'' THEN ''TES'' WHEN SALESUOM_ID = ''MIL'' THEN ''TH'' WHEN SALESUOM_ID = ''TNE'' THEN ''TO'' WHEN SALESUOM_ID = ''VLT'' THEN ''V'' WHEN SALESUOM_ID = ''C36'' THEN ''V02'' WHEN SALESUOM_ID = ''WTT'' THEN ''W'' WHEN SALESUOM_ID = ''WEE'' THEN ''WCH'' WHEN SALESUOM_ID = ''D53'' THEN ''WMK'' WHEN SALESUOM_ID = ''YRD'' THEN ''YD'' WHEN SALESUOM_ID = ''YDQ'' THEN ''YD3'' WHEN SALESUOM_ID = ''EA'' THEN ''Z1'' ELSE SALESUOM_ID END '")

	
	primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  mamtrl_inbound set process_status = ''DUPLICATE'' from mamtrl_inbound(nolock) join (select sap_part_number,max(cpqtableentryid) as cpqtableentryid from mamtrl_inbound where isnull(process_status,'''')='''' group by sap_part_number having count(cpqtableentryid)>1 )SUB_MAMTRL on mamtrl_inbound.sap_part_number = SUB_MAMTRL.sap_part_number where mamtrl_inbound.cpqtableentryid<> SUB_MAMTRL.cpqtableentryid and isnull(process_status,'''')=''''  ' "
		)

	primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  mamtrl_inbound set process_status=''DUPLICATE'' from mamtrl_inbound (nolock) left join mamsop_inbound(nolock) on mamtrl_inbound.session_id = mamsop_inbound.session_id where mamsop_inbound.session_id is null' "
		)
	
	primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  mamsop_inbound set process_status=''DUPLICATE'' from mamtrl_inbound(nolock) join mamsop_inbound(nolock) on mamtrl_inbound.session_id = mamsop_inbound.session_id where isnull(mamtrl_inbound.process_status,'''')=''DUPLICATE''  ' "
		)
		
	primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  mamtrl_INBOUND set mamtrl_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "',process_status='''' FROM mamtrl_INBOUND (nolock) where session_id in (select session_id from mamsop_INBOUND (nolock) where isnull(process_status,'''')IN (''READY FOR UPLOAD'',''INPROGRESS'',''''))  ' ")

	primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  mamsop_INBOUND set mamsop_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "',process_status='''' FROM mamsop_INBOUND(nolock) where isnull(process_status,'''')IN (''READY FOR UPLOAD'',''INPROGRESS'','''')  ' ")

	primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  mamtrl_INBOUND set mamtrl_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "',process_status='''' FROM mamtrl_INBOUND (nolock) where isnull(process_status,'''')IN (''READY FOR UPLOAD'',''INPROGRESS'','''')  ' ")



	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter1.QUERY_CRITERIA_1)
				+ "  MAMTRL_INBOUND set MAMTRL_INBOUND.process_status=''Inprogress'',MAMTRL_INBOUND.ERROR='''',MAMTRL_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "' FROM MAMTRL_INBOUND (nolock) where isnull(MAMTRL_INBOUND.process_status,'''')='''' and MAMTRL_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "'' "
			)
			
	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter1.QUERY_CRITERIA_1)
				+ "  MAMSOP_INBOUND set MAMSOP_INBOUND.process_status=''Inprogress'',MAMSOP_INBOUND.ERROR='''',MAMSOP_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "' from MAMSOP_INBOUND (nolock) join MAMTRL_INBOUND (nolock) on MAMSOP_INBOUND.session_id = MAMTRL_INBOUND.session_id where isnull(MAMSOP_INBOUND.process_status,'''')='''' and MAMTRL_INBOUND.process_status=''Inprogress'' ' "
			)

	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter1.QUERY_CRITERIA_1)
				+ "  MAMACT_INBOUND set MAMACT_INBOUND.process_status=''Inprogress'',MAMACT_INBOUND.ERROR='''',MAMACT_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "' from MAMACT_INBOUND (nolock) join MAMTRL_INBOUND (nolock) on MAMACT_INBOUND.session_id = MAMTRL_INBOUND.session_id where isnull(MAMACT_INBOUND.process_status,'''')='''' and MAMTRL_INBOUND.process_status=''Inprogress'' ' "
			)

	#MAMTRL Validation
	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter1.QUERY_CRITERIA_1)
				+ "  MAMTRL_INBOUND SET ERROR = ISNULL(ERROR,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,MAMTRL_INBOUND.ERP_CREATE_DATE),MAMTRL_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMTRL_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200000'' WHERE MAMTRL_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'')  AND ISDATE(ERP_CREATE_DATE) = ''0'' AND ISNULL(ERP_CREATE_DATE,'''')<>'''' AND SYMSGS.OBJECT_APINAME = ''MAMTRL'' AND MAMTRL_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "' '"
			)

	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter1.QUERY_CRITERIA_1)
				+ "  MAMTRL_INBOUND SET ERROR = ISNULL(ERROR,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMTRL_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMTRL_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200001'' WHERE MAMTRL_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'')  AND ISNULL(MATERIALTYPE_ID,'''') = '''' AND SYMSGS.OBJECT_APINAME = ''MAMTRL'' AND MAMTRL_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "' '"
			)
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMTRL_INBOUND SET ERROR = ISNULL(ERROR,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMTRL_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMTRL_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200002'' WHERE MAMTRL_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'')  AND ISNULL(SAP_PART_NUMBER,'''') = '''' AND SYMSGS.OBJECT_APINAME = ''MAMTRL'' AND MAMTRL_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMTRL_INBOUND SET ERROR = ISNULL(ERROR,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMTRL_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMTRL_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200003'' WHERE MAMTRL_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'')  AND ISNULL(SAP_DESCRIPTION,'''') = '''' AND SYMSGS.OBJECT_APINAME = ''MAMTRL'' AND MAMTRL_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMTRL_INBOUND SET ERROR = ISNULL(ERROR,'''') + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMTRL_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMTRL_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200004'' WHERE MAMTRL_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND ISNULL(MATERIALGROUP_ID,'''') = '''' AND SYMSGS.OBJECT_APINAME = ''MAMTRL'' AND MAMTRL_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  '"
	)

	#MAMSOP Validation
	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter1.QUERY_CRITERIA_1)
				+ "  MAMSOP_INBOUND SET MAMSOP_INBOUND.ERROR = MAMSOP_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,MAMSOP_INBOUND.SALESORG_ID),MAMSOP_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK) LEFT JOIN SASORG (NOLOCK) ON MAMSOP_INBOUND.SALESORG_ID = SASORG.SALESORG_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200005'' WHERE MAMSOP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMSOP'' AND MAMSOP_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "'  AND SASORG.SALESORG_ID IS NULL AND MAMSOP_INBOUND.SALESORG_ID <> '''' '"
			)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMSOP_INBOUND SET MAMSOP_INBOUND.ERROR = MAMSOP_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,MAMSOP_INBOUND.PLANT_ID),MAMSOP_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK) LEFT JOIN MAPLNT (NOLOCK) ON MAMSOP_INBOUND.PLANT_ID = MAPLNT.PLANT_ID LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200006'' WHERE MAMSOP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMSOP'' AND MAMSOP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND MAPLNT.PLANT_ID IS NULL AND MAMSOP_INBOUND.PLANT_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMSOP_INBOUND SET MAMSOP_INBOUND.ERROR = MAMSOP_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,MAMSOP_INBOUND.DISTRIBUTIONCHANNEL_ID),MAMSOP_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK) LEFT JOIN SADSCH (NOLOCK) ON MAMSOP_INBOUND.DISTRIBUTIONCHANNEL_ID = SADSCH.DISTRIBUTIONCHANNEL_ID LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200007'' WHERE MAMSOP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMSOP'' AND MAMSOP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND SADSCH.DISTRIBUTIONCHANNEL_ID IS NULL AND MAMSOP_INBOUND.DISTRIBUTIONCHANNEL_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMSOP_INBOUND SET MAMSOP_INBOUND.ERROR = MAMSOP_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,MAMSOP_INBOUND.DIVISION_ID),MAMSOP_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK) LEFT JOIN SADIVN (NOLOCK) ON MAMSOP_INBOUND.DIVISION_ID = SADIVN.DIVISION_ID LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200008'' WHERE MAMSOP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMSOP'' AND MAMSOP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND SADIVN.DIVISION_ID IS NULL AND MAMSOP_INBOUND.DIVISION_ID <> '''''"
	)

	"""primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMSOP_INBOUND SET MAMSOP_INBOUND.ERROR = MAMSOP_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,MAMSOP_INBOUND.MATERIALSTATUS_ID),MAMSOP_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK) LEFT JOIN MAMTST (NOLOCK) ON MAMSOP_INBOUND.MATERIALSTATUS_ID = MAMTST.MATERIALSTATUS_ID LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200009'' WHERE MAMSOP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMSOP'' AND MAMSOP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND MAMTST.MATERIALSTATUS_ID IS NULL AND MAMSOP_INBOUND.MATERIALSTATUS_ID <> '''''"
	)"""

	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter1.QUERY_CRITERIA_1)
				+ "  MAMSOP_INBOUND SET MAMSOP_INBOUND.ERROR = MAMSOP_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMSOP_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200010'' WHERE MAMSOP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMSOP'' AND MAMSOP_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "'  AND SALESORG_ID = '''''"
			)

	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter1.QUERY_CRITERIA_1)
				+ "  MAMSOP_INBOUND SET MAMSOP_INBOUND.ERROR = MAMSOP_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMSOP_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200011'' WHERE MAMSOP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMSOP'' AND MAMSOP_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "'   AND SAP_PART_NUMBER = '''' '"
			)

	"""primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMSOP_INBOUND SET MAMSOP_INBOUND.ERROR = MAMSOP_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMSOP_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK)  LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200012'' WHERE MAMSOP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMSOP'' AND MAMSOP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND PLANT_ID = '''''"
	)"""

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMSOP_INBOUND SET MAMSOP_INBOUND.ERROR = MAMSOP_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMSOP_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK)  ON SYMSGS.MESSAGE_CODE = ''200013'' WHERE MAMSOP_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMSOP'' AND MAMSOP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND DISTRIBUTIONCHANNEL_ID = '''''"
	)

	#MAMACT Validation
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMACT_INBOUND SET MAMACT_INBOUND.ERROR = MAMACT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE)+''-''+convert(nvarchar,MAMACT_INBOUND.CATEGORY_ID),MAMACT_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMACT_INBOUND(NOLOCK) LEFT JOIN MACATG(NOLOCK) ON MAMACT_INBOUND.CATEGORY_ID = MACATG.CATEGORY_ID LEFT JOIN SYMSGS(NOLOCK) SYMSGS ON SYMSGS.MESSAGE_CODE = ''200014'' WHERE MAMACT_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMACT'' AND MAMACT_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND MACATG.CATEGORY_ID IS NULL AND MAMACT_INBOUND.CATEGORY_ID <> '''''"
	)

	primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter1.QUERY_CRITERIA_1)
				+ "  MAMACT_INBOUND SET MAMACT_INBOUND.ERROR = MAMACT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMACT_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMACT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200015'' WHERE MAMACT_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMACT'' AND MAMACT_INBOUND.TIMESTAMP='"
				+ str(timestamp_sessionid)
				+ "'   AND SAP_PART_NUMBER = '''' '"
			)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMACT_INBOUND SET MAMACT_INBOUND.ERROR = MAMACT_INBOUND.ERROR + ''||''+convert(nvarchar,SYMSGS.MESSAGE_CODE),MAMACT_INBOUND.PROCESS_STATUS=''ERROR'' FROM MAMACT_INBOUND(NOLOCK) LEFT JOIN SYMSGS(NOLOCK) ON SYMSGS.MESSAGE_CODE = ''200016'' WHERE MAMACT_INBOUND.PROCESS_STATUS IN (''Inprogress'',''ERROR'') AND SYMSGS.OBJECT_APINAME = ''MAMACT'' AND MAMACT_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "'  AND CATEGORY_ID = '''''"
	)

	#Validation Completed

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMTRL_INBOUND SET PROCESS_STATUS=''READY FOR UPLOAD'' WHERE PROCESS_STATUS=''Inprogress'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(ERROR,'''')='''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMSOP_INBOUND SET PROCESS_STATUS=''READY FOR UPLOAD'' WHERE PROCESS_STATUS=''Inprogress'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(ERROR,'''')='''' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMACT_INBOUND SET PROCESS_STATUS=''READY FOR UPLOAD'' WHERE PROCESS_STATUS=''Inprogress'' AND TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' AND ISNULL(ERROR,'''')='''' '"
	)

	#Error Logging 
	
	#Error log table creating dynamically

	Temp_Table_Name = 'ERROR_LOG'
	
	ERRLOG_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(Temp_Table_Name)+"'' ) BEGIN DROP TABLE "+str(Temp_Table_Name)+" END  ' ")

	TempTable = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(Temp_Table_Name)+"'' ) BEGIN DROP TABLE "+str(Temp_Table_Name)+" END CREATE TABLE "+str(Temp_Table_Name)+" (SESSION_ID VARCHAR(100),INTEGRATION_TYPE VARCHAR(100) ,PROCESS_STATUS VARCHAR(100),CpqTableEntryDateModified date )'")

	primaryQueryItems = SqlHelper.GetFirst(""+ str(Parameter.QUERY_CRITERIA_1)+ " ERROR_LOG (SESSION_ID,CpqTableEntryDateModified) SELECT SESSION_ID,getdate() FROM (SELECT DISTINCT MAMTRL_INBOUND.SESSION_ID as SESSION_ID FROM MAMTRL_INBOUND (NOLOCK) WHERE  ISNULL(MAMTRL_INBOUND.PROCESS_STATUS,'''')=''ERROR'' AND MAMTRL_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "'  union 	SELECT MAMSOP_INBOUND.SESSION_ID FROM MAMSOP_INBOUND (NOLOCK)  JOIN MAMTRL_INBOUND (NOLOCK) ON MAMSOP_INBOUND.SESSION_ID=MAMTRL_INBOUND.SESSION_ID WHERE  ISNULL(MAMSOP_INBOUND.PROCESS_STATUS,'''')=''ERROR'' AND MAMSOP_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "' UNION SELECT MAMACT_INBOUND.SESSION_ID FROM MAMACT_INBOUND (NOLOCK)  JOIN MAMTRL_INBOUND(NOLOCK) ON MAMACT_INBOUND.SESSION_ID=MAMTRL_INBOUND.SESSION_ID WHERE  ISNULL(MAMACT_INBOUND.PROCESS_STATUS,'''')=''ERROR'' AND MAMACT_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')SUB_ERRLOG  ' ")

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMTRL_INBOUND SET PROCESS_STATUS=''ERROR'' FROM MAMTRL_INBOUND(NOLOCK) JOIN ERROR_LOG(NOLOCK) ON MAMTRL_INBOUND.SESSION_ID = ERROR_LOG.SESSION_ID WHERE MAMTRL_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' '"
	)

	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMSOP_INBOUND SET PROCESS_STATUS=''ERROR'' FROM MAMSOP_INBOUND(NOLOCK) JOIN ERROR_LOG(NOLOCK) ON MAMSOP_INBOUND.SESSION_ID = ERROR_LOG.SESSION_ID WHERE MAMSOP_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
		""
		+ str(Parameter1.QUERY_CRITERIA_1)
		+ "  MAMACT_INBOUND SET PROCESS_STATUS=''ERROR'' FROM MAMACT_INBOUND JOIN ERROR_LOG ON MAMACT_INBOUND.SESSION_ID = ERROR_LOG.SESSION_ID WHERE MAMACT_INBOUND.TIMESTAMP='"
		+ str(timestamp_sessionid)
		+ "' '"
	)

	#Upload Starts
	#MAMTRL

	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAMTRL SET MAMTRL.CpqTableEntryModifiedBy = ''"
	+ str(User.Id)
	+ "'',MAMTRL.CpqTableEntryDateModified = GetDate(),MAMTRL.UNIT_OF_MEASURE =  MAMUOM.UOM, MAMTRL.UOM_RECORD_ID = MAMUOM.UNIT_OF_MEASURE_RECORD_ID,MATERIALCONFIG_TYPE  = MAMTRL_INBOUND.MATERIALCONFIG_TYPE,  MAMTRL.ERP_CREATE_DATE = CONVERT(DATE,MAMTRL_INBOUND.ERP_CREATE_DATE), MAMTRL.MATERIALGROUP_ID = MAMGRP.MATERIALGROUP_ID, MAMTRL.MATERIALGROUP_RECORD_ID = MAMGRP.MATERIAL_GROUP_RECORD_ID, MAMTRL.MATERIALTYPE_ID = MAMTYP.MATERIALTYPE_ID, MAMTRL.MATERIALTYPE_RECORD_ID = MAMTYP.MATERIAL_TYPE_RECORD_ID,MAMTRL.SAP_DESCRIPTION = MAMTRL_INBOUND.SAP_DESCRIPTION,  MAMTRL.MATERIALSTATUS_ID = MAMTST.MATERIALSTATUS_ID, MAMTRL.MATERIALSTATUS_RECORD_ID = MAMTST.MATERIAL_STATUS_RECORD_ID, MAMTRL.PROD_INSP_MEMO = MAMTRL_INBOUND.PROD_INSP_MEMO FROM MAMTRL_INBOUND(NOLOCK) JOIN MAMTYP(NOLOCK) on MAMTRL_INBOUND.MATERIALTYPE_ID = MAMTYP.MATERIALTYPE_ID LEFT JOIN MAMUOM(NOLOCK) ON MAMTRL_INBOUND.UNIT_OF_MEASURE = MAMUOM.UOM LEFT JOIN MAMTST(NOLOCK) ON MAMTRL_INBOUND.MATERIALSTATUS_ID = MAMTST.MATERIALSTATUS_ID JOIN MAMGRP(NOLOCK) on MAMTRL_INBOUND.MATERIALGROUP_ID = MAMGRP.MATERIALGROUP_ID JOIN MAMTRL(NOLOCK) ON MAMTRL_INBOUND.SAP_PART_NUMBER = MAMTRL.SAP_PART_NUMBER   WHERE MAMTRL_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND ISNULL(MAMTRL_INBOUND.ERROR,'''') = '''' AND MAMTRL_INBOUND.TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "'  ' "
	)

	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " MAMTRL (UNIT_OF_MEASURE,UOM_RECORD_ID,MATERIALCONFIG_TYPE,ERP_CREATE_DATE,INTERNAL_NOTES,MATERIALGROUP_ID,MATERIALGROUP_RECORD_ID,MATERIALTYPE_ID,MATERIALTYPE_RECORD_ID,SAP_DESCRIPTION,SAP_PART_NUMBER,MATERIALSTATUS_ID,MATERIALSTATUS_RECORD_ID,DIVISION_ID,DIVISION_RECORD_ID,PROD_INSP_MEMO,MATERIAL_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_MAMTRL.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',GETDATE() FROM (SELECT DISTINCT MAMUOM.UOM AS UNIT_OF_MEASURE,MAMUOM.UNIT_OF_MEASURE_RECORD_ID AS UOM_RECORD_ID , MAMTRL_INBOUND.MATERIALCONFIG_TYPE,CONVERT(DATE,ERP_CREATE_DATE) AS ERP_CREATE_DATE,INTERNAL_NOTES,MAMGRP.MATERIALGROUP_ID,MAMGRP.MATERIAL_GROUP_RECORD_ID,MAMTYP.MATERIALTYPE_ID,MAMTYP.MATERIAL_TYPE_RECORD_ID,MAMTRL_INBOUND.SAP_DESCRIPTION,MAMTRL_INBOUND.SAP_PART_NUMBER, MAMTST.MATERIALSTATUS_ID,MAMTST.MATERIAL_STATUS_RECORD_ID,MAMTRL_INBOUND.DIVISION_ID,SADIVN.DIVISION_RECORD_ID,MAMTRL_INBOUND.PROD_INSP_MEMO FROM MAMTRL_INBOUND(NOLOCK) JOIN MAMTYP(NOLOCK) on MAMTRL_INBOUND.MATERIALTYPE_ID = MAMTYP.MATERIALTYPE_ID LEFT JOIN MAMUOM(NOLOCK) ON MAMTRL_INBOUND.UNIT_OF_MEASURE = MAMUOM.UOM  LEFT JOIN MAMTST(NOLOCK) ON CASE WHEN ISNULL(MAMTRL_INBOUND.MATERIALSTATUS_ID,'''')='''' THEN ''AC'' ELSE MAMTRL_INBOUND.MATERIALSTATUS_ID END = MAMTST.MATERIALSTATUS_ID JOIN MAMGRP(NOLOCK) on MAMTRL_INBOUND.MATERIALGROUP_ID = MAMGRP.MATERIALGROUP_ID JOIN SADIVN (NOLOCK) ON MAMTRL_INBOUND.DIVISION_ID = SADIVN.DIVISION_ID WHERE MAMTRL_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND ISNULL(MAMTRL_INBOUND.ERROR,'''') = '''' AND MAMTRL_INBOUND.TIMESTAMP='"	+ str(timestamp_sessionid)+ "')SUB_MAMTRL LEFT JOIN MAMTRL(NOLOCK)  ON SUB_MAMTRL.SAP_PART_NUMBER = MAMTRL.SAP_PART_NUMBER WHERE MAMTRL.SAP_PART_NUMBER IS NULL '"	)
	
	primaryQueryItems = SqlHelper.GetFirst("sp_executesql @t=N'update mamtrl set materialconfig_type =''SIMPLE MATERIAL'' where isnull(materialconfig_type,'''')=''''  ' ")

	primaryQueryItems = SqlHelper.GetFirst("sp_executesql @t=N'update mamtrl set materialconfig_type =''CONFIGURABLE MATERIAL'' where isnull(materialconfig_type,'''')=''X''  ' ")
	
	UpdateTable1=SqlHelper.GetFirst("sp_executesql @T=N'update mamtrl set IS_SPARE_PART= case when isnull(is_spares,'''')=''SP'' then ''true'' else ''false'' end from mamtrl join mamsop_inbound  on mamtrl.sap_part_number = mamsop_inbound.sap_part_number'")

	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAMTRL_INBOUND SET PROCESS_STATUS = ''UPLOADED'' WHERE PROCESS_STATUS=''READY FOR UPLOAD'' AND TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "'  '"
	)

	#MAMSOP

	Sql = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ " MAMSOP SET MAMSOP.CpqTableEntryModifiedBy = ''"+ str(User.Id)+ "'',MAMSOP.CpqTableEntryDateModified = GetDate(),MAMSOP.MATERIALSTATUS_ID=MAMSOP_INBOUND.MATERIALSTATUS_ID,MAMSOP.ITMCATGRP_ID=MAMSOP_INBOUND.ITMCATGRP_ID,PLANT_ID = mamsop_INBOUND.PLANT_ID,PLANT_RECORD_ID = MAPLNT.PLANT_RECORD_ID,MATSTAT_VALFRM = CONVERT(DATE,VALID_FROM) FROM MAMSOP (NOLOCK) JOIN MAMSOP_INBOUND (NOLOCK) ON MAMSOP.SAP_PART_NUMBER=MAMSOP_INBOUND.SAP_PART_NUMBER AND MAMSOP.SALESORG_ID=MAMSOP_INBOUND.SALESORG_ID AND MAMSOP.DISTRIBUTIONCHANNEL_ID = MAMSOP_INBOUND.DISTRIBUTIONCHANNEL_ID AND MAMSOP.DIVISION_ID = MAMSOP_INBOUND.DIVISION_ID LEFT JOIN MAPLNT (NOLOCK) ON  MAPLNT.PLANT_ID = MAMSOP_INBOUND.PLANT_ID WHERE ISNULL(MAMSOP_INBOUND.PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND ISNULL(ERROR,'''')='''' AND TIMESTAMP = '"+ str(timestamp_sessionid)+ "'  '")
	
	Sql = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ " MAMSOP SET MAMSOP.CpqTableEntryModifiedBy = ''"+ str(User.Id)+ "'',MAMSOP.CpqTableEntryDateModified = GetDate(),MAMSOP.SALESUOM_ID=UOM,MAMSOP.SALESUOM_RECORD_ID=UNIT_OF_MEASURE_RECORD_ID FROM MAMSOP (NOLOCK) JOIN MAMSOP_INBOUND (NOLOCK) ON MAMSOP.SAP_PART_NUMBER=MAMSOP_INBOUND.SAP_PART_NUMBER AND MAMSOP.SALESORG_ID=MAMSOP_INBOUND.SALESORG_ID AND MAMSOP.DISTRIBUTIONCHANNEL_ID = MAMSOP_INBOUND.DISTRIBUTIONCHANNEL_ID  JOIN MAMUOM MAMUOM(NOLOCK) ON MAMSOP_INBOUND.SALESUOM_ID = MAMUOM.UOM WHERE ISNULL(MAMSOP_INBOUND.PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND ISNULL(ERROR,'''')='''' AND TIMESTAMP = '"+ str(timestamp_sessionid)+ "'  AND ISNULL(MAMSOP_INBOUND.SALESUOM_ID,'''')<>'''' '")
	
	ERRLOG_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''TEMP_PROCESS'' ) BEGIN DROP TABLE TEMP_PROCESS END CREATE TABLE TEMP_PROCESS (SESSION_ID VARCHAR(100),PROCESS_STATUS VARCHAR(100)) ' ")
 
	Check_flag = 1
	while Check_flag == 1:
		primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter.QUERY_CRITERIA_1)
			+ " TEMP_PROCESS (SESSION_ID)SELECT DISTINCT TOP 5000 MAMSOP_INBOUND.SAP_PART_NUMBER FROM MAMSOP_INBOUND (NOLOCK) LEFT JOIN TEMP_PROCESS (NOLOCK) ON MAMSOP_INBOUND.SAP_PART_NUMBER = TEMP_PROCESS.SESSION_ID WHERE MAMSOP_INBOUND.PROCESS_STATUS=''READY FOR UPLOAD'' AND ISNULL(ERROR,'''')=''''  AND MAMSOP_INBOUND.TIMESTAMP='"
			+ str(timestamp_sessionid)
			+ "' AND TEMP_PROCESS.SESSION_ID IS NULL  ' "
		)

		primaryQueryItems = SqlHelper.GetFirst(
			"select 'x' as a from TEMP_PROCESS(nolock)  where isnull(PROCESS_STATUS,'')='' "
		)

		if str(primaryQueryItems) != "None":

			MamsopInsertQuery = SqlHelper.GetFirst(
				""
				+ str(Parameter.QUERY_CRITERIA_1)
				+ " MAMSOP (PLANT_ID,PLANT_RECORD_ID,MATERIAL_RECORD_ID,MATSTAT_VALFRM,MATERIALSTATUS_ID,MATERIALSTATUS_RECORD_ID,SALESORG_ID,SAP_PART_NUMBER,MATERIAL_NAME,SALESORG_RECORD_ID,SALESORG_NAME,ITMCATGRP_ID,ITMCATGRP_RECORD_ID,DISTRIBUTIONCHANNEL_ID,DISTRIBUTIONCHANNEL_RECORD_ID,DIVISION_ID,DIVISION_RECORD_ID,SALESUOM_ID,SALESUOM_RECORD_ID,MATERIAL_SALES_ORG_PLANT__RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_MAMSOP.*,CONVERT(VARCHAR(4000),NEWID()),''"
				+ str(User.UserName)
				+ "'',GETDATE() FROM (	SELECT DISTINCT  MAMSOP_INBOUND.PLANT_ID,MAPLNT.PLANT_RECORD_ID,MAMTRL.MATERIAL_RECORD_ID,CONVERT(DATE,VALID_FROM) AS MATSTAT_VALFRM,MAMTST.MATERIALSTATUS_ID,MAMTST.MATERIAL_STATUS_RECORD_ID,MAMSOP_INBOUND.SALESORG_ID,MAMSOP_INBOUND.SAP_PART_NUMBER,MAMTRL.SAP_DESCRIPTION AS MATERIAL_NAME,SASORG.SALES_ORG_RECORD_ID AS SALESORG_RECORD_ID,SASORG.SALESORG_NAME,MAMSOP_INBOUND.ITMCATGRP_ID,MAITCG.ITEM_CATEGORY_GROUP_RECORD_ID AS ITMCATGRP_RECORD_ID,SADSCH.DISTRIBUTIONCHANNEL_ID,SADSCH.DISTRIBUTION_CHANNEL_RECORD_ID AS DISTRIBUTIONCHANNEL_RECORD_ID,MAMTRL.DIVISION_ID,MAMTRL.DIVISION_RECORD_ID,MAMUOM.UOM,MAMUOM.UNIT_OF_MEASURE_RECORD_ID FROM MAMSOP_INBOUND (NOLOCK) JOIN TEMP_PROCESS(NOLOCK) ON MAMSOP_INBOUND.SAP_PART_NUMBER = TEMP_PROCESS.SESSION_ID INNER JOIN MAMTRL (NOLOCK) ON MAMSOP_INBOUND.SAP_PART_NUMBER = MAMTRL.SAP_PART_NUMBER JOIN SASORG (NOLOCK) ON MAMSOP_INBOUND.SALESORG_ID = SASORG.SALESORG_ID JOIN SADSCH (NOLOCK) ON MAMSOP_INBOUND.DISTRIBUTIONCHANNEL_ID = SADSCH.DISTRIBUTIONCHANNEL_ID  LEFT JOIN MAPLNT (NOLOCK) ON MAMSOP_INBOUND.PLANT_ID = MAPLNT.PLANT_ID LEFT JOIN MAMTST (NOLOCK) ON CASE WHEN ISNULL(MAMSOP_INBOUND.MATERIALSTATUS_ID,'''')='''' THEN ''AC'' ELSE MAMSOP_INBOUND.MATERIALSTATUS_ID END = MAMTST.MATERIALSTATUS_ID LEFT JOIN MAITCG (NOLOCK) ON MAMSOP_INBOUND.ITMCATGRP_ID = MAITCG.ITMCATGRP_ID LEFT JOIN MAMUOM MAMUOM(NOLOCK) ON MAMSOP_INBOUND.SALESUOM_ID = MAMUOM.UOM WHERE ISNULL(MAMSOP_INBOUND.PROCESS_STATUS,'''')=''READY FOR UPLOAD'' AND ISNULL(MAMSOP_INBOUND.ERROR,'''')='''' AND MAMSOP_INBOUND.TIMESTAMP = '"+ str(timestamp_sessionid)+ "' AND ISNULL(TEMP_PROCESS.PROCESS_STATUS,'''')='''' )SUB_MAMSOP LEFT JOIN MAMSOP (NOLOCK) ON SUB_MAMSOP.SAP_PART_NUMBER = MAMSOP.SAP_PART_NUMBER AND SUB_MAMSOP.SALESORG_ID = MAMSOP.SALESORG_ID  WHERE MAMSOP.SAP_PART_NUMBER IS NULL '"
				)
				
			UpdateQuery = SqlHelper.GetFirst(
				"sp_executesql @T=N'update TEMP_PROCESS set process_status=''completed'' where isnulL(process_status,'''')='''' ' "
				)
		else:
			Check_flag = 0
	
	DeleteQuery = SqlHelper.GetFirst(
				"sp_executesql @T=N'Delete from TEMP_PROCESS Where process_status=''completed'' ' "
				)
	
	Check_flag1 = 1
	while Check_flag1 == 1:
		primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter.QUERY_CRITERIA_1)
			+ " TEMP_PROCESS (SESSION_ID)SELECT DISTINCT TOP 5000 MAMSOP_INBOUND.SAP_PART_NUMBER FROM MAMSOP_INBOUND(NOLOCK) LEFT JOIN TEMP_PROCESS(NOLOCK) ON MAMSOP_INBOUND.SAP_PART_NUMBER = TEMP_PROCESS.SESSION_ID WHERE MAMSOP_INBOUND.PROCESS_STATUS=''READY FOR UPLOAD'' AND ISNULL(ERROR,'''')=''''  AND MAMSOP_INBOUND.TIMESTAMP='"
			+ str(timestamp_sessionid)
			+ "' AND TEMP_PROCESS.SESSION_ID IS NULL  ' "
		)

		primaryQueryItems = SqlHelper.GetFirst(
			"select 'x' as a from TEMP_PROCESS(nolock)  where isnull(PROCESS_STATUS,'')='' "
		)

		if str(primaryQueryItems) != "None":

			primaryQueryItems = SqlHelper.GetFirst(
				""
				+ str(Parameter.QUERY_CRITERIA_1)
				+ " MAMASO(SALESORG_ID,SALESORG_NAME,SALESORG_RECORD_ID,SAP_DESCRIPTION,MATERIAL_RECORD_ID,SAP_PART_NUMBER,MATERIAL_SALES_ORG_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED) SELECT SUB_MAMSOP.SALESORG_ID,SUB_MAMSOP.SALESORG_NAME ,SUB_MAMSOP.SALESORG_RECORD_ID ,SUB_MAMSOP.SAP_DESCRIPTION ,SUB_MAMSOP.MATERIAL_RECORD_ID ,SUB_MAMSOP.SAP_PART_NUMBER  ,CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)
				+ "'',GETDATE() FROM (SELECT DISTINCT MAMSOP.SALESORG_ID,MAMSOP.SALESORG_NAME ,MAMSOP.SALESORG_RECORD_ID ,MAMSOP.MATERIAL_NAME AS SAP_DESCRIPTION ,MAMSOP.MATERIAL_RECORD_ID ,MAMSOP.SAP_PART_NUMBER FROM MAMSOP(NOLOCK) JOIN TEMP_PROCESS(NOLOCK) ON MAMSOP.SAP_PART_NUMBER = TEMP_PROCESS.SESSION_ID WHERE ISNULL(TEMP_PROCESS.PROCESS_STATUS,'''')='''' )SUB_MAMSOP LEFT JOIN MAMASO(NOLOCK) ON SUB_MAMSOP.SAP_PART_NUMBER = MAMASO.SAP_PART_NUMBER AND SUB_MAMSOP.SALESORG_ID = MAMASO.SALESORG_ID WHERE MAMASO.SAP_PART_NUMBER IS NULL' ")
				
			primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  MAMSOP SET MATSOR_RECORD_ID = MATERIAL_SALES_ORG_RECORD_ID FROM MAMSOP (NOLOCK) JOIN TEMP_PROCESS(NOLOCK) ON MAMSOP.SAP_PART_NUMBER = TEMP_PROCESS.SESSION_ID JOIN MAMASO(NOLOCK) ON MAMSOP.SAP_PART_NUMBER = MAMASO.SAP_PART_NUMBER AND MAMSOP.SALESORG_ID = MAMASO.SALESORG_ID WHERE ISNULL(MATSOR_RECORD_ID,'''')='''' AND ISNULL(TEMP_PROCESS.PROCESS_STATUS,'''')='''' '")
			
			primaryQueryItems = SqlHelper.GetFirst(
			""
			+ str(Parameter1.QUERY_CRITERIA_1)
			+ "  MAMSOP SET MATPRIGRP_ID =MAMSOP_INBOUND.PRICEGROUP_ID,MATPRIGRP_RECORD_ID = MAPGRP.PRICE_GROUP_RECORD_ID,MATPRIGRP_NAME=PRICEGROUP_DESCRIPTION FROM MAMSOP (NOLOCK) JOIN TEMP_PROCESS(NOLOCK) ON MAMSOP.SAP_PART_NUMBER = TEMP_PROCESS.SESSION_ID JOIN MAMSOP_INBOUND(NOLOCK) ON MAMSOP.SAP_PART_NUMBER = MAMSOP_INBOUND.SAP_PART_NUMBER AND MAMSOP.SALESORG_ID = MAMSOP_INBOUND.SALESORG_ID JOIN MAPGRP (NOLOCK) ON MAPGRP.PRICEGROUP_ID = MAMSOP_INBOUND.PRICEGROUP_ID WHERE MAMSOP_INBOUND.PROCESS_STATUS=''READY FOR UPLOAD'' AND MAMSOP_INBOUND.TIMESTAMP='"
					+ str(timestamp_sessionid)
					+ "' AND ISNULL(TEMP_PROCESS.PROCESS_STATUS,'''')='''' '")
				
			UpdateQuery = SqlHelper.GetFirst(
				"sp_executesql @T=N'update TEMP_PROCESS set process_status=''completed'' where isnulL(process_status,'''')='''' ' "
				)
		else:
			Check_flag1 = 0
	
	DeleteQuery = SqlHelper.GetFirst(
				"sp_executesql @T=N'Delete from TEMP_PROCESS Where process_status=''completed'' ' "
				)

	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAMSOP_INBOUND SET PROCESS_STATUS = ''UPLOADED'' WHERE PROCESS_STATUS=''READY FOR UPLOAD'' AND TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "'  '"
	)
	
	#Insert Query
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter.QUERY_CRITERIA_1)
	+ " MAMACT (CATEGORY_ID,CATEGORY_NAME,CATEGORY_RECORD_ID,MATERIAL_RECORD_ID,PAR_CATEGORY_ID,PAR_CATEGORY_NAME,SAP_DESCRIPTION,SAP_PART_NUMBER,CATEGORY_PRODUCT_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED)SELECT SUB_MAMACT.*, CONVERT(VARCHAR(4000),NEWID()),''"+ str(User.UserName)+ "'',GETDATE() FROM (SELECT DISTINCT MACATG.CATEGORY_ID,MACATG.CATEGORY_NAME,MACATG.CATEGORY_RECORD_ID,MAMTRL.MATERIAL_RECORD_ID,MACATG.PAR_CATEGORY_ID,MACATG.PAR_CATEGORY_NAME,MAMTRL.SAP_DESCRIPTION,MAMTRL.SAP_PART_NUMBER FROM MAMACT_INBOUND(NOLOCK) JOIN MACATG(NOLOCK) on MAMACT_INBOUND.CATEGORY_ID = MACATG.CATEGORY_ID JOIN MAMTRL(NOLOCK) ON MAMACT_INBOUND.SAP_PART_NUMBER = MAMTRL.SAP_PART_NUMBER   WHERE MAMACT_INBOUND.PROCESS_STATUS = ''READY FOR UPLOAD''  AND ISNULL(MAMACT_INBOUND.ERROR,'''') = '''' AND MAMACT_INBOUND.TIMESTAMP='"+ str(timestamp_sessionid)+ "')SUB_MAMACT LEFT JOIN MAMACT(NOLOCK) ON SUB_MAMACT.CATEGORY_ID = MAMACT.CATEGORY_ID AND SUB_MAMACT.SAP_PART_NUMBER = MAMACT.SAP_PART_NUMBER WHERE MAMACT.CATEGORY_ID IS NULL '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAMACT_INBOUND SET PROCESS_STATUS = ''UPLOADED'' WHERE PROCESS_STATUS=''READY FOR UPLOAD'' AND TIMESTAMP='"
	+ str(timestamp_sessionid)
	+ "'  '"
	)
	
	primaryQueryItems = SqlHelper.GetFirst(
	""
	+ str(Parameter1.QUERY_CRITERIA_1)
	+ "  MAKTPT SET PART_RECORD_ID = MATERIAL_RECORD_ID FROM MAKTPT (NOLOCK) JOIN MAMTRL(NOLOCK) ON MAKTPT.PART_NUMBER = MAMTRL.SAP_PART_NUMBER WHERE ISNULL(MAKTPT.PART_RECORD_ID,'''')=''''  '"
	)
	
	#MATMAS Errors mail system 
	Error_list = []
	Resp_msg = {}
	Lst_resp = []
	Error_check = 1
	while Error_check == 1:
		Error_primaryQuery = SqlHelper.GetList(
			"select top 10 SESSION_ID from ERROR_LOG(NOLOCK) where ISNULL(PROCESS_STATUS,'')= '' and isnull(SESSION_ID,'')<>''  "
		)

		Session_lst_count = []
		for data in Error_primaryQuery:
			Session_lst_count.append(data.SESSION_ID)

		Session_lst = tuple(Session_lst_count)
		# Log.Info("2608 2608 Session_lst------>"+str(Session_lst))
		if len(Session_lst_count) == 1:
			Session_lst = "('" + Session_lst_count[0] + "')"
		
		if len(Session_lst_count) > 0:
			primaryQueryItems = SqlHelper.GetList(
				"select distinct sap_part_number,ERROR from mamtrl_inbound (nolock) where isnull(ERROR,'')<>'' and session_id in "
				+ str(Session_lst)
				+ " union select distinct sap_part_number,ERROR from mamsop_inbound (nolock) where isnull(ERROR,'')<>'' and session_id in "
				+ str(Session_lst)
				+ "union select distinct sap_part_number,ERROR from mamsop_inbound (nolock) where isnull(ERROR,'')<>'' and session_id in "
				+ str(Session_lst)
				+ " union select distinct sap_part_number,ERROR from mamact_inbound (nolock) where isnull(ERROR,'')<>'' and session_id in "
				+ str(Session_lst)
				+ " "
			)
			Dt = {}
			for ins in primaryQueryItems:
				Modi_integration_status = []
				inte_status = str(ins.ERROR).split("||")
				ERROR = set(inte_status)
				ERROR = list(ERROR)
				if "" in ERROR:
					ERROR.remove("")
				
				for uu in ERROR:
					split_data = uu.split("-", 1)
					SYMSGS_MSG_TEXT = SqlHelper.GetFirst(
						"SELECT MESSAGE_TEXT,RECORD_ID AS REC_ID,OBJECT_APINAME,OBJECT_RECORD_ID,MESSAGE_TYPE FROM SYMSGS(NOLOCK) WHERE MESSAGE_CODE = '"
						+ str(split_data[0])
						+ "'"
					)

					if len(split_data) > 1:
						CONVERTED_MSG = SYMSGS_MSG_TEXT.MESSAGE_TEXT + " - " + split_data[-1]
					else:
						CONVERTED_MSG = SYMSGS_MSG_TEXT.MESSAGE_TEXT

					Modi_integration_status.append(CONVERTED_MSG)
					
					SYELOG_tableInfo = SqlHelper.GetTable("SYELOG")
					GuidQuery = SqlHelper.GetFirst("SELECT CONVERT(VARCHAR(4000),NEWID()) AS A")
					Dit = {}
					Dit["ERROR_LOGS_RECORD_ID"] = GuidQuery.A
					Dit["ERRORMESSAGE_RECORD_ID"] = SYMSGS_MSG_TEXT.REC_ID
					Dit["ERRORMESSAGE_DESCRIPTION"] = SYMSGS_MSG_TEXT.MESSAGE_TEXT
					Dit["OBJECT_RECORD_ID"] = SYMSGS_MSG_TEXT.OBJECT_RECORD_ID
					Dit["OBJECT_TYPE"] = SYMSGS_MSG_TEXT.MESSAGE_TYPE
					Dit["OBJECT_NAME"] = SYMSGS_MSG_TEXT.OBJECT_APINAME
					if len(split_data) > 1:
						Dit["OBJECT_VALUE"] = split_data[-1]
					if len(split_data) == 1:
						Dit["OBJECT_VALUE"] = ""
					Dit["CPQTABLEENTRYDATEADDED"] = Modi_date
					Dit["CPQTABLEENTRYADDEDBY"] = User.UserName
					SYELOG_tableInfo.AddRow(Dit)
				sqlInfo = SqlHelper.Upsert(SYELOG_tableInfo)
				if str(ins.sap_part_number) in Dt:
					for data in Modi_integration_status:
						if data not in Dt[ins.sap_part_number]:
							Dt[ins.sap_part_number].append(data)
				else:
					Dt[ins.sap_part_number] = Modi_integration_status
					
				for sap_part_number in Dt:
					inte_status_info = ""
					# Log.Info("232323 sap_part_number--->"+str(sap_part_number))
					for data in Dt[sap_part_number]:
						inte_status_info = inte_status_info + data + "||"

					Error_list.append(sap_part_number + "--" + inte_status_info[:-2])

				ErrorQueryItems = SqlHelper.GetFirst(""+ str(Parameter1.QUERY_CRITERIA_1)+ "  "+str(Temp_Table_Name)+" SET PROCESS_STATUS = ''UPLOADED'' WHERE SESSION_ID  IN "+ str(Session_lst).replace("'","''")+ "  '")



		
		else:
			Error_check = 0
	#Log.Info("456789 ---->"+str(Error_list))		
	if len(Error_list) > 0:
	
		Header = "<!DOCTYPE html><html><head><style>table {font-family: Calibri, sans-serif; border-collapse: collapse; width: 75%}td, th {  border: 1px solid #dddddd;  text-align: left; padding: 8px;}.im {color: #222;}tr:nth-child(even) {background-color: #dddddd;}</style></head><body>"

		Table_start = "<p>Hi Team,<br>Please find the below exceptions for your reference</p><table class='table table-bordered'><tr><th>SNO</th><th>SAP_PART_NUMBER</th><th>ERROR MESSAGE</th></tr>"
		Table_End = "</table><p><strong>Note : </strong>Please do not reply to this email.</p></body></html>"
		Table_info = ""
		unique_Error_list = set(Error_list)
		for indx, data in enumerate(unique_Error_list, 1):
			data = data.split("--")
			Table_record = (
				"<tr>"
				+ "<td>"
				+ str(indx)
				+ "</td>"
				+ "<td>"
				+ str(data[0])
				+ "</td>"
				+ "<td>"
				+ str(data[-1])
				+ "</td>"
				+ "</tr>"
			)
			Table_info = Table_info + Table_record

		Error_Info = Header + Table_start + Table_info + Table_End

		LOGIN_CRE = SqlHelper.GetFirst("SELECT USER_NAME as Username,Password FROM SYCONF where Domain ='SUPPORT_MAIL'")

		# Create new SmtpClient object
		mailClient = SmtpClient()

		# Set the host and port (eg. smtp.gmail.com)
		mailClient.Host = "smtp.gmail.com"
		mailClient.Port = 587
		mailClient.EnableSsl = "true"

		# Setup NetworkCredential
		mailCred = NetworkCredential()
		mailCred.UserName = str(LOGIN_CRE.Username)
		mailCred.Password = str(LOGIN_CRE.Password)
		mailClient.Credentials = mailCred

		# Create two mail adresses, one for send from and the another for recipient
		toEmail = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
		fromEmail = MailAddress("INTEGRATION.SUPPORT@BOSTONHARBORCONSULTING.COM")

		# Create new MailMessage object
		msg = MailMessage(fromEmail, toEmail)

		# Set message subject and body
		msg.Subject = "AMAT INTEGRATION MATMAS EXCEPTIONS - CPQ(X-Tenant)"
		msg.IsBodyHtml = True
		msg.Body = Error_Info

		# CC Emails	
		copyEmail5 = MailAddress("suresh.muniyandi@bostonharborconsulting.com")
		msg.CC.Add(copyEmail5)
		
		copyEmail4 = MailAddress("baji.baba@bostonharborconsulting.com")
		msg.CC.Add(copyEmail4)
		
		# Send the message
		mailClient.Send(msg)
		Result = '{"Response": [{"Status": "400", "Message": "Error mail sended"}]}'

	else:
		Result = '{"Response": [{"Status": "200", "Message": "Data successfully uploaded"}]}'


	#Deleting dynamically created table(ERROR_LOG
	TempTable = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(Temp_Table_Name)+"'' ) BEGIN DROP TABLE "+str(Temp_Table_Name)+" END'")
	ERRLOG_DRP = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''TEMP_PROCESS'' ) BEGIN DROP TABLE TEMP_PROCESS END ' ")
	
except:

	#Deleting dynamically created table(ERROR_LOG)
	Temp_Table_Name = 'ERROR_LOG'
	TempTable = SqlHelper.GetFirst("sp_executesql @T=N'IF EXISTS (SELECT ''X'' FROM SYS.OBJECTS WHERE NAME= ''"+str(Temp_Table_Name)+"'' ) BEGIN DROP TABLE "+str(Temp_Table_Name)+" END'")

	Log.Info("BULK MATMAS ERROR---->:" + str(sys.exc_info()[1]))
	Log.Info("BULK MATMAS ERROR LINE NO---->:" + str(sys.exc_info()[-1].tb_lineno))
	error_info = {"Response": [{"Status": "400", "Message": str(sys.exc_info()[1])}]}
	Result  = str(error_info)
