# =========================================================================================================================================
#   __script_name : CQVLDPRDEF.PY
#   __script_description : THIS SCRIPT IS USED FOR PREDEFINED VALUES IN VALUE DRIVER (GETS TRIGGERED AFTER IFLOW SCRIPT - CQTVLDRIFW.py)
#   __primary_author__ : 
#   __create_date :06-09-2021
#   © BOSTON HARBOR TECHNOLOGY LLC - ALL RIGHTS RESERVED
# ==========================================================================================================================================
import Webcom.Configurator.Scripting.Test.TestProduct
import clr
import System.Net
import sys
import datetime
from System.Net import CookieContainer, NetworkCredential, Mail
from System.Net.Mail import SmtpClient, MailAddress, Attachment, MailMessage
from SYDATABASE import SQL

Sql = SQL()


try:
    Qt_rec_id = Param.CPQ_Columns['Quote'] 
except:
    Qt_rec_id = ""

#Log.Info("Qt_rec_id ->"+str(Qt_rec_id))
try:
    LEVEL = Param.CPQ_Columns['Level']
except:
    LEVEL = ""

try:
    TreeParam = Param.CPQ_Columns['TreeParam']
    TreeParentParam = Param.CPQ_Columns['TreeParentParam']
    TreeSuperParentParam = Param.CPQ_Columns['TreeSuperParentParam']
    TreeTopSuperParentParam = Param.CPQ_Columns['TreeTopSuperParentParam']
    userId = Param.CPQ_Columns['Userid']
    userName = Param.CPQ_Columns['Username']
    quote_revision_record_id = Param.CPQ_Columns['quote_revision_record_id']
except: 
    TreeParam = ""
    TreeParentParam = ""
    TreeSuperParentParam = ""
    TreeTopSuperParentParam = ""
    userId = ""
    userName = ""
    quote_revision_record_id = ""


##A055S000P01-4420 starts
def predefined_wafer():
    saqscd_insert_wafer = """ INSERT SAQSCD (
        QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
        EQUIPMENT_DESCRIPTION,
        EQUIPMENT_ID,
        EQUIPMENT_RECORD_ID,
        QUOTE_ID,
        QUOTE_NAME,
        QUOTE_RECORD_ID,
        SERIAL_NUMBER,
        QTESRVCOB_RECORD_ID,
        SERVICE_DESCRIPTION,
        SERVICE_ID,
        SERVICE_RECORD_ID,
        VALUEDRIVER_ID,
        VALUEDRIVER_RECORD_ID,
        VALUEDRIVER_TYPE,
        VALUEDRIVER_NAME,
        GREENBOOK,
        GREENBOOK_RECORD_ID,
        FABLOCATION_ID,
        FABLOCATION_NAME,
        FABLOCATION_RECORD_ID,
        QTESRVFBL_RECORD_ID,
        QTESRVGBK_VDR_RECORD_ID,
        CPQTABLEENTRYADDEDBY,
        CPQTABLEENTRYDATEADDED,
        QTEREV_ID,
        QTEREV_RECORD_ID)
        SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
        SAQSCO.EQUIPMENT_DESCRIPTION,
        SAQSCO.EQUIPMENT_ID,
        SAQSCO.EQUIPMENT_RECORD_ID,
        SAQSCO.QUOTE_ID,
        SAQSCO.QUOTE_NAME,
        SAQSCO.QUOTE_RECORD_ID,
        SAQSCO.SERIAL_NO as SERIAL_NUMBER,
        SAQSCO.QUOTE_SERVICE_COVERED_OBJECTS_RECORD_ID,
        SAQSCO.SERVICE_DESCRIPTION,
        SAQSCO.SERVICE_ID,
        SAQSCO.SERVICE_RECORD_ID,
        PRSVDR.VALUEDRIVER_ID,
        PRSVDR.VALUEDRIVER_RECORD_ID,
        PRSVDR.VALUEDRIVER_TYPE,
        PRSVDR.VALUEDRIVER_NAME,
        SAQSCO.GREENBOOK,
        SAQSCO.GREENBOOK_RECORD_ID,
        SAQSCO.FABLOCATION_ID,
        SAQSCO.FABLOCATION_NAME,
        SAQSCO.FABLOCATION_RECORD_ID,
        '' as QTESRVFBL_RECORD_ID,
        '' as QTESRVGBK_VDR_RECORD_ID,
        '{username}' as CPQTABLEENTRYADDEDBY ,
        '{datetimenow}' as CPQTABLEENTRYDATEADDED ,
        SAQSCO.QTEREV_ID,
        SAQSCO.QTEREV_RECORD_ID 
        from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_RECORD_ID = SAQSCO.EQUIPMENT_RECORD_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID  WHERE  SAQSCO.QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}'  AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = 'Wafer-Node' AND (MAEQUP.VALDRV_WAFERNODE is not null or MAEQUP.VALDRV_WAFERNODE != '') AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCD.VALUEDRIVER_ID = 'Wafer-Node' )""".format(Qt_rec_id=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)


    saqscv_insert_wafer = """ INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,
            EQUIPMENT_DESCRIPTION,
            EQUIPMENT_ID,
            EQUIPMENT_RECORD_ID,
            QUOTE_ID,
            QUOTE_NAME,
            QUOTE_RECORD_ID,
            QTESRVCOB_RECORD_ID,
            QTESRVCOB_VDR_RECORD_ID,
            SERIAL_NUMBER,
            SERVICE_DESCRIPTION,
            SERVICE_ID,
            SERVICE_RECORD_ID,
            TOOL_VALUEDRIVER_ID,
            TOOL_VALUEDRIVER_RECORD_ID,
            TOOL_VALUEDRIVER_VALUE_CODE,
            TOOL_VALUEDRIVER_VALUE_DESCRIPTION,
            GREENBOOK,
            GREENBOOK_RECORD_ID,
            TOOL_VALUEDRIVER_VALUE_RECORD_ID,
            VALUEDRIVER_COEFFICIENT,
            VALUEDRIVER_COEFFICIENT_RECORD_ID,
            FABLOCATION_ID,
            CPQTABLEENTRYADDEDBY,
            ADDUSR_RECORD_ID,
            FABLOCATION_NAME,
            FABLOCATION_RECORD_ID,
            CPQTABLEENTRYDATEADDED,
            QTESRVFBL_RECORD_ID,
            QTEREV_ID,
            QTEREV_RECORD_ID)
            SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,
            SAQSCO.EQUIPMENT_DESCRIPTION,
            SAQSCO.EQUIPMENT_ID,
            SAQSCO.EQUIPMENT_RECORD_ID,
            SAQSCO.QUOTE_ID,
            SAQSCO.QUOTE_NAME,
            SAQSCO.QUOTE_RECORD_ID,
            SAQSCO.QUOTE_SERVICE_COVERED_OBJECTS_RECORD_ID,
            SAQSCD.QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID as QTESRVCOB_VDR_RECORD_ID,
            SAQSCO.SERIAL_NO as SERIAL_NUMBER,
            SAQSCO.SERVICE_DESCRIPTION,
            SAQSCO.SERVICE_ID,
            SAQSCO.SERVICE_RECORD_ID,
            PRSDVL.VALUEDRIVER_ID,
            PRSDVL.VALUEDRIVER_RECORD_ID,
            PRSDVL.VALUEDRIVER_VALUE_CODE,
            PRSDVL.VALUEDRIVER_VALUE_DESCRIPTION,
            SAQSCO.GREENBOOK,
            SAQSCO.GREENBOOK_RECORD_ID,
            PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,
            PRSDVL.VALUEDRIVER_COEFFICIENT,
            PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,
            SAQSCO.FABLOCATION_ID,
            '{username}' as CPQTABLEENTRYADDEDBY ,
            '{userid}' as ADDUSR_RECORD_ID ,
            SAQSCO.FABLOCATION_NAME,
            SAQSCO.FABLOCATION_RECORD_ID,
            '{datetimenow}' as CPQTABLEENTRYDATEADDED,
            '' as QTESRVFBL_RECORD_ID,
            SAQSCO.QTEREV_ID as QTEREV_ID,
            SAQSCO.QTEREV_RECORD_ID 
            from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_RECORD_ID = SAQSCO.EQUIPMENT_RECORD_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID AND PRSDVL.VALUEDRIVER_VALUE_CODE = MAEQUP.VALDRV_WAFERNODE INNER JOIN SAQSCD ON SAQSCO.SERVICE_ID = SAQSCD.SERVICE_ID AND SAQSCO.QUOTE_RECORD_ID = SAQSCD.QUOTE_RECORD_ID  AND SAQSCO.QTEREV_RECORD_ID = SAQSCD.QTEREV_RECORD_ID AND SAQSCO.EQUIPMENT_RECORD_ID = SAQSCD.EQUIPMENT_RECORD_ID and SAQSCD.VALUEDRIVER_ID = 'Wafer-Node' WHERE SAQSCO.QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSDVL.VALUEDRIVER_ID = 'Wafer-Node' AND (MAEQUP.VALDRV_WAFERNODE is not null or MAEQUP.VALDRV_WAFERNODE != '') AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCV.TOOL_VALUEDRIVER_ID = 'Wafer-Node')""".format(Qt_rec_id=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
    #Log.Info('saqscd_insert--wafer'+str(saqscd_insert_wafer))
    #Log.Info('saqscv_insert--wafer'+str(saqscv_insert_wafer))
    Sql.RunQuery(saqscd_insert_wafer)
    Sql.RunQuery(saqscv_insert_wafer)
##A055S000P01-4420 ends

##A055S000P01-8778 starts
def predefined_device_type():
    Log.Info('device fn')
    saqscd_insert_device = """ INSERT SAQSCD (
        QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
        EQUIPMENT_DESCRIPTION,
        EQUIPMENT_ID,
        EQUIPMENT_RECORD_ID,
        QUOTE_ID,
        QUOTE_NAME,
        QUOTE_RECORD_ID,
        SERIAL_NUMBER,
        QTESRVCOB_RECORD_ID,
        SERVICE_DESCRIPTION,
        SERVICE_ID,
        SERVICE_RECORD_ID,
        VALUEDRIVER_ID,
        VALUEDRIVER_RECORD_ID,
        VALUEDRIVER_TYPE,
        VALUEDRIVER_NAME,
        GREENBOOK,
        GREENBOOK_RECORD_ID,
        FABLOCATION_ID,
        FABLOCATION_NAME,
        FABLOCATION_RECORD_ID,
        QTESRVFBL_RECORD_ID,
        QTESRVGBK_VDR_RECORD_ID,
        CPQTABLEENTRYADDEDBY,
        CPQTABLEENTRYDATEADDED,
        QTEREV_ID,
        QTEREV_RECORD_ID)
        SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
        SAQSCO.EQUIPMENT_DESCRIPTION,
        SAQSCO.EQUIPMENT_ID,
        SAQSCO.EQUIPMENT_RECORD_ID,
        SAQSCO.QUOTE_ID,
        SAQSCO.QUOTE_NAME,
        SAQSCO.QUOTE_RECORD_ID,
        SAQSCO.SERIAL_NO as SERIAL_NUMBER,
        SAQSCO.QUOTE_SERVICE_COVERED_OBJECTS_RECORD_ID,
        SAQSCO.SERVICE_DESCRIPTION,
        SAQSCO.SERVICE_ID,
        SAQSCO.SERVICE_RECORD_ID,
        PRSVDR.VALUEDRIVER_ID,
        PRSVDR.VALUEDRIVER_RECORD_ID,
        PRSVDR.VALUEDRIVER_TYPE,
        PRSVDR.VALUEDRIVER_NAME,
        SAQSCO.GREENBOOK,
        SAQSCO.GREENBOOK_RECORD_ID,
        SAQSCO.FABLOCATION_ID,
        SAQSCO.FABLOCATION_NAME,
        SAQSCO.FABLOCATION_RECORD_ID,
        '' as QTESRVFBL_RECORD_ID,
        '' as QTESRVGBK_VDR_RECORD_ID,
        '{username}' as CPQTABLEENTRYADDEDBY ,
        '{datetimenow}' as CPQTABLEENTRYDATEADDED ,
        SAQSCO.QTEREV_ID,
        SAQSCO.QTEREV_RECORD_ID 
        from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_RECORD_ID = SAQSCO.EQUIPMENT_RECORD_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID  WHERE  SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}'  AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = 'Device Type' AND (MAEQUP.VALDRV_DEVICETYPE is not null or MAEQUP.VALDRV_DEVICETYPE != '') AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND SAQSCD.VALUEDRIVER_ID = 'Device Type' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)


    saqscv_insert_device = """ INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,
            EQUIPMENT_DESCRIPTION,
            EQUIPMENT_ID,
            EQUIPMENT_RECORD_ID,
            QUOTE_ID,
            QUOTE_NAME,
            QUOTE_RECORD_ID,
            QTESRVCOB_RECORD_ID,
            QTESRVCOB_VDR_RECORD_ID,
            SERIAL_NUMBER,
            SERVICE_DESCRIPTION,
            SERVICE_ID,
            SERVICE_RECORD_ID,
            TOOL_VALUEDRIVER_ID,
            TOOL_VALUEDRIVER_RECORD_ID,
            TOOL_VALUEDRIVER_VALUE_CODE,
            TOOL_VALUEDRIVER_VALUE_DESCRIPTION,
            GREENBOOK,
            GREENBOOK_RECORD_ID,
            TOOL_VALUEDRIVER_VALUE_RECORD_ID,
            VALUEDRIVER_COEFFICIENT,
            VALUEDRIVER_COEFFICIENT_RECORD_ID,
            FABLOCATION_ID,
            CPQTABLEENTRYADDEDBY,
            ADDUSR_RECORD_ID,
            FABLOCATION_NAME,
            FABLOCATION_RECORD_ID,
            CPQTABLEENTRYDATEADDED,
            QTESRVFBL_RECORD_ID,
            QTEREV_ID,
            QTEREV_RECORD_ID)
            SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,
            SAQSCO.EQUIPMENT_DESCRIPTION,
            SAQSCO.EQUIPMENT_ID,
            SAQSCO.EQUIPMENT_RECORD_ID,
            SAQSCO.QUOTE_ID,
            SAQSCO.QUOTE_NAME,
            SAQSCO.QUOTE_RECORD_ID,
            SAQSCO.QUOTE_SERVICE_COVERED_OBJECTS_RECORD_ID,
            SAQSCD.QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID as QTESRVCOB_VDR_RECORD_ID,
            SAQSCO.SERIAL_NO as SERIAL_NUMBER,
            SAQSCO.SERVICE_DESCRIPTION,
            SAQSCO.SERVICE_ID,
            SAQSCO.SERVICE_RECORD_ID,
            PRSDVL.VALUEDRIVER_ID,
            PRSDVL.VALUEDRIVER_RECORD_ID,
            MAEQUP.VALDRV_DEVICETYPE,
            PRSDVL.VALUEDRIVER_VALUE_DESCRIPTION,
            SAQSCO.GREENBOOK,
            SAQSCO.GREENBOOK_RECORD_ID,
            PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,
            PRSDVL.VALUEDRIVER_COEFFICIENT,
            PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,
            SAQSCO.FABLOCATION_ID,
            '{username}' as CPQTABLEENTRYADDEDBY ,
            '{userid}' as ADDUSR_RECORD_ID ,
            SAQSCO.FABLOCATION_NAME,
            SAQSCO.FABLOCATION_RECORD_ID,
            '{datetimenow}' as CPQTABLEENTRYDATEADDED,
            '' as QTESRVFBL_RECORD_ID,
            SAQSCO.QTEREV_ID as QTEREV_ID,
            SAQSCO.QTEREV_RECORD_ID 
            from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_RECORD_ID = SAQSCO.EQUIPMENT_RECORD_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID AND PRSDVL.VALUEDRIVER_VALUE_CODE = MAEQUP.VALDRV_DEVICETYPE INNER JOIN SAQSCD ON SAQSCO.SERVICE_ID = SAQSCD.SERVICE_ID AND SAQSCO.QUOTE_RECORD_ID = SAQSCD.QUOTE_RECORD_ID  AND SAQSCO.QTEREV_RECORD_ID = SAQSCD.QTEREV_RECORD_ID AND SAQSCO.EQUIPMENT_RECORD_ID = SAQSCD.EQUIPMENT_RECORD_ID and SAQSCD.VALUEDRIVER_ID = 'Device Type' WHERE SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSDVL.VALUEDRIVER_ID = 'Device Type' AND (MAEQUP.VALDRV_DEVICETYPE is not null or MAEQUP.VALDRV_DEVICETYPE != '') AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND SAQSCV.TOOL_VALUEDRIVER_ID = 'Device Type')""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
    #Log.Info('saqscd_insert-device-'+str(saqscd_insert_device))
    #Log.Info('saqscv_insert-device-'+str(saqscv_insert_device))
    Sql.RunQuery(saqscd_insert_device)
    Sql.RunQuery(saqscv_insert_device)

##A055S000P01-8778 ends
def predefined_csa_tools():
    
    account_id_query = Sql.GetFirst("SELECT ACCOUNT_ID FROM SAQTMT (NOLOCK) WHERE MASTER_TABLE_QUOTE_RECORD_ID = '"+str(Qt_rec_id)+"'")
    account_bluebook_query = Sql.GetFirst("SELECT BLUEBOOK FROM SAACNT (NOLOCK) WHERE ACCOUNT_ID = '"+str(account_id_query.ACCOUNT_ID)+"'")
    tools_count_query = SqlHelper.GetList("SELECT COUNT(GREENBOOK) AS COUNT FROM SAQSCO (NOLOCK) WHERE QUOTE_RECORD_ID = '"+str(Qt_rec_id)+"' GROUP BY FABLOCATION_NAME")
    Log.Info("tools_count_query-----> "+str(Qt_rec_id))
    if account_bluebook_query.BLUEBOOK != "DISPLAY":
        for count in tools_count_query:
            if count.COUNT > 50:
                quer_statement = """ INSERT SAQSCD (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,SERIAL_NUMBER,QTESRVCOB_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,VALUEDRIVER_ID,VALUEDRIVER_RECORD_ID,VALUEDRIVER_TYPE,VALUEDRIVER_NAME,GREENBOOK,GREENBOOK_RECORD_ID,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,QTESRVFBL_RECORD_ID,QTESRVGBK_VDR_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,'' as QTESRVCOB_RECORD_ID,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSVDR.VALUEDRIVER_ID,PRSVDR.VALUEDRIVER_RECORD_ID,PRSVDR.VALUEDRIVER_TYPE,PRSVDR.VALUEDRIVER_NAME,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,SAQSCO.FABLOCATION_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'' as QTESRVFBL_RECORD_ID,'' as QTESRVGBK_VDR_RECORD_ID,'{username}' as CPQTABLEENTRYADDEDBY ,'{datetimenow}' as CPQTABLEENTRYDATEADDED ,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID  WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD (NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND VALUEDRIVER_ID = '# of CSA tools in Fab' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement)
                
                quer_statement_2 = """ INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,QTESRVCOB_RECORD_ID,QTESRVCOB_VDR_RECORD_ID,SERIAL_NUMBER,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,TOOL_VALUEDRIVER_ID,TOOL_VALUEDRIVER_RECORD_ID,TOOL_VALUEDRIVER_VALUE_CODE,TOOL_VALUEDRIVER_VALUE_DESCRIPTION,GREENBOOK,GREENBOOK_RECORD_ID,TOOL_VALUEDRIVER_VALUE_RECORD_ID,VALUEDRIVER_COEFFICIENT,VALUEDRIVER_COEFFICIENT_RECORD_ID,FABLOCATION_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,CPQTABLEENTRYDATEADDED,QTESRVFBL_RECORD_ID,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,'' as QTESRVCOB_RECORD_ID,SAQSCD.QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID as QTESRVCOB_VDR_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSDVL.VALUEDRIVER_ID,PRSDVL.VALUEDRIVER_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_CODE,PRSDVL.VALUEDRIVER_VALUE_DESCRIPTION,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,PRSDVL.VALUEDRIVER_COEFFICIENT,PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,SAQSCO.FABLOCATION_ID,'{username}' as CPQTABLEENTRYADDEDBY,'{userid}' as ADDUSR_RECORD_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'{datetimenow}' as CPQTABLEENTRYDATEADDED,'' as QTESRVFBL_RECORD_ID,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID INNER JOIN SAQSCD ON SAQSCO.SERVICE_ID = SAQSCD.SERVICE_ID AND SAQSCO.QTEREV_RECORD_ID = SAQSCD.QTEREV_RECORD_ID AND SAQSCO.EQUIPMENT_ID = SAQSCD.EQUIPMENT_ID AND SAQSCD.VALUEDRIVER_ID = PRSDVL.VALUEDRIVER_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND PRSDVL.VALUEDRIVER_VALUE_CODE = '# CSA tools in Fab_>50' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV(NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND TOOL_VALUEDRIVER_ID = '# of CSA tools in Fab' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement_2)
                Log.Info("quer_statement_2_chk_j "+str(quer_statement_2))
            elif count.COUNT in range(10,51):
                quer_statement = """ INSERT SAQSCD (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,SERIAL_NUMBER,QTESRVCOB_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,VALUEDRIVER_ID,VALUEDRIVER_RECORD_ID,VALUEDRIVER_TYPE,VALUEDRIVER_NAME,GREENBOOK,GREENBOOK_RECORD_ID,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,QTESRVFBL_RECORD_ID,QTESRVGBK_VDR_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,'' as QTESRVCOB_RECORD_ID,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSVDR.VALUEDRIVER_ID,PRSVDR.VALUEDRIVER_RECORD_ID,PRSVDR.VALUEDRIVER_TYPE,PRSVDR.VALUEDRIVER_NAME,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,SAQSCO.FABLOCATION_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'' as QTESRVFBL_RECORD_ID,'' as QTESRVGBK_VDR_RECORD_ID,'{username}' as CPQTABLEENTRYADDEDBY ,'{datetimenow}' as CPQTABLEENTRYDATEADDED ,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID  WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD (NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND VALUEDRIVER_ID = '# of CSA tools in Fab' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement)
                
                quer_statement_2 = """ INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,QTESRVCOB_RECORD_ID,QTESRVCOB_VDR_RECORD_ID,SERIAL_NUMBER,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,TOOL_VALUEDRIVER_ID,TOOL_VALUEDRIVER_RECORD_ID,TOOL_VALUEDRIVER_VALUE_CODE,TOOL_VALUEDRIVER_VALUE_DESCRIPTION,GREENBOOK,GREENBOOK_RECORD_ID,TOOL_VALUEDRIVER_VALUE_RECORD_ID,VALUEDRIVER_COEFFICIENT,VALUEDRIVER_COEFFICIENT_RECORD_ID,FABLOCATION_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,CPQTABLEENTRYDATEADDED,QTESRVFBL_RECORD_ID,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,'' as QTESRVCOB_RECORD_ID,SAQSCD.QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID as QTESRVCOB_VDR_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSDVL.VALUEDRIVER_ID,PRSDVL.VALUEDRIVER_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_CODE,PRSDVL.VALUEDRIVER_VALUE_DESCRIPTION,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,PRSDVL.VALUEDRIVER_COEFFICIENT,PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,SAQSCO.FABLOCATION_ID,'{username}' as CPQTABLEENTRYADDEDBY,'{userid}' as ADDUSR_RECORD_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'{datetimenow}' as CPQTABLEENTRYDATEADDED,'' as QTESRVFBL_RECORD_ID,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID INNER JOIN SAQSCD ON SAQSCO.SERVICE_ID = SAQSCD.SERVICE_ID AND SAQSCO.QTEREV_RECORD_ID = SAQSCD.QTEREV_RECORD_ID AND SAQSCO.EQUIPMENT_ID = SAQSCD.EQUIPMENT_ID AND SAQSCD.VALUEDRIVER_ID = PRSDVL.VALUEDRIVER_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND PRSDVL.VALUEDRIVER_VALUE_CODE = '# CSA tools in Fab_10-50' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV(NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND TOOL_VALUEDRIVER_ID = '# of CSA tools in Fab' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement_2)
                Log.Info("quer_statement_2_chk_j "+str(quer_statement_2))
            elif count.COUNT < 10:
                quer_statement = """ INSERT SAQSCD (
                    QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
                    EQUIPMENT_DESCRIPTION,
                    EQUIPMENT_ID,
                    EQUIPMENT_RECORD_ID,
                    QUOTE_ID,QUOTE_NAME,
                    QUOTE_RECORD_ID,
                    SERIAL_NUMBER,
                    QTESRVCOB_RECORD_ID,
                    SERVICE_DESCRIPTION,
                    SERVICE_ID,
                    SERVICE_RECORD_ID,
                    VALUEDRIVER_ID,
                    VALUEDRIVER_RECORD_ID,
                    VALUEDRIVER_TYPE,
                    VALUEDRIVER_NAME,
                    GREENBOOK,
                    GREENBOOK_RECORD_ID,
                    FABLOCATION_ID,
                    FABLOCATION_NAME,
                    FABLOCATION_RECORD_ID,
                    QTESRVFBL_RECORD_ID,
                    QTESRVGBK_VDR_RECORD_ID,
                    CPQTABLEENTRYADDEDBY,
                    CPQTABLEENTRYDATEADDED,
                    QTEREV_ID,
                    QTEREV_RECORD_ID
                )
                SELECT 
                CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
                SAQSCO.EQUIPMENT_DESCRIPTION,
                SAQSCO.EQUIPMENT_ID,
                SAQSCO.EQUIPMENT_RECORD_ID,
                SAQSCO.QUOTE_ID,
                SAQSCO.QUOTE_NAME,
                SAQSCO.QUOTE_RECORD_ID,
                SAQSCO.SERIAL_NO as SERIAL_NUMBER,
                '' as QTESRVCOB_RECORD_ID,
                SAQSCO.SERVICE_DESCRIPTION,
                SAQSCO.SERVICE_ID,
                SAQSCO.SERVICE_RECORD_ID,
                PRSVDR.VALUEDRIVER_ID,
                PRSVDR.VALUEDRIVER_RECORD_ID,
                PRSVDR.VALUEDRIVER_TYPE,
                PRSVDR.VALUEDRIVER_NAME,
                SAQSCO.GREENBOOK,
                SAQSCO.GREENBOOK_RECORD_ID,
                SAQSCO.FABLOCATION_ID,
                SAQSCO.FABLOCATION_NAME,
                SAQSCO.FABLOCATION_RECORD_ID,
                '' as QTESRVFBL_RECORD_ID,
                '' as QTESRVGBK_VDR_RECORD_ID,
                '{username}' as CPQTABLEENTRYADDEDBY ,
                '{datetimenow}' as CPQTABLEENTRYDATEADDED ,
                '' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID 
                from MAEQUP 
                INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK 
                INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID  
                WHERE 
                SAACNT.ACCOUNT_ID != 'DISPLAY' 
                AND SAQSCO.QUOTE_RECORD_ID ='{rec}' 
                AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' 
                AND SAQSCO.SERVICE_ID ='{treeparam}' 
                AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab'
                """.format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement)
                
                quer_statement_2 = """ INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,QTESRVCOB_RECORD_ID,QTESRVCOB_VDR_RECORD_ID,SERIAL_NUMBER,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,TOOL_VALUEDRIVER_ID,TOOL_VALUEDRIVER_RECORD_ID,TOOL_VALUEDRIVER_VALUE_CODE,TOOL_VALUEDRIVER_VALUE_DESCRIPTION,GREENBOOK,GREENBOOK_RECORD_ID,TOOL_VALUEDRIVER_VALUE_RECORD_ID,VALUEDRIVER_COEFFICIENT,VALUEDRIVER_COEFFICIENT_RECORD_ID,FABLOCATION_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,CPQTABLEENTRYDATEADDED,QTESRVFBL_RECORD_ID,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,'' as QTESRVCOB_RECORD_ID,SAQSCD.QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID as QTESRVCOB_VDR_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSDVL.VALUEDRIVER_ID,PRSDVL.VALUEDRIVER_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_CODE,PRSDVL.VALUEDRIVER_VALUE_DESCRIPTION,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,PRSDVL.VALUEDRIVER_COEFFICIENT,PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,SAQSCO.FABLOCATION_ID,'{username}' as CPQTABLEENTRYADDEDBY,'{userid}' as ADDUSR_RECORD_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'{datetimenow}' as CPQTABLEENTRYDATEADDED,'' as QTESRVFBL_RECORD_ID,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID INNER JOIN SAQSCD ON SAQSCO.SERVICE_ID = SAQSCD.SERVICE_ID AND SAQSCO.QTEREV_RECORD_ID = SAQSCD.QTEREV_RECORD_ID AND SAQSCO.EQUIPMENT_ID = SAQSCD.EQUIPMENT_ID AND SAQSCD.VALUEDRIVER_ID = PRSDVL.VALUEDRIVER_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND PRSDVL.VALUEDRIVER_VALUE_CODE = '# CSA tools in Fab_<10' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD (NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND VALUEDRIVER_ID = '# of CSA tools in Fab' AND PRSDVL.VALUEDRIVER_VALUE_CODE = '# CSA tools in Fab_<10'  AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV(NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND TOOL_VALUEDRIVER_ID = '# of CSA tools in Fab' ))""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement_2)
                Log.Info("quer_statement_2_chk_j "+str(quer_statement_2))
            Log.Info("SAQSCD_CSA_INSERT-----> "+str(quer_statement))
            Log.Info("SAQSCV_CSA_INSERT-----> "+str(quer_statement_2))
    elif account_bluebook_query.BLUEBOOK == "DISPLAY":
        for count in tools_count_query:
            if count.COUNT > 7:
                quer_statement = """ INSERT SAQSCD (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,SERIAL_NUMBER,QTESRVCOB_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,VALUEDRIVER_ID,VALUEDRIVER_RECORD_ID,VALUEDRIVER_TYPE,VALUEDRIVER_NAME,GREENBOOK,GREENBOOK_RECORD_ID,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,QTESRVFBL_RECORD_ID,QTESRVGBK_VDR_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,'' as QTESRVCOB_RECORD_ID,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSVDR.VALUEDRIVER_ID,PRSVDR.VALUEDRIVER_RECORD_ID,PRSVDR.VALUEDRIVER_TYPE,PRSVDR.VALUEDRIVER_NAME,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,SAQSCO.FABLOCATION_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'' as QTESRVFBL_RECORD_ID,'' as QTESRVGBK_VDR_RECORD_ID,'{username}' as CPQTABLEENTRYADDEDBY ,'{datetimenow}' as CPQTABLEENTRYDATEADDED ,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID  WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD (NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND VALUEDRIVER_ID = '# of CSA tools in Fab' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement)
                
                quer_statement_2 = """ INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,QTESRVCOB_RECORD_ID,QTESRVCOB_VDR_RECORD_ID,SERIAL_NUMBER,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,TOOL_VALUEDRIVER_ID,TOOL_VALUEDRIVER_RECORD_ID,TOOL_VALUEDRIVER_VALUE_CODE,TOOL_VALUEDRIVER_VALUE_DESCRIPTION,GREENBOOK,GREENBOOK_RECORD_ID,TOOL_VALUEDRIVER_VALUE_RECORD_ID,VALUEDRIVER_COEFFICIENT,VALUEDRIVER_COEFFICIENT_RECORD_ID,FABLOCATION_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,CPQTABLEENTRYDATEADDED,QTESRVFBL_RECORD_ID,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,'' as QTESRVCOB_RECORD_ID,SAQSCD.QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID as QTESRVCOB_VDR_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSDVL.VALUEDRIVER_ID,PRSDVL.VALUEDRIVER_RECORD_ID,'# CSA tools in Fab_>7' as TOOL_VALUEDRIVER_VALUE_CODE,'# CSA tools in Fab_>7' as TOOL_VALUEDRIVER_VALUE_DESCRIPTION,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,PRSDVL.VALUEDRIVER_COEFFICIENT,PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,SAQSCO.FABLOCATION_ID,'{username}' as CPQTABLEENTRYADDEDBY,'{userid}' as ADDUSR_RECORD_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'{datetimenow}' as CPQTABLEENTRYDATEADDED,'' as QTESRVFBL_RECORD_ID,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID INNER JOIN SAQSCD ON SAQSCO.SERVICE_ID = SAQSCD.SERVICE_ID AND SAQSCO.QTEREV_RECORD_ID = SAQSCD.QTEREV_RECORD_ID AND SAQSCO.EQUIPMENT_ID = SAQSCD.EQUIPMENT_ID AND SAQSCD.VALUEDRIVER_ID = PRSDVL.VALUEDRIVER_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND PRSDVL.VALUEDRIVER_VALUE_CODE = '# CSA tools in Fab_>50' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV(NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND TOOL_VALUEDRIVER_ID = '# of CSA tools in Fab' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement_2)
            elif count.COUNT in range(3,8):
                quer_statement = """ INSERT SAQSCD (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,SERIAL_NUMBER,QTESRVCOB_RECORD_ID,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,VALUEDRIVER_ID,VALUEDRIVER_RECORD_ID,VALUEDRIVER_TYPE,VALUEDRIVER_NAME,GREENBOOK,GREENBOOK_RECORD_ID,FABLOCATION_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,QTESRVFBL_RECORD_ID,QTESRVGBK_VDR_RECORD_ID,CPQTABLEENTRYADDEDBY,CPQTABLEENTRYDATEADDED,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,'' as QTESRVCOB_RECORD_ID,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSVDR.VALUEDRIVER_ID,PRSVDR.VALUEDRIVER_RECORD_ID,PRSVDR.VALUEDRIVER_TYPE,PRSVDR.VALUEDRIVER_NAME,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,SAQSCO.FABLOCATION_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'' as QTESRVFBL_RECORD_ID,'' as QTESRVGBK_VDR_RECORD_ID,'{username}' as CPQTABLEENTRYADDEDBY ,'{datetimenow}' as CPQTABLEENTRYDATEADDED ,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID  WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD (NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND VALUEDRIVER_ID = '# of CSA tools in Fab' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement)
                
                quer_statement_2 = """ INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,QTESRVCOB_RECORD_ID,QTESRVCOB_VDR_RECORD_ID,SERIAL_NUMBER,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,TOOL_VALUEDRIVER_ID,TOOL_VALUEDRIVER_RECORD_ID,TOOL_VALUEDRIVER_VALUE_CODE,TOOL_VALUEDRIVER_VALUE_DESCRIPTION,GREENBOOK,GREENBOOK_RECORD_ID,TOOL_VALUEDRIVER_VALUE_RECORD_ID,VALUEDRIVER_COEFFICIENT,VALUEDRIVER_COEFFICIENT_RECORD_ID,FABLOCATION_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,CPQTABLEENTRYDATEADDED,QTESRVFBL_RECORD_ID,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,'' as QTESRVCOB_RECORD_ID,SAQSCD.QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID as QTESRVCOB_VDR_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSDVL.VALUEDRIVER_ID,PRSDVL.VALUEDRIVER_RECORD_ID,'# CSA tools in Fab_3-7' as TOOL_VALUEDRIVER_VALUE_CODE,'# CSA tools in Fab_3-7' as TOOL_VALUEDRIVER_VALUE_DESCRIPTION,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,PRSDVL.VALUEDRIVER_COEFFICIENT,PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,SAQSCO.FABLOCATION_ID,'{username}' as CPQTABLEENTRYADDEDBY,'{userid}' as ADDUSR_RECORD_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'{datetimenow}' as CPQTABLEENTRYDATEADDED,'' as QTESRVFBL_RECORD_ID,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID INNER JOIN SAQSCD ON SAQSCO.SERVICE_ID = SAQSCD.SERVICE_ID AND SAQSCO.QTEREV_RECORD_ID = SAQSCD.QTEREV_RECORD_ID AND SAQSCO.EQUIPMENT_ID = SAQSCD.EQUIPMENT_ID AND SAQSCD.VALUEDRIVER_ID = PRSDVL.VALUEDRIVER_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND PRSDVL.VALUEDRIVER_VALUE_CODE = '# CSA tools in Fab_10-50' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV(NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND TOOL_VALUEDRIVER_ID = '# of CSA tools in Fab' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement_2)
            elif count.COUNT < 3:
                quer_statement = """ INSERT SAQSCD (
                    QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
                    EQUIPMENT_DESCRIPTION,
                    EQUIPMENT_ID,
                    EQUIPMENT_RECORD_ID,
                    QUOTE_ID,QUOTE_NAME,
                    QUOTE_RECORD_ID,
                    SERIAL_NUMBER,
                    QTESRVCOB_RECORD_ID,
                    SERVICE_DESCRIPTION,
                    SERVICE_ID,
                    SERVICE_RECORD_ID,
                    VALUEDRIVER_ID,
                    VALUEDRIVER_RECORD_ID,
                    VALUEDRIVER_TYPE,
                    VALUEDRIVER_NAME,
                    GREENBOOK,
                    GREENBOOK_RECORD_ID,
                    FABLOCATION_ID,
                    FABLOCATION_NAME,
                    FABLOCATION_RECORD_ID,
                    QTESRVFBL_RECORD_ID,
                    QTESRVGBK_VDR_RECORD_ID,
                    CPQTABLEENTRYADDEDBY,
                    CPQTABLEENTRYDATEADDED,
                    QTEREV_ID,
                    QTEREV_RECORD_ID
                )
                SELECT 
                CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
                SAQSCO.EQUIPMENT_DESCRIPTION,
                SAQSCO.EQUIPMENT_ID,
                SAQSCO.EQUIPMENT_RECORD_ID,
                SAQSCO.QUOTE_ID,
                SAQSCO.QUOTE_NAME,
                SAQSCO.QUOTE_RECORD_ID,
                SAQSCO.SERIAL_NO as SERIAL_NUMBER,
                '' as QTESRVCOB_RECORD_ID,
                SAQSCO.SERVICE_DESCRIPTION,
                SAQSCO.SERVICE_ID,
                SAQSCO.SERVICE_RECORD_ID,
                PRSVDR.VALUEDRIVER_ID,
                PRSVDR.VALUEDRIVER_RECORD_ID,
                PRSVDR.VALUEDRIVER_TYPE,
                PRSVDR.VALUEDRIVER_NAME,
                SAQSCO.GREENBOOK,
                SAQSCO.GREENBOOK_RECORD_ID,
                SAQSCO.FABLOCATION_ID,
                SAQSCO.FABLOCATION_NAME,
                SAQSCO.FABLOCATION_RECORD_ID,
                '' as QTESRVFBL_RECORD_ID,
                '' as QTESRVGBK_VDR_RECORD_ID,
                '{username}' as CPQTABLEENTRYADDEDBY ,
                '{datetimenow}' as CPQTABLEENTRYDATEADDED ,
                '' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID 
                from MAEQUP 
                INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK 
                INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID  
                WHERE 
                SAACNT.ACCOUNT_ID != 'DISPLAY' 
                AND SAQSCO.QUOTE_RECORD_ID ='{rec}' 
                AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' 
                AND SAQSCO.SERVICE_ID ='{treeparam}' 
                AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab'
                AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD (NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND VALUEDRIVER_ID = '# of CSA tools in Fab' )
                """.format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement)
                
                quer_statement_2 = """ INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,EQUIPMENT_DESCRIPTION,EQUIPMENT_ID,EQUIPMENT_RECORD_ID,QUOTE_ID,QUOTE_NAME,QUOTE_RECORD_ID,QTESRVCOB_RECORD_ID,QTESRVCOB_VDR_RECORD_ID,SERIAL_NUMBER,SERVICE_DESCRIPTION,SERVICE_ID,SERVICE_RECORD_ID,TOOL_VALUEDRIVER_ID,TOOL_VALUEDRIVER_RECORD_ID,TOOL_VALUEDRIVER_VALUE_CODE,TOOL_VALUEDRIVER_VALUE_DESCRIPTION,GREENBOOK,GREENBOOK_RECORD_ID,TOOL_VALUEDRIVER_VALUE_RECORD_ID,VALUEDRIVER_COEFFICIENT,VALUEDRIVER_COEFFICIENT_RECORD_ID,FABLOCATION_ID,CPQTABLEENTRYADDEDBY,ADDUSR_RECORD_ID,FABLOCATION_NAME,FABLOCATION_RECORD_ID,CPQTABLEENTRYDATEADDED,QTESRVFBL_RECORD_ID,QTEREV_ID,QTEREV_RECORD_ID)
                SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,'' as QTESRVCOB_RECORD_ID,SAQSCD.QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID as QTESRVCOB_VDR_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSDVL.VALUEDRIVER_ID,PRSDVL.VALUEDRIVER_RECORD_ID,'# CSA tools in Fab_<7' as VALUEDRIVER_VALUE_CODE,'# CSA tools in Fab_<7' as TOOL_VALUEDRIVER_VALUE_DESCRIPTION,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,PRSDVL.VALUEDRIVER_COEFFICIENT,PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,SAQSCO.FABLOCATION_ID,'{username}' as CPQTABLEENTRYADDEDBY,'{userid}' as ADDUSR_RECORD_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'{datetimenow}' as CPQTABLEENTRYDATEADDED,'' as QTESRVFBL_RECORD_ID,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID INNER JOIN SAQSCD ON SAQSCO.SERVICE_ID = SAQSCD.SERVICE_ID AND SAQSCO.QTEREV_RECORD_ID = SAQSCD.QTEREV_RECORD_ID AND SAQSCO.EQUIPMENT_ID = SAQSCD.EQUIPMENT_ID AND SAQSCD.VALUEDRIVER_ID = PRSDVL.VALUEDRIVER_ID INNER JOIN SAACNT (NOLOCK) ON SAQSCO.ACCOUNT_ID = SAACNT.ACCOUNT_ID INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID WHERE SAACNT.ACCOUNT_ID != 'DISPLAY' AND SAQSCO.QUOTE_RECORD_ID ='{rec}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = '# of CSA tools in Fab' AND PRSDVL.VALUEDRIVER_VALUE_CODE = '# CSA tools in Fab_<10' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV(NOLOCK) WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{rec}' AND TOOL_VALUEDRIVER_ID = '# of CSA tools in Fab' )""".format(rec=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)
                Sql.RunQuery(quer_statement_2)
            Log.Info("SAQSCD_CSA_INSERT-----> "+str(quer_statement))
            Log.Info("SAQSCV_CSA_INSERT-----> "+str(quer_statement_2))


def predefined_contract_cov_time():
    entitlement_obj = Sql.GetList("select ENTITLEMENT_NAME,ENTITLEMENT_VALUE_CODE,ENTITLEMENT_DISPLAY_VALUE,ENTITLEMENT_DESCRIPTION from (SELECT distinct e.QUOTE_RECORD_ID,e.QTEREV_RECORD_ID, replace(X.Y.value('(ENTITLEMENT_NAME)[1]', 'VARCHAR(128)'),';#38','&') as ENTITLEMENT_NAME,replace(X.Y.value('(ENTITLEMENT_VALUE_CODE)[1]', 'VARCHAR(128)'),';#38','&') as ENTITLEMENT_VALUE_CODE,replace(X.Y.value('(ENTITLEMENT_DISPLAY_VALUE)[1]', 'VARCHAR(128)'),';#38','&') as ENTITLEMENT_DISPLAY_VALUE,replace(X.Y.value('(ENTITLEMENT_DESCRIPTION)[1]', 'VARCHAR(128)'),';#38','&') as ENTITLEMENT_DESCRIPTION FROM (select QUOTE_RECORD_ID,QTEREV_RECORD_ID,convert(xml,replace(ENTITLEMENT_XML,'&',';#38')) as ENTITLEMENT_XML from {} (nolock) where QUOTE_RECORD_ID = '{Qt_rec_id}' AND QTEREV_RECORD_ID = '{qurev_rec_id}' and SERVICE_ID = '{treeparam}' ) e OUTER APPLY e.ENTITLEMENT_XML.nodes('QUOTE_ITEM_ENTITLEMENT') as X(Y) ) as m where ENTITLEMENT_NAME IN  ('AGS_CRT_RSP_TIM','AGS_CRT_CON_COV')".format('SAQTSE',Qt_rec_id=Qt_rec_id,qurev_rec_id=quote_revision_record_id,treeparam=TreeParam))

    for coverageresponse in entitlement_obj:
        if coverageresponse.ENTITLEMENT_DESCRIPTION =="Contract Coverage":
            coverage=coverageresponse.ENTITLEMENT_DISPLAY_VALUE	
        elif coverageresponse.ENTITLEMENT_DESCRIPTION =="Response Time":
            time=coverageresponse.ENTITLEMENT_DISPLAY_VALUE          
    time=time.split(' ')[0]
    value = coverage+time
    saqscd_insert_contract = """INSERT SAQSCD (
        QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
        EQUIPMENT_DESCRIPTION,
        EQUIPMENT_ID,
        EQUIPMENT_RECORD_ID,
        QUOTE_ID,
        QUOTE_NAME,
        QUOTE_RECORD_ID,
        SERIAL_NUMBER,
        QTESRVCOB_RECORD_ID,
        SERVICE_DESCRIPTION,
        SERVICE_ID,
        SERVICE_RECORD_ID,
        VALUEDRIVER_ID,
        VALUEDRIVER_RECORD_ID,
        VALUEDRIVER_TYPE,
        VALUEDRIVER_NAME,
        GREENBOOK,
        GREENBOOK_RECORD_ID,
        FABLOCATION_ID,
        FABLOCATION_NAME,
        FABLOCATION_RECORD_ID,
        QTESRVFBL_RECORD_ID,
        QTESRVGBK_VDR_RECORD_ID,
        CPQTABLEENTRYADDEDBY,
        CPQTABLEENTRYDATEADDED,
        QTEREV_ID,
        QTEREV_RECORD_ID)SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
        SAQSCO.EQUIPMENT_DESCRIPTION,
        SAQSCO.EQUIPMENT_ID,
        SAQSCO.EQUIPMENT_RECORD_ID,
        SAQSCO.QUOTE_ID,
        SAQSCO.QUOTE_NAME,
        SAQSCO.QUOTE_RECORD_ID,
        SAQSCO.SERIAL_NO as SERIAL_NUMBER,
        SAQSCO.QUOTE_SERVICE_COVERED_OBJECTS_RECORD_ID,
        SAQSCO.SERVICE_DESCRIPTION,
        SAQSCO.SERVICE_ID,
        SAQSCO.SERVICE_RECORD_ID,
        PRSVDR.VALUEDRIVER_ID,
        PRSVDR.VALUEDRIVER_RECORD_ID,
        PRSVDR.VALUEDRIVER_TYPE,
        PRSVDR.VALUEDRIVER_NAME,
        SAQSCO.GREENBOOK,
        SAQSCO.GREENBOOK_RECORD_ID,
        SAQSCO.FABLOCATION_ID,
        SAQSCO.FABLOCATION_NAME,
        SAQSCO.FABLOCATION_RECORD_ID,
        '' as QTESRVFBL_RECORD_ID,
        '' as QTESRVGBK_VDR_RECORD_ID,
        '' as CPQTABLEENTRYADDEDBY ,
        '' as CPQTABLEENTRYDATEADDED ,
        SAQSCO.QTEREV_ID,
        SAQSCO.QTEREV_RECORD_ID 
        from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_RECORD_ID = SAQSCO.EQUIPMENT_RECORD_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID  WHERE  SAQSCO.QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = 'Contract Coverage & Response Time' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCD.VALUEDRIVER_ID = 'Contract Coverage & Response Time' )""".format(Qt_rec_id=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id)

    saqscv_insert_contract = """INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,
        EQUIPMENT_DESCRIPTION,
        EQUIPMENT_ID,
        EQUIPMENT_RECORD_ID,
        QUOTE_ID,
        QUOTE_NAME,
        QUOTE_RECORD_ID,
        QTESRVCOB_RECORD_ID,
        SERIAL_NUMBER,
        SERVICE_DESCRIPTION,
        SERVICE_ID,
        SERVICE_RECORD_ID,
        TOOL_VALUEDRIVER_ID,
        TOOL_VALUEDRIVER_RECORD_ID,
        TOOL_VALUEDRIVER_VALUE_CODE,
        TOOL_VALUEDRIVER_VALUE_DESCRIPTION,
        GREENBOOK,
        GREENBOOK_RECORD_ID,
        TOOL_VALUEDRIVER_VALUE_RECORD_ID,
        VALUEDRIVER_COEFFICIENT,
        VALUEDRIVER_COEFFICIENT_RECORD_ID,
        FABLOCATION_ID,
        CPQTABLEENTRYADDEDBY,
        ADDUSR_RECORD_ID,
        FABLOCATION_NAME,
        FABLOCATION_RECORD_ID,
        CPQTABLEENTRYDATEADDED,
        QTESRVFBL_RECORD_ID,
        QTEREV_ID,
        QTEREV_RECORD_ID)
        SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID, SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,SAQSCO.QUOTE_SERVICE_COVERED_OBJECTS_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSDVL.VALUEDRIVER_ID,PRSDVL.VALUEDRIVER_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_CODE,PRSDVL.VALUEDRIVER_VALUE_DESCRIPTION,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,PRSDVL.VALUEDRIVER_COEFFICIENT,PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,SAQSCO.FABLOCATION_ID,'' as CPQTABLEENTRYADDEDBY,'' as ADDUSR_RECORD_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'' as CPQTABLEENTRYDATEADDED,'' as QTESRVFBL_RECORD_ID,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP 
        INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK 
        INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID
        WHERE SAQSCO.QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSDVL.VALUEDRIVER_ID = 'Contract Coverage & Response Time' AND PRSDVL.VALUEDRIVER_VALUE_DESCRIPTION ='{value}' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCV.TOOL_VALUEDRIVER_ID = 'Contract Coverage & Response Time')""".format(Qt_rec_id=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id,value = value)
    Log.Info('value'+str(value))
    Log.Info('time'+str(time))
    Log.Info('saqscd_insert--contract'+str(saqscd_insert_contract))
    Log.Info('saqscv_insert--contract'+str(saqscv_insert_contract))
    Sql.RunQuery(saqscd_insert_contract)
    Sql.RunQuery(saqscv_insert_contract)


def predefined_contract_cov_time_entitlemen_trolldown():
    Log.Info('TreeParam'+str(TreeParam))
    Log.Info('TreeParentParam'+str(TreeParentParam))
    Log.Info('TreeSuperParentParam'+str(TreeSuperParentParam))
    
    entitlement_obj = Sql.GetList("select ENTITLEMENT_NAME,ENTITLEMENT_VALUE_CODE,ENTITLEMENT_DISPLAY_VALUE,ENTITLEMENT_DESCRIPTION from (SELECT distinct e.QUOTE_RECORD_ID,e.QTEREV_RECORD_ID, replace(X.Y.value('(ENTITLEMENT_NAME)[1]', 'VARCHAR(128)'),';#38','&') as ENTITLEMENT_NAME,replace(X.Y.value('(ENTITLEMENT_VALUE_CODE)[1]', 'VARCHAR(128)'),';#38','&') as ENTITLEMENT_VALUE_CODE,replace(X.Y.value('(ENTITLEMENT_DISPLAY_VALUE)[1]', 'VARCHAR(128)'),';#38','&') as ENTITLEMENT_DISPLAY_VALUE,replace(X.Y.value('(ENTITLEMENT_DESCRIPTION)[1]', 'VARCHAR(128)'),';#38','&') as ENTITLEMENT_DESCRIPTION FROM (select QUOTE_RECORD_ID,QTEREV_RECORD_ID,convert(xml,replace(ENTITLEMENT_XML,'&',';#38')) as ENTITLEMENT_XML from {treeparam} (nolock) {treeParentParam} ) e OUTER APPLY e.ENTITLEMENT_XML.nodes('QUOTE_ITEM_ENTITLEMENT') as X(Y) ) as m where ENTITLEMENT_NAME IN  ('AGS_CRT_RSP_TIM','AGS_CRT_CON_COV')".format(treeparam=TreeParam,treeParentParam=TreeParentParam))

    for coverageresponse in entitlement_obj:
        if coverageresponse.ENTITLEMENT_DESCRIPTION =="Contract Coverage":
            coverage=coverageresponse.ENTITLEMENT_DISPLAY_VALUE	
        elif coverageresponse.ENTITLEMENT_DESCRIPTION =="Response Time":
            time=coverageresponse.ENTITLEMENT_DISPLAY_VALUE          
    time=time.split(' ')[0]
    value = coverage+time
    saqscd_insert_contract = """INSERT SAQSCD (
        QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
        EQUIPMENT_DESCRIPTION,
        EQUIPMENT_ID,
        EQUIPMENT_RECORD_ID,
        QUOTE_ID,
        QUOTE_NAME,
        QUOTE_RECORD_ID,
        SERIAL_NUMBER,
        QTESRVCOB_RECORD_ID,
        SERVICE_DESCRIPTION,
        SERVICE_ID,
        SERVICE_RECORD_ID,
        VALUEDRIVER_ID,
        VALUEDRIVER_RECORD_ID,
        VALUEDRIVER_TYPE,
        VALUEDRIVER_NAME,
        GREENBOOK,
        GREENBOOK_RECORD_ID,
        FABLOCATION_ID,
        FABLOCATION_NAME,
        FABLOCATION_RECORD_ID,
        QTESRVFBL_RECORD_ID,
        QTESRVGBK_VDR_RECORD_ID,
        CPQTABLEENTRYADDEDBY,
        CPQTABLEENTRYDATEADDED,
        QTEREV_ID,
        QTEREV_RECORD_ID)SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_RECORD_ID,
        SAQSCO.EQUIPMENT_DESCRIPTION,
        SAQSCO.EQUIPMENT_ID,
        SAQSCO.EQUIPMENT_RECORD_ID,
        SAQSCO.QUOTE_ID,
        SAQSCO.QUOTE_NAME,
        SAQSCO.QUOTE_RECORD_ID,
        SAQSCO.SERIAL_NO as SERIAL_NUMBER,
        SAQSCO.QUOTE_SERVICE_COVERED_OBJECTS_RECORD_ID,
        SAQSCO.SERVICE_DESCRIPTION,
        SAQSCO.SERVICE_ID,
        SAQSCO.SERVICE_RECORD_ID,
        PRSVDR.VALUEDRIVER_ID,
        PRSVDR.VALUEDRIVER_RECORD_ID,
        PRSVDR.VALUEDRIVER_TYPE,
        PRSVDR.VALUEDRIVER_NAME,
        SAQSCO.GREENBOOK,
        SAQSCO.GREENBOOK_RECORD_ID,
        SAQSCO.FABLOCATION_ID,
        SAQSCO.FABLOCATION_NAME,
        SAQSCO.FABLOCATION_RECORD_ID,
        '' as QTESRVFBL_RECORD_ID,
        '' as QTESRVGBK_VDR_RECORD_ID,
        '' as CPQTABLEENTRYADDEDBY ,
        '' as CPQTABLEENTRYDATEADDED ,
        SAQSCO.QTEREV_ID,
        SAQSCO.QTEREV_RECORD_ID 
        from MAEQUP INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_RECORD_ID = SAQSCO.EQUIPMENT_RECORD_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK INNER JOIN PRSVDR ON SAQSCO.SERVICE_ID = PRSVDR.SERVICE_ID  WHERE  SAQSCO.QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSVDR.VALUEDRIVER_ID = 'Contract Coverage & Response Time' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCD WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCD.VALUEDRIVER_ID = 'Contract Coverage & Response Time' )""".format(Qt_rec_id=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,treeParentParam=TreeParentParam,qurev_rec_id=quote_revision_record_id)

    saqscv_insert_contract = """INSERT SAQSCV (QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID,
        EQUIPMENT_DESCRIPTION,
        EQUIPMENT_ID,
        EQUIPMENT_RECORD_ID,
        QUOTE_ID,
        QUOTE_NAME,
        QUOTE_RECORD_ID,
        QTESRVCOB_RECORD_ID,
        SERIAL_NUMBER,
        SERVICE_DESCRIPTION,
        SERVICE_ID,
        SERVICE_RECORD_ID,
        TOOL_VALUEDRIVER_ID,
        TOOL_VALUEDRIVER_RECORD_ID,
        TOOL_VALUEDRIVER_VALUE_CODE,
        TOOL_VALUEDRIVER_VALUE_DESCRIPTION,
        GREENBOOK,
        GREENBOOK_RECORD_ID,
        TOOL_VALUEDRIVER_VALUE_RECORD_ID,
        VALUEDRIVER_COEFFICIENT,
        VALUEDRIVER_COEFFICIENT_RECORD_ID,
        FABLOCATION_ID,
        CPQTABLEENTRYADDEDBY,
        ADDUSR_RECORD_ID,
        FABLOCATION_NAME,
        FABLOCATION_RECORD_ID,
        CPQTABLEENTRYDATEADDED,
        QTESRVFBL_RECORD_ID,
        QTEREV_ID,
        QTEREV_RECORD_ID)
        SELECT CONVERT(VARCHAR(4000),NEWID()) as QUOTE_SERVICE_COVERED_OBJ_TOOL_DRIVER_VALUE_RECORD_ID, SAQSCO.EQUIPMENT_DESCRIPTION,SAQSCO.EQUIPMENT_ID,SAQSCO.EQUIPMENT_RECORD_ID,SAQSCO.QUOTE_ID,SAQSCO.QUOTE_NAME,SAQSCO.QUOTE_RECORD_ID,SAQSCO.QUOTE_SERVICE_COVERED_OBJECTS_RECORD_ID,SAQSCO.SERIAL_NO as SERIAL_NUMBER,SAQSCO.SERVICE_DESCRIPTION,SAQSCO.SERVICE_ID,SAQSCO.SERVICE_RECORD_ID,PRSDVL.VALUEDRIVER_ID,PRSDVL.VALUEDRIVER_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_CODE,PRSDVL.VALUEDRIVER_VALUE_DESCRIPTION,SAQSCO.GREENBOOK,SAQSCO.GREENBOOK_RECORD_ID,PRSDVL.VALUEDRIVER_VALUE_RECORD_ID,PRSDVL.VALUEDRIVER_COEFFICIENT,PRSDVL.SRVDRVAL_RECORD_ID as VALUEDRIVER_COEFFICIENT_RECORD_ID,SAQSCO.FABLOCATION_ID,'' as CPQTABLEENTRYADDEDBY,'' as ADDUSR_RECORD_ID,SAQSCO.FABLOCATION_NAME,SAQSCO.FABLOCATION_RECORD_ID,'' as CPQTABLEENTRYDATEADDED,'' as QTESRVFBL_RECORD_ID,'' as QTEREV_ID,SAQSCO.QTEREV_RECORD_ID from MAEQUP 
        INNER JOIN SAQSCO (NOLOCK) ON MAEQUP.EQUIPMENT_ID = SAQSCO.EQUIPMENT_ID and MAEQUP.GREENBOOK = SAQSCO.GREENBOOK 
        INNER JOIN PRSDVL ON SAQSCO.SERVICE_ID = PRSDVL.SERVICE_ID
        WHERE SAQSCO.QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCO.QTEREV_RECORD_ID = '{qurev_rec_id}' AND SAQSCO.SERVICE_ID ='{treeparam}' AND PRSDVL.VALUEDRIVER_ID = 'Contract Coverage & Response Time' AND PRSDVL.VALUEDRIVER_VALUE_DESCRIPTION ='{value}' AND MAEQUP.EQUIPMENT_ID NOT IN (SELECT EQUIPMENT_ID FROM SAQSCV WHERE QTEREV_RECORD_ID = '{qurev_rec_id}' AND SERVICE_ID ='{treeparam}' AND QUOTE_RECORD_ID ='{Qt_rec_id}' AND SAQSCV.TOOL_VALUEDRIVER_ID = 'Contract Coverage & Response Time')""".format(Qt_rec_id=Qt_rec_id, datetimenow=datetime.datetime.now().strftime("%m/%d/%Y %H:%M:%S %p"), userid=userId, username=userName,treeparam=TreeParam,qurev_rec_id=quote_revision_record_id,value = value,treeParentParam=TreeParentParam)
    Log.Info('value'+str(value))
    Log.Info('time'+str(time))
    Log.Info('saqscd_insert--contract'+str(saqscd_insert_contract))
    Log.Info('saqscv_insert--contract'+str(saqscv_insert_contract))
    
    Sql.RunQuery(saqscd_insert_contract)
    Sql.RunQuery(saqscv_insert_contract)



def predefined_values():
    ##predefined value for wafer
    try:
        predefined_wafer()
    except Exception,e:
        Log.Info('wafer type--'+str(e))

    ####calling function for device type predefined logic... 
    try:
        predefined_device_type()
    except Exception,e:
        Log.Info('device type--'+str(e))

    try:
        predefined_csa_tools()
    except Exception,e:
        Log.Info('csa tools--'+str(e))

    try:
        predefined_contract_cov_time()
    except Exception,e:
        Log.Info('contract coverage time--'+str(e))
###calling all functions for predefined
try:
    Qt_rec_id = Param.CPQ_Columns['Quote'] 
except:
    Qt_rec_id = ""

try:
    LEVEL = Param.CPQ_Columns['Level']
except:
    LEVEL = ""
Log.Info("LEVEL--in-PD"+str(LEVEL))
try:
    TreeParam = Param.CPQ_Columns['TreeParam']
    TreeParentParam = Param.CPQ_Columns['TreeParentParam']
    TreeSuperParentParam = Param.CPQ_Columns['TreeSuperParentParam']
    TreeTopSuperParentParam = Param.CPQ_Columns['TreeTopSuperParentParam']
    userId = Param.CPQ_Columns['Userid']
    userName = Param.CPQ_Columns['Username']
    quote_revision_record_id = Param.CPQ_Columns['quote_revision_record_id']
except: 
    TreeParam = ""
    TreeParentParam = ""
    TreeSuperParentParam = ""
    TreeTopSuperParentParam = ""
    userId = ""
    userName = ""
    quote_revision_record_id = ""

if 'PREDEFINED DRIVER' in LEVEL:
    predefined_values()
elif 'ENTITLEMENT PREDEFINED DRIVER' in LEVEL:
    predefined_contract_cov_time_entitlemen_trolldown()
    Log.Info("LEVEL--2222222")